### ISSUE TITLE
Automatic Release fails if automatically generated release number was already used

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1514]
source: http://help.octopusdeploy.com/discussions/problems/31398

**Comment by Dalmirog** [comment]
I was able to reproduce it on my end. Full stack trace

```
Caught exception while receiving: Octopus.Server.Communications.Packages.PackagePushedEvent
Raven.Abstractions.Exceptions.OperationVetoedException: PUT vetoed by Raven.Bundles.UniqueConstraints.UniqueConstraintsPutTrigger because: Ensure unique constraint violated for fields: VersionByProject
   at Raven.Database.DocumentDatabase.AssertPutOperationNotVetoed(String key, RavenJObject metadata, RavenJObject document, TransactionInformation transactionInformation) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 938
   at Raven.Database.DocumentDatabase.<>c__DisplayClass4b.<Put>b__43(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 780
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 608
   at Raven.Database.DocumentDatabase.Put(String key, Etag etag, RavenJObject document, RavenJObject metadata, TransactionInformation transactionInformation) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 843
   at Raven.Database.Extensions.CommandExtensions.Execute(ICommandData self, DocumentDatabase database, BatchResult batchResult) in c:\Builds\RavenDB-Stable\Raven.Database\Extensions\CommandExtensions.cs:line 54
   at Raven.Database.DocumentDatabase.ProcessBatch(IList`1 commands) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 2086
   at Raven.Database.DocumentDatabase.<>c__DisplayClass10c.<Batch>b__108(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 2048
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 666
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 617
   at Raven.Database.DocumentDatabase.Batch(IList`1 commands) in c:\Builds\RavenDB-Stable\Raven.Database\DocumentDatabase.cs:line 2051
   at Raven.Client.Embedded.EmbeddedDatabaseCommands.Batch(IEnumerable`1 commandDatas) in c:\Builds\RavenDB-Stable\Raven.Client.Embedded\EmbeddedDatabaseCommands.cs:line 709
   at Raven.Client.Document.DocumentSession.SaveChanges() in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Document\DocumentSession.cs:line 664
   at Octopus.Server.Orchestration.ReleaseCreation.ReleaseCreationFactory.CreateRelease(IDocumentSession session, IEventStore eventStore, IPackageRepositoryFactory packageRepositoryFactory, IMasterKeyEncryption encryption, Project project, Release release) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\ReleaseCreation\ReleaseCreationFactory.cs:line 82
   at Octopus.Server.Communications.Packages.PackageEvaluator.CreateRelease(String packageId, String packageVersion, Project project, DeploymentProcess deploymentProcess) in y:\work\refs\heads\master\source\Octopus.Server\Communications\Packages\PackageEvaluator.cs:line 143
   at Octopus.Server.Communications.Packages.PackageEvaluator.Evaluate(String packageId, String packageVersion) in y:\work\refs\heads\master\source\Octopus.Server\Communications\Packages\PackageEvaluator.cs:line 80
   at Pipefish.Actor.OnReceivingTyped[TBody](Message message) in y:\work\3cbe05672d69a231\source\Pipefish\Actor.cs:line 113
```
