### ISSUE TITLE
New install of Octopus Deploy Server is showing an error in CheckForOctopusUpgrades

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1685]
The entries below are the most recent warning- and error-level events recorded on the Octopus Server in this session.

Error    2015-06-29 06:25:56
Error when running scheduled task: CheckForOctopusUpgrades
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.CheckForUpdates() in y:\work\refs\heads\feature-migratehistory\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 86
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.Trigger() in y:\work\refs\heads\feature-migratehistory\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 67
   at Octopus.Server.Schedules.Scheduler.RunTask(IRunOnASchedule task) in y:\work\refs\heads\feature-migratehistory\source\Octopus.Server\Schedules\Scheduler.cs:line 125

**Comment by PaulStovell** [comment]
I had this last night too, I think it might just happen when the website is unavailable

**Comment by PaulStovell** [comment]
Going to ignore it for now since it must be an occasional issue
