### ISSUE TITLE
Cannot browse to Tentacle (10933) or Server (10943) for troubleshooting

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1708]
Attempting to browse to a Tentacle instance (think troubleshooting) is broken:

```
2015-07-13 15:28:35.0201      6  INFO  Agent will trust Octopus servers with the thumbprint: 29FEFE0F5A1E8576B094CF681B845BE364DF04A8
2015-07-13 15:28:35.0991      6  INFO  listen://0.0.0.0:10933/           6  Listener started
2015-07-13 15:28:35.1181      6  INFO  Agent listening on: 0.0.0.0:10933
2015-07-13 15:28:35.1181      6  INFO  The Windows Service has started
2015-07-13 15:28:35.1181      6  INFO  Tentacle version: 1.0.0 / local
2015-07-13 15:28:42.2341      7  INFO  listen://0.0.0.0:10933/           7  Accepted TCP client: 127.0.0.1:50280
2015-07-13 15:28:42.2401     12  INFO  listen://0.0.0.0:10933/          12  Accepted TCP client: 127.0.0.1:50281
2015-07-13 15:28:42.2401      4  INFO  listen://0.0.0.0:10933/           4  Performing SSL (TLS 1.0) server handshake
2015-07-13 15:28:42.2401      5  INFO  listen://0.0.0.0:10933/           5  Performing SSL (TLS 1.0) server handshake
2015-07-13 15:28:42.2401      4  INFO  listen://0.0.0.0:10933/           4  Unhandled error when handling request from client: 127.0.0.1:50280
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in y:\work\7ab39c94136bc5c6\source\Halibut\Transport\SecureListener.cs:line 94
2015-07-13 15:28:42.4832     12  INFO  listen://0.0.0.0:10933/          12  Accepted TCP client: 127.0.0.1:50282
2015-07-13 15:28:42.4832      4  INFO  listen://0.0.0.0:10933/           4  Performing SSL (TLS 1.0) server handshake
2015-07-13 15:28:52.2332      5  INFO  listen://0.0.0.0:10933/           5  Unhandled error when handling request from client: 127.0.0.1:50281
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in y:\work\7ab39c94136bc5c6\source\Halibut\Transport\SecureListener.cs:line 94
2015-07-13 15:29:02.2343      4  INFO  listen://0.0.0.0:10933/           4  Unhandled error when handling request from client: 127.0.0.1:50282
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in y:\work\7ab39c94136bc5c6\source\Halibut\Transport\SecureListener.cs:line 94
```

**Comment by michaelnoonan** [comment]
Browsing to Server also fails:
```
Octopus Deploy: Server version 1.0.0.0

Browse your Octopus server at: http://localhost:80/
The Octopus server is starting: Initializing database and performing migrations...
Beginning database upgrade
Fetching list of already executed scripts.
No new scripts need to be executed - completing.
The Octopus server is starting: Starting message distributor...
listen://0.0.0.0:10943/           1  Listener started
The Octopus server is starting: Starting task scheduler...
The Octopus server is starting: Starting task queue...
Web server is ready to process requests
Running. Press <enter> to shut down...
listen://0.0.0.0:10943/           3  Accepted TCP client: 127.0.0.1:50366
listen://0.0.0.0:10943/          14  Accepted TCP client: 127.0.0.1:50367
listen://0.0.0.0:10943/           8  Performing SSL (TLS 1.0) server handshake
listen://0.0.0.0:10943/           5  Performing SSL (TLS 1.0) server handshake
listen://0.0.0.0:10943/           8  Unhandled error when handling request from client: 127.0.0.1:50366
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in y:\work\7ab39c94136bc5c6\source\Halibut\Transport\SecureListener.cs:line 94
```

**Comment by michaelnoonan** [comment]
Ah, bug in the test: I was attempting to connect over `HTTP` instead of `HTTPS`. Closing.
