### ISSUE TITLE
Apply retention policy fails because cannot access the file 'C:\Octopus\DeploymentJournal.xml' 

### ISSUE THREAD

**Issue by clain23** [OctopusDeploy/Issues#1752]
```
System.IO.IOException: The process cannot access the file 'C:\Octopus\DeploymentJournal.xml' because it is being used by another process.
12:54:29Error
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
12:54:29Error
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
12:54:29Error
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
12:54:29Error
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
12:54:29Error
   at Calamari.Integration.FileSystem.CalamariPhysicalFileSystem.OpenFile(String path, FileMode mode, FileAccess access, FileShare share) in y:\work\b1fd300731d5f2fc\source\Calamari\Integration\FileSystem\CalamariPhysicalFileSystem.cs:line 178
12:54:29Error
   at Calamari.Integration.FileSystem.CalamariPhysicalFileSystem.OpenFile(String path, FileAccess access, FileShare share) in y:\work\b1fd300731d5f2fc\source\Calamari\Integration\FileSystem\CalamariPhysicalFileSystem.cs:line 173
12:54:29Error
   at Calamari.Deployment.Journal.DeploymentJournal.<Read>d__b.MoveNext() in y:\work\b1fd300731d5f2fc\source\Calamari\Deployment\Journal\DeploymentJournal.cs:line 83
12:54:29Error
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
12:54:29Error
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
12:54:29Error
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
12:54:29Error
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
12:54:29Error
   at System.Linq.Enumerable.<SkipWhileIterator>d__52`1.MoveNext()
12:54:29Error
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
12:54:29Error
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
12:54:29Error
   at Calamari.Deployment.Retention.RetentionPolicy.ApplyRetentionPolicy(String retentionPolicySet, Nullable`1 days, Nullable`1 releases) in y:\work\b1fd300731d5f2fc\source\Calamari\Deployment\Retention\RetentionPolicy.cs:line 36
12:54:29Error
   at Calamari.Commands.CleanCommand.Execute(String[] commandLineArguments) in y:\work\b1fd300731d5f2fc\source\Calamari\Commands\CleanCommand.cs:line 47
12:54:29Error
   at Calamari.Program.Main(String[] args) in y:\work\b1fd300731d5f2fc\source\Calamari\Program.cs:line 18
```

http://d.pr/i/1bz1N/5w81JMbo

https://www.dropbox.com/s/nvxin2teaj1atkf/ServerTasks-1819.log.txt?dl=0

**Comment by michaelnoonan** [comment]
Hi Igor,

Thanks for getting in touch! We are going to investigate this issue further and look to fixing it as soon as practical.

In the meantime can you tell me if the issue is still occurring? It should be intermittent.

Thanks!
Mike

**Comment by clain23** [comment]
Hi,

This issue occurred sporadically for 2 days until I've disabled retention.

We have many projects deploying to 1 machine during CI process, so it's looks like this file blocked during `Adding journal entry: <Deployment Id="...`

**Comment by Pondidum** [comment]
We are also getting this issue intermittently.
We are running Octopus Server 3.0.11.
It only seems to happen in our dev environment, which has around 20 projects triggered at the same time from our CI server.  
No apparent pattern in which project hits the issue (although all projects get triggered in the same order each time).

**Comment by MattLaw75** [comment]
Just to say "Me too". Just hit this now. We run are running 5 concurrent deployment projects at the time.

**Comment by zentron** [comment]
Thanks for the find guys. We tracked down this bug to a rouge IEnumerable which caused the reading of the deployment journal to take place outside the locks. It should be out in next release

**Comment by zentron** [comment]
Release Note: Applying retention policy avoids file system resource contention that was generating IO exceptions.

**Comment by Pondidum** [comment]
Thanks :+1:
