### ISSUE TITLE
Active directory hanging after few hours

### ISSUE THREAD

**Issue by Nepomuceno** [OctopusDeploy/Issues#1773]
After few hours that the server it is on and you are using AD integration the server it is not able to authenticate anyone it keeps checking credentials for ever.

This it is new for the version 3.0.5

**Comment by PaulStovell** [comment]
Does restarting the Octopus service fix it? 

We haven't changed any of the AD-related code in 3.0 compared to 2.6

**Comment by Nepomuceno** [comment]
Yes restarting the octopus service fix it

**Comment by Nepomuceno** [comment]
Yes you guys have changed the code on version 3.0 
https://github.com/OctopusDeploy/Issues/issues/1756

**Comment by Nepomuceno** [comment]
2015-07-31 15:28:04.9089     70  INFO  listen://0.0.0.0:10943/          70  Performing SSL (TLS 1.0) server handshake
2015-07-31 15:28:05.7213     13 ERROR  The server could not be contacted.
System.DirectoryServices.AccountManagement.PrincipalServerDownException: The server could not be contacted. ---> System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.SDSCache.GetContext(String name, NetCred credentials, ContextOptions contextOptions)
   at System.DirectoryServices.AccountManagement.AuthZSet.get_CurrentAsPrincipal()
   at System.DirectoryServices.AccountManagement.FindResultEnumerator`1.get_Current()
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.ReadGroups(IEnumerable`1 groupPrincipals, ICollection`1 groups) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 167
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetMemberExternalSecurityGroupIds(String username) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 124
2015-07-31 15:28:05.7895     20  INFO  listen://0.0.0.0:10943/          20  Accepted TCP client: 83.151.254.19:7309
2015-07-31 15:28:05.7895     71  INFO  listen://0.0.0.0:10943/          71  Performing SSL (TLS 1.0) server handshake
2015-07-31 15:28:06.0589     13 ERROR  The server is not operational.

Name: "my.active.directory.server"

System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException: The server is not operational.

Name: "my.active.directory.server"
 ---> System.Runtime.InteropServices.COMException: The server is not operational.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.ExpandWellKnownDN(WellKnownDN dn)
   at System.DirectoryServices.ActiveDirectory.DomainController.get_Domain()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)
   at System.DirectoryServices.AccountManagement.Principal.GetGroupsHelper()
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.ReadUserGroups(Principal principal, ICollection`1 groups) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 154
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetMemberExternalSecurityGroupIds(String username) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 133

**Comment by Damovisa** [comment]
Another reported instance: http://help.octopusdeploy.com/discussions/problems/39005

**Comment by michaelnoonan** [comment]
Will be fixed by OctopusDeploy/Issues#2001

**Comment by bdaniel7** [comment]
I'm running 3.3.6 and getting a "LdapException: The LDAP server is unavailable", even though the domain controller is available, replies to ping and can be queried using the AD Users and Computers console. After several restarts and refreshing the application page, the server does login.
A side note: TeamCity, which also uses AD authentication, doesn't have this problem.
Is there a way to implement a sort of caching of the users authentication?
Or maybe use the same mechanism as TeamCity?

This is the full stack trace:

```
System.DirectoryServices.AccountManagement.PrincipalServerDownException: The server could not be contacted. ---> System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container)
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetContext(String domain) in Y:\work\refs\tags\3.3.6\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 104
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetOrCreateUser(String username, Boolean& wasCreated) in Y:\work\refs\tags\3.3.6\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 228
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetOrCreateUser(IPrincipal principal) in Y:\work\refs\tags\3.3.6\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 343
   at Octopus.Server.Web.Infrastructure.Authentication.OctopusPrincipalEstablisher.GetPresentedUserIdentity(NancyContext context) in Y:\work\refs\tags\3.3.6\source\Octopus.Server\Web\Infrastructure\Authentication\OctopusPrincipalEstablisher.cs:line 98
   at Octopus.Server.Web.Infrastructure.Authentication.OctopusPrincipalEstablisher.EstablishPrincipalForRequest(NancyContext context) in Y:\work\refs\tags\3.3.6\source\Octopus.Server\Web\Infrastructure\Authentication\OctopusPrincipalEstablisher.cs:line 43
```

**Comment by michaelnoonan** [comment]
Hi! Can I get you to log a request with our support team on this one? They will be best suited to help you out.

https://octopus.com/support

Hope that helps!
Mike
