### ISSUE TITLE
Azure endpoints deployment failing on package aquistion

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1782]
Happens for all production deployments for customer.
They have tried multiple versions, works for dev and staging, but as soon as it hits production it fails, for a few different projects. Please see source for logs.
https://secure.helpscout.net/conversation/107663215/369/
Second source: http://help.octopusdeploy.com/discussions/problems/36431

```
No package for the action '6829b303-f5e9-4fa3-92f1-62037d66edc4' and machine 'Machines-25' was acquired.
11:43:42
Info
Guidance received: Fail
11:43:42
Error
No package for the action '6829b303-f5e9-4fa3-92f1-62037d66edc4' and machine 'Machines-25' was acquired. System.Collections.Generic.KeyNotFoundException: No package for the action '6829b303-f5e9-4fa3-92f1-62037d66edc4' and machine 'Machines-25' was acquired. at Octopus.Server.Orchestration.Deploy.Acquire.StagedPackageMap.Get(String actionId, String machineId) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Acquire\StagedPackageMap.cs:line 27 at Octopus.Server.Orchestration.Deploy.Package.PackageActionHandler.Execute(ActionCommand command, Machine machine) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Package\PackageActionHandler.cs:line 22 at Octopus.Server.Orchestration.Deploy.Guidance.ExecuteWithGuidance(Action callback) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Guidance.cs:line 73 at Octopus.Server.Orchestration.Deploy.DeploymentTaskController.ExecuteActions(PlannedStep step, Machine machine) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\DeploymentTaskController.cs:line 196 at Octopus.Shared.Tasks.OctoThreadClosure`1.Execute() in y:\work\refs\heads\master\source\Octopus.Shared\Tasks\OctoThreadClosure.cs:line 29 Octopus.Server version 3.0.6.2140
```

**Comment by Jevonius** [comment]
Hi,

We are seeing this too, publishing from a local server to an Azure smoketest box (though I'm not sure it's an Azure issue as the box is just a hosted VM that we uploaded).

In our case, it seems to be related to 'Manual intervention' steps - the 1 step we have before an Intervention succeeded, those after it failed.

**Our workaround:**
Disabling the step temporarily (by marking it as only for a different Environment) allowed all the other steps to succeed.

An example failure trace:
```
No package for the action 'c0e3b8c9-59a7-40fd-ab08-b28ad5e9c9be' and machine 'Machines-2' was acquired.
System.Collections.Generic.KeyNotFoundException: No package for the action 'c0e3b8c9-59a7-40fd-ab08-b28ad5e9c9be' and machine 'Machines-2' was acquired.
   at Octopus.Server.Orchestration.Deploy.Acquire.StagedPackageMap.Get(String actionId, String machineId) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Acquire\StagedPackageMap.cs:line 27
   at Octopus.Server.Orchestration.Deploy.Package.PackageActionHandler.Execute(ActionCommand command, Machine machine) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Package\PackageActionHandler.cs:line 22
   at Octopus.Server.Orchestration.Deploy.Guidance.Execute(Action callback) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\Guidance.cs:line 50
   at Octopus.Server.Orchestration.Deploy.DeploymentTaskController.ExecuteActions(PlannedStep step, Machine machine) in y:\work\refs\heads\master\source\Octopus.Server\Orchestration\Deploy\DeploymentTaskController.cs:line 196
   at Octopus.Shared.Tasks.OctoThreadClosure`1.Execute() in y:\work\refs\heads\master\source\Octopus.Shared\Tasks\OctoThreadClosure.cs:line 29
Octopus.Server version 3.0.6.2140
```

**Comment by djmnz** [comment]
We are having same issue. Our test environments all work fine, but they are single targets for deployment that include all the roles.
The production environment fail, and we have more than one environment deployment target and an authorisation step at the beginning.

The work around from @Jevonius worked for us - we disabled our manual intervention step.

**Comment by maartenba** [comment]
The workaround works, technically. However we do want to have the manual intervention step.

**Comment by pravin88** [comment]
Just to note, we see the same behaviour (Error message) in on-premise tentacles as well

**Comment by PaulStovell** [comment]
This will be fixed in today's release (3.0.7). 

The problem was that if the manual step happens *after* package acquisition, the acquired packages would be forgotten when the deployment resumed. It worked if the manual step happens before packages are acquired.

**Comment by maartenba** [comment]
:+1: awesome!

**Comment by Ugwum** [comment]
Thank this help me
