### ISSUE TITLE
Exception when Azure Management cert is password protected.

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1793]
From http://help.octopusdeploy.com/discussions/problems/36421

When adding an Azure management cert (pfx) that is password protected, Octopus returns this exception.

System.ArgumentNullException: Value cannot be null.
Parameter name: certificate
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Octopus.Shared.Security.Certificates.CertificateEncoder.DoFromBase64String(String thumbprint, String certificateString, X509Store store) in y:\work\refs\heads\master\source\Octopus.Shared\Security\Certificates\CertificateEncoder.cs:line 67
   at Octopus.Server.Web.Api.Rules.AzureCertificateThumbprintWillBeSet.AfterMapBeforeStore(AzureAccount model, AzureSubscriptionAccountResource resource, ISpecialRuleContext context) in y:\work\refs\heads\master\source\Octopus.Server\Web\Api\Rules\AzureCertificateThumbprintWillBeSet.cs:line 18
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRules[TRule](Action`2 ruleCallback) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 188
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.Execute() in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Api\CreateResponseDescriptor.cs:line 52
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 162
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\work\refs\heads\master\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 46
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by zentron** [comment]
Looks like we need to add optional password like we do for ssh keypairs

**Comment by zentron** [comment]
If the user lets OD generate the certificate it will be password free

**Comment by DamianMac** [comment]
Yep, In this instance the customer had an existing cert they wanted to use

**Comment by zentron** [comment]
Discussing this with @mjrichardson we decided that there is no real need to provide and store passwords since we already encrypt them internally. Will provide better error message and documentation on stripping passwords off `.pfx` files.

**Comment by zentron** [comment]
Ticket Closed: Documentation updated including sample script to strip password. Form & exception also updated to indicate password not required
