### ISSUE TITLE
Only log Error in GetMemberExternalSecurityGroupIds(String username) if it really fails

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#1850]
We've had several reports of this Error being logged even though users are able to sign in and their groups are identified successfully: `An error (1301) occurred while enumerating the groups.  The group's SID could not be resolved.`

We try two methods of getting the groups and log the Error if the first attempt fails but the second succeeds.

We should correct the logging so we don't mislead with false-negative error logs.

```
2015-08-06 12:49:13.7995    120 TRACE  Loading permissions for user: jamesr@redacted.net  
2015-08-06 12:49:13.8151    120 DEBUG  Finding external security groups for 'jamesr@redacted.net'...  
2015-08-06 12:49:13.9245    120 ERROR  An error (1301) occurred while enumerating the groups.  The group's SID could not be resolved.  
System.DirectoryServices.AccountManagement.PrincipalOperationException: An error (1301) occurred while enumerating the groups.  The group's SID could not be resolved.  
   at System.DirectoryServices.AccountManagement.SidList.TranslateSids(String target, IntPtr[] pSids)
   at System.DirectoryServices.AccountManagement.SidList..ctor(SID_AND_ATTR[] sidAndAttr)
   at System.DirectoryServices.AccountManagement.AuthZSet..ctor(Byte[] userSid, NetCred credentials, ContextOptions contextOptions, String flatUserAuthority, StoreCtx userStoreCtx, Object userCtxBase)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOfAZ(Principal p)
   at System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroupsHelper()
   at Octopus.Server.Web.Infrastructure.Authentication.ActiveDirectoryMembership.GetMemberExternalSecurityGroupIds(String username) in y:\work\refs\heads\master\source\Octopus.Server\Web\Infrastructure\Authentication\ActiveDirectoryMembership.cs:line 126
```

**Comment by IanMercer** [comment]
Release note: Eliminate false error report when querying Active Directory groups
