### ISSUE TITLE
Race condition building a signature file in a cluster

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1879]
Cannot create a file when that file already exists.

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Octopus.Shared.Packages.PackageDeltaFactory.BuildSignature(String nearestPackageFilePath, ISemaphore semaphore) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Shared\Packages\PackageDeltaFactory.cs:line 59
   at Octopus.Worker.Tentacles.PackageUploadMediator.UploadAndApplyDelta(PackageAcquisition acquisition, StoredPackage nearestLocalPackage, StoredPackage package, String fullPathOnRemoteMachine) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Worker\Tentacles\PackageUploadMediator.cs:line 204
   at Octopus.Worker.Tentacles.PackageUploadMediator.UploadPackageAsDelta(PackageAcquisition acquisition, IEnumerable`1 foundPackages, Stream package, String packageHash) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Worker\Tentacles\PackageUploadMediator.cs:line 152
   at Octopus.Worker.Tentacles.PackageUploadMediator.DownloadPackageAndPushToAgent(PackageAcquisition acquisition, PackageToAcquire packageToAcquire) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Worker\Tentacles\PackageUploadMediator.cs:line 89
   at Octopus.Server.Orchestration.Deploy.Acquire.AcquisitionService.AcquirePackages(Machine machine, PackageAcquisition acquisition, PackageToAcquire packageToAcquire, StagedPackageMap map, VariableDictionary variables) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Server\Orchestration\Deploy\Acquire\AcquisitionService.cs:line 104
   at Octopus.Server.Orchestration.Deploy.Acquire.AcquisitionService.<>c__DisplayClass2.<Run>b__0(Tuple`2 t) in y:\work\refs\heads\bug-taskOverload\source\Octopus.Server\Orchestration\Deploy\Acquire\AcquisitionService.cs:line 42
   at Octopus.Shared.Tasks.OctoThreadClosure`1.Execute() in y:\work\refs\heads\bug-taskOverload\source\Octopus.Shared\Tasks\OctoThreadClosure.cs:line 29
Octopus.Server version 3.1.0.2353

**Comment by tothegills** [comment]
Happens occasionally when in a cluster

**Comment by PaulStovell** [comment]
We use a system-wide semaphore to prevent two signatures being created, which obviously doesn't extend around the whole cluster. We might need to do some trickery around using a random file name and then renaming in case we do end up doing it twice.

**Comment by IanMercer** [comment]
Creating a parallel .lock file next to the file we want to create and then acquiring a lock on that file would be a good way to solve this: https://msdn.microsoft.com/en-us/library/system.io.filestream.lock(v=vs.110).aspx

**Comment by IanMercer** [comment]
See also ... http://stackoverflow.com/questions/31303474/concurrent-file-move-of-the-same-file
"Atomic" doesn't mean much as far as the file system is concerned. There may be other places we need to take a lock before doing what we otherwise assumed was an 'atomic' operation.

**Comment by tothegills** [comment]
Release note: Added a cluster-wide semaphore to avoid race condition while performing operations in a cluster
