### ISSUE TITLE
Installation fails when using AD Authentication

### ISSUE THREAD

**Issue by brianfeucht** [OctopusDeploy/Issues#193]
When running the installer using AD authentication, it fails with the following error.  I removed my AD information from the log.

Creating empty configuration file: E:\OctopusBeta\OctopusServer\OctopusServer.config
Saving instance: OctopusServer
Home directory set to: E:\OctopusBeta
Generating a new Master Key for this Octopus Server...
Master Key saved; use the Octopus Administration tool to back the key up.
Storage mode set to: Embedded
Allow checking for upgrades: True
Include usage statistics: True
Web authentication mode: Domain
Web force SSL: False
Web listen prefixes: http://localhost:8456/
Service stopped
You can browse the RavenDB server at: http://localhost:10930/
Creating default Octopus Server certificate
Creating default Windows Azure certificate
Creating default upgrade availability
Creating built-in role Project viewer
Creating built-in role Project contributor
Creating built-in role Project lead
Creating built-in role Project deployer
Creating built-in role Project initiator
Creating built-in role Environment viewer
Creating built-in role Environment manager
Creating built-in role System administrator
Creating default team Octopus Administrators
Creating default team Everyone
Creating default retention policy
Creating default backup configuration
Creating default SMTP configuration
## Creating default project group

A fatal exception occurred
System.IO.FileNotFoundException: Could not load file or assembly 'Octopus.Shared.XmlSerializers' or one of its dependencies. The system cannot find the file specified.
File name: 'Octopus.Shared.XmlSerializers'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.LoadWithPartialNameInternal(AssemblyName an, Evidence securityEvidence, StackCrawlMark& stackMark)
   at System.DirectoryServices.AccountManagement.UnsafeNativeMethods.IADsPathname.Retrieve(Int32 lnFormatType)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.LoadDomainInfo()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.get_DnsDomainName()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetAsPrincipal(Object storeObject, Object discriminant)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRefHelper(Type principalType, String urnScheme, String urnValue, DateTime referenceDate, Boolean useSidHistory)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRef(Type principalType, String urnScheme, String urnValue, DateTime referenceDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   at Octopus.Server.Commands.AdminCommand.Start() in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Server\Commands\AdminCommand.cs:line 69
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Shared\Startup\ConsoleHost.cs:line 36

=== Pre-bind state information ===
LOG: User = domain\XXXXX
LOG: DisplayName = Octopus.Shared.XmlSerializers
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: Octopus.Shared.XmlSerializers | Domain ID: 1
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/Program Files (x86)/Octopus/Server/
LOG: DEVPATH = C:\ProgramData\Red Gate.NET Reflector\DevPath
LOG: Initial PrivatePath = NULL
# Calling assembly : System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Octopus\Server\Octopus.Server.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Octopus/Server/Octopus.Shared.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Octopus/Server/Octopus.Shared.XmlSerializers/Octopus.Shared.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Octopus/Server/Octopus.Shared.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Octopus/Server/Octopus.Shared.XmlSerializers/Octopus.Shared.XmlSerializers.EXE.

---

Error: The previous command returned a non-zero exit code of: 100
Error: The command that failed was: "C:\Program Files (x86)\Octopus\Server\Octopus.Server.exe" admin --instance "OctopusServer" --username "XXXXX" --wait 5000

**Comment by prebenh** [comment]
The same exception is raised when you configure octopus server over command line to use Active directory.
Only when you do not specify a domain.

Does not work:
```
Octopus.Server.exe admin --username=YOURUSERNAME
```
Works: 
```
Octopus.Server.exe admin --username=DOMAIN\YOURUSERNAME
```

**Comment by AwaNoodle** [comment]
I'm encountering the same issue. I've attempted a 2.6 -> 3.2 upgrade and have got the error:

```
2016-02-05 17:23:05.7057      1  INFO  Creating default Octopus Server certificate
2016-02-05 17:23:06.6264      1 ERROR  ===============================================================================
2016-02-05 17:23:06.6420      1 FATAL  Could not load file or assembly 'Octopus.Shared.XmlSerializers' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Octopus.Shared.XmlSerializers' or one of its dependencies. The system cannot find the file specified.
File name: 'Octopus.Shared.XmlSerializers'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.LoadWithPartialNameInternal(AssemblyName an, Evidence securityEvidence, StackCrawlMark& stackMark)
```

I've installed the hotfix which hasn't altered anything. The file it is looking for isn't part of the install package or the installed directory. Does anyone have any suggestions?

**Comment by michaelnoonan** [comment]
Hi @AwaNoodle - I'd recommend getting in touch with our [support team](https://octopus.com/support) to get help with this issue. Hope that helps!
