### ISSUE TITLE
ImporterController.ImportScript() is finding duplicate Steps and/or Actions and throwing

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2024]
When importing Scripts from another 3.x instance the migrator is failing claiming to have found duplicate Actions and throws. It looks like the matching code is too permissive.

```
2015-09-23 02:27:17.3882      1 FATAL  System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleTSource
   at Octopus.Migrator.ImportProcess.ImportController.ImportScript(ImportContext context, String scriptFile) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 449
   at Octopus.Migrator.ImportProcess.ImportController.ImportScripts(ImportContext context) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 410
   at Octopus.Migrator.ImportProcess.ImportController.Import(IImportedDocumentSource backup) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 112
   at Octopus.Migrator.Commands.ImportFilesCommand.Start() in Y:\work\refs\heads\master\source\Octopus.Migrator\Commands\ImportFilesCommand.cs:line 90
   at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in Y:\work\refs\heads\master\source\Octopus.Shared\Startup\AbstractCommand.cs:line 57
   at Octopus.Shared.Startup.ConsoleHost.Run(Action1 start, Action shutdown) in Y:\work\refs\heads\master\source\Octopus.Shared\Startup\ConsoleHost.cs:line 36
2015-09-23 02:27:17.4819      1 FATAL  Sequence contains more than one matching element
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable1 source, Func2 predicate)
   at Octopus.Migrator.ImportProcess.ImportController.ImportScript(ImportContext context, String scriptFile) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 449
   at Octopus.Migrator.ImportProcess.ImportController.ImportScripts(ImportContext context) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 410
   at Octopus.Migrator.ImportProcess.ImportController.Import(IImportedDocumentSource backup) in Y:\work\refs\heads\master\source\Octopus.Migrator\ImportProcess\ImportController.cs:line 112
   at Octopus.Migrator.Commands.ImportFilesCommand.Start() in Y:\work\refs\heads\master\source\Octopus.Migrator\Commands\ImportFilesCommand.cs:line 90
   at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in Y:\work\refs\heads\master\source\Octopus.Shared\Startup\AbstractCommand.cs:line 57
   at Octopus.Shared.Startup.ConsoleHost.Run(Action1 start, Action shutdown) in Y:\work\refs\heads\master\source\Octopus.Shared\Startup\ConsoleHost.cs:line 81
   at Octopus.Shared.Startup.OctopusProgram.Run() in Y:\work\refs\heads\master\source\Octopus.Shared\Startup\OctopusProgram.cs:line 73
```

This is happening in `3.0.15` but will also happen in later releases up to the current at time of writing.

The possible workaround is to name the Steps and Actions uniquely without using a common prefix.

Source: http://help.octopusdeploy.com/discussions/problems/39281-error-on-import
Potentially related: https://secure.helpscout.net/conversation/122787293/1782/

**Comment by Dalmirog** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/40408

**Comment by zentron** [comment]
This looks to be because the names for the script files are concatinated using 
`<ProjectName> - <StepName> - <ActionName>.ps1`
with custom scripts added as
`<ProjectName> - <StepName> - <ActionName> - [PreDeply|PostDeploy|Deploy].ps1`

This causes problems where the step name also has the `-` special character in it.
I see two possible work arounds.

1. We start making the export escape the special character in their names and parse them back when reading.
2. We break up the scripts into separate subfolders instead of using special characters to differentiate.

In my opinion option 1 allows us to more easily be backwards compatible with importing the vast majority of previous exports (assuming they weren't encountering this problem). It also leads to a flatter (simpler) export file structure.

**Comment by zentron** [comment]
Leaning towards option 2 now as its more likely to be failsafe. It does mean a bit more tweaking to import to be backwards compatible.

**Comment by zentron** [comment]
Release Node: Allow migrator to import step scripts where one step name may be a sub path of another
