### ISSUE TITLE
Error setting up a new tentacle on Octo Server 3.1.3

### ISSUE THREAD

**Issue by bDino** [OctopusDeploy/Issues#2053]
Hey there,

i'm having issues setting up a new tentacle after upgrading our octo server to the newest version. Couldn't find any solutions..

After installing the tentacle (3.1.3) i get the following error message:

Connecting to server: http://myOcto.de
Connected successfully, Octopus Server version: 3.1.3
Authenticating as administrator...
Authenticated successfully
Getting available roles...
Error: You must be logged in to perform this action. Please provide a valid API key or log in again.
Octopus.Client.Exceptions.OctopusSecurityException: You must be logged in to perform this action. Please provide a valid API key or log in again.
   at Octopus.Client.OctopusClient.DispatchRequest[TResponseResource](OctopusRequest request, Boolean readResponse) in Y:\work\refs\tags\3.1.3\source\Octopus.Client\OctopusClient.cs:line 457
   at Octopus.Client.OctopusClient.Get[TResource](String path, Object pathParameters) in Y:\work\refs\tags\3.1.3\source\Octopus.Client\OctopusClient.cs:line 83
   at Octopus.Client.OctopusRepository.MachineRoleRepository.GetAllRoleNames() in Y:\work\refs\tags\3.1.3\source\Octopus.Client\OctopusRepository.cs:line 690

I also tried various hostnames but nothing worked
https://myOcto.de
https://myOcto.de:10943
http://myOcto.de

The target mashines are Windows Server 2008 R2 SP1 and Windows Server 2012
I also tried an older tentacle version (3.0.21) on the WS 2008 R2 because of the SP1 Issue with the 3.1.3 tentacle.

Any ideas?

Thanks!!

**Comment by Dalmirog** [comment]
Please use the forum http://help.OctopusDeploy.com for these kind of questions. Will continue the conversation here: http://help.octopusdeploy.com/discussions/problems/40057-issue-setting-up-a-new-tentacle-on-octopus-313 .
