### ISSUE TITLE
System.ArgumentNullException when changing empty variable type to sensitive

### ISSUE THREAD

**Issue by ajakuszyk** [OctopusDeploy/Issues#2081]
Steps to reproduce (Octopus 3.1.2)

1. Go to project variables
2. Create new variable and assign no value to it
3. Press 'Save' button
4. Change new variable value type to 'sensitive'
5. Press 'Save' button

The result is the following error on screen:

System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at Octopus.Shared.Security.MasterKey.MasterKeyEncryptionExtensions.StringToCiphertext(IMasterKeyEncryption encryption, String plaintext) in Y:\work\refs\tags\3.1.2\source\Octopus.Shared\Security\MasterKey\MasterKeyEncryptionExtensions.cs:line 12
   at Octopus.Core.RelationalStorage.VariableConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in Y:\work\refs\tags\3.1.2\source\Octopus.Core\RelationalStorage\VariableConverter.cs:line 38
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at Octopus.Server.EventStore.CaptureDiff[TDocument](IRelationalTransaction session, Event event, TDocument model) in Y:\work\refs\tags\3.1.2\source\Octopus.Server\EventStore.cs:line 74
   at Octopus.Server.EventStore.Store[TDocument](IRelationalTransaction session, Event event, TDocument model, IOctopusPrincipal currentPrincipal) in Y:\work\refs\tags\3.1.2\source\Octopus.Server\EventStore.cs:line 69
   at Octopus.Server.Web.Api.Actions.VariableSetUpdateAction.Execute() in Y:\work\refs\tags\3.1.2\source\Octopus.Server\Web\Api\Actions\VariableSetUpdateAction.cs:line 127
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in Y:\work\refs\tags\3.1.2\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 162
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass0_0.<.ctor>b__0(Object o) in Y:\work\refs\tags\3.1.2\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 46
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by mjrichardson** [comment]
Release note:Resolved issue saving empty sensitive variables
