### ISSUE TITLE
Deployments to Offline Package Drops fail when multiple steps use same NuGet-package

### ISSUE THREAD

**Issue by allansson** [OctopusDeploy/Issues#2090]
We are using a step template to deploy a NuGet-package with slightly different configuration. Our project uses this step template multiple times in its process, e.g.

1. Install App for Customer 1
2. Install App for Customer 2

When creating a release and deploying it to a Offline Package Drop, we _occasionally_ receive the following error (slightly redacted):

```
10:01:14   Info     |     Making a list of packages to download
10:01:15   Info     |     Looking up the package location from the built-in package repository...
10:01:15   Verbose  |     SHA1 hash of package MyPackage is: cc5d91e79c3ff49284ff0ee5720175ec489668ba
10:01:15   Fatal    |     The step failed: One or more child activities failed.
10:01:15   Verbose  |     Acquire Packages completed
                    |     
10:01:15   Error    |       The process cannot access the file '\\localhost\c$\Octopus\Drop\Dev\My Project\0.0.7\Packages\MyPackage.1.0.0.0.nupkg' because it is being used by another process.
                    |       System.IO.IOException: The process cannot access the file '\\localhost\c$\Octopus\Drop\Dev\My Project\0.0.7\Packages\MyPackage.1.0.0.0.nupkg' because it is being used by another process.
                    |       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    |       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
                    |       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
                    |       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    |       at Octopus.Shared.Util.OctopusPhysicalFileSystem.OpenFile(String path, FileMode mode, FileAccess access, FileShare share) in Y:\work\refs\tags\3.1.3\source\Octopus.Shared\Util\OctopusPhysicalFileSystem.cs:line 184
                    |       at Octopus.Worker.OfflineDrop.OfflineDropBatch.StagePackage(RequiredPackage requiredPackage, IPackageSource packageSource, TargetManifest targetManifest) in Y:\work\refs\tags\3.1.3\source\Octopus.Worker\OfflineDrop\OfflineDropBatch.cs:line 65
                    |       at Octopus.Worker.OfflineDrop.OfflineDropWorker.StagePackage(RequiredPackage acquisition, IPackageSource packageSource, TargetManifest targetManifest) in Y:\work\refs\tags\3.1.3\source\Octopus.Worker\OfflineDrop\OfflineDropWorker.cs:line 28
                    |       at Octopus.Server.Orchestration.Deploy.Acquire.AcquireMachinePackageTask.Acquire(AcquiredPackageMap acquiredPackageMap) in Y:\work\refs\tags\3.1.3\source\Octopus.Server\Orchestration\Deploy\Acquire\AcquireMachinePackageTask.cs:line 27
                    |       at Octopus.Shared.Tasks.OctoThreadClosure`1.Execute() in Y:\work\refs\tags\3.1.3\source\Octopus.Shared\Tasks\OctoThreadClosure.cs:line 29
                    |       Octopus.Server version 3.1.3 (3.1.3+Branch.master.Sha.645480fc4eeb916ceefd1725a1d0a80493cabfb6)
                    |     
                    |       Running: Upload package MyPackage 1.0.0.0
10:01:15   Info     |         Uploading package to '\\localhost\c$\Octopus\Drop\Dev\My Project\0.0.7\Packages'
10:01:15   Verbose  |         SHA1 hash of package is cc5d91e79c3ff49284ff0ee5720175ec489668ba
                    |       
                    |       Success: Upload package MyPackage 1.0.0.0
10:01:15   Info     |         Uploading package to '\\localhost\c$\Octopus\Drop\Dev\My Project\0.0.7\Packages'
10:01:15   Verbose  |         SHA1 hash of package is cc5d91e79c3ff49284ff0ee5720175ec489668ba

```

It seems that during the Acquire Packages step in the deployment, the same package is being uploaded to the deployment target twice. This apparently causes some race condition causing the deployments to fail every once in a while.

**Comment by campearce** [comment]
+1

**Comment by ceilingfish** [comment]
+1

**Comment by DamianMac** [comment]
Release Note: Added locking to prevent errors with multiple packages in offline drops
