### ISSUE TITLE
SQL timeout when trying to delete environment

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2214]
The timeout is actually getting related documents, I think it is because their database is so large.

Refer to: https://secure.helpscout.net/conversation/145457810/3499/?folderId=571723

**Comment by tothegills** [comment]
System.Data.SqlClient.SqlException (0x80131904): Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)

at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

at System.Data.SqlClient.SqlDataReader.get_MetaData()

at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)

at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)

at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)

at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)

at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)

at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()

at Octopus.Core.RelationalStorage.TransientFaultHandling.IDbCommandExtensions.<>c__DisplayClass5_0.<ExecuteReaderWithRetry>b__0() in Y:\work\refs\tags\3.2.8\source\Octopus.Core\RelationalStorage\TransientFaultHandling\IDbCommandExtensions.cs:line 67

at Octopus.Shared.TransientFaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in Y:\work\refs\tags\3.2.8\source\Octopus.Shared\TransientFaultHandling\RetryPolicy.cs:line 215

at Octopus.Core.RelationalStorage.RelationalTransaction.<Stream>d__24`1.MoveNext() in Y:\work\refs\tags\3.2.8\source\Octopus.Core\RelationalStorage\RelationalTransaction.cs:line 241

at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

at Octopus.Core.Persistence.Indexes.DocumentUsageFinder.RelationshipBuilder`2.FindUsages(IRelationalTransaction transaction, Object from, List`1 referencingDocuments) in Y:\work\refs\tags\3.2.8\source\Octopus.Core\Persistence\Indexes\DocumentUsageFinder.cs:line 314

at Octopus.Core.Persistence.Indexes.DocumentUsageFinder.FindReferences[TDocument](IRelationalTransaction transaction, TDocument document) in Y:\work\refs\tags\3.2.8\source\Octopus.Core\Persistence\Indexes\DocumentUsageFinder.cs:line 269

at Octopus.Server.Web.Infrastructure.Api.DeleteOnBackgroundResponseDescriptor`2.Responder.CheckForVetoRules(TModel model) in Y:\work\refs\tags\3.2.8\source\Octopus.Server\Web\Infrastructure\Api\DeleteOnBackgroundResponseDescriptor.cs:line 103

at Octopus.Server.Web.Infrastructure.Api.DeleteOnBackgroundResponseDescriptor`2.Responder.Execute() in Y:\work\refs\tags\3.2.8\source\Octopus.Server\Web\Infrastructure\Api\DeleteOnBackgroundResponseDescriptor.cs:line 59

at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in Y:\work\refs\tags\3.2.8\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 162

at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)

at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )

at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass0_0.<.ctor>b__0(Object o) in Y:\work\refs\tags\3.2.8\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 46

at CallSite.Target(Closure , CallSite , Func`2 , Object )

at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

ClientConnectionId:3f214bae-ab26-42ae-8463-e0d9b21fe222

**Comment by michaelnoonan** [comment]
To fix this issue properly we really need to profile Octopus running against this database.

**Comment by tothegills** [comment]
See also: http://help.octopusdeploy.com/discussions/problems/43717

**Comment by tothegills** [comment]
Release note: Increased delete performance when deleting documents that may be used in variable sets or deployment processes
