### ISSUE TITLE
Path to long when extracting nuget package to install folder.

### ISSUE THREAD

**Issue by dazinator** [OctopusDeploy/Issues#2217]
I have packaged up an ASP.NET 5 application into a NuGet package. When deploying this NuGet Package through Octopus (standard NuGet package step with no optional features) - the deployment falls over with this error:

```

Deploying package 'C:\Octopus\Files\WebApplication.Mvc.1.0.490.nupkg-bc3e15a8-e654-4d96-8057-5d374a700c0b' to machine 'https://rchdevweb01:10933/'
12:05:07Info
Deploying package:    C:\Octopus\Files\WebApplication.Mvc.1.0.490.nupkg-bc3e15a8-e654-4d96-8057-5d374a700c0b
12:05:12Error
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
12:05:12Error
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
12:05:12Error
   at System.IO.Path.GetDirectoryName(String path)
12:05:12Error
   at Calamari.Integration.Packages.LightweightPackageExtractor.Install(String packageFile, String directory, Boolean suppressNestedScriptWarning, Int32& filesExtracted) in Y:\work\14ffc968155e4956\source\Calamari\Integration\Packages\LightweightPackageExtractor.cs:line 79
12:05:12Error
   at Calamari.Deployment.Conventions.ExtractPackageConvention.Install(RunningDeployment deployment) in Y:\work\14ffc968155e4956\source\Calamari\Deployment\Conventions\ExtractPackageConvention.cs:line 28
12:05:12Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 60
12:05:12Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 28
12:05:12Error
Running rollback conventions...
12:05:12Error
System.ArgumentNullException: Value cannot be null.
12:05:12Error
Parameter name: path
12:05:12Error
   at System.IO.DirectoryInfo..ctor(String path)
12:05:12Error
   at Calamari.Integration.FileSystem.CalamariPhysicalFileSystem.EnumerateFiles(String parentDirectoryPath, String[] searchPatterns) in Y:\work\14ffc968155e4956\source\Calamari\Integration\FileSystem\CalamariPhysicalFileSystem.cs:line 179
12:05:12Error
   at Calamari.Integration.Scripting.PackagedScriptRunner.FindScripts(RunningDeployment deployment) in Y:\work\14ffc968155e4956\source\Calamari\Integration\Scripting\PackagedScriptRunner.cs:line 55
12:05:12Error
   at Calamari.Integration.Scripting.PackagedScriptRunner.RunScripts(RunningDeployment deployment) in Y:\work\14ffc968155e4956\source\Calamari\Integration\Scripting\PackagedScriptRunner.cs:line 29
12:05:12Error
   at Calamari.Deployment.ConventionProcessor.RunRollbackConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 69
12:05:12Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 48
12:05:12Error
   at Calamari.Commands.DeployPackageCommand.Execute(String[] commandLineArguments) in Y:\work\14ffc968155e4956\source\Calamari\Commands\DeployPackageCommand.cs:line 103
12:05:12Error
   at Calamari.Program.Execute(String[] args) in Y:\work\14ffc968155e4956\source\Calamari\Program.cs:line 38
12:05:13Error
The remote script failed with exit code 100
```

This is telling me that some file within the NuGet package, has a full path that is too long for windows to cope with.

Please can it tell me which files? 

I would love for octopus to do a check in advance of extracting the package to disk, to check to make sure that no files will exceed this limit, and then to raise a more informative error about the problematic files if it finds any.

This will also save it leaving a package half extracted to the installation directory!

**Comment by dazinator** [comment]
Unfortunately, even changing the tentacle's app dir to something short, and trying to use a short custom installation dir on the package step - still results in this same exception, there seems to be no way I can make the extracted path short enough. I have logged a support issue: http://help.octopusdeploy.com/discussions/problems/43158-path-too-long-exception

I think this could be viewed as a bug, because it seems you cant directly take control of the length of the directory the package is extracted to - octopus automatically appends the nuget pacakge name to the path, and the environment name, so it would require attempting to use a very short package name (which you may not directly be in control of) and a very short environment name (ours are already short) to try and bring the extraction path down.

**Comment by dazinator** [comment]
The only way I could resolve this problem was to change the name of my nuget package to be something shorter (3 characters) in combination with changing the tentacle app dir to be "E:/App". The envrionment name was allready short "Dev".

**Comment by dazinator** [comment]
Hi @vanessalove - this is still an issue with octopus as far as I know - is there a reason for the closure? I have managed to find a workaround but really, I was kind of hoping Octopus would deal with this problem in a future version..?

**Comment by vanessalove** [comment]
@dazinator I will respond to your ticket about our solutions and your issue. But please read our https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md Contributing guideline and https://octopus.com/company/roadmap/why-was-this-closed why we close issues

**Comment by dazinator** [comment]
@vanessalove - ah ok sorry didn't realise you aren't meant to create issues here directly.. thanks.

**Comment by dazinator** [comment]
@vanessalove - as a side note - imho the text in bold here: https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md

Could really do with being put on the README here: https://github.com/OctopusDeploy/Issues so it's immediately visible to idiots like me! ;)

**Comment by OxanaAngel** [comment]
What about using Long Path Tool? It's very helpful.

**Comment by dazinator** [comment]
@OxanaAngel - what's long path tool? Could you elaborate :)
