### ISSUE TITLE
Export crashes when exporting variable set

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2249]
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Octopus.Shared.Util.OctopusPhysicalFileSystem.EqualHash(Stream first, Stream second) in Y:\work\refs\tags\3.2.13\source\Octopus.Shared\Util\OctopusPhysicalFileSystem.cs:line 507
at Octopus.Shared.Util.OctopusPhysicalFileSystem.Replace(String oldFilePath, Stream newStream, Int32 overwriteFileRetryAttempts) in Y:\work\refs\tags\3.2.13\source\Octopus.Shared\Util\OctopusPhysicalFileSystem.cs:line 494
at Octopus.Migrator.ExportProcess.ExportController.ExportAttachments(IId obj) in Y:\work\refs\tags\3.2.13\source\Octopus.Migrator\ExportProcess\ExportController.cs:line 488
at Octopus.Migrator.ExportProcess.ExportController.WriteProjects(ExportContext context) in Y:\work\refs\tags\3.2.13\source\Octopus.Migrator\ExportProcess\ExportController.cs:line 316
at Octopus.Migrator.ExportProcess.ExportController.Export() in Y:\work\refs\tags\3.2.13\source\Octopus.Migrator\ExportProcess\ExportController.cs:line 92
at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in Y:\work\refs\tags\3.2.13\source\Octopus.Shared\Startup\AbstractCommand.cs:line 57
at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown) in Y:\work\refs\tags\3.2.13\source\Octopus.Shared\Startup\ConsoleHost.cs:line 72
at Octopus.Shared.Startup.OctopusProgram.Run() in Y:\work\refs\tags\3.2.13\source\Octopus.Shared\Startup\OctopusProgram.cs:line 87
Error: The previous command returned a non-zero exit code of: 100
```

Source: https://secure.helpscout.net/conversation/151765423/3829/

**Comment by robpearson** [comment]
Release Note: Export process is not more resilient when saving files to disk.
