### ISSUE TITLE
Calamari bug when transforming simple XML

### ISSUE THREAD

**Issue by nkomp18** [OctopusDeploy/Issues#2513]
If you have a simple xml

```
<?xml version="1.0"?> 
<rootElement>
 ...
</rootElement>
```

 and you try to transform it with:

```
<?xml version="1.0"?> 
<rootElement xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform" xdt:Transform="Remove">
 ...
</rootElement>
```

Calamari will give an error. Note that this previews and transforms fine with local tools or with the msTask builder. It only fails when transformed with Calamari. 

Also the "Replace" command works well. It only crashed on "Remove".

The full stack of the error is pasted below

```
System.Xml.XmlException: Root element is missing.
19:40:42Error
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
19:40:42Error
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
19:40:42Error
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
19:40:42Error
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
19:40:42Error
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
19:40:42Error
   at Calamari.Integration.ConfigurationVariables.ConfigurationVariablesReplacer.ReadXmlDocument(String configurationFilePath) in Y:\work\14ffc968155e4956\source\Calamari\Integration\ConfigurationVariables\ConfigurationVariablesReplacer.cs:line 62
19:40:42Error
   at Calamari.Integration.ConfigurationVariables.ConfigurationVariablesReplacer.ModifyConfigurationFile(String configurationFilePath, VariableDictionary variables) in Y:\work\14ffc968155e4956\source\Calamari\Integration\ConfigurationVariables\ConfigurationVariablesReplacer.cs:line 53
19:40:42Error
   at Calamari.Deployment.Conventions.ConfigurationVariablesConvention.Install(RunningDeployment deployment) in Y:\work\14ffc968155e4956\source\Calamari\Deployment\Conventions\ConfigurationVariablesConvention.cs:line 32
19:40:42Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 60
19:40:42Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 28
19:40:42Error
Running rollback conventions...
19:40:42Error
System.Xml.XmlException: Root element is missing.
19:40:42Error
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
19:40:42Error
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
19:40:42Error
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
19:40:42Error
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
19:40:42Error
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
19:40:42Error
   at Calamari.Integration.ConfigurationVariables.ConfigurationVariablesReplacer.ReadXmlDocument(String configurationFilePath) in Y:\work\14ffc968155e4956\source\Calamari\Integration\ConfigurationVariables\ConfigurationVariablesReplacer.cs:line 62
19:40:42Error
   at Calamari.Integration.ConfigurationVariables.ConfigurationVariablesReplacer.ModifyConfigurationFile(String configurationFilePath, VariableDictionary variables) in Y:\work\14ffc968155e4956\source\Calamari\Integration\ConfigurationVariables\ConfigurationVariablesReplacer.cs:line 53
19:40:42Error
   at Calamari.Deployment.Conventions.ConfigurationVariablesConvention.Install(RunningDeployment deployment) in Y:\work\14ffc968155e4956\source\Calamari\Deployment\Conventions\ConfigurationVariablesConvention.cs:line 32
19:40:42Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 60
19:40:42Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() in Y:\work\14ffc968155e4956\source\Calamari\Deployment\ConventionProcessor.cs:line 50
19:40:42Error
   at Calamari.Commands.DeployPackageCommand.Execute(String[] commandLineArguments) in Y:\work\14ffc968155e4956\source\Calamari\Commands\DeployPackageCommand.cs:line 110
19:40:42Error
   at Calamari.Program.Execute(String[] args) in Y:\work\14ffc968155e4956\source\Calamari\Program.cs:line 38
19:40:43Fatal
The remote script failed with exit code 100
```

**Comment by vanessalove** [comment]
Hi @nkomp18, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
