### ISSUE TITLE
Pushing packages to Octopus server: System.ArgumentException:

### ISSUE THREAD

**Issue by lavrenov** [OctopusDeploy/Issues#2641]
Pushing packages to Octopus server: System.ArgumentException:

Octopus 3.3.27

So here is my log from TeamCity, I have also tried to download latest command line tool, same result:
[21:31:29][Octopus Deploy] Running command:   octo.exe push --server http://octopus.xxx.xxx.xxx:7890 --apikey SECRET --package C:\xxx\xxx\.nupkg --replace-existing
[21:31:29][Octopus Deploy] Pushing packages to Octopus server
[21:31:29][Octopus Deploy] Octopus Deploy Command Line Tool, version 3.3.8+Branch.master.Sha.f8a34fc6097785d7d382ddfaa9a7f009f29bc5fb
[21:31:29][Octopus Deploy] 
[21:31:30][Octopus Deploy] Handshaking with Octopus server: http://octopus.xxx.xxx.xxx:7890 
[21:31:31][Octopus Deploy] System.ArgumentException: Specified value has invalid Control characters.
[21:31:31][Octopus Deploy] Parameter name: value
[21:31:31][Octopus Deploy]    at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
[21:31:31][Octopus Deploy]    at System.Net.WebHeaderCollection.Set(String name, String value)
[21:31:31][Octopus Deploy]    at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
[21:31:31][Octopus Deploy]    at Octopus.Client.OctopusClient.DispatchRequest[TResponseResource](OctopusRequest request, Boolean readResponse)
[21:31:31][Octopus Deploy]    at Octopus.Client.OctopusClient.Get[TResource](String path, Object pathParameters)
[21:31:31][Octopus Deploy]    at Octopus.Client.OctopusClient.EstablishSession()
[21:31:31][Octopus Deploy]    at System.Lazy`1.CreateValue()
[21:31:31][Octopus Deploy]    at System.Lazy`1.LazyInitValue()
[21:31:31][Octopus Deploy]    at System.Lazy`1.get_Value()
[21:31:31][Octopus Deploy]    at Octopus.Client.OctopusClient.get_RootDocument()
[21:31:31][Octopus Deploy]    at Octopus.Cli.Commands.ApiCommand.Execute(String[] commandLineArguments)
[21:31:31][Octopus Deploy]    at Octopus.Cli.Program.Main(String[] args)
[21:31:31][Octopus Deploy] Exit code: -3
[21:31:31][Octopus Deploy] Octo.exe exit code: -3

**Comment by matt-richardson** [comment]
Hi @lavrenov, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
