### ISSUE TITLE
"'' is not a valid version string" for package dependencies

### ISSUE THREAD

**Issue by kowalgta** [OctopusDeploy/Issues#2785]
If nuget package specification file contains dependency with version="" package fails to be deployed with the exception.

    '' is not a valid version string.
    System.ArgumentException: '' is not a valid version string.
    at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
    at NuGet.Packaging.ManifestReader.<>c.<ReadDependencies>b__9_3(<>f__AnonymousType7`2 <>h__TransparentIdentifier1)
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at NuGet.Packaging.ManifestReader.ReadDependencyGroups(XElement dependenciesElement)
    at NuGet.Packaging.ManifestReader.ReadMetadataValue(ManifestMetadata manifestMetadata, XElement element, HashSet`1 allElements)
    at NuGet.Packaging.ManifestReader.ReadMetadata(XElement xElement)
    at NuGet.Packaging.ManifestReader.ReadManifest(XDocument document)
    at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
    at Octopus.Core.Packages.NuGet.LocalNuGetPackage.ReadMetadata(String filePath, Nullable`1& createdDate) in Y:\Work\refs\tags\3.4.8\source\Octopus.Core\Packages\NuGet\LocalNuGetPackage.cs:line 97
    at Octopus.Core.Packages.NuGet.LocalNuGetPackage..ctor(String filePath) in Y:\Work\refs\tags\3.4.8\source\Octopus.Core\Packages\NuGet\LocalNuGetPackage.cs:line 27
    at Octopus.Core.Packages.PackageDownloader.AttemptToFindAndDownloadPackage(Int32 attempt, PackageIdentifier packageIdentifier, IFeed feed, String cacheDirectory, IPackage& downloadedPackage, String& path) in Y:\Work\refs\tags\3.4.8\source\Octopus.Core\Packages\PackageDownloader.cs:line 154
    at Octopus.Core.Packages.PackageDownloader.AttemptToDownload(PackageIdentifier packageIdentifier, IFeed feed) in Y:\Work\refs\tags\3.4.8\source\Octopus.Core\Packages\PackageDownloader.cs:line 102
    Octopus.Server version 3.4.8 (3.4.8+Branch.master.Sha.3b954a4f3454a6e57742a7a5d5d9e2708a12f454)

If the version="" is omitted than there is no problem.

Prior to version 3.4.8 version="" worked fine. Because of this problem we are unable to deploy some of the historical packages.

**Comment by Dalmirog** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

**Comment by Dalmirog** [comment]
Hi @kowalgta - I found this ticket in our queue with the exact same question: http://help.octopusdeploy.com/discussions/problems/47742

We'll answer you on that forum as soon as we can. Thanks!
