### ISSUE TITLE
Catch and log the exception we get when the Tentacle/Server connection drops

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#2914]
At the moment when the Tentacle/Server Halibut connection is lost we dump out an unhandled IOException. We really should be catching this and logging and Info level message "Tentacle connection lost, reconnecting..." or something. Maybe a note that if deployments are working fine this is nothing to worry about, but may point to network issues if it is regular?

Full stack trace:
```
nhandled error when handling request from client: [::ffff:192.168.1.1]:64551
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- End of inner exception stack trace ---
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamReader.ReadBuffer()
at System.IO.StreamReader.ReadLine()
at Halibut.Transport.Protocol.MessageExchangeStream.ReadLine() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 93
at Halibut.Transport.Protocol.MessageExchangeStream.ExpectNextOrEnd() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 67
at Halibut.Transport.Protocol.MessageExchangeProtocol.ProcessClientRequests(Func`2 incomingRequestProcessor) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 110
at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsServer(Func`2 incomingRequestProcessor, Func`2 pendingRequests) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 95
at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\SecureListener.cs:lin
```

**Comment by MarcoJ-CID** [comment]
Hi @all.
Same Issue here. 
Every hour we got this Stacktrace in our Tentacle logfiles.

We're still running Octopus in version 3.4.11. 
````
2016-12-05 11:44:51.9037     91  INFO  listen://[::]:10933/             91  Accepted TCP client: [::ffff:IP_REMOVED]:42320
2016-12-05 11:44:51.9193     82  INFO  listen://[::]:10933/             82  Performing TLS server handshake
2016-12-05 11:44:51.9349     82  INFO  listen://[::]:10933/             82  Secure connection established, client is not yet authenticated, client connected with Tls12
2016-12-05 11:44:51.9349     82  INFO  listen://[::]:10933/             82  Client at [::ffff:IP_REMOVED]:42320 authenticated as THISISOURTHUMBPRINTOFTHEOCTOPUSSERVER123
2016-12-05 11:54:52.9993     82  INFO  listen://[::]:10933/             82  Unhandled error when handling request from client: [::ffff:IP_REMOVED]:42320
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadLine() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 93
   at Halibut.Transport.Protocol.MessageExchangeStream.ExpectNextOrEnd() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 67
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ProcessClientRequests(Func`2 incomingRequestProcessor) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 110
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\SecureListener.cs:line 140
2016-12-05 12:45:19.1374     91  INFO  listen://[::]:10933/             91  Accepted TCP client: [::ffff:IP_REMOVED]:60354
2016-12-05 12:45:19.1374     56  INFO  listen://[::]:10933/             56  Performing TLS server handshake
2016-12-05 12:45:19.1374     56  INFO  listen://[::]:10933/             56  Secure connection established, client is not yet authenticated, client connected with Tls12
2016-12-05 12:45:19.1530     56  INFO  listen://[::]:10933/             56  Client at [::ffff:IP_REMOVED]:60354 authenticated as THISISOURTHUMBPRINTOFTHEOCTOPUSSERVER123
2016-12-05 12:55:20.2326     56  INFO  listen://[::]:10933/             56  Unhandled error when handling request from client: [::ffff:IP_REMOVED]:60354
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadLine() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 93
   at Halibut.Transport.Protocol.MessageExchangeStream.ExpectNextOrEnd() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 67
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ProcessClientRequests(Func`2 incomingRequestProcessor) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 110
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\SecureListener.cs:line 140
2016-12-05 13:45:45.8920     63  INFO  listen://[::]:10933/             63  Accepted TCP client: [::ffff:IP_REMOVED]:45564
2016-12-05 13:45:45.8920     27  INFO  listen://[::]:10933/             27  Performing TLS server handshake
2016-12-05 13:45:45.8920     27  INFO  listen://[::]:10933/             27  Secure connection established, client is not yet authenticated, client connected with Tls12
2016-12-05 13:45:45.9233     27  INFO  listen://[::]:10933/             27  Client at [::ffff:IP_REMOVED]:45564 authenticated as THISISOURTHUMBPRINTOFTHEOCTOPUSSERVER123
2016-12-05 13:55:46.9991     27  INFO  listen://[::]:10933/             27  Unhandled error when handling request from client: [::ffff:IP_REMOVED]:45564
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadLine() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 93
   at Halibut.Transport.Protocol.MessageExchangeStream.ExpectNextOrEnd() in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 67
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ProcessClientRequests(Func`2 incomingRequestProcessor) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 110
   at Halibut.Transport.SecureListener.ExecuteRequest(TcpClient client) in Z:\BuildAgent\work\e1bda71fea4b4831\source\Halibut\Transport\SecureListener.cs:line 140
````

Are there any news about this error, cause this issue was opened 22 days ago.

**Comment by markryd** [comment]
A few instances of Halibut dropping stack traces due to normal operation where cleaned up in Octopus 3.8.6. (Such as the one shown in the log above, which happens when a listening Tentacles doesn't get any new requests from the Server for 10 minutes). Closing this. We'll handle further instances on a case by case basis until we get to the point that Halibut is only dumping stack traces in the logs in exceptional circumstances.
