### ISSUE TITLE
Failure to restart service when changing bindings

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2963]
I ran into the following problem changing the bindings via the Server Manager UI. (3.5.6)

The service ended up stopped.

```
SSL Certificate successfully deleted


SSL Certificate successfully added

Loading plugins from: C:\Program Files\Octopus Deploy\Octopus\BuiltInExtensions
==== Configure command starting ====
Web force SSL: False
==== Configure command completed ====
Loading plugins from: C:\Program Files\Octopus Deploy\Octopus\BuiltInExtensions
==== Configure command starting ====
Web listen prefixes: https://uatzebra.helpmewithit.org.au/Octopus
==== Configure command completed ====
Loading plugins from: C:\Program Files\Octopus Deploy\Octopus\BuiltInExtensions
Stopping service...
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: StopPending
Waiting for service to become Stopped. Current status: Running
<snip>
Waiting for service to become Stopped. Current status: Running
The service could not be stopped
-------------------------------------------------------------------------------
Error: Exceeded max retries
-------------------------------------------------------------------------------
Full error details are available in the log files.
At: C:\Octopus\Logs
===============================================================================
Exceeded max retries
System.Exception
   at Octopus.Shared.Startup.ConfigureServiceHelper.Retry(Func`1 func, Int32 maxRetries) in ConfigureServiceHelper.cs:line 233
   at Octopus.Shared.Startup.ConfigureServiceHelper.ConfigureService() in ConfigureServiceHelper.cs:line 190
   at Octopus.Shared.Startup.ServiceCommand.Start() in ServiceCommand.cs:line 47
   at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in AbstractCommand.cs:line 61
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) in OctopusProgram.cs:line 231
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown) in ConsoleHost.cs:line 77
   at Octopus.Shared.Startup.OctopusProgram.Run() in OctopusProgram.cs:line 116


Error: The previous command returned a non-zero exit code of: 100
Error: The command that failed was: "C:\Program Files\Octopus Deploy\Octopus\Octopus.Server.exe" service --instance "OctopusServer" --stop --start
```

**Comment by droyad** [comment]
Could not reproduce
