### ISSUE TITLE
Database upgrade script fails with collation mismatch error

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2976]
Upgrading from `3.2.7` to `3.6.0` fails with the following error message:

```
2016-12-02 02:49:39.7308      7  INFO  SQL exception has occured in script: 'Octopus.Core.UpgradeScripts.Script0044 - Octopus 3.4 Schema.sql'
2016-12-02 02:49:39.7308      7 ERROR  Script block number: 20; Block line 9; Message: TenantProject
2016-12-02 02:49:39.7908      7 ERROR  System.Data.SqlClient.SqlException (0x80131904): Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the like operation.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at DbUp.Support.SqlServer.SqlScriptExecutor.<>c__DisplayClass7.<Execute>b__4(Func`1 dbCommandFactory)
   at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
ClientConnectionId:078bfe40-1a2f-41a5-92b8-fd8c07fa01f8
Error Number:468,State:9,Class:16
```

Source: http://help.octopusdeploy.com/discussions/problems/49567

**Comment by vanessalove** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Database upgrade script fails with collation mismatch error](https://trello.com/c/qEzXXOEt/31-database-upgrade-script-fails-with-collation-mismatch-error)

**Comment by MJRichardson** [comment]
Another report: http://help.octopusdeploy.com/discussions/problems/50591-collation-upgrade-errors

**Comment by MJRichardson** [comment]
We have implemented [this](https://github.com/OctopusDeploy/Issues/issues/3069) to prevent this in the future.
