### ISSUE TITLE
Skipping actions that don't exist throw NRE

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3059]
See https://secure.helpscout.net/conversation/302620507?folderId=571723

System.NullReferenceException: Object reference not set to an instance of an object.
at Octopus.Server.Web.Api.Actions.DeploymentActionRules.CanBeSkipped(DeploymentAction action) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Web\Api\Actions\DeploymentActionRules.cs:line 13
at Octopus.Server.Orchestration.Deploy.DeploymentFactory.ValidateDeploymentProcessActions(Project project, DeploymentProcess deploymentProcess, DeploymentEnvironment environment, Tenant tenant, ITenantTagTester tenantTagTester, Channel channel, ReferenceCollection skipActions) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Orchestration\Deploy\DeploymentFactory.cs:line 440
at Octopus.Server.Orchestration.Deploy.DeploymentFactory.CreateDeployment(IRelationalTransaction transaction, Deployment deployment, User user, DateTimeOffset queueTime, ILifecycleProgressionEvaluator lifecycleProgressionEvaluator, ILifecycleService lifecycleService, IDeploymentSummaryService deploymentSummaryService, Func`2 promptedVariableProvider) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Orchestration\Deploy\DeploymentFactory.cs:line 84
at Octopus.Server.Web.Api.Actions.DeploymentCreateAction.Execute() in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Web\Api\Actions\DeploymentCreateAction.cs:line 82
at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 145
at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass0_0.<.ctor>b__0(Object o) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 46
at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skipping actions that don't exist throw NRE #3059](https://trello.com/c/Bj41KgvX/125-skipping-actions-that-don-t-exist-throw-nre-3059)

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skipping actions that don't exist throw NRE #3059](https://trello.com/c/Bj41KgvX/125-skipping-actions-that-don-t-exist-throw-nre-3059)
