### ISSUE TITLE
Unhandled exception on log file terminates Tentacle.exe 

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3105]
On the OctopusDSC build, there have been failures with one of the test Tentacle's not starting.

It uses the DSC to create 2 tentacles (1 listening, 1 polling) and then ensures they are both in the correct state. The polling tentacle has been failing to start - I presume its a timing issue of some description. 

```
2017-01-27 06:22:39.0054     14 FATAL  Unhandled AppDomain exception occurred: The process cannot access the file 'C:\Octopus\Work\20170126202238-2\Output.log' because it is being used by another process.
System.IO.IOException: The process cannot access the file 'C:\Octopus\Work\20170126202238-2\Output.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.OpenFile(String path, FileMode mode, FileAccess access, FileShare share) in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Shared\Util\OctopusPhysicalFileSystem.cs:line 189
   at Octopus.Tentacle.Services.Scripts.ScriptLog.CreateWriter() in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Tentacle\Services\Scripts\ScriptLog.cs:line 26
   at Octopus.Shared.Scripts.RunningScript.Execute() in Z:\buildAgent\workDir\eec88466c176b607\source\Octopus.Shared\Scripts\RunningScript.cs:line 34
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by matt-richardson** [comment]
Issue (in the case of the DSC at least) was that 2 tentacles have the same home directory, and getting clashes on filenames.

Fixed the DSC by adding support for modifying the home directory and specifying different home directories for each tentacle.

**Comment by matt-richardson** [comment]
The underlying crash though is still there - we should handle it and return an error to the server.

**Comment by droyad** [comment]
Having two tentacles on the same server is an edge case, going to close this for now.
