### ISSUE TITLE
Using AppPool user name beginning with .\ causes failure when using HTTPS certificate managed by Octopus

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#3499]
While the windows service and IIS App Pool username fields both accept usernames in the format `.\RogerRamjet`, this format fails when adding a HTTPS binding with a certificate managed by Octopus.

To reproduce:

1. Add a 'Deploy an IIS Website' step
2. Enter a user name beginning with `.\` in the _Application Pool name_ field
3. Add a HTTPS binding using a certificate managed by Octopus

The exception thrown is similar to:

```
System.Exception: Could not set security on private-key ---> System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
May 15th 2017 16:55:49Error
at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
May 15th 2017 16:55:49Error
at System.Security.Principal.NTAccount.Translate(Type targetType)
May 15th 2017 16:55:49Error
at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
May 15th 2017 16:55:49Error
at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
May 15th 2017 16:55:49Error
at Calamari.Integration.Certificates.WindowsX509CertificateStore.SetCspPrivateKeySecurity(SafeCertContextHandle certificate, ICollection`1 accessRules) in Z:\buildAgent\workDir\14ffc968155e4956\source\Calamari\Integration\Certificates\WindowsX509CertificateStore.cs:line 411
May 15th 2017 16:55:49
```

As reported by https://secure.helpscout.net/conversation/365789294?folderId=571733 (private link)

**Comment by ElleryW** [comment]
I'm running into this same issue with an app pool user that is a local user on the deployment target.
