### ISSUE TITLE
Adding public ip as an Octopus Server binding fails

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3585]
source: https://secure.helpscout.net/conversation/384679534/16580/?folderId=969747

Given a scenario where the public ip is handled externally to a server (eg, on a cloud server), adding the public ip as a binding is accepted, but then the service fails to start with an exception:

```
2017-06-22 08:09:54.2260      6 FATAL  Unhandled AppDomain exception occurred: The format of the specified network name is invalid
System.Net.HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Octopus.Server.Web.OctopusNancyHost.TryStartListener()
   at Octopus.Server.Web.OctopusNancyHost.StartListener()
   at Octopus.Server.Web.OctopusNancyHost.Start()
   at Octopus.Server.Web.WebServerInitializer.Start()
   at Octopus.Server.OctopusServerEngine.Start()
   at Octopus.Server.Commands.RunCommand.Start()
   at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions, String displayName, String version, String informationalVersion, String[] environmentInformation, String instanceName)
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime)
   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass1_0.<Run>b__0()
   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The solution is to add a dns entry for the ip address, and add the binding for that dns entry instead.

If an ip address is used, we should validate that the machine is aware of that address before allowing it.
This might end up with too many false positives - might be better to add it to our exception knowledge base.

**Comment by droyad** [comment]
While annoying, this is an edge case and has not cropped up again. As stated above, it might be tricky to implement. We will most likely not get to implementing this. Comment below if you disagree.
