### ISSUE TITLE
LifecycleProgressionEvaluator throws when the Lifecycle only has optional Phases

### ISSUE THREAD

**Issue by markryd** [OctopusDeploy/Issues#3594]
As per the title. Make a Lifecycle with only optional Phases and we get an error when viewing the dashboard or creating a release.

Reported: http://help.octopusdeploy.com/discussions/problems/55498

Workaround: It looks like you can work around this by having at least one phase in the Lifecycle as `All must complete`.

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LifecycleProgressionEvaluator throws when the Lifecycle only has optional Phases](https://trello.com/c/JGRAcHbl/663-lifecycleprogressionevaluator-throws-when-the-lifecycle-only-has-optional-phases)

**Comment by danielfischeroctopus** [comment]
Another report: http://help.octopusdeploy.com/discussions/questions/12038

```
Failed Assertion: Could not determine current phase
Octopus.Server.Communications.Lifecycles.FailedAssertionException
at Octopus.Server.Communications.Lifecycles.LifecycleProgressionEvaluator.Evaluate(Boolean releaseHasUnresolvedDefect, IList1 deployments, List1 allEnvironments, Lifecycle lifecycle, IList1 tenants, String projectId)
at Octopus.Server.Communications.Lifecycles.LifecycleProgressionEvaluator.Evaluate(Boolean releaseHasUnresolvedDefect, IList1 deployments, List1 allEnvironments, Lifecycle lifecycle)
at Octopus.Server.Communications.Lifecycles.LifecycleEvaluator.Evaluate(String releaseId)
at Octopus.Server.Web.Api.Rules.ReleaseCreationEventWillFire.AfterCommit(Release model, ReleaseResource resource, ISpecialRuleContext context)
at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRulesTRule
at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor2.Responder.Execute()
at Octopus.Server.Web.Infrastructure.Api.Responder1.Respond(TDescriptor options, NancyContext context)
at System.Dynamic.UpdateDelegates.UpdateAndExecute3T0,T1,T2,TRet
at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c_DisplayClass14_0.<get_Routes>b1(Object x)
at Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b_3(Object parameters, CancellationToken context)
```

**Comment by pawelpabich** [comment]
Release Note: Lifecycle must have at least one phase that is not optional
