### ISSUE TITLE
Intermittent System.AccessViolationException using built-in Octopus Certificate feature

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3644]
The customer reported a problem where:

1. Auto-deploy is configured for several projects which deploy IIS web sites using the new certificate support in Octopus
2. A new machine is added and a handful of projects start deploying concurrently
3. A `System.AccessViolationException` is thrown when using the interop code to set the ACLs on the certificate's private key.

This happens on Octopus Server `3.14.15926` and Calamari `3.7.83`.

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsNative.WindowsX509Native.CryptAcquireCertificatePrivateKey(SafeCertContextHandle pCert, AcquireCertificateKeyOptions dwFlags, IntPtr pvReserved, SafeCspHandle& phCryptProvOrNCryptKey, Int32& dwKeySpec, Boolean& pfCallerFreeProvOrNCryptKey)

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsNative.CertificatePal.GetCspPrivateKey(SafeCertContextHandle certificate)

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsX509CertificateStore.GetCspPrivateKeySecurity(SafeCertContextHandle certificate)

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsX509CertificateStore.SetCspPrivateKeySecurity(SafeCertContextHandle certificate, ICollection`1 accessRules)

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsX509CertificateStore.AddPrivateKeyAccessRules(ICollection`1 accessRules, SafeCertContextHandle certificate)

July 3rd 2017 09:05:16

Error

at Calamari.Integration.Certificates.WindowsX509CertificateStore.AddPrivateKeyAccessRules(String thumbprint, StoreLocation storeLocation, String storeName, ICollection`1 privateKeyAccessRules)

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.Features.IisWebSiteAfterPostDeployFeature.EnsureApplicationPoolHasCertificatePrivateKeyAccess(VariableDictionary variables)

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.Features.IisWebSiteAfterPostDeployFeature.Execute(RunningDeployment deployment)

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.Conventions.FeatureConventionBase.ExecuteFeatureClasses(RunningDeployment deployment, String feature)

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.Conventions.FeatureConventionBase.Run(RunningDeployment deployment)

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.ConventionProcessor.RunInstallConventions()

July 3rd 2017 09:05:16

Error

at Calamari.Deployment.ConventionProcessor.RunConventions()

July 3rd 2017 09:05:16

Error

at Calamari.Commands.DeployPackageCommand.Execute(String[] commandLineArguments)

July 3rd 2017 09:05:16

Error

at Calamari.Program.Execute(String[] args)

July 3rd 2017 09:05:16

Error

at Calamari.Program.Main(String[] args)

July 3rd 2017 09:05:16

Fatal

The remote script failed with exit code -1073741819
```

# Source

This issue was sourced from this private support discussion: https://secure.helpscout.net/conversation/390921237/16867/?folderId=571731

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intermittent System.AccessViolationException using built-in Octopus Certificate feature](https://trello.com/c/RmUMNth4/564-intermittent-systemaccessviolationexception-using-built-in-octopus-certificate-feature)
