### ISSUE TITLE
Unhealthy Azure WebApps are not shown in the Environments tab

### ISSUE THREAD

**Issue by deanmalone** [OctopusDeploy/Issues#3650]
Unhealthy Azure WebApps are not displayed as expected under then 'Unhealthy' section on the Environments tab.

For example, on deploy3.octopushq.com, unhealthy targets are not showing up.

![image](https://user-images.githubusercontent.com/12163663/28004137-d0814666-6585-11e7-9ad2-9129cfee8ccf.png)

The following error is occurring on the browser:

Creating Octopus client for endpoint: https://deploy3.octopushq.com/
3angular.js:12314 Error: Cannot find module './Server-Unhealthy.AzureWebApp.png'.
    at https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:21910:42
    at webpackContextResolve (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:21910:90)
    at webpackContext (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:21907:30)
    at Object.calculateTargetIcon (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:2946:17)
    at renderStatus (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32742:46)
    at renderMachineList (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32699:26)
    at update (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32721:33)
    at ensureMachineList (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32725:18)
    at render (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32732:18)
    at link (https://deploy3.octopushq.com/application.0-53-9094886b8ab2b39.hashedasset.js:32779:14) <machine-list machines="machines[environment.Id]['Unhealthy']" show="show" class="ng-isolate-scope">

**Comment by droyad** [comment]
Some `Unhealthy` icons are missing. Been broken for at least 6 months, so I think we should wait until this screen is rewritten in 4.0

**Comment by droyad** [comment]
Obsolete if we remove them in #3806

**Comment by droyad** [comment]
Not removing them
https://trello.com/c/lVgclU76/494-icon-is-missing-for-unhealthy-azure-webapps

**Comment by droyad** [comment]
Release Note: Added an icon for Unhealthy Azure cloud services
