### ISSUE TITLE
Blocked deployments with optional phases leads to "Failed Assertion: Could not determine current phase"

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#3668]
This bug was reported via https://secure.helpscout.net/conversation/396847610?folderId=557082.

How to reproduce:

1. Create a lifecycle with 2 phases. The second phase is optional.
2. Create a project using the lifecycle from step 1.
3. Create a release and push it to the first phase.
4. Block the deployment.
5. Change the lifecycle so the first phase is optional and the second is not.
6. Open the project overview. You will see an error.

```
Failed Assertion: Could not determine current phase
Octopus.Server.Communications.Lifecycles.FailedAssertionException
   at Octopus.Server.Communications.Lifecycles.LifecycleProgressionEvaluator.Evaluate(Boolean releaseHasUnresolvedDefect, IList`1 deployments, List`1 allEnvironments, Lifecycle lifecycle, IList`1 tenants, String projectId)
   at Octopus.Server.Web.Api.Actions.ProgressionViewActionController.GetProgression(Release release, IEnumerable`1 deployments, List`1 environmentIds, Lifecycle lifecycle, List`1 projectTenants)
   at Octopus.Server.Web.Api.Actions.ProgressionViewActionController.<>c__DisplayClass5_0.<GetReleaseProgression>b__13(<>f__AnonymousType70`2 <>h__TransparentIdentifier1)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Actions.ProgressionViewActionController.GetReleaseProgression(String projectId, IOctopusPrincipalInternal octopusPrincipal)
   at Octopus.Server.Web.Api.Actions.ProgressionViewAction.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

![bug](https://user-images.githubusercontent.com/160104/28252077-7d96c17a-6acf-11e7-9c20-75188015c1d1.PNG)

**Comment by mcasperson** [comment]
This was verfified on 3.15.5

**Comment by alfhenrik** [comment]
Looks like this line of code https://github.com/OctopusDeploy/OctopusDeploy/blob/master/source/Octopus.Server/Communications/Lifecycles/LifecycleProgressionEvaluator.cs#L58 is why that error is returned

**Comment by alexrolleyoctopus** [comment]
Another reported case of this issue: http://help.octopusdeploy.com/discussions/problems/56024

**Comment by mcasperson** [comment]
The fix for this has been merged into master.
