### ISSUE TITLE
Exception when blocking a deployment while its current phase or a deployed to phase is optional.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3693]
Currently when you attempt to block a deployment while its current phase is optional, you are met with a couple of exceptions.

Both the same.
```
Failed Assertion: Could not determine current phase
Octopus.Server.Communications.Lifecycles.FailedAssertionException
   at Octopus.Server.Communications.Lifecycles.LifecycleProgressionEvaluator.Evaluate(Boolean releaseHasUnresolvedDefect, IList`1 deployments, List`1 allEnvironments, Lifecycle lifecycle, IList`1 tenants, String projectId)
   at Octopus.Server.Web.Api.Actions.ReleaseLifecycleProgressionAction.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

Steps to reproduce: (3.15.6)

1: Create project/lifecycle with at least one optional phase.
2: Create release, before selecting to deploy where the phase is optional, select to block deployment.
3: Enter description and select to block.

Extra: Deploy to the option phase then block deployment. UI for deployed optional phase does not display correctly, needs further investigation.

See following exception.

![block](https://user-images.githubusercontent.com/18252832/28550600-51a171f8-7125-11e7-8139-1e6af8441f67.JPG)

Source: http://help.octopusdeploy.com/discussions/questions/12038

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exception when blocking a deployment while its current phase or a deployed to phase is optional](https://trello.com/c/z96fBc1T/695-exception-when-blocking-a-deployment-while-its-current-phase-or-a-deployed-to-phase-is-optional)

**Comment by johnsimons** [comment]
I attempted to reproduce this issue in the latest version of v4 and could not.
If this is still an issue please reopen and we look at it again.
