### ISSUE TITLE
Azure Web Apps UI error when using Azure Mgt Certificate

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3731]
There is a UI bug in the Azure Web Site step template when using a **PremiumV2** tier app service in your account and connecting with an **Azure Management Certificate**.

When the "Web "App" dropdown tries to load, you receive this error in the UI:

```
Requested value 'PremiumV2' was not found.
System.ArgumentException
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.WindowsAzure.Management.WebSites.WebSpaceOperationsExtensions.ListWebSites(IWebSpaceOperations operations, String webSpaceName, WebSiteListParameters parameters)
   at Octopus.Server.Web.Api.Actions.AzureWebSitesListAction.<>c__DisplayClass3_0.<GetSites>b__0(WebSpace webSpace)
   at System.Linq.Enumerable.SelectManyIterator
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Actions.AzureWebSitesListAction.GetSites(AzureAccount certificateAccount)
   at Octopus.Server.Web.Api.Actions.AzureWebSitesListAction.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

You do not receive this error when using a Service Principal account.

You can workaround this issue by either:
1) Using a Service Principal account
2) Selecting the "Custom Expression" checkbox next to account and filling out the details of the resource group/web app manually

But these workarounds are obviously not ideal. We need to fix the `AzureWebSitesListAction` (when using mgt certificates) to handle this situation.

****

After further discussion, we should:

1. add a deprecation notice to the UI account selector when Management Certificates are selected
2. add a warning log during a deployment process if a management certificate is used (except for Cloud Services) to say "hey just letting you know this is marked as deprecated, pls consider updating to Service Principal account"

This should help move people towards Service Principals over Mgt Certs.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Azure Web Apps UI error when using Azure Mgt Certificate](https://trello.com/c/aTgsNRg6/270-azure-web-apps-ui-error-when-using-azure-mgt-certificate)

**Comment by halvardskogensjotveit** [comment]
@thebigmoosey Is this fixed? I am getting the error atm. It ws working a week ago. I did not change any configuration.

**Comment by halvardskogensjotveit** [comment]
I can't find "Custom Expression" either. I am running Octopus v2018.2.8.

**Comment by thebigmoosey** [comment]
@halvardskogensjotveit This issue is still open. We found that you do not receive this error when using a Service Principal account. The only fix we can do here is add warnings as discussed in the issue description.

Regarding the "Custom Expression", this is referring to the "Bind" action next to the account selector (it looks like a chain-link and says Bind when you hover over it). This action used to be called "Custom Expression" in the older UI.

Hope this helps.

**Comment by thebigmoosey** [comment]
Azure are [deprecating support for Service Management APIs](https://blogs.msdn.microsoft.com/appserviceteam/2018/03/12/deprecating-service-management-apis-support-for-azure-app-services/) (which will include mgt certs to Web App Services) on June 30th 2018, so the solution to this issue is to switch to a Service Principal as discussed.

**Comment by thebigmoosey** [comment]
Release Note: Added warnings about Management Certificates for Azure's up-coming June 30th deprecation deadline
