### ISSUE TITLE
Artifacts from old Tentacles are preventing post 3.15.3 Tentacles from running

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3740]
We introduced a check for expected logging configuration on Tentacles in 3.15.3:

https://github.com/OctopusDeploy/OctopusDeploy/commit/779ed22552f7375b7048cdcea0153e367b5994fc
https://github.com/OctopusDeploy/OctopusTentacle/commit/1f9f283234202b3b73eef89d664bb9f14b64c99f

Tentacle installations that have been around since v2 have the obsolete v2 files still present in the Tentacle installation folder.  Among them is an `nlog.config` file which I believe is being preferred to the contemporary `tentacle.exe.nlog` and causing the log assertion to fail:

```
Error: Unhandled Exception: System.Exception: Invalid logging configuration: missing target 'stdout'
Error:    at Octopus.Shared.Startup.OctopusProgram.AssertLoggingConfigurationIsCorrect()
Error:    at Octopus.Shared.Startup.OctopusProgram.Run()
Error:    at Octopus.Tentacle.Program.Main(String[] args)
The previous command returned a non-zero exit code of: -532462766
The command that failed was: "C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" service --instance "Tentacle" --stop
```

### Workaround

1. Uninstall Tentacle
2. Delete the contents of the Tentacle installation directory (by default `C:\Program Files\Octopus Deploy\Tentacle`)
3. Install Tentacle

Note that any Tentacles instances will persist through the re-install process.

**Comment by tothegills** [comment]
Related support queries:
http://help.octopusdeploy.com/discussions/problems/56940
https://secure.helpscout.net/conversation/412819010?folderId=557082
http://help.octopusdeploy.com/discussions/problems/56970

**Comment by michaelnoonan** [comment]
This seems to apply to both Octopus and Tentacle. At this point I'm voting we should clean up those old files rather than leave them around and ignore the problem(s) they may be creating.

This assertion was added because certain features are depending on a specific structure to our logging configuration. The one thing Octopus Admins should be changing is the log level which can be done as described here: https://octopus.com/docs/reference/log-files#Logfiles-Changingloglevels

**Comment by tothegills** [comment]
Release note: On startup Octopus will delete obsolete files leftover from old Octopus Server installations
