### ISSUE TITLE
System.FormatException: String was not recognized as a valid Boolean.

### ISSUE THREAD

**Issue by jobou363** [OctopusDeploy/Issues#3801]
Since I upgrade to verson 3.17 I receive the following message and I'm not sure where to look, I have check all the variable and they look ok : 
.... 
Copied 1196 files
September 15th 2017 11:38:46Error
System.FormatException: String was not recognized as a valid Boolean.
September 15th 2017 11:38:46Error
   at System.Boolean.Parse(String value)
September 15th 2017 11:38:46Error
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Features.IisWebSiteBeforeDeployFeature.EnsureCertificatesUsedInBindingsAreInStore(VariableDictionary variables)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Features.IisWebSiteBeforeDeployFeature.Execute(RunningDeployment deployment)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Conventions.FeatureConventionBase.Run(RunningDeployment deployment)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
September 15th 2017 11:38:46Error
   at Calamari.Deployment.ConventionProcessor.RunConventions()
September 15th 2017 11:38:46Error
Running rollback conventions...
September 15th 2017 11:38:46Error
String was not recognized as a valid Boolean.
September 15th 2017 11:38:46Error
System.FormatException
September 15th 2017 11:38:46Error
   at System.Boolean.Parse(String value)
September 15th 2017 11:38:46Error
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Features.IisWebSiteBeforeDeployFeature.EnsureCertificatesUsedInBindingsAreInStore(VariableDictionary variables)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Features.IisWebSiteBeforeDeployFeature.Execute(RunningDeployment deployment)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.Conventions.FeatureConventionBase.Run(RunningDeployment deployment)
September 15th 2017 11:38:46Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
September 15th 2017 11:38:46Error
   at Calamari.Deployment.ConventionProcessor.RunConventions()
September 15th 2017 11:38:46Error
   at Calamari.Commands.DeployPackageCommand.Execute(String[] commandLineArguments)
September 15th 2017 11:38:46Error
   at Calamari.Program.Execute(String[] args)
September 15th 2017 11:38:46Fatal
The remote script failed with exit code 100
September 15th 2017 11:38:46Fatal
Deploy Site participant to IIS on Serveur Validation (SaiWeb008-v)

**Comment by matt-richardson** [comment]
Thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support.

We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).

Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
