### ISSUE TITLE
Unhandled exception in Renci.SshNet.SshCommand.Session_ErrorOccured

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#3874]
Octopus Server crashed due to an unhandled exception, exception in Event Viewer:

```
2017-10-16 18:47:50.5217   3052    364 FATAL  Unhandled AppDomain exception occurred: Object reference not set to an instance of an object.
System.NullReferenceException
   at Renci.SshNet.SshCommand.Session_ErrorOccured(Object sender, ExceptionEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Renci.SshNet.Session.RaiseError(Exception exp)
   at Renci.SshNet.Session.MessageListener()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Renci.SshNet.SshCommand.Session_ErrorOccured(Object sender, ExceptionEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Renci.SshNet.Session.RaiseError(Exception exp)
   at Renci.SshNet.Session.MessageListener()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Source (private): https://help.octopusdeploy.com/discussions/problems/60751

**Comment by droyad** [comment]
Has not been reported again

**Comment by KennethBates** [comment]
Possible second source: https://help.octopus.com/t/octopus-deploy-server-crashed-with-unhandled-exception-in-renci-sshnet-sshcommand-session-erroroccured/21891
