### ISSUE TITLE
Exception thrown when establishing a principal when Active Directory has multiple principals containing a matching identity.

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#3887]
Source: https://secure.helpscout.net/conversation/436613438?folderId=557082 (private link)

When users log in to Octopus portal using their domain credentials, certain users whose identities match multiple identity in Active Directory cannot login. 

The error message is not too bad, but it would be useful to catch it and use our exception knowledge base to assist customers and reduce support questions. Perhaps we can describe which user accounts have matching identities to make it easier to diagnose in Active Directory.

confirmed Octopus version where this issue occurs: 3.15.8

2017-10-18 14:30:10.6207 2392 1716 WARN An exception was thrown while trying to establish a principal for the current request

System.DirectoryServices.AccountManagement.MultipleMatchesException: Multiple principals contain a matching Identity.

at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRefHelper(Type principalType, String urnScheme, String urnValue, DateTime referenceDate, Boolean useSidHistory)

at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRef(Type principalType, String urnScheme, String urnValue, DateTime referenceDate)

at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)

at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)

at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, String identityValue)

at Octopus.Server.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesCredentialValidator.GetOrCreateUser(String username)

at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()

at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

at Octopus.Server.Web.Infrastructure.Authentication.ExternalPrincipalRequestAuthenticator.TryAuthenticateRequest(NancyContext context)

at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()

at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

at Octopus.Server.Web.Infrastructure.Authentication.OctopusPrincipalEstablisher.EstablishPrincipalForRequest(NancyContext context)

**Comment by spuder** [comment]
I am also seeing that error on octopus 4.1.x when trying to authenticate against a domain with a one way trust. 

>An exception was thrown while trying to establish a principal for the current request
System.DirectoryServices.AccountManagement.PrincipalOperationException: There is no such object on the server.

```
2017-12-12 18:13:52.8441   4868     14  INFO  Synchronizing external security groups for 1 user. Loading users took 0.02s.
2017-12-12 18:13:53.0942   4868     14  INFO  External security groups were already correct for all users. No changes were made. Processing users took 0.23s
.
2017-12-12 18:14:00.3712   4868     18  WARN  An exception was thrown while trying to establish a principal for the current request
System.DirectoryServices.AccountManagement.PrincipalOperationException: There is no such object on the server.
 ---> System.DirectoryServices.DirectoryServicesCOMException: There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)
   at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptio
ns options)
   at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInit()
   --- End of inner exception stack trace ---
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityTyp
e, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   at Octopus.Node.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesCredentialValidator.GetOrCreateUser(String username, Ca
ncellationToken cancellationToken)
   at Octopus.Node.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesUserCreationFromPrincipal.GetOrCreateUser(IPrincipal pr
incipal, CancellationToken cancellationToken)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Web.Infrastructure.Authentication.ExternalPrincipalRequestAuthenticator.TryAuthenticateRequest(NancyContext context) in Z:\buildAgent\w
orkDir\eec88466c176b607\source\Octopus.Server\Web\Infrastructure\Authentication\ExternalPrincipalRequestAuthenticator.cs:line 42
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Web.Infrastructure.Authentication.OctopusPrincipalEstablisher.EstablishPrincipalForRequest(NancyContext context) in Z:\buildAgent\workD
ir\eec88466c176b607\source\Octopus.Server\Web\Infrastructure\Authentication\OctopusPrincipalEstablisher.cs:line 41
2017-12-12 18:14:48.9828   4868     21  INFO  Running System Integrity Check
2017-12-12 18:14:49.1703   4868     21  INFO  Completed System Integrity Check. Overall Result: Passed
```
