### ISSUE TITLE
Variable replacement in JSON files fails if the root object is an array

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3896]
`Newtonsoft.Json.JsonReaderException : Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Calamari.Integration.JsonVariables.JsonConfigurationVariableReplacer.LoadJson(String jsonFilePath)
   at Calamari.Integration.JsonVariables.JsonConfigurationVariableReplacer.ModifyJsonFile(String jsonFilePath, VariableDictionary variables)
   at Calamari.Tests.Fixtures.JsonVariables.JsonConfigurationVariableReplacerFixture.Replace(VariableDictionary variables, String existingFile) in C:\Code\Calamari\source\Calamari.Tests\Fixtures\JsonVariables\JsonConfigurationVariableReplacerFixture.cs:line 337
   at Calamari.Tests.Fixtures.JsonVariables.JsonConfigurationVariableReplacerFixture.ShouldReplaceVariablesInTopLevelArray() in C:\Code\Calamari\source\Calamari.Tests\Fixtures\JsonVariables\JsonConfigurationVariableReplacerFixture.cs:line 84
`
Source: https://secure.helpscout.net/conversation/440556808?folderId=557077

**Comment by pawelpabich** [comment]
Release Note: Variable substitution works now with JSON files that have an array as the root object
