### ISSUE TITLE
No validation environment exists when creating tenant via api

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4032]
There is no validation an environment exists when creating a tenant via api, so it saves it in the database with invalid data.

```
ctopus.Client.Exceptions.OctopusServerException: Octopus Server returned an error: Value cannot be null.
Parameter name: key
Server exception: 
Value cannot be null.
Parameter name: key
System.ArgumentNullException
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Octopus.Server.Web.Api.Actions.TenantVariableController.GetProjectVariableResouce(IOctopusPrincipalInternal principal, Tenant tenant, List`1 existingValues, Project project)
   at Octopus.Server.Web.Api.Actions.TenantVariableController.BuildResource(IOctopusPrincipalInternal principal, Tenant tenant)
   at Octopus.Server.Web.Api.Actions.TenantVariablesGetResponder.ExecuteRegistered(String id)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by TomPeters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No validation environment exists when creating tenant via api](https://trello.com/c/4bu1hZ5I/978-no-validation-environment-exists-when-creating-tenant-via-api)

**Comment by TomPeters** [comment]
Release Note: Validate that environment ids exist when creating or modifying tenants
