### ISSUE TITLE
errors when importing of a project with a Channel that has version rule

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4037]
## Issue
Import a project with channel that has version rules will fail

## Steps to reproduce
- Create a project on source server
- Add a channel with Version rule
- Use Octo.exe (4.27.2) to export the project
- Use octo.exe(4.27.2) to import the project on another server
- I used 4.0.10 and customer used 4.0.8, believed that same issue in 3.x

## Error
`No validation errors found. Project is ready to import.
Beginning the import
Beginning import of project 'ExternalServices'
Importing Project
Project does not exist, a new project will be created
Importing the channels for the project
Channel 'Default' already exists, channel will be updated with new settings
Channel Stable does not exist, a new channel will be created
Octopus Server returned an error: Unable to find action references [NC.ExternalServices] on project Projects-43
Server exception:
Unable to find action references [NC.ExternalServices] on project Projects-43
System.Exception
   at Octopus.Server.Web.CanonicalActionNameMapper.GetIdsFromReferences(String projectId, ReferenceCollection actionReferences)
   at Octopus.Server.Web.Api.Rules.ChannelVersionRulesWillBePersisted.<>c_DisplayClass6_0.<AfterMapBeforeStore>b0(ChannelVersionRuleResource rule)
   at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Octopus.Server.Web.Api.Rules.ChannelVersionRulesWillBePersisted.AfterMapBeforeStore(Channel model, ChannelResource resource, ISpecialRuleContext context)
   at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRegisteredRules[TRule](Action2 ruleCallback)
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor2.Responder.ExecuteRegistered()
   at Octopus.Server.Web.Infrastructure.Api.Responder1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3T0,T1,T2,TRet
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>cDisplayClass14_0.<get_Routes>b1(Object x)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b_3(Object parameters, CancellationToken context)
-----------------------`

**Comment by mayuanyang** [comment]
Release Note: Fix a bug where project import will fail if the project has a channel with version rule
