### ISSUE TITLE
Unable to create a release with custom feed expressions and channel version rules

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#4065]
Create a project that has a deploy package step. For the feed property in this step, make sure it uses a bound variable expression, rather than specifying a specific feed.

Setup up a channel in this project, and configure a version rule for your package step. You may get errors using the Design Rule dialog as per https://github.com/OctopusDeploy/Issues/issues/4059, so you can just enter in your version rule configuration without using the dialog.

Go to create a release in this channel. It doesn't matter what versions you configure for your package. Save your release. You will get an error like: 

```
Object reference not set to an instance of an object.
System.NullReferenceException
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.<>c__DisplayClass10_1.<GetStepsWithPackageRuleViolations>b__8(Feed feed) in SelectedPackagesPassChannelRules.cs:line 60
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.<>c__DisplayClass10_0.<GetStepsWithPackageRuleViolations>b__2(PackageStepVersion package)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.AfterMapBeforeStore(Release model, ReleaseResource resource, ISpecialRuleContext context) in SelectedPackagesPassChannelRules.cs:line 35
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRegisteredRules[TRule](Action`2 ruleCallback) in Responder.cs:line 285
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.ExecuteRegistered()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in Responder.cs:line 244
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x) in OctopusNancyModule.cs:line 102
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

This happens when we try to verify that the specified package version complies with the version constraints for the channel. As part of this, we try to load the feed resource using the variable expression as the feed id, which of course fails.

As a workaround, try to avoid using custom feed expressions, and instead duplicate your deploy package step with hard-coded feeds. Scope these different steps to run against the appropriate channels/environments/etc.

**Comment by TomPeters** [comment]
There might be some way that we could avoid loading the feed resource when we create a deployment. We only load it to get the feed type, which we use to construct a version object of the correct package type for use in comparing the version.

**Comment by droyad** [comment]
The above exception started occuring due to this change: https://github.com/OctopusDeploy/OctopusDeploy/commit/09e28216 (`4.1.0`)

**Comment by droyad** [comment]
Related: Dynamic package feeds no longer working #4174

**Comment by johnsimons** [comment]
@droyad so is this and #4174 the same bug ?

**Comment by droyad** [comment]
@johnsimons Yes it is
