### ISSUE TITLE
Project > Triggers page exceptions when step used by ARC is disabled then deleted

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4075]
Octopus 4.1.2

When disabling then deleting a step (while it's disabled) which is also configured as the Automatic Release Creation step, and recreating a package step, then going into the Project > Triggers page causes the exception shown in the following screenshot. This page crashes which prevents you from removing ARC setting to fix it.

![trigger_error](https://user-images.githubusercontent.com/20388190/33977036-845b9ad6-e0e4-11e7-89a6-a642c90515f7.png)

Error message:
```
TypeError: Cannot read property 'Name' of undefined
    at t.build (https://master.octopushq.com/projects.6557d67421856c24b80d.hashedasset.js:1:1308151)
    at t.render (https://master.octopushq.com/projects.6557d67421856c24b80d.hashedasset.js:1:1307008)
    at u (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:287981)
    at beginWork (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:289481)
    at i (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:301773)
    at u (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:302289)
    at c (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:302764)
    at m (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:304786)
    at h (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:304295)
    at Object.enqueueSetState (https://master.octopushq.com/react.2f83430958cc6f6e616e.hashedasset.js:1:285562)
```

You are prevented from deleting a step that's associated with ARC in the project, but you aren't prevented from deleting the same step if it's currently disabled.

Steps to reproduce
1. Create trigger on this step
2. Disable step
3. Delete step
4. Add a new package step
5. Go to Project > Triggers page

Recording of repro:

![arc_package_disable_delete](https://user-images.githubusercontent.com/20388190/33977222-994870bc-e0e5-11e7-9886-2d3b7977c7ab.gif)

**Workaround** 

Remove ARC settings from project via the API using the following script:
https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/REST/PowerShell/DeploymentProcesses/RemoveARCSettingsFromProject.ps1

Source: https://help.octopusdeploy.com/discussions/problems/65687-exception-while-editing-project-triggers

**Comment by KennethBates** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project > Triggers page exceptions when step used by ARC is disabled then deleted](https://trello.com/c/gEY6ZRDa/893-project-triggers-page-exceptions-when-step-used-by-arc-is-disabled-then-deleted)

**Comment by pawelpabich** [comment]
Release Note: Steps used in Automatic Release Creation can't be disabled anymore
