### ISSUE TITLE
ARM template empty "Deployment mode" throws exception

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4128]
If you create an ARM template step but fail to specify the "Deployment mode" when selecting the account, the deployment will fail with an unhelpful exception:

```
01:50:35   Error    |       System.ArgumentNullException: Value cannot be null.
01:50:35   Error    |       Parameter name: value
01:50:35   Error    |       at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
01:50:35   Error    |       at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
01:50:35   Error    |       at Calamari.Azure.Deployment.Conventions.DeployAzureResourceGroupConvention.Install(RunningDeployment deployment)
01:50:35   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
01:50:35   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
```

### The Proposed Solution
When setting up the step, the API should be validating that all required fields are included, and this should probably default to the first enum option when setting up the step so people can't so easily walk into this trap.

It may also be worth checking how this was handled in the v3 UI, as this may be a new v4 bug (and we just never noticed that the API did not include the necessary validation for this step type).

Source: https://secure.helpscout.net/conversation/485816502?folderId=801354

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ARM template empty "Deployment mode" throws exception](https://trello.com/c/V5bjEFoD/534-arm-template-empty-deployment-mode-throws-exception)
