### ISSUE TITLE
Ilegal characters in path when setting tentacle.exe configure --app

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/Issues#4154]
When running 
```
tentacle.exe configure --instance "Tentacle" --app "C:\SomeDirectory\" --console
```
 if the value for `C:\SomeDirectory\` has a trailing `\` you will get Illegal characters in path.

if you remove the trailing `\` the command will succeed successfully.

To reproduce:
```
C:\Program Files\Octopus Deploy\Tentacle>tentacle.exe configure --instance "Tentacle" --app "C:\Program Files\Octopus Deploy\Octopus\" --console
===============================================================================
Illegal characters in path.
System.ArgumentException
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.GetFullPath(String relativeOrAbsoluteFilePath)
   at Octopus.Tentacle.Commands.ConfigureCommand.<>c__DisplayClass7_2.<.ctor>b__3()
   at Octopus.Tentacle.Commands.ConfigureCommand.Start()
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown)
   at Octopus.Shared.Startup.OctopusProgram.Run()
-------------------------------------------------------------------------------
Terminating process with exit code 100
Full error details are available in the log files at:
C:\Octopus\Logs
C:\Users\lawrence\AppData\Local\Octopus\Logs
If you need help, please send these log files to https://octopus.com/support
-------------------------------------------------------------------------------


C:\Program Files\Octopus Deploy\Tentacle>tentacle.exe configure --instance "Tentacle" --app "C:\Program Files\Octopus Deploy\Octopus" --console
Application directory set to: C:\Program Files\Octopus Deploy\Octopus
These changes require a restart of the Tentacle.

C:\Program Files\Octopus Deploy\Tentacle>
```

Source (Private link): https://secure.helpscout.net/conversation/490052334/22331?folderId=845288

**Comment by matt-richardson** [comment]
Hmmm. Are you sure?

If its escaping, `--app "C:\SomeDirectory\"` would escape the `S` as well as the trailing `"`, wouldn't it?

**Comment by markryd** [comment]
I tested it and that's seems to be what is happening. I've tried to dig in to what the internet says should happen but escaping stuff in cmd is a total dumpster fire apparently. At least _some_ of the things I read said that backslash escaping a double quote only kicks in once you are already inside double quotes, and _only_ effects double quote, not other characters.

**Comment by matt-richardson** [comment]
Erk. Sounds painful. Not sure its a good idea, but we _could_ detect if the string contains a `\"` or something? Not sure its a good idea though.

**Comment by markryd** [comment]
Yeah, my initial thought was "hey we can check for this!" but then what about people who know this and do things "right", we might break them. Actually thinking now I think the best thing might be to check if we have a valid directory and fail cleanly if we don't "The directory you passed c:\xxxx\xxxx is not valid, check that it exists blah blah" at the moment we're just falling over with an unclear message when we try to treat it as a dir. I'll take a swing at it tomorrow. Hopefully users can see what is going on if we tell them they passed `"C:\\SomeDirectory\" --console"` as a directory. The error message could even point to escaping (could def check for `"\` when building the error message.
