### ISSUE TITLE
Dynamic package feeds no longer working

### ISSUE THREAD

**Issue by tw17** [OctopusDeploy/Issues#4174]
Dynamic package feeds no longer working on the latest version of Octopus (from 4.1.0)

```The feed resource '#{Nuget.Feed}' was not found. Ensure that the feed is not specified using a variable expression.  
Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules+FeedNotFoundException  
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.<>c__DisplayClass10_0.<GetStepsWithPackageRuleViolations>b__7(String feedId)
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.<>c__DisplayClass10_0.<GetStepsWithPackageRuleViolations>b__2(PackageStepVersion package)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Rules.SelectedPackagesPassChannelRules.AfterMapBeforeStore(Release model, ReleaseResource resource, ISpecialRuleContext context)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRegisteredRules[TRule](Action`2 ruleCallback)
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.ExecuteRegistered()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)```

**Comment by tw17** [comment]
ReleaseNote: Dynamic package feeds now working again with channel rules.
