### ISSUE TITLE
Variables passed through by deploy release step can break the deployment

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4466]
Example output:

```
 Bad JSON escape sequence: \E. Path 'ApiKey', line 1, position 15.
                    |       Newtonsoft.Json.JsonReaderException
                    |       at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
                    |       at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
                    |       at Newtonsoft.Json.JsonTextReader.ReadAsString()
                    |       at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    |       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
                    |       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    |       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    |       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    |       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    |       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.DeployRelease.DeployReleaseActionHandler.Execute(ActionCommand command)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.OldActionDispatcher.<>c__DisplayClass4_0.<DispatchServerAction>b__0()
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(Action callback)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(Action callback, String actionName)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.OldActionDispatcher.DispatchServerAction(ActionCommand command)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.OldActionDispatcher.Dispatch(ActionCommand command, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Dispatch(ActionCommand command, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.<>c__DisplayClass31_0.<ExecuteActionAndInitLoggingContext>b__0()
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteWithTransientErrorDetection(Action action, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteActionAndInitLoggingContext(PlannedStep step, Machine machine, PlannedAction action)
15:02:29   Fatal    |       The action Deploy on the Octopus Server failed
```

To reproduce:
- Create a project with a variable and script step
- Create a project with deploy release step to deploy previous project
- Create a variable in the parent project with value `C:\Example`
- Contribute the parent variable to the child project

**Comment by tothegills** [comment]
Reported by: https://secure.helpscout.net/conversation/557911048?folderId=557077
https://help.octopus.com/t/problem-with-variable-encoding-when-deploying-child-release/19599

**Comment by florin-at-intersolve** [comment]
Any plans to solve this issue?
