### ISSUE TITLE
Raw scripting doesn't work from a package on bash, and then doesn't run the script

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4475]
Attempting to run a raw bash script from a package:

```
11:08:21   Verbose  |       This target can only run Bash scripts, but only PowerShell scripts were supplied
                    |       System.Exception
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.Immediate.ImmediateExecutor.ExecuteRawScript(ScriptCollection scripts)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.CommandBuilders.RawScriptCommandBuilder.Execute()
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Script.ScriptActionHandler2.RunRawScript(IActionHanderContext context)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Script.ScriptActionHandler2.Execute(IActionHanderContext context)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.<>c__DisplayClass11_0.<Execute>b__2()
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(Action callback)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(Action callback, String actionName)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Execute(ActionCommand command, Maybe`1 inContextOf, IExecutor executor, TargetManifest targetManifest, Maybe`1 stagedPackagePath)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.ExecuteOnDeploymentTarget(ActionCommand command, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Dispatch(ActionCommand command, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.<>c__DisplayClass31_0.<ExecuteActionAndInitLoggingContext>b__0()
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteWithTransientErrorDetection(Action action, Machine machine)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteActionAndInitLoggingContext(PlannedStep step, Machine machine, PlannedAction action)

```

After manually adding the variable to set `Octopus.Action.Script.Syntax` to `Bash`, the script doesn't appear to run.

**Comment by GoldUniform** [comment]
Is there an ETA for development on this bug?

**Comment by droyad** [comment]
Show a nicer exception at deployment time

**Comment by droyad** [comment]
There is now an option in the UI to select the script.
