### ISSUE TITLE
NullRefException showing tentacle configuration

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#4620]
1) logged onto an instance that already had a tentacle installed `3.21.0+Branch.master.Sha.5b432062a93ad6cdd58d0bd9bb319daf889780c0`
2) created a new instance `.\Tentacle.exe create-instance --config c:\worker.config`
3) installed the service `.\Tentacle.exe service --install --instance Tentacle`
4) tried to show the configuration `.\Tentacle.exe show-configuration`

```
Object reference not set to an instance of an object.
System.NullReferenceException
   at Octopus.Tentacle.Commands.ShowConfigurationCommand.CollectConfigurationSettings
   at Octopus.Tentacle.Commands.ShowConfigurationCommand.StartAsync
   at Octopus.Tentacle.Commands.ShowConfigurationCommand.Start()
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown)
   at Octopus.Shared.Startup.OctopusProgram.Run()
-------------------------------------------------------------------------------
Terminating process with exit code 100
Full error details are available in the log files at:
c:\Logs
C:\Users\Administrator\AppData\Local\Octopus\Logs
If you need help, please send these log files to https://octopus.com/support
-------------------------------------------------------------------------------
```

This was on a hosted instance, server core 2016, running `v2018-6-0-vnext0755`.

Also crashes with `.\Tentacle.exe show-configuration --instance Tentacle`

Works after you create a certificate
```
.\Tentacle.exe new-certificate --instance "Tentacle" --if-blank --console
```

**Comment by matt-richardson** [comment]
Included in server: https://github.com/OctopusDeploy/OctopusDeploy/commit/7ee26f6ff76ddfe003443498cc690a4da77f4761
Tests: https://github.com/OctopusDeploy/OctopusDeploy/pull/2926/commits/6f775b48e78270c58b06bbda6bc02687dafa0fb4
