### ISSUE TITLE
Error while executing SQL command in transaction 'TargetLimitPolicy': Invalid column name 'CommunicationStyle'.

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#4739]
The licensing check we perform to prevent customers from upgrading Octopus Server, only to find their server is no longer compliant, is failing due to bug in the query.

Discovered in `2018.7.0`. Fixed in `2018.7.1`.

# Affected customers

This only affects customers upgrading from Octopus Server `2018.5.x` or earlier to `2018.7.0`.

# Mitigation

Upgrade directly to Octopus Server `2018.7.1` or newer which has the fixed query.

# Workaround

Use this upgrade path:

1. Your version of Octopus Server
2. Upgrade to [Octopus Server 2018.6.15](https://octopus.com/downloads/2018.6.15)
3. Upgrade to [Octopus Server 2018.7.0](https://octopus.com/downloads/2018.7.0)

# Details

```Error: Could not check whether this upgrade would cause the licence to no longer be compliant and therefor block deployments. Preventing upgrade to be safe. Please send your current version and the below error to Octopus support via https://g.octopushq.com/HelpReportAProblem.
Error: Check our licence, and if you want to proceed with the upgrade regardless, run `C:\Program Files\Octopus Deploy\Octopus\Octopus.Server.exe database --upgrade --skipLicenseCheck`
Error: Error while executing SQL command in transaction 'TargetLimitPolicy': Invalid column name 'CommunicationStyle'.
Error: Invalid column name 'CommunicationStyle'.
Error: The command being executed was:
Error: SELECT COUNT(Id) FROM dbo.[Machine] WHERE IsDisabled = 0 AND CommunicationStyle IN ('TentaclePassive','TentacleActive','Ssh','OfflineDrop','AzureCloudService','AzureWebApp','AzureServiceFabricCluster','Kubernetes')
Error: SQL Error 207 - Invalid column name 'CommunicationStyle'.
Error: Invalid column name 'CommunicationStyle'.
Error: System.Exception: Error while executing SQL command in transaction 'TargetLimitPolicy': Invalid column name 'CommunicationStyle'.
Error: Invalid column name 'CommunicationStyle'.
Error: The command being executed was:
Error: SELECT COUNT(Id) FROM dbo.[Machine] WHERE IsDisabled = 0 AND CommunicationStyle IN ('TentaclePassive','TentacleActive','Ssh','OfflineDrop','AzureCloudService','AzureWebApp','AzureServiceFabricCluster','Kubernetes') ---> System.Data.SqlClient.SqlException: Invalid column name 'CommunicationStyle'.
Error: Invalid column name 'CommunicationStyle'.
Error: at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
Error: at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
Error: at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
Error: at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
Error: at System.Data.SqlClient.SqlDataReader.get_MetaData()
Error: at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
Error: at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
Error: at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
Error: at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
Error: at System.Data.SqlClient.SqlCommand.ExecuteScalar()
Error: at Nevermore.Transient.IDbCommandExtensions.<>c__DisplayClass11_0.<ExecuteScalarWithRetry>b__0()
Error: at Nevermore.Transient.RetryPolicy.ExecuteAction[TResult](Func`1 func)
Error: at Nevermore.RelationalTransaction.ExecuteScalar[T](String query, CommandParameterValues args, Nullable`1 commandTimeoutSeconds)
Error: --- End of inner exception stack trace ---
Error: at Nevermore.RelationalTransaction.ExecuteScalar[T](String query, CommandParameterValues args, Nullable`1 commandTimeoutSeconds)
Error: at Octopus.Core.Features.Licensing.Schemes.Policies.TargetLimitPolicy.GetUsage(IRelationalStore store, Int32 numberOfMachinesToAdd)
Error: at Octopus.Core.Features.Licensing.Schemes.Policies.TargetLimitPolicy.Apply(LicenseCheckResultBuilder resultBuilder)
Error: at Octopus.Core.Features.Licensing.Schemes.Policies.CombinedLicenseLimitPolicy.Apply(LicenseCheckResultBuilder resultBuilder)
Error: at Octopus.Core.Features.Licensing.Schemes.CurrentLicensingScheme.Check(LicenseKey licenseKey)
Error: at Octopus.Core.Features.Licensing.LicenseChecker.Check(License license)
Error: at Octopus.Core.Initialization.DatabaseUpgrader.CheckLicenceIsCurrentWithThisVersion(IRelationalStore store, ILicenseChecker licenseChecker, ILog log)
Error: Failed to upgrade the database 'OctopusDeploy' on SQL Server at 'tcp:octopusevhaahdstwdfy.database.windows.net,1433' to the expected schema running as 'adminsql@octopusevhaahdstwdfy': The reason should be logged above.
Error: All changes have been rolled back to the last known good state. If you know what the problem is and how to fix it, please fix the problem and then run the same command to try the upgrade again. Otherwise you should reinstall the version of Octopus Server you just upgraded from, and then contact our support team for help resolving this problem.
Error: The previous command returned a non-zero exit code of: 1
Error: The command that failed was: "C:\Program Files\Octopus Deploy\Octopus\Octopus.Server.exe" database --instance "OctopusServer" -upgrade```

# Sources

Some may be private.

https://secure.helpscout.net/conversation/623065221/29546?folderId=557082

**Comment by michaelnoonan** [comment]
Release note: Fixed a bug preventing upgrades from Octopus Server `2018.5.7` or earlier directly to `2018.7.0` - please upgrade directly to `2018.7.1`
