### ISSUE TITLE
Upgrading to 2018.7.x can fail with error `Unrecognised document prefix Accounts-1`

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#4742]
**Issue:**
If you are upgrading to Octopus 2018.7.0 or 2018.7.1 from an earlier version of Octopus and have an account with the format Accounts-x the upgrade will fail and leave you in an inconsistent state requiring a database restore from backup.

**Error message:**
```
2018-07-19 14:43:32.1707   6224      7 FATAL  Unhandled AppDomain exception occurred: Failed upgrading database schema - the entire upgrade has been rolled back to its last known good state.
Unrecognised document prefix Accounts-1
System.Exception
   at Octopus.Core.UpgradeScripts.Script0120PopulateRelatedDocumentTable.GetDocumentTypeFromIdForMachines(String relatedId)
   at Octopus.Core.UpgradeScripts.Helpers.RelatedDocumentTableMigration.MigrateReferenceCollectionColumn(Func`1 dbCommandFactory, String parentTableName, Func`2 getTableNameFromId)
   at Octopus.Core.UpgradeScripts.Script0120PopulateRelatedDocumentTable.ProvideScript(Func`1 dbCommandFactory)
   at DbUp.Engine.LazySqlScript.get_Contents()
   at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
Logs:
Beginning transaction
Executing SQL Server script 'Octopus.Core.UpgradeScripts.Script0120PopulateRelatedDocumentTable.cs'
Upgrade failed due to an unexpected exception:
System.Exception: Unrecognised document prefix Accounts-1
   at Octopus.Core.UpgradeScripts.Script0120PopulateRelatedDocumentTable.GetDocumentTypeFromIdForMachines(String relatedId)
   at Octopus.Core.UpgradeScripts.Helpers.RelatedDocumentTableMigration.MigrateReferenceCollectionColumn(Func`1 dbCommandFactory, String parentTableName, Func`2 getTableNameFromId)
   at Octopus.Core.UpgradeScripts.Script0120PopulateRelatedDocumentTable.ProvideScript(Func`1 dbCommandFactory)
   at DbUp.Engine.LazySqlScript.get_Contents()
   at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()

System.Exception
   at Octopus.Core.Initialization.DatabaseUpgrader.RunSchemaUpgradeScripts(IRelationalStore store, IScriptProvider scriptProvider, ILog customLog)
   at Octopus.Core.Initialization.DatabaseUpgrader.Upgrade(IRelationalStore store, ILicenseChecker licenseChecker, Boolean skipLicenceCheck, ILog customLog, CancellationToken cancellationToken, IScriptProvider scriptProvider, Boolean skipPostUpgradeScripts)
   at Octopus.Core.Initialization.BuiltIn.DatabaseUpgradeInitializer.Initialize(IRelationalStore store)
   at Nevermore.StoreInitializer.Initialize()
   at Octopus.Server.OctopusServerEngine.Start()
   at Octopus.Server.Commands.RunCommand.Start()
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)
   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass1_0.<Run>b__0()
   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by michaelnoonan** [comment]
Release Note: Fixed a bug preventing upgrades to Octopus Server `2018.7.0` or `2018.7.1` with a message like `Unrecognised document prefix Accounts-` - please upgrade directly to `2018.7.2` or newer
