### ISSUE TITLE
Receiving intermittent connection errors on azure web app deploy

### ISSUE THREAD

**Issue by albernhagen** [OctopusDeploy/Issues#4993]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

I am running Octopus in an Azure VM.  I am intermittently getting errors like this when deploying azure web apps:

```
Deploying to Azure WebApp 'my-appi', deployment slot 'staging' in Resource Group 'my-resource-group', using subscription-id 'my-subscription-id-guid' 
October 17th 2018 14:52:16Error
System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference 
October 17th 2018 14:52:16Error
   at CallSite.Target(Closure , CallSite , Object ) 
October 17th 2018 14:52:16Error
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.Execute() 
October 17th 2018 14:52:16Error
   --- End of inner exception stack trace --- 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(AzureServicePrincipalAccount account, String resourceGroupName, AzureTargetSite azureTargetSite) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment) 
October 17th 2018 14:52:16Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() 
October 17th 2018 14:52:16Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() 
October 17th 2018 14:52:16Error
---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference 
October 17th 2018 14:52:16Error
   at CallSite.Target(Closure , CallSite , Object ) 
October 17th 2018 14:52:16Error
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.Execute()<--- 
October 17th 2018 14:52:16Error
Running rollback conventions... 
October 17th 2018 14:52:16Error
One or more errors occurred. 
October 17th 2018 14:52:16Error
System.AggregateException 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(AzureServicePrincipalAccount account, String resourceGroupName, AzureTargetSite azureTargetSite) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment) 
October 17th 2018 14:52:16Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() 
October 17th 2018 14:52:16Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Commands.DeployAzureWebCommand.Execute(String[] commandLineArguments) 
October 17th 2018 14:52:16Error
   at Calamari.Program.Execute(String[] args) 
October 17th 2018 14:52:16Error
--Inner Exception-- 
October 17th 2018 14:52:16Error
Cannot perform runtime binding on a null reference 
October 17th 2018 14:52:16Error
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException 
October 17th 2018 14:52:16Error
   at CallSite.Target(Closure , CallSite , Object ) 
October 17th 2018 14:52:16Error
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) 
October 17th 2018 14:52:16Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 14:52:16Error
   at System.Threading.Tasks.Task.Execute() 
October 17th 2018 14:52:18Fatal
The remote script failed with exit code 100 
```

## Affected versions

2018.8.9 x64
I recently upgraded, but I'm seeing the same error even if I rollback.

**Comment by albernhagen** [comment]
Similarly, I receive intermittent errors when the publishing profile can't be retrieved.  It seems the site name can't be retrieved sometimes as noted below by the double slash -- even though this same job will sometimes run fine.

```Retrieving publishing credentials failed. Publish-settings URI: https://management.azure.com/subscriptions/my-guid/resourceGroups/my-rg/providers/Microsoft.Web/sites//slots/staging/config/publishingCredentials/list?api-version=2016-08-01 
October 17th 2018 15:07:56Error
System.AggregateException: One or more errors occurred. ---> System.Exception: Retrieving publishing credentials failed with HTTP status 404 - Not Found 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.Execute() 
October 17th 2018 15:07:56Error
   --- End of inner exception stack trace --- 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(AzureServicePrincipalAccount account, String resourceGroupName, AzureTargetSite azureTargetSite) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment) 
October 17th 2018 15:07:56Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() 
October 17th 2018 15:07:56Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() 
October 17th 2018 15:07:56Error
---> (Inner Exception #0) System.Exception: Retrieving publishing credentials failed with HTTP status 404 - Not Found 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.Execute()<--- 
October 17th 2018 15:07:56Error
Running rollback conventions... 
October 17th 2018 15:07:56Error
One or more errors occurred. 
October 17th 2018 15:07:56Error
System.AggregateException 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(AzureServicePrincipalAccount account, String resourceGroupName, AzureTargetSite azureTargetSite) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables) 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment) 
October 17th 2018 15:07:56Error
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions() 
October 17th 2018 15:07:56Error
   at Calamari.Deployment.ConventionProcessor.RunConventions() 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Commands.DeployAzureWebCommand.Execute(String[] commandLineArguments) 
October 17th 2018 15:07:56Error
   at Calamari.Program.Execute(String[] args) 
October 17th 2018 15:07:56Error
--Inner Exception-- 
October 17th 2018 15:07:56Error
Retrieving publishing credentials failed with HTTP status 404 - Not Found 
October 17th 2018 15:07:56Error
System.Exception 
October 17th 2018 15:07:56Error
   at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_1.<GetPublishProperties>b__1(Task`1 publishSettingsResponse) 
October 17th 2018 15:07:56Error
   at System.Threading.Tasks.Task.Execute() 
October 17th 2018 15:07:56Fatal
The remote script failed with exit code 100 ```

**Comment by stevenkuhn** [comment]
I am experiencing the same issue as well. Running Octopus Deploy server on an Azure VM. We have 7 Azure Web Apps being deployed as part of a deployment. One of those 7 will randomly fail with the same exception. Here is an example log from one of our deployments (some of the information has been redacted):

```
                    |   == Failed: Step 6: Deploy Catalog Service ==
17:09:31   Fatal    |     The step failed: Activity Deploy Catalog Service on the Octopus Server failed with error 'The remote script failed with exit code 100'.
17:09:31   Verbose  |     Deploy Catalog Service completed
                    |   
                    |     Failed: Octopus Server
17:08:58   Verbose  |       Octopus Server version: 2018.4.5+Branch.master.Sha.1ca8e07d1811da5d2e92c9880e845134c51b583c
17:08:58   Verbose  |       Environment Information:
                    |       OperatingSystem: Microsoft Windows NT 6.3.9600.0
                    |       OsBitVersion: x64
                    |       Is64BitProcess: True
                    |       CurrentUser: NT AUTHORITY\SYSTEM
                    |       MachineName: OCTOPUS
                    |       ProcessorCount: 2
                    |       CurrentDirectory: C:\Windows\system32
                    |       TempDirectory: C:\Windows\TEMP\
                    |       HostProcessName: Octopus.Server
                    |       PID: 1432
17:08:58   Verbose  |       Using account ID '<<REDACTED>>'
17:08:58   Verbose  |       Running this script as the Octopus Server (NT AUTHORITY\SYSTEM)
17:08:58   Verbose  |       Starting C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20181017170858-41413-431' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
17:08:59   Verbose  |       Octopus Deploy: Calamari.Azure version 4.5.7
17:08:59   Verbose  |       Environment Information:
17:08:59   Verbose  |       OperatingSystem: Microsoft Windows NT 6.3.9600.0
17:08:59   Verbose  |       OsBitVersion: x64
17:08:59   Verbose  |       Is64BitProcess: True
17:08:59   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
17:08:59   Verbose  |       MachineName: OCTOPUS
17:08:59   Verbose  |       ProcessorCount: 2
17:08:59   Verbose  |       CurrentDirectory: C:\Octopus\Work\20181017170858-41413-431
17:08:59   Verbose  |       TempDirectory: C:\Windows\TEMP\
17:08:59   Verbose  |       HostProcessName: Calamari.Azure
17:08:59   Info     |       Deploying package:    C:\Octopus\Packages\InRule.Catalog.Service\InRule.Catalog.Service.5.1.1.157+Cloud.166.zip
17:08:59   Verbose  |       Extracting package to: C:\Octopus\Work\20181017170858-41413-431\staging
17:09:00   Verbose  |       Extracted 56 files
17:09:01   Info     |       Performing variable substitution on 'C:\Octopus\Work\20181017170858-41413-431\staging\Web.Release.config'
17:09:01   Info     |       Transforming 'C:\Octopus\Work\20181017170858-41413-431\staging\Web.config' using 'C:\Octopus\Work\20181017170858-41413-431\staging\Web.Release.config'.
17:09:01   Verbose  |       Warning will be elevated to errors. Prevent this by adding the variable Octopus.Action.Package.TreatConfigTransformationWarningsAsErrors and setting it to false.
17:09:01   Verbose  |       Executing Insert (transform line 7, 196)
17:09:01   Verbose  |       on /configuration/appSettings/add
17:09:01   Verbose  |       Applying to 'appSettings' element (source line 9, 4)
17:09:01   Verbose  |       Inserted 'add' element
17:09:01   Verbose  |       Done executing Insert
17:09:01   Verbose  |       Executing Insert (transform line 8, 54)
17:09:01   Verbose  |       on /configuration/appSettings/add
17:09:01   Verbose  |       Applying to 'appSettings' element (source line 9, 4)
17:09:01   Verbose  |       Inserted 'add' element
17:09:01   Verbose  |       Done executing Insert
17:09:01   Verbose  |       Executing Insert (transform line 9, 84)
17:09:01   Verbose  |       on /configuration/appSettings/add
17:09:01   Verbose  |       Applying to 'appSettings' element (source line 9, 4)
17:09:01   Verbose  |       Inserted 'add' element
17:09:01   Verbose  |       Done executing Insert
17:09:01   Verbose  |       Executing Replace (transform line 13, 23)
17:09:01   Verbose  |       on /configuration/inrule.repository.service/connectionString
17:09:01   Verbose  |       Applying to 'connectionString' element (source line 23, 6)
17:09:01   Verbose  |       Replaced 'connectionString' element
17:09:01   Verbose  |       Done executing Replace
17:09:01   Verbose  |       Executing Replace (transform line 15, 35)
17:09:01   Verbose  |       on /configuration/inrule.repository.service/authentication
17:09:01   Verbose  |       Applying to 'authentication' element (source line 28, 6)
17:09:01   Verbose  |       Replaced 'authentication' element
17:09:01   Verbose  |       Done executing Replace
17:09:01   Verbose  |       Executing SetAttributes (transform line 30, 38)
17:09:01   Verbose  |       on /configuration/system.serviceModel/bindings/wsHttpBinding/binding[@name='WSHttpBinding']/security
17:09:01   Verbose  |       Applying to 'security' element (source line 111, 12)
17:09:01   Verbose  |       Set 'mode' attribute
17:09:01   Verbose  |       Set 1 attributes
17:09:01   Verbose  |       Done executing SetAttributes
17:09:01   Verbose  |       Executing SetAttributes (transform line 38, 92)
17:09:01   Verbose  |       on /configuration/system.serviceModel/services/service[@name='InRule.Repository.Service.RepositoryService']/endpoint
17:09:01   Verbose  |       Applying to 'endpoint' element (source line 121, 10)
17:09:01   Verbose  |       Set 'behaviorConfiguration' attribute
17:09:01   Verbose  |       Set 1 attributes
17:09:01   Verbose  |       Done executing SetAttributes
17:09:01   Verbose  |       Executing Insert (transform line 43, 26)
17:09:01   Verbose  |       on /configuration/system.serviceModel/behaviors/endpointBehaviors
17:09:01   Verbose  |       Applying to 'behaviors' element (source line 126, 6)
17:09:01   Verbose  |       Inserted 'endpointBehaviors' element
17:09:01   Verbose  |       Done executing Insert
17:09:01   Verbose  |       Executing Insert (transform line 50, 17)
17:09:01   Verbose  |       on /configuration/system.serviceModel/extensions
17:09:01   Verbose  |       Applying to 'system.serviceModel' element (source line 106, 4)
17:09:01   Verbose  |       Inserted 'extensions' element
17:09:01   Verbose  |       Done executing Insert
17:09:01   Info     |       Deploying to Azure WebApp '<<REDACTED>>' in Resource Group <<REDACTED>>, using subscription-id '<<REDACTED>>'
17:09:01   Verbose  |       Authentication Context: https://login.windows.net/<<REDACTED>>
17:09:30   Verbose  |       Retrieving publishing profile from https://management.azure.com/subscriptions/<<REDACTED>>/resourceGroups/<<REDACTED>>/providers/Microsoft.Web/sites/<<REDACTED>>/config/publishingCredentials/list?api-version=2015-08-01
17:09:31   Error    |       System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
17:09:31   Error    |       at CallSite.Target(Closure , CallSite , Object )
17:09:31   Error    |       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
17:09:31   Error    |       at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_2.<GetPublishProperties>b__4(Task`1 publishSettingsResponse)
17:09:31   Error    |       at System.Threading.Tasks.Task.Execute()
17:09:31   Error    |       --- End of inner exception stack trace ---
17:09:31   Error    |       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
17:09:31   Error    |       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
17:09:31   Error    |       at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(String subscriptionId, String resourceGroupName, String siteName, String tenantId, String applicationId, String password, String resourceManagementEndpoint, String activeDirectoryEndPoint)
17:09:31   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables)
17:09:31   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment)
17:09:31   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
17:09:31   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
17:09:31   Error    |       ---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
17:09:31   Error    |       at CallSite.Target(Closure , CallSite , Object )
17:09:31   Error    |       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
17:09:31   Error    |       at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_2.<GetPublishProperties>b__4(Task`1 publishSettingsResponse)
17:09:31   Error    |       at System.Threading.Tasks.Task.Execute()<---
17:09:31   Error    |       Running rollback conventions...
17:09:31   Error    |       One or more errors occurred.
17:09:31   Error    |       System.AggregateException
17:09:31   Error    |       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
17:09:31   Error    |       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
17:09:31   Error    |       at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.GetPublishProperties(String subscriptionId, String resourceGroupName, String siteName, String tenantId, String applicationId, String password, String resourceManagementEndpoint, String activeDirectoryEndPoint)
17:09:31   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.GetPublishProfile(VariableDictionary variables)
17:09:31   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment)
17:09:31   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
17:09:31   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
17:09:31   Error    |       at Calamari.Azure.Commands.DeployAzureWebCommand.Execute(String[] commandLineArguments)
17:09:31   Error    |       at Calamari.Program.Execute(String[] args)
17:09:31   Error    |       --Inner Exception--
17:09:31   Error    |       Cannot perform runtime binding on a null reference
17:09:31   Error    |       Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
17:09:31   Error    |       at CallSite.Target(Closure , CallSite , Object )
17:09:31   Error    |       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
17:09:31   Error    |       at Calamari.Azure.Integration.Websites.Publishing.ResourceManagerPublishProfileProvider.<>c__DisplayClass0_2.<GetPublishProperties>b__4(Task`1 publishSettingsResponse)
17:09:31   Error    |       at System.Threading.Tasks.Task.Execute()
17:09:31   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20181017170858-41413-431 exited with code 100
17:09:31   Verbose  |       Updating manifest with output variables
17:09:31   Verbose  |       Updating manifest with action evaluated variables
17:09:31   Fatal    |       The remote script failed with exit code 100
17:09:31   Fatal    |       The action Deploy Catalog Service on the Octopus Server failed
```

While we've had intermittent problems in the past (like not being able to resolve the Azure management hostname), I've never encountered this specific issue before. This issue has only arisen in the last 24 hours.

**Comment by albernhagen** [comment]
This was an Azure outage.  I will close the issue.
