### ISSUE TITLE
Certificates validation failures on Read can prevent UI from operating correctly in versions 2018.8.7 and greater

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5020]
Some certificates have been identified as being un-readable by Octopus Deploy version 2018.8.7 and greater. These certificates could have been stored prior to upgrade, and cause error messages like `Failed to read certificate: version 1 certificate contains extra data` when a user browses to a route that attempts to read the certificate. 

Such places include the variable editor, tenant variable editor and the certificate list and edit pages. The API is also effected, any GET operations against the `Certificate` resource trigger this error, and in worst cases, this can block releases altogether.

### Additional detail

The certificates that appear to be an issue were generated using the pyOpenSSL library. One such certificate is as follows:

```
-----BEGIN CERTIFICATE-----
MIIDAjCCAeoCFB+M5Oi9qfGrPikV/d44DfLCVMDuMA0GCSqGSIb3DQEBCwUAMC4x
CzAJBgNVBAYTAlVTMQwwCgYDVQQKDANYWFgxETAPBgNVBAMMCE15IENBIFYzMB4X
DTE4MTAyMzA4MjQzOFoXDTI4MTAyMDA4MjQzOFowLjELMAkGA1UEBhMCVVMxDDAK
BgNVBAoMA1hYWDERMA8GA1UEAwwITXkgQ0EgVjMwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC2ATfFRW9oM3Yz10EEIVcRlOnfPsQQBT9Z7GKuP5MKZAI1
CHX9ujf1A/EeKBHtCTU5q7TLtRIpAfFVJj7KynSqcN9SzXBvvyIX82VienV4S4XK
ywiY0yfmeVFZy2IQz2o5vm+Al+jzBm200rwPtadHy0z4xsLy7ly1K1fd828Ui9pB
nCaeuoih4n2GSpqgNIHnlkHGwmWYeryveXpSsWJYodQroNl89usHqRXlH0alVpQs
Tfk+LNoiDGwTdRZFeLYo/Rqw0iSvCNgSULrK2TpT4ZNHe6HIr9I2t9fNUvf0J9bG
EJrL1K7Gh2V85dcYBs/0Nh+eFs7Hp5Ua0JlxCufjAgMBAAGjHTAbMAwGA1UdEwQF
MAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQASQ6195ALx1Mfs
ZXF5OqBKC6DR0d4UC/pxth5xpl5wM5FpiH/bMUIqzKLEvyV3ZMZ4UyPC+tn5k+gs
HAwUJpZDKKmzhgZbmeuwNbRk3H5NRjQ3do2jwneDdIGAI8DtjOlEOtbkfO0xDxP/
UM7EUt3/Lk6SxPhoDep7MdkWzJkpjzPzz3UO/nGNTfGOJza2pTIV+h7oKGpnxkdX
4oJOLBa1C4ONDQQOCYpC2O+66p/j5YGIY/ifuxviPItYk8DZR2YgNC7vRuVMBXAz
wY48OlOW+ybmolmMO4Hg19BT45zJLEqF/Sju+e+QZHMHTe5jen76cA3RZxdQ656w
wj47Z+DO
-----END CERTIFICATE-----
```

## What I expected to happen

Certificates that were once stored by Octopus Deploy, should be readable, regardless of origin.

## Steps to reproduce

1. In version 2018.7.7 upload the certificate above into the certificate library
2. Create a project `A` that has a variable that uses this certificate
3. Upgrade the instance to 2018.8.7
4. Browse to the variable editor for `A` and observe an error (stack trace below)

### Screen capture

![image](https://user-images.githubusercontent.com/579657/47352834-4e65c900-d702-11e8-9c2a-1141b103cf74.png)

### Typical stack trace

```
Octopus v2018.8.9

An error occurred on the mapping CertificateResource.CertificateDataFormat = Certificate.CertificateDataFormat [attempted value was (unknown)]: problem parsing cert: Org.BouncyCastle.Security.Certificates.CertificateException: Failed to read certificate ---> System.ArgumentException: version 1 certificate contains extra data

at Org.BouncyCastle.Asn1.X509.TbsCertificateStructure..ctor(Asn1Sequence seq)
at Org.BouncyCastle.Asn1.X509.TbsCertificateStructure.GetInstance(Object obj)
at Org.BouncyCastle.Asn1.X509.X509CertificateStructure..ctor(Asn1Sequence seq)
at Org.BouncyCastle.Asn1.X509.X509CertificateStructure.GetInstance(Object obj)
at Org.BouncyCastle.X509.X509CertificateParser.ReadDerCertificate(Asn1InputStream dIn)
at Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Stream inStream)
--- End of inner exception stack trace ---
```

## Affected versions

**Octopus Server:** version 2018.8.7 and above.

## Workarounds
If releases are blocked, *and* the effected certificates are required, a downgrade to version `2018.8.6` is recommended as there is no workaround that maintains the original certificate.

If the effected certificates that are no longer required, they can be removed by using direct API calls to send DELETE requests to the Certificate resource by `Id`, to unblock the UI. However if they are associated with variable sets or tenant variables, these variables may need to be deleted first.

## Links

As this issue appears to be caused by changes to certificate validation in a dependency I have raised an issue regarding those changes with the project https://github.com/bcgit/bc-csharp/issues/158

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

**Comment by jburger** [comment]
Quick update: The certificates that cause this issue do not have a version number specified, but use V3 extensions, which is a non-compliant structure.  For new certificates, please ensure they specify a version number if they are not V1 certificates. We are working on a better experience for existing non-compliant certificates in the event that some were uploaded prior to `2018.8.7`

In the meantime, if you are in a situation where you experience this issue, please reach out to us via support@octopus.com

**Comment by jburger** [comment]
Another update - we have seen another incident where non compliant DER values are now being validated, causing certificates with incorrect DER encoding to fail to be read and produce a similar stack trace to the one above - however the message reads `corrupted stream detected`.

**Comment by jburger** [comment]
To prevent further issues, we're rolling back to a previous version of bouncy castle while we determine improvements to allow us to get back on the mainline.
