### ISSUE TITLE
Cannot retrieve VariableSet by using deployment.ManifestVariableSetId when the variable is scoped to a channel

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#5097]
- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
An exception with message `Value cannot be null` is thrown when try to retrieve a `VariableSet` by using `deployment.ManifestVariableSetId`, and there is a variable that scoped to a channel

## What I expected to happen
Should be able to retrieve the `VariableSet`

### Error message

```
project) at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.<>c__DisplayClass0_0.<StartPermissionCheck>b__2(VariableDeclaration v) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.<>c__DisplayClass18_0.<BuildViewPermissionFilter>b__0(IId x) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.<>c__DisplayClass13_0.<FilterVariableSetResource>b__4(VariableResource vr) at Octopus.Shared.Util.ListExtensions.RemoveWhere[TElement](IList1 source, Func2 remove) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.FilterVariableSetResource(VariableSet set, VariableSetResource setResource) at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRules[TRule](Action2 ruleCallback) at Octopus.Server.Web.Infrastructure.Api.LoadResponseDescriptor2.BaseLoadResponder.Execute()
at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRegistered() at Octopus.Server.Web.Infrastructure.Api.Responder1.Respond(TDescriptor options, NancyContext context)
at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
at Nancy.Routing.Route.<>c__DisplayClass4.b__3(Object parameters, CancellationToken context)
at Octopus.Client.OctopusAsyncClient.d__511.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Octopus.Client.OctopusAsyncClient.<Get>d__301.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OneInc.PolicyOne.DeploymentOne.Octopus.DeploymentsService.d__8.MoveNext() in C:\Projects\policyone.tools\Oneinc.PolicyOne.DeploymentOne\OneInc.PolicyOne.DeploymentOne\Octopus\DeploymentsService.cs:line 100
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at OneInc.PolicyOne.DeploymentOne.Octopus.DeploymentsService.d__7.MoveNext() in C:\Projects\policyone.tools\Oneinc.PolicyOne.DeploymentOne\OneInc.PolicyOne.DeploymentOne\Octopus\DeploymentsService.cs:line 77
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OneInc.PolicyOne.DeploymentOne.Octopus.DeploymentsService.d__6.MoveNext() in C:\Projects\policyone.tools\Oneinc.PolicyOne.DeploymentOne\OneInc.PolicyOne.DeploymentOne\Octopus\DeploymentsService.cs:line 49
— End of inner exception stack trace —
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at OneInc.PolicyOne.DeploymentOne.RecurringJobs.GetDeploymentsRecurringJob.Execute(PerformContext context) in C:\Projects\policyone.tools\Oneinc.PolicyOne.DeploymentOne\OneInc.PolicyOne.DeploymentOne\RecurringJobs\GetDeploymentsRecurringJob.cs:line 23
—> (Inner Exception #0) Octopus.Client.Exceptions.OctopusServerException: Octopus Server returned an error: Value cannot be null.
Parameter name: source
Server exception:
Value cannot be null.
Parameter name: source
System.ArgumentNullException
at System.Linq.Enumerable.Where[TSource](IEnumerable1 source, Func2 predicate)
at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.DeriveEnvironmentsFromChannels(IReadOnlyCollection1 allEnvironments, IList1 allChannels, IEnumerable1 lifecycles, VariableDeclaration v, Project project) at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.<>c__DisplayClass0_0.<StartPermissionCheck>b__2(VariableDeclaration v) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.<>c__DisplayClass18_0.<BuildViewPermissionFilter>b__0(IId x) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.<>c__DisplayClass13_0.<FilterVariableSetResource>b__4(VariableResource vr) at Octopus.Shared.Util.ListExtensions.RemoveWhere[TElement](IList1 source, Func2 remove) at Octopus.Server.Web.Api.Actions.InaccessibleVariablesWillBeRemovedRule.FilterVariableSetResource(VariableSet set, VariableSetResource setResource) at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRules[TRule](Action2 ruleCallback) at Octopus.Server.Web.Infrastructure.Api.LoadResponseDescriptor2.BaseLoadResponder.Execute()
at Octopus.Server.Web.Infrastructure.Api.Responder1.ExecuteRegistered() at Octopus.Server.Web.Infrastructure.Api.Responder1.Respond(TDescriptor options, NancyContext context)
at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
at Nancy.Routing.Route.<>c__DisplayClass4.b__3(Object parameters, CancellationToken context)
```

## Links
https://help.octopus.com/t/error-while-get-variables-set/21777

**Comment by mayuanyang** [comment]
Release Note: Fix a bug where `VariableSet` cannot be retrieved through `Deployment.ManifestVariableSetId` when there is variable scoped to channel
