### ISSUE TITLE
Migrating step-template versions can cause duplicate versions

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5115]
When importing Step Templates without the `--overwrite` flag specified, it is possible for `ActionTemplateVersion` records _greater than the current version_ of the `ActionTemplate` in the destination to be imported.

The result of this is that when someone updates the template in the destination and then attempts to update usages of the template, it fails with an error similar to:

```
Sequence contains more than one matching element
System.InvalidOperationException
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Web.Api.Actions.DeploymentActionUpdate.ActionTemplateActionsUpdateResponder.<>c__DisplayClass5_2.<ExecuteRegistered>b__4(DeploymentAction a)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Actions.DeploymentActionUpdate.ActionTemplateActionsUpdateResponder.ExecuteRegistered(String actionTemplateId)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

Alternatively, this can be caused by renaming an ActionTemplate before exporting it, where the new name clashes with an existing template in the destination.

Reported by https://secure.helpscout.net/conversation/712911629 (private link) and discussed further in https://octopususergroup.slack.com/archives/C6UEBB7R9/p1541114183053300 (Octopus community Slack thread)

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrating step-template versions can cause duplicate versions](https://trello.com/c/UAqmZBwe/28-migrating-step-template-versions-can-cause-duplicate-versions)

**Comment by droyad** [comment]
Similar to #4001
