### ISSUE TITLE
Action Templates which have an 'Octopus.Action.Package.PackageId' parameter but no property were not converted to packages collection

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5156]
https://github.com/OctopusDeploy/Issues/issues/5054 was reported to be still affecting at least one customer after upgrading to >= 2018.9.9.

The cause seems to be step templates which have an `Octopus.Action.Package.PackageId` parameter, but no corresponding property.  This meant these templates were missed by all the data-migration scripts around packages, and now have no entry in the packages collection.

When they are added into a project deployment process, a package entry is created and assigned an ID.  However, this ID changes when the action template is updated, resulting in the error similar to 

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Octopus.Server.Web.Mapping.DeploymentActionPackageNameMapper.MapToNames(String projectId, IEnumerable`1 models)
at Octopus.Server.Web.Mapping.ResourceMappings.<>c__DisplayClass9_4.<CreateBaseMappings>b__115(ChannelVersionRule rule)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Reported by https://secure.helpscout.net/conversation/725804522/36430?folderId=571733 (private link)

**Comment by MJRichardson** [comment]
Only one customer was seen which had this configuration, and they have been manually resolved.

Closing for now.  We can reopen if we see it again.
