### ISSUE TITLE
Migration from version prior to 2019.1 can corrupt `builtinrepositoryconfigurations-single` configuration json column

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5338]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Access to `/library/builtinrepository` thrown an exception
```
Octopus v2019.1.10

An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BuiltInFeedStatsResponder (DelegateActivator), Services = [Octopus.Server.Web.Api.NuGet.BuiltInFeedStatsResponder], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BuiltInFeedStatsResponder (ReflectionActivator), Services = [Octopus.Server.Web.Api.NuGet.BuiltInFeedStatsResponder], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BuiltInPackageRepository (DelegateActivator), Services = [Octopus.Core.BuiltInFeed.IBuiltInPackageRepository], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BuiltInPackageRepository (ReflectionActivator), Services = [Octopus.Core.BuiltInFeed.BuiltInPackageRepository, Octopus.Core.BuiltInFeed.IBuiltInPackageRepository], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Octopus.Shared.Util.IOctopusFileSystem, Octopus.Core.RelationalStorage.IOctopusRelationalStore, Octopus.Core.BuiltInFeed.IBuiltInRepositoryConfigurationStore, Octopus.Core.Model.Events.IEventStore)' on type 'BuiltInPackageRepository'. ---> Unexpected character encountered while parsing value: @. Path '', line 0, position 0. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)

Autofac.Core.DependencyResolutionException

at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)

at Autofac.Core.Resolving.InstanceLookup.Execute()

at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)

at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)

at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)

at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)

at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)

at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)


--Inner Exception--
```

It seems in older versions the PackagesDirectory was stored as a fully qualified path.

## What I expected to happen

It should list the built in packages

## Steps to reproduce

1. Upgrade from a previous version, eg 3.17.12

### Screen capture

![image](https://user-images.githubusercontent.com/122651/53448313-d8cc8980-3a62-11e9-9b36-983633b03a61.png)

## Affected versions

v2019.1+

**Octopus Server:** 

## Workarounds

```
update [Configuration] setJSON='{"PackagesDirectory":"Packages"}'
WHERE Id ='builtinrepositoryconfigurations-single'
```

## Links

https://secure.helpscout.net/conversation/787440212/39901/

**Comment by johnsimons** [comment]
Release Note: Corrupt `builtinrepositoryconfigurations-single` configuration json column fixed
