### ISSUE TITLE
new_octopusartifact fails to collect artifact on Linux SSH target for relative paths

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5385]
`new_octopusartifact` fails to collect artifacts on Linux SSH target that have relative paths, the error message provided indicates that the file doesn't exist.

The library used to retrieve the file appears to use `$HOME` as the relative path root, instead of the current working directory.

## What I expected to happen

`new_octopusartifact` should attempt to use the same relative path root, as the script it is running in, so that it can access the desired file correctly.

## Steps to reproduce

1. Use the following script against a linux based ssh target
```
#!/usr/bin/env bash

resultsFileName="./TestResults.trx"
echo "hello world" >> $resultsFileName
new_octopusartifact $resultsFileName
```
2. Upon deployment, see error as described below in **Log excerpt**

### Screen capture
![image](https://user-images.githubusercontent.com/579657/54250092-5085d280-4592-11e9-97b1-e8df6a14b6d9.png)

### Log exerpt

```
No such file
Renci.SshNet.Common.SftpPathNotFoundException
   at Renci.SshNet.Common.AsyncResult.EndInvoke()
   at Octopus.Server.Orchestration.Targets.Ssh.Connectivity.SshCommandObserver.PerformDownload(SftpClient client, String remotePath, Int64 totalLength, Action`1 progress)
   at Octopus.Server.Orchestration.Targets.Ssh.Connectivity.SshCommandObserver.<>c__DisplayClass4_0.<DownloadStreamUntilComplete>b__0()
   at Nevermore.Transient.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Octopus.Server.Orchestration.Targets.Ssh.SshRemoteEndpointFacade.DownloadArtifact(CollectedArtifact artifact)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Octopus.Server.Orchestration.Targets.Ssh.SshRemoteEndpointFacade.UploadExecuteDownload(StartScriptCommand command)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.Immediate.ExecutionTargets.SshBashExecutionTarget.Execute(String bootstrapper, IReadOnlyList`1 boostrapperArguments, IReadOnlyList`1 files, Nullable`1 forceIsolationLevel, Boolean raw)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.Immediate.ImmediateExecutor.ExecuteCalamari(ICalamariFlavour flavour, String calamariCommand, IReadOnlyList`1 calamariArguments, IReadOnlyList`1 files, IReadOnlyList`1 deploymentTools, VariableCollection extraVariables, TargetManifest targetManifest)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.CommandBuilders.RunCalamariCommandBuilder.Execute()
   at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Script.ScriptActionHandler.Execute(IActionHanderContext context)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.<>c__DisplayClass12_0.<Execute>b__2()
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.ExecuteOnDeploymentTarget(ActionCommand command, DeploymentTarget deploymentTarget, Maybe`1 guidanceExcludeCallback)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.<>c__DisplayClass38_1.<ExecuteActionAndInitLoggingContext>b__1()
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.<>c__DisplayClass38_0.<ExecuteActionAndInitLoggingContext>b__0()
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteWithTransientErrorDetection(Action action, DeploymentTarget deploymentTarget)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentTaskController.ExecuteActionAndInitLoggingContext(PlannedStep step, DeploymentTarget targetContext, PlannedAction action) 
```
## Affected versions

Full list TBA 
Seen in Octopus Server `2019.2.3`

## Workarounds

This feature appears to work when using absolute paths - please try this if possible.

## Links
[support ticket](https://help.octopus.com/t/new-octopusartifact-claims-its-picking-up-file-but-doesnt/22515)

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

**Comment by NickJosevski** [comment]
internal shortcut link

https://app.shortcut.com/octopusdeploy/story/107126/a-bug-with-the-artifacts-feature-in-bash-if-you-don-t-fully-qualify-the-directory-for-the-artifact-calamari-bash-sends-the

**Comment by NickJosevski** [comment]
The Octopus engineering team has reviewed this issue.  
After careful consideration, we’ve classed this low priority. This means we won’t work on it in the near future. 
We prioritize issues based on the number of people affected, the impact type, and available workarounds. 
If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.
