### ISSUE TITLE
Server fails to start as part of upgrading to 2019.2.5

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5414]
# The bug

For a small set of customers, with specifically misconfigured UserRoles the upgrade to 2019.2.5 would fail with an exception, preventing Octopus from starting up.

This bug does not cause data corruption, it simply blocks the startup of the server.

### Log exerpt

```
ERROR  Upgrade failed due to an unexpected exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Octopus.Core.UpgradeScripts.Script0001RemoveTaskViewLogPermissionAgain.UserRoleData.get_GrantedSpacePermissions()
   at Octopus.Core.UpgradeScripts.Script0001RemoveTaskViewLogPermissionAgain.RoleNeedsUpgrading(UserRoleData role)
```

## Affected versions

**Octopus Server:** 2018.2.5 only (which is no longer available for download)

## Workarounds

Update to 2018.2.6

**Comment by NickJosevski** [comment]
Release Note: Fixed startup issue for a subset of customers by a data consistency script in 2019.2.5
