### ISSUE TITLE
ArgumentNullException thrown during upgrade to 2019.2.5

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5416]
In some cases where a database is upgraded to 2019.2.5 there have been some reports that upgrades fail due to an ArgumentNullException while attempting to cleanup `TaskViewLog` permission in user roles.

## What I expected to happen

Upgrade scripts should be more resilient to these shapes of UserRole exist.

## Steps to reproduce
1. On version 2019.2.4 modify an existing UserRole to contain TaskViewLog permission, and remove the GrantedSpacePermission array on the resource
2. Perform the upgrade to 2019.2.5
3. Observe the error

### Log exerpt

```
2019-03-21 08:53:40.3771   6376      7  WARN  Error occured when executing scripts, transaction will be rolled back
2019-03-21 08:53:40.3934   6376      7 ERROR  Upgrade failed due to an unexpected exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Octopus.Core.UpgradeScripts.Script0001RemoveTaskViewLogPermissionAgain.UserRoleData.get_GrantedSpacePermissions()
```
## Affected versions

**Octopus Server: 2019.2.5** 

## Workarounds

If you've upgraded to `2019.2.5` and are experiencing this issue, please upgrade to `2019.2.6`.

## Links

[internal ticket](https://secure.helpscout.net/conversation/807221500/41186?folderId=557082)

**Comment by jburger** [comment]
Release note: Fixes ArgumentNullException thrown during to some upgrades of 2019.2.5

**Comment by jburger** [comment]
Closed as duplicate of https://github.com/OctopusDeploy/Issues/issues/5414
