### ISSUE TITLE
Package metadata calculation doesn't handle steps scoped to channels

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#5465]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a deployment process contains a step that is scoped to a channel the create release processing throws an error while trying to calculate the package metadata.

## What I expected to happen

The release should be created.

## Steps to reproduce

1. Create a project
2. Add 2 package steps and scope one to a channel
3. Create a release

### Log exerpt

```
Sequence contains no matching element
System.InvalidOperationException
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Communications.Packages.ReleaseCreation.ReleasePackageMetadataCalculator.<>c__DisplayClass5_3.<DeterminePackageMetadata>b__11(PackageReference packageReference)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Server.Communications.Packages.ReleaseCreation.ReleasePackageMetadataCalculator.DeterminePackageMetadata(IOctopusQueryExecutor queryExecutor, Project project, IEnumerable`1 releaseSelectedPackages, IList`1 packageActions)
   at Octopus.Server.Web.Api.Rules.ReleaseWorkItemsRule.AfterMapBeforeStore(Release model, ReleaseResource resource, ISpecialRuleContext context)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRegisteredRules[TRule](Action`2 ruleCallback)
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.ExecuteRegistered()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

## Affected versions

**Octopus Server:** `2019.4.0`

## Workarounds

None.

## Links

https://help.octopus.com/t/exception-when-creating-new-release-on-existing-project-in-2019-4-0/22676
https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1554722578118300

**Comment by hnrkndrssn** [comment]
Release note: Fixed bug in release creation when steps are scoped to channels
