### ISSUE TITLE
2.0 trying to discover 1.6 tentacle

### ISSUE THREAD

**Issue by embedjohndc** [OctopusDeploy/Issues#558]
guys - i'm seeing 2.0 comms handshaking trying to contact/discover a server in japan which never had a 2.0 tentacle installed but was installed with 1.6 and I have done a migration previously into 2.0. 

This error is being logged every minute in diagnostics, and i am seeing it for other IP addresses.  

The thing is since all my tentacles are online and polling, i should not be seeing any connection errors.

```
----------------------------
c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Server\Communications\Handshaking\PassiveTentacleHandshaker.cs:line 56
   at Pipefish.Actor.OnReceivingTyped[TBody](Message message) in c:\TeamCity\buildAgent\work\cf0b1f41263b24b9\source\Pipefish\Actor.cs:line 113
15:07:35Fatal
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 211.197.74.201:10933
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at Pipefish.Transport.SecureTcp.Client.SecureTcpClient.Send(SecureTcpRequest request) in c:\TeamCity\buildAgent\work\cf0b1f41263b24b9\source\Pipefish.Transport.SecureTcp\Client\SecureTcpClient.cs:line 39
   at Octopus.Server.Communications.Handshaking.PassiveTentacleHandshaker.Receive(PassiveTentacleHandshakeRequest message) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Server\Communications\Handshaking\PassiveTentacleHandshaker.cs:line 56
   at Pipefish.Actor.OnReceivingTyped[TBody](Message message) in c:\TeamCity\buildAgent\work\cf0b1f41263b24b9\source\Pipefish\Actor.cs:line 113
15:07:38Error
Failed to discover SQUID for TAITO(ECSSERVER)
----------------------------
```

**Comment by bmmiller** [comment]
I'm definitely seeing this now.  Unclear how long it has been occurring, but in trying to fix one issue, I happen to check the Diagnostic screen and am getting exactly these errors.  It seems to be a "ghost" tentacle that no longer exists.  Trying to force a tentacle with the same name and IP so I can delete it manually is giving me difficulties in matching the thumbprint.  Is there a way to change the thumbprint of the tentacle to recreate this ghost tentacle in order to properly delete it?
