### ISSUE TITLE
CheckForOctopusUpgrade.IsLinux fails with NullReferenceException

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#5847]
# The bug

Server reports errors in Diagnostics, `CheckForOctopusUpgrade.IsLinux fails with NullReferenceException`

### Screen capture

![image](https://user-images.githubusercontent.com/119096/64695111-b66dfb00-d4de-11e9-9e6b-8f68b2c84b91.png)

### Log exerpt

```
Failed checking for updates System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.IsLinux(Machine machine) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 294
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.AddSpaceMetrics(IOctopusQueryExecutor allPartitionsAsUserWithAllPermissions, Dictionary`2 jsonBuilder, String spaceId) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 308
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.BuildRequestPayload() in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 272
   at Octopus.Server.Schedules.CheckForOctopusUpgrades.CheckForUpdates() in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 207
```

## Affected versions

**Octopus Server:** 2019.8.3, 2019.8.4

## Workarounds

Wait for 2019.8.5

## Links

None

**Comment by NickJosevski** [comment]
Release note: fix for NullReferenceException in CheckForOctopusUpgrade reported in server dignostic errors
