### ISSUE TITLE
Deploying to Linux Azure Web App fails with 404 Not Found

### ISSUE THREAD

**Issue by octocrock** [OctopusDeploy/Issues#6108]
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have verified the problem exists in the latest version
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
## What I expected to happen

I should be able to deploy to a Linux Web App, it looks like this has worked in the past: https://github.com/OctopusDeploy/Issues/issues/5012

## Steps to reproduce

1. Set up a Linux Azure Web App, stack set to .Net Core.
2. Create Azure Web App Deployment Target pointing to Linux Web App
3. In project use built in step of "DEPLOY AN AZURE WEB APP" and set to deploy a .Net Core Package (although this doesn't matter too much as it doesn't get that far)
4. Create release and deploy.
5. Get 404 when trying to reach 'https://<APP-NAME>.scm.azurewebsites.net/msdeploy.axd?site=<APP-NAME>' - it isn't there as Linux.

Looking at this with Bob, it looks to be a hardcoded value here: https://github.com/OctopusDeploy/Calamari/blob/34239a538ad580a7e5e1aee73c13587ad1590112/source/Calamari.Azure/Deployment/Conventions/AzureWebAppConvention.cs#L165

### Log exerpt

```
14:49:50   Verbose  |       Found site:
14:49:50   Verbose  |       Magic / bakeryocto
14:49:50   Verbose  |       Using site 'bakeryocto'
14:49:50   Verbose  |       Using slot ''
14:49:50   Verbose  |       Using ID '94df8cda-3d2c-449c-aa73-6607457692d5' for connections to the remote server.
14:49:50   Verbose  |       Pre-authenticating to remote agent URL 'https://bakeryocto.scm.azurewebsites.net/msdeploy.axd?site=bakeryocto' as '$bakeryocto'.
14:49:52   Verbose  |       Retry #1 on Azure deploy. Exception: Could not connect to the remote computer ("bakeryocto.scm.azurewebsites.net"). On the remote computer, make sure that Web Deploy is installed and that the required process ("Web Management Service") is started.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE.
14:49:54   Verbose  |       Using site 'bakeryocto'
14:49:54   Verbose  |       Using slot ''
14:49:54   Verbose  |       Using ID 'b843ac9f-c8af-4a6f-b6cb-cc07bfb0b891' for connections to the remote server.
14:49:54   Verbose  |       Pre-authenticating to remote agent URL 'https://bakeryocto.scm.azurewebsites.net/msdeploy.axd?site=bakeryocto' as '$bakeryocto'.
14:49:55   Verbose  |       Retry #2 on Azure deploy. Exception: Could not connect to the remote computer ("bakeryocto.scm.azurewebsites.net"). On the remote computer, make sure that Web Deploy is installed and that the required process ("Web Management Service") is started.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE.
14:49:59   Verbose  |       Using site 'bakeryocto'
14:49:59   Verbose  |       Using slot ''
14:49:59   Verbose  |       Using ID 'a836e5b0-c6ed-43d9-b632-e4faed600984' for connections to the remote server.
14:49:59   Verbose  |       Pre-authenticating to remote agent URL 'https://bakeryocto.scm.azurewebsites.net/msdeploy.axd?site=bakeryocto' as '$bakeryocto'.
14:50:00   Verbose  |       Retry #3 on Azure deploy. Exception: Could not connect to the remote computer ("bakeryocto.scm.azurewebsites.net"). On the remote computer, make sure that Web Deploy is installed and that the required process ("Web Management Service") is started.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE.
14:50:08   Verbose  |       Using site 'bakeryocto'
14:50:08   Verbose  |       Using slot ''
14:50:08   Verbose  |       Using ID '91c82c13-db23-4289-b1fb-0fbdf8f661de' for connections to the remote server.
14:50:08   Verbose  |       Pre-authenticating to remote agent URL 'https://bakeryocto.scm.azurewebsites.net/msdeploy.axd?site=bakeryocto' as '$bakeryocto'.
14:50:09   Error    |       Calamari.exe : Microsoft.Web.Deployment.DeploymentDetailedException: Could not connect to the remote computer
14:50:09   Error    |       ("bakeryocto.scm.azurewebsites.net"). On the remote computer, make sure that Web Deploy is installed and that the
14:50:09   Error    |       required process ("Web Management Service") is started.  Learn more at:
14:50:09   Error    |       http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE. ---> System.Net.WebException: The
14:50:09   Error    |       remote server returned an error: (404) Not Found.
14:50:09   Error    |       At C:\Octopus\Work\20200115144948-2549-24\Bootstrap.ps1:49 char:1
14:50:09   Error    |       + &  "C:\Octopus\OctopusServer\Tools\Calamari.Cloud\8.1.4\Calamari.exe" ...
14:50:09   Error    |       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:50:09   Error    |       + CategoryInfo          : NotSpecified: (Microsoft.Web.D...404) Not Found.:String) [], RemoteException
14:50:09   Error    |       + FullyQualifiedErrorId : NativeCommandError
14:50:09   Error    |       at System.Net.HttpWebRequest.GetResponse()
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponseHelper(HttpWebRequest request)
14:50:09   Error    |       --- End of inner exception stack trace ---
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponseHelper(HttpWebRequest request)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponse(HttpWebRequest request)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.PerformHeadRequestHelper(Boolean getVersionInfo, Version&
14:50:09   Error    |       maximumSupportedVersion, Version& minimumSupportedVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider..ctor(DeploymentProviderContext providerContext,
14:50:09   Error    |       DeploymentBaseContext baseContext, String serverVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.DeploymentManager.CreateObjectPrivate(DeploymentProviderContext providerContext,
14:50:09   Error    |       DeploymentBaseOptions baseOptions, DeploymentObject sourceObject, String serverVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions,
14:50:09   Error    |       DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
14:50:09   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.DeployToAzure(RunningDeployment deployment,
14:50:09   Error    |       AzureTargetSite targetSite, CalamariVariableDictionary variables, WebDeployPublishSettings publishSettings)
14:50:09   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment)
14:50:09   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
14:50:09   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
14:50:09   Error    |       Running rollback conventions...
14:50:09   Error    |       Could not connect to the remote computer ("bakeryocto.scm.azurewebsites.net"). On the remote computer, make sure that
14:50:09   Error    |       Web Deploy is installed and that the required process ("Web Management Service") is started.  Learn more at:
14:50:09   Error    |       http://go.microsoft.com/fwlin
14:50:09   Error    |       k/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE.
14:50:09   Error    |       Microsoft.Web.Deployment.DeploymentDetailedException
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponseHelper(HttpWebRequest request)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponse(HttpWebRequest request)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.PerformHeadRequestHelper(Boolean getVersionInfo, Version&
14:50:09   Error    |       maximumSupportedVersion, Version& minimumSupportedVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider..ctor(DeploymentProviderContext providerContext,
14:50:09   Error    |       DeploymentBaseContext baseContext, String serverVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.DeploymentManager.CreateObjectPrivate(DeploymentProviderContext providerContext,
14:50:09   Error    |       DeploymentBaseOptions baseOptions, DeploymentObject sourceObject, String serverVersion)
14:50:09   Error    |       at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions,
14:50:09   Error    |       DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
14:50:09   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.DeployToAzure(RunningDeployment deployment,
14:50:09   Error    |       AzureTargetSite targetSite, CalamariVariableDictionary variables, WebDeployPublishSettings publishSettings)
14:50:09   Error    |       at Calamari.Azure.Deployment.Conventions.AzureWebAppConvention.Install(RunningDeployment deployment)
14:50:09   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
14:50:09   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions()
14:50:09   Error    |       at Calamari.Azure.Commands.DeployAzureWebCommand.Execute(String[] commandLineArguments)
14:50:09   Error    |       at Calamari.Program.Execute(String[] args)
14:50:09   Error    |       --Inner Exception--
14:50:09   Error    |       The remote server returned an error: (404) Not Found.
14:50:09   Error    |       System.Net.WebException
14:50:09   Error    |       at System.Net.HttpWebRequest.GetResponse()
14:50:09   Error    |       at Microsoft.Web.Deployment.AgentClientProvider.GetHttpResponseHelper(HttpWebRequest request)
14:50:09   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20200115144948-2549-24 exited with code 100
14:50:09   Verbose  |       Updating manifest with output variables
14:50:09   Verbose  |       Updating manifest with action evaluated variables
14:50:09   Fatal    |       The remote script failed with exit code 100
14:50:09   Fatal    |       The action Deploy web app on Bakery Linux Web App failed
                    |     
```

## Affected versions

**Octopus Server:**  2019.11.0, 
2019.13.0

## Workarounds

This appears to work if you first deploy from Visual Studio.

## Links

https://github.com/OctopusDeploy/Issues/issues/5012

**Comment by benPearce1** [comment]
Looks like a regression of https://github.com/OctopusDeploy/Issues/issues/5012

**Comment by shaunmarx** [comment]
@octocrock I have tried to reproduce this, but have not been successful so far unless I use the SCM endpoint for linux web apps.

Did you happen to set the `WEBSITE_WEBDEPLOY_USE_SCM` variable to `false` in the Azure portal? It does [mention in their docs](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq#continuous-integration-and-deployment) that you need to enable that setting to use web deploy. 

![image](https://user-images.githubusercontent.com/6700195/72499514-cecf9700-387d-11ea-99f3-08f866deb8f1.png)

**Comment by octocrock** [comment]
@shaunmarx Thank you, I missed that, that wasn't set.  Have tried that now and it works.
