### ISSUE TITLE
Octopus Server: Bad gzip header when extracting tar.gz

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#6130]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When extracting a `tar.gz` archive on the server, such as when using a helm feed for example, we incorrectly use the `tar` extractor which results in an error such as `Bad GZIP Header`

## What I expected to happen

Expect the correct extractor to be used based on the archive type and succeeding to extract the package

## Steps to reproduce

1. Add a upgrade helm chart step
2. Specify a custom helm tool package

### Screenshots

![image](https://user-images.githubusercontent.com/6700195/73320406-ea2d9f80-428a-11ea-9c45-3bb68c2b0cf0.png)

### Log exerpt

```
SharpCompress.Compressors.Deflate.ZlibException : Bad GZIP header.
   at SharpCompress.Common.GZip.GZipFilePart.ReadAndValidateGzipHeader(Stream stream)
   at SharpCompress.Common.GZip.GZipFilePart..ctor(Stream stream, ArchiveEncoding archiveEncoding)
   at SharpCompress.Common.GZip.GZipEntry.GetEntries(Stream stream, OptionsBase options)+MoveNext()
   at Octopus.Core.Packages.Extraction.TarPackageExtractor.Install(Stream packageStream, String directory, ILog log, Boolean suppressNestedScriptWarning) in E:\octopus\OctopusDeploy\source\Octopus.Core\Packages\Extraction\TarPackageExtractor.cs:line 35
   at Octopus.Core.Packages.Extraction.TarPackageExtractor.Install(String packageFile, String directory, ILog log, Boolean suppressNestedScriptWarning) in E:\octopus\OctopusDeploy\source\Octopus.Core\Packages\Extraction\TarPackageExtractor.cs:line 23
   at Octopus.IntegrationTests.Octopus.Core.Packages.PackageExtractorFixture.ExtractCanHandleEmptyFolders(Type extractorType, String extension, Boolean preservesTimestamp) in E:\octopus\OctopusDeploy\source\Octopus.IntegrationTests\Octopus.Core\Packages\PackageExtractorFixture.cs:line 125
```

## Affected versions
**Octopus Server: 2019.4.0-2019.13.0** 

## Workarounds

The workaround for this is to avoid using anything which results in the tar.gz being extracted on the server such as specifying a package.

**Comment by shaunmarx** [comment]
Release Note: Fix an issue where Octopus Server would user the tar extractor for tar.gz resulting in Bad GZIP header error messages
