### ISSUE TITLE
Un-representable DateTime in ScheduledTriggerFilters during database upgrade

### ISSUE THREAD

**Issue by thedewi** [OctopusDeploy/Issues#6152]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

During database upgrade, a `ScheduledTriggerFilter` with a `NextScheduledRun` close to `DateTime.MaxValue`  can cause timezone conversion to fail.

## What I expected to happen

The upgrade should not crash.

## Steps to reproduce

1. Create a `ScheduledTriggerFilter` with a `"NextScheduledRun": "9999-12-31T23:59:59.9999999"`
2. Run a database upgrade taking in `Script0227ProjectTriggersModelChange`

### Log exerpt

```
Executing .NET Database Server script 'Octopus.Core.UpgradeScripts.Script0227ProjectTriggersModelChange.cs'
Moving StartTime from scheduled project triggers from CRON expression
Processing ProjectTriggers-7
Processing ProjectTriggers-228
Processing ProjectTriggers-362
Error occured when executing scripts, transaction will be rolled back
Upgrade failed due to an unexpected exception:
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: t
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at Octopus.Core.Extensions.DateTimeExtensions.ConvertToTimeZone(DateTime baseUtcDateTime, String timezoneId) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Core\Extensions\DateTimeExtensions.cs:line 68
   at Octopus.Core.Extensions.CrontabScheduleExtensions.GetPreviousOccurrenceInSpecifiedTimeZone(CrontabSchedule crontabSchedule, DateTime currentProcessingTimeUtc, String timeZone) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Core\Extensions\CrontabScheduleExtensions.cs:line 44
   at Octopus.Core.UpgradeScripts.Script0227ProjectTriggersModelChange.GetPreviousOccurence(ScheduleTriggerFilter scheduleTriggerFilter) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Core\UpgradeScripts\Script0227ProjectTriggersModelChange.cs:line 70
 ```

## Affected versions

Affected customer installing Octopus Server 2019.12.1.

## Workarounds

The customer worked around it by deleting some problem records and re-entering after upgrade.

## Links

Reported by a customer (private link): https://secure.helpscout.net/conversation/1076378393/56912/

**Comment by flin-8** [comment]
> During database upgrade, a ScheduledTriggerFilter with a NextScheduledRun close to > DateTime.MaxValue can cause timezone conversion to fail.

I'm curious:
1. does `NextScheduledRun` ever get "close" to or is always "exactly" `DateTime.MaxValue`/`MinValue` ? 
2. how does it get there in the first place?

**Comment by thedewi** [comment]
Release Note: Fix DateTime overflow and year skip in db upgrade schedule conversion
