### ISSUE TITLE
Linux tentacle upgrades from tarball install can not be upgraded

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6212]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When attempting to upgrade a linux tentacle installed from a tarball (so, not using a package manager), the upgrade process fails with the following error:
```
System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
```

## What I expected to happen

Upgrade process should successfully uncompress the tarball and apply the upgrade.

## Steps to reproduce

1. Install an older version of Tentacle on a linux box (I used 5.0.6 for my test) from a tarball - https://download.octopusdeploy.com/linux-tentacle/tentacle-5.0.12-linux_x64.tar.gz
2. Run configuration and connect it to an Octopus instance that shipped with a version newer than 5.0.6
3. After initial healthcheck, attempt to perform a tentacle upgrade on the target.
4. Boom.

### Log exerpt

```
Server exception: 
System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   at System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal()
   at Newtonsoft.Json.Bson.BsonDataReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadBsonMessage[T]() in C:\buildAgent\work\fe2b45bbd4978f75\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 250
   at Halibut.Transport.Protocol.MessageExchangeStream.Receive[T]() in C:\buildAgent\work\fe2b45bbd4978f75\source\Halibut\Transport\Protocol\MessageExchangeStream.cs:line 207
   at Halibut.Transport.Protocol.MessageExchangeProtocol.<ProcessReceiverInternalAsync>d__18.MoveNext() in C:\buildAgent\work\fe2b45bbd4978f75\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:line 231 
```

## Affected versions

**Octopus Server: -> Latest** 

## Workarounds
Install the tentacle upgrade manually, rather than using the web UI.

## Links
Log: https://deploy.octopushq.com/app#/Spaces-1/tasks/ServerTasks-585081?activeTab=taskLog (Internal link)
Original ticket: https://secure.helpscout.net/conversation/1081990372/57218/ (Internal link)

**Comment by NickJosevski** [comment]
@Justin-Walsh can you confirm which version you used when you raised this issue please

**Comment by Justin-Walsh** [comment]
Ran it on 2020.1

**Comment by adam-mccoy** [comment]
Release Note: Fix bug with auto-upgrade of tarball Linux tentacles
