### ISSUE TITLE
Unable to create a new host instance using the Terraform provider due to TagSet validation error

### ISSUE THREAD

**Issue by uglybugger** [OctopusDeploy/Issues#6471]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

It appears that the Terraform provider is sending tagsets containing tags with single-token names, which has fallen afoul of more strict validation that was introduced in `2020.3.0-rc0002`.

## What I expected to happen

A server instance to be created with projects, tags and tagsets in the correct structure.

## Steps to reproduce

(Rough reproduction steps; to be clarified.)

1. Attempt to deploy an instance specifying tags and tagsets using the Terraform scripts in the `HostedScripts` package.
2. Use a single-token tag name when specifying a tag to be created.
2. Observe the validation error when Terraform calls the API to create the relevant tagset.

### Log exerpt

03:33:36   Error    |       Error: error creating tagSet Hosted Instances: octopus deploy api returned an error on endpoint tagSets - [Tag Id or name is in invalid format.]
03:33:36   Error    |       on tagSets.tf line 1, in resource "octopusdeploy_tag_set" "hosted_instances":
03:33:36   Error    |       1: resource "octopusdeploy_tag_set" "hosted_instances" {
03:33:36   Error    |       The following command: "C:\terraform\terraform.exe" apply -no-color -auto-approve -parallelism=1
03:33:36   Error    |       With the working directory of: E:\Octopus\Work\20200707033244-663976-260\staging\Hub
03:33:36   Error    |       Failed with exit code: 1
03:33:36   Error    |       Error: error creating tagSet Hosted Instances: octopus deploy api returned an error on endpoint tagSets - [Tag Id or name is in invalid format.]
03:33:36   Error    |       on tagSets.tf line 1, in resource "octopusdeploy_tag_set" "hosted_instances":
03:33:36   Error    |       1: resource "octopusdeploy_tag_set" "hosted_instances" {
03:33:36   Error    |       Calamari.Integration.Processes.CommandLineException
03:33:36   Error    |       at Calamari.Integration.Processes.CommandResult.VerifySuccess()
03:33:36   Error    |       at Calamari.Terraform.TerraformCliExecutor.ExecuteCommand(String[] arguments)
03:33:36   Error    |       at Calamari.Terraform.ApplyCommand.Execute(RunningDeployment deployment, Dictionary`2 environmentVariables)
03:33:36   Error    |       at Calamari.Terraform.TerraformCommand.<InstallAsync>d__9.MoveNext()
03:33:36   Error    |       --- End of stack trace from previous location where exception was thrown ---
03:33:36   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
03:33:36   Error    |       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
03:33:36   Error    |       at Calamari.Terraform.TerraformCommand.Execute()
03:33:36   Error    |       at Calamari.CalamariFlavourProgram.ResolveAndExecuteCommand(IContainer container, CommonOptions options)
03:33:36   Error    |       at Calamari.CalamariFlavourProgram.Run(String[] args)
03:33:36   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in E:\Octopus\Work\20200707033244-663976-260 exited with code 100

## Affected versions

2020.3.0-rc0002

**Octopus Server:**

## Workarounds

Unknown at this stage. Will update as and when workarounds are found.

## Links

https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1594093800482800 (Private link)

https://deploy.octopushq.com/app#/Spaces-142/projects/configure-reef/deployments/releases/6.9762.0/deployments/Deployments-78966?tasklineid=0%2FServerTasks-663976_XZWZFYCP32%2F855780fa222b41019e2f86f9f7230b6c&activeTab=taskLog (Private link)

**Comment by uglybugger** [comment]
Release Note: Fixes an issue where a caller passes an empty string to a tag ID instead of a null and the empty string fails validation.
