### ISSUE TITLE
NRE when attempting to view events

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6763]
# The bug

A null reference exception can occur when attempting to view events.

### Log excerpt

```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Server.Web.Api.Actions.GetEventResponder.DetectCorruptedDiff(Event model) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Api\Actions\GetEventResponder.cs:line 99
   at Octopus.Server.Web.Api.Actions.GetEventResponder.DoCorruptionCheck(Event model, IOctopusRelationalTransaction transaction) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Api\Actions\GetEventResponder.cs:line 50
   at Octopus.Server.Web.Api.Actions.GetEventResponder.ExecuteRegistered(String id) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Api\Actions\GetEventResponder.cs:line 41
   at Octopus.Server.Web.Infrastructure.Api.CustomActionWithIdResponder`1.ExecuteRegistered() in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Infrastructure\Api\CustomActionResponder.cs:line 46
   at Octopus.Server.Web.Infrastructure.Api.CustomResponder`1.Respond(TDescriptor options, NancyContext context) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Infrastructure\Api\CustomResponder.cs:line 288
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object o, CancellationToken x) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Infrastructure\OctopusNancyModule.cs:line 81
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
   at Octopus.NancyOwin.NancyMiddleware.RequestComplete(NancyContext context, IDictionary`2 environment) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Owin\NancyMiddleware.cs:line 171
   at Octopus.NancyOwin.NancyMiddleware.<>c__DisplayClass3_0.<<UseNancy>b__1>d.MoveNext() in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Owin\NancyMiddleware.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Middleware\OctopusClientOldVersionWarningMiddleware.cs:line 38
   at Octopus.Server.Web.Middleware.RequestLoggerMiddleware.InvokeAsync(HttpContext context) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Middleware\RequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in C:\buildAgent\work\f014c79b193351c2\source\Octopus.Server\Web\Middleware\ErrorHandlingMiddleware.cs:line 63
   ```

## Affected versions

**Octopus Server:** 2020.5.0+

## Links

https://octopus.zendesk.com/agent/tickets/64699

**Comment by tothegills** [comment]
Release note: Fix null reference exception when attempting to view events
