### ISSUE TITLE
Azure App Service step errors if no connection strings supplied and app settings are supplied

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6891]
The `Deploy an Azure App Service` step in will throw an error if app settings are specified, but no connection strings are.

Reported in `2021.1.7149`
[Reported by](https://octopus.zendesk.com/agent/tickets/69464) (private link)

![image](https://user-images.githubusercontent.com/113759/119280543-43d28e00-bc75-11eb-9ad6-e146b066793f.png)

```
Value cannot be null. (Parameter 'key')
System.ArgumentNullException
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
at Calamari.AzureAppService.Behaviors.AzureAppServiceSettingsBehaviour.PublishAppSettings(WebSiteManagementClient webAppClient, TargetSite targetSite, AppSetting[] appSettings, String authToken)
at Calamari.AzureAppService.Behaviors.AzureAppServiceSettingsBehaviour.Execute(RunningDeployment context)
at Calamari.Common.Plumbing.Pipeline.PipelineCommand.ExecuteBehaviour(RunningDeployment context, IBehaviour behaviour)
at Calamari.Common.Plumbing.Pipeline.PipelineCommand.Execute(ILifetimeScope lifetimeScope, IVariables variables)
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7202 |
| 2021.2 | 2021.2.4057 |
| 2021.3+ | <all releases> |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7202 |
| 2021.2 | 2021.2.4057 |
| 2021.3+ | -all releases- |
