### ISSUE TITLE
Add to HA Cluster wizard fails checking database connection

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6896]
When using the Octopus Server Manager to add an instance to a HA cluster an error occurs on the `Database` page of the wizard. It's not possible to progress past this.

Affects: 
`2020.6.4974`
`2021.1.7089`
`2021.2.3118`

## Workaround

Use the command line to configure the server

## Steps to reproduce

1. Run the Octopus Server Manager
2. Create a new Instance
3. Click the `Add this instance to a High Availability Cluster` option
4. Go through the wizard until the database tab
5. Enter the details of an existing SQL Server and DB
6. Click Next

NB: The existing SQL and DB can be on the same machine, you don't need two machines.

## Error
[This part of the Server Manager](https://github.com/OctopusDeploy/OctopusDeploy/blob/17da4f4f72ba1d7b2383630f89a274e9e51c6aa6/source/Octopus.Manager.Server/OctopusConfiguration/SetupWizard/SqlServerExpressConfigurer.cs#L105) checks to see if the target DB requires an upgrade. However [this part](https://github.com/OctopusDeploy/OctopusDeploy/blob/4deb11fe8b8884af278eba1368798c888709a831/source/Octopus.Upgraders/DatabaseUpgradeScriptDependencies.cs#L45-L48) of the upgrader fails because all the values are `null`. The `ctor` is called [here](https://github.com/OctopusDeploy/OctopusDeploy/blob/17da4f4f72ba1d7b2383630f89a274e9e51c6aa6/source/Octopus.Manager.Server/OctopusConfiguration/SetupWizard/SqlServerExpressConfigurer.cs#L114).

We changed it so that the upgrader takes these dependencies [here](https://github.com/OctopusDeploy/OctopusDeploy/pull/8523/files#diff-69d501820b3c922072699cd81bd0951eb783021362120a45ef1820bc348d5296R135)

```
Value cannot be null. (Parameter 'instance')
   at Autofac.RegistrationExtensions.RegisterInstance[T](ContainerBuilder builder, T instance)
   at Octopus.Upgraders.DatabaseUpgradeScriptDependencies.AddToContainer(ContainerBuilder upgradeScriptContainerBuilder) in C:\source\Octopus\Server.2021.1\source\Octopus.Upgraders\DatabaseUpgradeScriptDependencies.cs:line 45
   at Octopus.Upgraders.UpgradeScriptProvider.CreateInstance[T](Type type) in C:\source\Octopus\Server.2021.1\source\Octopus.Upgraders\UpgradeScriptProvider.cs:line 135
 <snip>
   at Octopus.Core.Initialization.DatabaseUpgrader.GetScriptsToExecute(IScriptProvider scriptProvider) in C:\source\Octopus\Server.2021.1\source\Octopus.Core\Initialization\DatabaseUpgrader.cs:line 66
   at Octopus.Core.Initialization.DatabaseUpgrader.IsUpgradeRequired() in C:\source\Octopus\Server.2021.1\source\Octopus.Core\Initialization\DatabaseUpgrader.cs:line 59
   at Octopus.Core.Initialization.DatabaseUpgradeCoordinator.IsUpgradeRequired() in C:\source\Octopus\Server.2021.1\source\Octopus.Core\Initialization\DatabaseUpgradeCoordinator.cs:line 46
   at Octopus.Core.Initialization.DatabaseUpgradeCoordinatorFactory.DisposableDatabaseUpgradeCoordinatorFacade.IsUpgradeRequired() in C:\source\Octopus\Server.2021.1\source\Octopus.Core\Initialization\DatabaseUpgradeCoordinatorFactory.cs:line 144
   at Octopus.Manager.Server.OctopusConfiguration.SetupWizard.SqlServerExpressConfigurer.TestExistingOctopusConnection() in C:\source\Octopus\Server.2021.1\source\Octopus.Manager.Server\OctopusConfiguration\SetupWizard\SqlServerExpressConfigurer.cs:line 115
   at Octopus.Manager.Server.OctopusConfiguration.SetupWizard.OctopusSetupWizardModel.TestOctopusSqlConnection() in C:\source\Octopus\Server.2021.1\source\Octopus.Manager.Server\OctopusConfiguration\SetupWizard\OctopusSetupWizardModel.cs:line 606
```

**Comment by droyad** [comment]
Release Note: Add to HA Cluster works again via the Wizard

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5080 |
| 2021.1 | 2021.1.7235 |
| 2021.2 | 2021.2.4280 |
| 2021.3+ | -all releases- |
