### ISSUE TITLE
Azure App Service step times out after 100 seconds when uploading package

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#6902]
In 2021.2 on deploy, when using the new Deploy an Azure App Service step to upload a package to Azure, the step times out after 100 seconds.

This appears to be related to the default timeout for the HttpClient class being 100 seconds (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-5.0)

![image](https://user-images.githubusercontent.com/113759/120326401-06809700-c32c-11eb-99ec-8cc362b4dec8.png)

Reported by: https://octopus.zendesk.com/agent/tickets/69928 (internal)

Error text includes:
```
System.Threading.Tasks.TaskCanceledException
at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Calamari.AzureAppService.Behaviors.AzureAppServiceBehaviour.UploadZipAsync(HttpClient client, String uploadZipPath, String targetSite)
```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.1 | 2021.1.7288 |
| 2021.2 | 2021.2.4545 |
| 2021.3+ | -all releases- |
