### ISSUE TITLE
Deploy Kubernetes Containers step custom resource with Windows line endings fails to deploy

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6978]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When the custom resource in a `Deploy Kubernetes containers` step includes Windows line endings, the deployment fails.

## Steps to reproduce

1. Create a new `Deploy Kubernetes container` step
2. Enable the `Custom Resources` feature
3. Add a Octostache marker with a variable containing Windows line endings

### Log excerpt

```
 HostProcessName: Octopus.Server
                    |       PID: 1
00:29:34   Info     |       Leasing WindowsDefault dynamic worker...
00:29:36   Info     |       Obtained worker lease successfully.
00:29:36   Verbose  |       Leased worker 21-08-05-1703-pklgh from pool Hosted Windows (lease Leases-1805543).
00:29:36   Verbose  |       Executing Deploy Octopus Server (type Deploy Kubernetes containers) on DynamicWorker 21-08-05-1703-pklgh
00:29:38   Verbose  |       Successfully called release for dynamic pool lease Leases-1805543 : 21-08-05-1703-pklgh
00:29:38   Verbose  |       (Line: 54, Col: 1, Idx: 3484) - (Line: 54, Col: 4, Idx: 3487): Expected 'StreamEnd', got 'DocumentStart' (at Line: 54, Col: 1, Idx: 3484).
                    |       YamlDotNet.Core.YamlException
                    |       at YamlDotNet.Core.ParserExtensions.Expect[T](IParser parser)
                    |       at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
                    |       at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
                    |       at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
                    |       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
                    |       at Octopus.Kubernetes.ActionHandler.KubernetesDeployContainersActionHandler.Execute(IActionHandlerContext context, ITaskLog taskLog) in KubernetesDeployContainersActionHandler.cs:line 61
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.<>c__DisplayClass15_0.<Execute in NewActionDispatcher.cs:line 205
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in EitherAsyncOrSync.cs:line 38
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in Guidance.cs:line 116
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Maybe`1 callbackOnExclude, CancellationToken cancellationToken) in Guidance.cs:line 67
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Execute(ActionCommand command, Maybe`1 inContextOf, IExecutor executor, TargetManifest targetManifest, Maybe`1 stagedPackagePath, IActionAndTargetScopedVariables variables, ITaskLog taskLog, Maybe`1 guidanceExcludeCallback, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 211
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.ExecuteOnWorker(ActionCommand command, Maybe`1 inContextOf, ITaskLog taskLog, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 159
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Dispatch(ActionCommand command, DeploymentTarget deploymentTarget, ITaskLog taskLogForTarget, ITaskLog taskLogRoot, Maybe`1 guidanceExcludeCallback, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 92
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.<>c__DisplayClass38_2.<ExecuteActionAndInitLoggingContext in ExecutionTaskController.cs:line 601
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in EitherAsyncOrSync.cs:line 38
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in Guidance.cs:line 116
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Maybe`1 callbackOnExclude, CancellationToken cancellationToken) in Guidance.cs:line 67
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.<>c__DisplayClass38_1.<ExecuteActionAndInitLoggingContext in ExecutionTaskController.cs:line 607
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass4_0`2.<Execute in UnitOfWorkExecutor.cs:line 74
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 73
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 73
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,T2](Func`4 action, CancellationToken cancellationToken, String name) in UnitOfWorkExecutor.cs:line 75
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.<>c__DisplayClass38_0.<ExecuteActionAndInitLoggingContext in ExecutionTaskController.cs:line 608
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.ExecuteWithTransientErrorDetection(Func`2 action, ITaskLog taskLog, CancellationToken cancellationToken, DeploymentTarget deploymentTarget) in ExecutionTaskController.cs:line 753
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.ExecuteActionAndInitLoggingContext(PlannedStep step, DeploymentTarget targetContext, PlannedAction action, ITaskLog taskLogForTarget, ITaskLog taskLogRoot, CancellationToken cancellationToken) in ExecutionTaskController.cs:line 626
00:29:38   Fatal    |       The action Deploy Octopus Server on p210806102459050hcus failed
                    |    
```

## Affected versions

All versions of Octopus until 2021.3.

## Workarounds

Custom resources can be deployed in a script step where Octopus does not attempt to parse the YAML.

## Links

Internal Link: https://trello.com/c/V7aqqyTD/129-builtin-deploy-kubernetes-containers-step-doesnt-handle-custom-yaml-resources-with-r-n

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1483 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.1483 |
| 2022.1+ | _all releases_ |
