### ISSUE TITLE
Script0266 causes database servers to run out of disk

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#6983]
# The bug

Script0266ReorderVariableSetColumns uses a lot of disk to perform its schema upgrade, causing the upgrade to fail when there is not enough disk available.

## Log excerpt

```
Error: Reorganizing columns in the VariableSet table, this operation requires approximately 32GB of free disk space on your database server.
Error: SQLException has occured in one of the SQL commands executed by this .NET script: 'Script0266ReorderVariableSetColumns.cs'. The stack trace will show you how to find the specific SQL command being executed at the time. Line: 1; Procedure: ; Error Number: 9002; Message: The transaction log for database 'OctopusDeploy' is full due to 'ACTIVE_TRANSACTION'.
Error: Error occured when executing scripts, transaction will be rolled back
Error: Upgrade failed due to an unexpected exception:
Error: Microsoft.Data.SqlClient.SqlException (0x80131904): The transaction log for database 'OctopusDeploy' is full due to 'ACTIVE_TRANSACTION'.
Error:    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
Error:    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
Error:    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
Error:    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
Error:    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
Error:    at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
Error:    at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
Error:    at Octopus.Core.Initialization.DbCommandExecutor.ExecuteNonQuery(String commandText, IDictionary`2 commandParameters, Nullable`1 commandType) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Upgraders\DbCommandExecutor.cs:line 25
Error:    at Octopus.Core.UpgradeScripts.Script0266ReorderVariableSetColumns.Execute(IDbCommandExecutor commandExecutor, IUpgradeLog log) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\UpgradeScripts\Script0266ReorderVariableSetColumns.cs:line 52
Error:    at Octopus.Core.Initialization.DbCommandExecutorUpgradeScript.Execute(Func`1 commandFactory, IUpgradeLog log) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\Initialization\DbCommandExecutorUpgradeScript.cs:line 12
Error:    at Octopus.Core.Initialization.LegacyDbCommandUpgradeScriptResolver.Execute(Func`1 commandFactory, IUpgradeLog log) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\Initialization\LegacyDbCommandUpgradeScriptResolver.cs:line 33
Error:    at Octopus.Core.Initialization.DatabaseUpgrader.OctopusUpgradeScriptExecutor.<>c__DisplayClass6_0.<ExecuteDbCommandUpgradeScript>b__0(Func`1 commandFactory) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\Initialization\DatabaseUpgrader.cs:line 361
Error:    at DbUp.Engine.Transactions.SingleTransactionStrategy.Execute(Action`1 action)
Error:    at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action)
Error:    at Octopus.Core.Initialization.DatabaseUpgrader.OctopusUpgradeScriptExecutor.ExecuteDbCommandUpgradeScript(IConnectionManager connectionManager, IJournal journal, IUpgradeLog log, IDbCommandUpgradeScript upgradeScript) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\Initialization\DatabaseUpgrader.cs:line 349
Error:    at Octopus.Core.Initialization.DatabaseUpgrader.OctopusUpgradeScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\BuildAgent\work\c42ca9d2b8233f1c\source\Octopus.Core\Initialization\DatabaseUpgrader.cs:line 329
Error:    at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```

## Affected versions

**Octopus Server:** 2020.6

## Workarounds

Increase the disk available to the database server.

## Links

https://octopus.zendesk.com/agent/tickets/73415

**Comment by tothegills** [comment]
Release note: Improved speed and reduced disk usage of upgrade script (Script0266)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5371 |
| 2021.1 | _tbc_ |
| 2021.2 | _tbc_ |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5371 |
| 2021.1 | 2021.1.7737 |
| 2021.2 | _tbc_ |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5371 |
| 2021.1 | 2021.1.7737 |
| 2021.2 | 2021.2.7492 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5371 |
| 2021.1 | 2021.1.7737 |
| 2021.2 | 2021.2.7492 |
| 2021.3 | 2021.3.2040 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5371 |
| 2021.1 | 2021.1.7737 |
| 2021.2 | 2021.2.7492 |
| 2021.3 | 2021.3.2040 |
| 2022.1+ | _all releases_ |
