### ISSUE TITLE
Deployments with Manual Intervention and Tenants fail with "Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed"

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6992]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

Deployments with Manual Intervention and Tenants fail with "Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed"

## What I expected to happen

For them to succeed.

## Steps to reproduce

1. Create a project with Tenants 
2. Have a manual intervention step
3. Deploy

### Log excerpt

```
16:37:47   Verbose  |     An operation in "Acquire Packages" failed

                    |     Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

                    |     System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

                    |     at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action`1 configurationAction)

                    |     at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,TResult](Func`3 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 167

                    |     at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)

                    |     at Octopus.Core.Features.Tags.TagTesterFactory.LoadAllTags() in ./source/Octopus.Core/Features/Tags/TagTesterFactory.cs:line 64

                    |     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

                    |     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)

                    |     at System.Lazy`1.CreateValue()

                    |     at Octopus.Core.Features.Tags.TagTesterFactory.For(IEnumerable`1 tagIdsOrNames) in ./source/Octopus.Core/Features/Tags/TagTesterFactory.cs:line 40

                    |     at Octopus.Core.Model.Variables.ScopeScenario.IsTenantTagMatched(ScopeValue ruleValue, ScopeValue scenarioValue, TagTesterFactory tagTesterFactory) in ./source/Octopus.Core/Model/Variables/ScopeScenario.cs:line 82

                    |     at Octopus.Core.Model.Variables.ScopeScenario.AppliesTo(ScopeSpecification scope, TagTesterFactory tagTesterFactory) in ./source/Octopus.Core/Model/Variables/ScopeScenario.cs:line 54

                    |     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

                    |     at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)

                    |     at System.Linq.GroupedEnumerable`2.GetEnumerator()

                    |     at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()

                    |     at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()

                    |     at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)

                    |     at Octopus.Core.Model.Variables.VariableCollection.AddRange(IEnumerable`1 variables) in ./source/Octopus.Core/Model/Variables/VariableCollection.cs:line 104

                    |     at Octopus.Core.Model.Variables.VariableCollection.Select(ScopeScenario scopeScenario, TagTesterFactory tagTesterFactory)

                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentPlan.GetParallelism(PlannedStep step) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/DeploymentPlan.cs:line 742

                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.<>c__DisplayClass29_0.<<AcquirePackages>b__0>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ExecutionTaskController.cs:line 366

                    |     --- End of stack trace from previous location ---

                    |     at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass3_0`1.<<Execute>b__0>d.MoveNext() in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 61

                    |     --- End of stack trace from previous location ---

                    |     at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 73

                    |     at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 73

                    |     at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T](Func`3 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 62

                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.AcquirePackages(PlannedStep step, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ExecutionTaskController.cs:line 371

                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.ExecuteStep(PlannedStep step, ITaskLog taskLogRoot, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ExecutionTaskController.cs:line 284

                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`1.DispatchStep(Planned`1 plannedStep, ITaskLog taskLogRoot, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ExecutionTaskController.cs:line 260

                    |     Octopus.Server version 2021.2.7293 (2021.2.7293+Branch.release-2021.2.Sha.c20dfc50495e91337d687c10ba9502cc87a368b7)

16:37:47   Fatal    |     The step failed: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
```

## Affected versions

**Octopus Server:** 2021.2

## Workarounds

Disable the manual intervention step

## Links

Source Ticket (INTERNAL): https://octopus.zendesk.com/agent/tickets/74612
Slack Conversation (INTERNAL): https://octopusdeploy.slack.com/archives/C27FNL3QW/p1629851110255100

**Comment by adam-mccoy** [comment]
Release Note: Fix failing deployments for projects with manual intervention and tenant tag scoped variables

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7427 |
| 2021.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7427 |
| 2021.3 | 2021.3.2035 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7427 |
| 2021.3 | 2021.3.2035 |
| 2022.1+ | _all releases_ |
