### ISSUE TITLE
After Upgrade "Synchronize external security groups" Fails - Users from Teams with AD Groups can't login

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#6995]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

After upgrading from previous versions (tested 2018.10.7 & 2019.12) to 2021.1.7xxx, the task "Sychronize external security groups" fails. 

This causes AD users who are inheriting Octopus permissions from an AD group that is synced to a Team to lose their permissions. This is resolved if the task is re-run and finishes without error.

## What I expected to happen

I would expect that the task "Synchronize external security groups" to be successful following an upgrade, and not required to be manually re-run.

## Steps to reproduce

1. Install Octopus Server 2019.12 with AD on a Domain computer.
2. Configure a Team with an external an AD Group.
3. Upgrade to Octopus 2021.1.7xxx.
4. Login with a user from that Team. 
4. See error.

### Screen capture

<img width="1062" alt="Screen Shot 2021-08-26 at 13 36 28" src="https://user-images.githubusercontent.com/78527975/130903318-57fb30d9-2983-48e1-b95d-1a052b2b9d31.png">

### Log excerpt

```
Task ID:        ServerTasks-27
Related IDs:    
Task status:    Success
Task queued:    Thursday, 26 August 2021 1:34:42 PM +10:00
Task started:   Thursday, 26 August 2021 1:34:43 PM +10:00
Task completed: Thursday, 26 August 2021 1:34:53 PM +10:00
Task duration:  10 seconds
Server version: 2021.1.7665+Branch.release-2021.1.Sha.4d3eb8f92b86188138c178123e05441941360b6b
Server node:    PROD-SERVER

                    | == Warning: Synchronize external security groups ==
13:34:43   Info     |   Synchronizing external security groups for 2 users. Loading users took 0.00s.
13:34:53   Info     |   2 users were updated to match their external security groups. Processing users took 10.10s.
13:34:53   Info     |   See verbose logs for details.
13:34:53   Verbose  |   Affected users:
                    |   Finn Test
                    | 
                    |   == Warning: Finn Test ==
13:34:43   Verbose  |     UserId: Users-21
                    |     Username: finntest@DOMAIN1.LOCAL
                    |     Email:
13:34:43   Info     |     Updating external security groups via GroupRetriever...
13:34:43   Verbose  |     Finding external security groups for 'DOMAIN1\finntest'...
13:34:52   Error    |     Active Directory search for DOMAIN1\finntest failed.
                    |     The server could not be contacted.
                    |     System.DirectoryServices.AccountManagement.PrincipalServerDownException: The server could not be contacted.
                    |     ---> System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
                    |     at System.DirectoryServices.Protocols.LdapConnection.Connect()
                    |     at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
                    |     at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
                    |     at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request)
                    |     at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
                    |     --- End of inner exception stack trace ---
                    |     at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
                    |     at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
                    |     at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
                    |     at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container)
                    |     at Octopus.Server.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesContextProvider.GetContext(String domain)
                    |     at Octopus.Server.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesExternalSecurityGroupLocator.GetGroupIdsForUser(String samAccountName, CancellationToken cancellationToken)
                    |     Octopus.Server version 2021.1.7665 (2021.1.7665+Branch.release-2021.1.Sha.4d3eb8f92b86188138c178123e05441941360b6b)
13:34:52   Warning  |     Couldn't retrieve groups for samAccountName DOMAIN1\finntest
13:34:52   Error    |     Couldn't retrieve groups for user finntest@DOMAIN1.LOCAL
13:34:52   Verbose  |     No external security groups from Active Directory: Couldn't retrieve groups for user finntest@DOMAIN1.LOCAL
13:34:52   Verbose  |     Invalidating cache for this user so these changes will be enforced by the Octopus Server.
13:34:52   Info     |     The user was updated.
```

## Affected versions

**Octopus Server:**
Confirmed in upgrade from 2019.12.0 to 2021.1.7665

## Workarounds

Re-running the failed task "Synchronize external security groups" will resolve this issue. 

## Links
[Zendesk](https://octopus.zendesk.com/agent/tickets/71900)
[Zendesk #2](https://octopus.zendesk.com/agent/tickets/74546)
[Zendesk Problem](https://octopus.zendesk.com/agent/tickets/74638)

**Comment by tothegills** [comment]
Not convinced this is a product issue - ZenDesk 71900 is about task frequency, so I don't think related. ZenDesk 74546 is not clear why the synchronize task is failing. In this issue, the log "The server could not be contacted." indicates an issue with the AD server.
