### ISSUE TITLE
Azure CLI Step with Token Account bound no longer deploys to Kubernetes Targets

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7067]
### Team

- [X] I've assigned a team label to this issue

### Severity

One customer effected so far

### Version

Issue discovered after upgrading from 2020.6.11 to 2021.2.7580

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Deployments to Kubernetes using a Token account bound to the Azure CLI step Account stared failing after upgrade.

### Reproduction

Using Octopus 2020.6.11:
1. Configure Private Kubernetes Cluster in Azure with a Token for authentication.
2. Create a deployment target in Octopus which uses a Token Account.
3. Configure an Azure CLI step which has an Account bound to that Token Account via a variable.
4. Upgrade to 2021.2.7580 - See error when deploying.

![image](https://user-images.githubusercontent.com/78527975/135225531-84f03824-9323-4945-a424-3f3b6965601f.png)

### Error and Stacktrace

```shell
05:50:56   Error    |       Value cannot be null. (Parameter 's')
05:50:56   Error    |       System.ArgumentNullException
05:50:56   Error    |       at System.Convert.FromBase64String(String s)
05:50:56   Error    |       at Calamari.AzureScripting.AzureContextScriptWrapper.CreateAzureCertificate(String workingDirectory) in C:\buildAgent\work\39e633882f029f14\source\Calamari\AzureContextScriptWrapper.cs:line 108
05:50:56   Error    |       at Calamari.AzureScripting.AzureContextScriptWrapper.ExecuteScript(Script script, ScriptSyntax scriptSyntax, ICommandLineRunner commandLineRunner, Dictionary`2 environmentVars) in C:\buildAgent\work\39e633882f029f14\source\Calamari\AzureContextScriptWrapper.cs:line 76
05:50:56   Error    |       at Calamari.Common.Features.FunctionScriptContributions.FunctionAppenderScriptWrapper.ExecuteScript(Script script, ScriptSyntax scriptSyntax, ICommandLineRunner commandLineRunner, Dictionary`2 environmentVars)
05:50:56   Error    |       at Calamari.Common.Features.Scripting.ScriptEngine.Execute(Script script, IVariables variables, ICommandLineRunner commandLineRunner, Dictionary`2 environmentVars)
05:50:56   Error    |       at Calamari.Scripting.ExecuteScriptBehaviour.Execute(RunningDeployment context)
05:50:56   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.ExecuteBehaviour(RunningDeployment context, IBehaviour behaviour)
05:50:56   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.Execute(ILifetimeScope lifetimeScope, IVariables variables)
05:50:56   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.Execute(ILifetimeScope lifetimeScope, IVariables variables)
05:50:56   Error    |       at Calamari.Common.CalamariFlavourProgramAsync.Run(String[] args)
05:50:56   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20210929055055-65-12 exited with code 100
```

### More Information

[Zendesk](https://octopus.zendesk.com/agent/tickets/76383)
[Slack - F&M](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1632808033373500)

Finn has a reproduction snapshot from prior to the upgrade and is happy to help clarify! 

### Workaround

Change the Run an Azure CLI step to be Run Kubectl CLI step with an Azure Service account configured instead of the Token account.

**Comment by paraicoceallaigh** [comment]
Potentially another client with the same issue: https://octopus.zendesk.com/agent/tickets/77169

**Comment by michelle-luana** [comment]
@FinnianDempsey this is a bit of a throw back but do you know if this was specific to the upgrade from 2020.6.11 to 2021.2.7580 or if it still occurring in newer versions?

**Comment by FinnianDempsey** [comment]
@michelle-luana I believe this will still be an issue for all newer versions as it involves a change to how the context works. I believe it's because we require an Azure Account for any Azure Steps, where it never checked the type of account previously, allowing for other types like Token to be used
