### ISSUE TITLE
Variables with an unexpected type can not be serialised

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7079]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking at least one customer, imagine there will be more

### Version

2021.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Attempting to load a variable set with a variable that has a type we don't expect results in an exception.

### Reproduction

- Create a project with a variable set in version 2021.2
- Create a variable with a type "Text" via the API
- Upgrade to 2021.3
- Try to load the variables

### Error and Stacktrace

```shell
Newtonsoft.Json.JsonSerializationException: Invalid Variable Type Nothing.
   at Octopus.Core.RelationalStorage.TypeHandlers.VariableTypeConverter.ReadJson(JsonReader reader, Type objectType, VariableType existingValue, Boolean hasExistingValue, JsonSerializer serializer) in O:\repo\OctopusDeploy\source\Octopus.Core\RelationalStorage\TypeHandlers\VariableTypeConverter.cs:line 30
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Octopus.Core.RelationalStorage.VariableConverter.ReadJsonInternal(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in O:\repo\OctopusDeploy\source\Octopus.Core\RelationalStorage\VariableConverter.cs:line 67
   at Octopus.Core.RelationalStorage.VariableConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in O:\repo\OctopusDeploy\source\Octopus.Core\RelationalStorage\VariableConverter.cs:line 62
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
```

### More Information

We used to not care if a variable had a type we didn't recognise.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.5416 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |
