### ISSUE TITLE
Health Check fails for Kubernetes Cluster targets when run in a Worker Image hosted on ECR

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#7158]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low - one or two customers affected

### Version

Earliest tried was 2021.3.7082

### Latest Version

I could reproduce the problem in the latest build

### What happened?

For Kubernetes Cluster targets where:
* A private container image is specified for Health Checks
* The image is hosted on an ECR feed
* The Worker Pool is in a different AWS region to the ECR feed

Health checks fail due to failure to pull the container image

### Reproduction

1. Create a new Container Image containing `kubectl` tools and publish it to an ECR feed
2. Create a new Listening Tentacle hosted on AWS in a different region to the ECR feed, and add it to a new Worker Pool
3. Create a Kuberneted Cluster Deployment Target hosted in EKS
  * Set the Worker Pool to the one created in step 2
  * Set the Health Check Worker Image to the one published in step 1
4. Run a Health Check on the worker

**Expected**
Assuming all credentials have been correctly configured, health check should complete successfully

**Actual**
Health check fails because Worker Image cannot be pulled from ECR

### Error and Stacktrace

```shell
Unable to find image '720766170633.dkr.ecr.eu-west-1.amazonaws.com/adamhollowecr:latest' locally
17:34:48   Error    |     docker: Error response from daemon: Head https://720766170633.dkr.ecr.eu-west-1.amazonaws.com/v2/adamhollowecr/manifests/latest: no basic auth credentials.
17:34:48   Error    |     See 'docker run --help'.
17:34:48   Verbose  |     Process /bin/bash in /home/Octopus/Work/20211110173447-126725-32 exited with code 125
17:34:48   Verbose  |     Successfully called release for dynamic pool lease Leases-39527934 : 21-11-10-1342-zqdwp
17:34:48   Verbose  |     Exit code: 125
17:34:48   Fatal    |     The remote script failed with exit code 125
17:34:48   Verbose  |     The remote script failed with exit code 125
                    |     Octopus.Server.Orchestration.Targets.Tasks.ActionHandlerFailedException: The remote script failed with exit code 125
                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.SuccessArbitrator.ThrowIfNotSuccessful(IActionHandlerResult result) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/SuccessArbitrator.cs:line 22
                    |     at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.AdHocActionDispatcher.Dispatch(Machine machine, ActionHandlerInvocation actionHandler, ITaskLog taskLog, VariableCollection variables) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/AdHocActionDispatcher.cs:line 57
                    |     at Octopus.Server.Orchestration.ServerTasks.HealthCheck.Controllers.VirtualTargetHealthController.CheckHealth(Machine machine, ITaskLog taskLog) in ./source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/Controllers/VirtualTargetHealthController.cs:line 107
                    |     at Octopus.Server.Orchestration.ServerTasks.HealthCheck.HealthCheckService.PerformHealthCheck(Machine machine, ITaskLog machineTaskLog, ITaskLog serverTaskLog, IHealthResultCollator healthResultCollator, CancellationToken cancellationToken, ExceptionHandling exceptionHandling, Action`2 customAction) in ./source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/HealthCheckService.cs:line 86
                    |     Octopus.Server version 2021.3.7082 (2021.3.7082)
```

### More Information

It looks like when trying to use an ECR container on a worker to health check a K8S cluster (or similar target) we’re not passing the AWS region through to the Health Check task, causing the auth to fail.

### Workaround

Deploy both the ECR Registry and the Worker Pool into the same AWS region

**Comment by mjhilton** [comment]
Potential duplicate of #6853 - needs checking to see if it's the same or different causes

**Comment by mjhilton** [comment]
Also check if PR https://github.com/OctopusDeploy/OctopusDeploy/pull/11185 can be revived and would solve this issue
