### ISSUE TITLE
Local Git directory corruption causes failure to create temp files for VCS conversion

### ISSUE THREAD

**Issue by garrettdass** [OctopusDeploy/Issues#7198]
### Team

- [X] I've assigned a team label to this issue

### Severity

Minimal - easy workaround

### Version

2021.3.8275

### Latest Version

I could not reproduce the problem

### What happened?

When trying to connect a project to Version Control an error can occur, caused by a corrupted folder in the local Git Cache where the clone/conversion work is performed. The error shows when connecting to a GitHub repository:
![image](https://user-images.githubusercontent.com/84342666/143281548-631b74c3-aa8b-4133-8ca4-cba785d4f336.png)

### Reproduction

Unable to reliably reproduce.

### Error and Stacktrace

```shell
Unhandled error on request: POST http://octopus.app/api/Spaces-222/projects/Projects-922/git/convert 0HMD94HD0LSSE:00000027 by GD : An exception was thrown while activating λ:Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Git.NameAsIdDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Git.GitDocumentStore`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> λ:Octopus.Core.Git.Transactions.IGitTransaction -> λ:Octopus.Core.Git.Transactions.IGitTransaction. Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Git.NameAsIdDocumentStoreDecorator`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Octopus.Core.Persistence.Git.GitDocumentStore`2[[Octopus.Core.Model.Projects.DeploymentProcess, Octopus.Core, Version=2021.3.8030.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> λ:Octopus.Core.Git.Transactions.IGitTransaction -> λ:Octopus.Core.Git.Transactions.IGitTransaction.
 ---> LibGit2Sharp.LibGit2SharpException: failed to create temporary file '/home/octopus/.octopus/OctopusServer/Server/Git/4TTDRLPEZ5SDPQOBD4JXVFD5C3KPFFIP/root/objects/pack/pack_git2_AbGwuA': No such file or directory
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at Octopus.Core.Git.GitSpaceLimit.DoOperationWithProgressHandler(Action`1 operation, Func`1 onUserCancelledOperation) in ./source/Octopus.Core/Git/GitSpaceLimit.cs:line 74
   at Octopus.Core.Git.Repositories.RepositoryRoot.<>c__DisplayClass23_0.<EnsureRepositoryIsCurrent>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Octopus.Core.Git.Repositories.RepositoryRoot.EnsureRepositoryIsCurrent(CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/RepositoryRoot.cs:line 258
   at Octopus.Core.Git.Repositories.RepositoryRoot.ValidateFullyQualifiedGitRef(String gitResourceName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/RepositoryRoot.cs:line 207
   at Octopus.Core.Git.Repositories.ErrorHandlingRepositoryRootDecorator.ValidateFullyQualifiedGitRef(String gitResourceName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/ErrorHandlingRepositoryRootDecorator.cs:line 43
   at Octopus.Core.Git.Repositories.FileSystemLoggingRepositoryRootDecorator.ValidateFullyQualifiedGitRef(String gitResourceName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/FileSystemLoggingRepositoryRootDecorator.cs:line 65
   at Octopus.Core.Git.Repositories.SpaceLimitRepositoryRootDecorator.ValidateFullyQualifiedGitRef(String gitResourceName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/SpaceLimitRepositoryRootDecorator.cs:line 43
   at Octopus.Core.Git.Repositories.GitRepository.PrepareWorkTree(GitRef gitRef, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/GitRepository.cs:line 111
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Octopus.Core.Persistence.Git.GitTransactionFactory.BeginOrAdoptExisting() in ./source/Octopus.Core/Persistence/Git/GitTransactionFactory.cs:line 49
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Features.Indexed.KeyedServiceIndex`2.get_Item(TKey key)
   at Octopus.Core.Persistence.DocumentStore`2.GetOrNullAsync(TKey id, CancellationToken cancellationToken) in ./source/Octopus.Core/Persistence/DocumentStore.cs:line 87
   at Octopus.Core.Features.DeploymentProcesses.CurrentDeploymentProcessDocumentStoreExtensionMethods.GetOrNullByProjectAsync(IDocumentStore`2 documentStore, Project project, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/DeploymentProcesses/CurrentDeploymentProcessDocumentStoreExtensionMethods.cs:line 24
   at Octopus.Server.Web.Api.Actions.Projects.ProjectToVersionControlConverter.ConfigureEntities(Project project, VersionControlSettings versionControlSettings, MessageCollection messages, DeploymentProcess databaseDeploymentProcess, DeploymentSettings databaseDeploymentSettings, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Api/Actions/Projects/ProjectToVersionControlConverter.cs:line 122
   at Octopus.Server.Web.Api.Actions.Projects.ProjectToVersionControlConverter.Convert(Project project, VersionControlSettings versionControlSettings, IOctopusQueryExecutor queryExecutor, MessageCollection messages, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Api/Actions/Projects/ProjectToVersionControlConverter.cs:line 84
   at Octopus.Server.Web.Api.Actions.Projects.ConvertProjectToVersionControlledCommandHandler.Handle(ConvertProjectToVersionControlledCommand command, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Api/Actions/Projects/ConvertProjectToVersionControlledCommandHandler.cs:line 61
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 28
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 31
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 44
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 28
   at Octopus.Server.Web.Controllers.Projects.ConvertProjectController.Convert(ConvertProjectToVersionControlledRequest request, CancellationToken token) in ./source/Octopus.Server/Web/Controllers/Projects/ConvertProjectController.cs:line 35
   at lambda_method1107264(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in ./source/Octopus.Server/Web/Infrastructure/Authentication/AuthorizationMiddlewareResultHandler.cs:line 52
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 38
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 48
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 55
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 67
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.RequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/RequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 75
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 103
```

### More Information

[[Internal Slack Link](https://octopusdeploy.slack.com/archives/C01AJE4K3T2/p1637193274094000)]

### Workaround

1. If using a Personal Access Token to connect to Github change the Username on the VCS page to something else. This will create a new uncorrupted folder and allow you to connect.
2. Use the Clear Local Cache button under Configuration > Features > Early Access:
![image](https://user-images.githubusercontent.com/84342666/143282967-d6b94153-b1a1-43d6-a93e-1af5efa68ece.png)

**Comment by acodrington** [comment]
After many (_many_) attempts, I have been unable to replicate this problem.

The error message indicates that there is a problem creating a pack file, which is used internally by git and therefore should not be touched by Octopus directly.

There are currently two theories as to what might be causing this:
1. One of our 'clear git cache' operations (which deletes the entire git folder) is occurring during the execution of the clone operation
2. Multiple concurrent git operations is causing the git folder to become corrupted

While it is possible that it is Theory#1, that seems unlikely as we have not seen any logging to indicate this, and the server task which runs each hour to clean out inactive repos has logic to handle this exact scenario (and seems to be working correctly).

Without any further information, we cannot find the cause of this problem. Given that this is a rarely occurring problem with a simple workaround, we have [added a number of verbose logs around our various git operations](https://github.com/OctopusDeploy/OctopusDeploy/pull/11068) (to help us if/when this occurs again) and will close this ticket for now.

We assume we will see this problem again, at which time hopefully we can find out the root cause and refer back to this ticket.
