### ISSUE TITLE
Package steps for Offline targets convert '/' characters to Windows-1252 encoding

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#7220]
### Team

- [X] I've assigned a team label to this issue

### Severity

One customer reported

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If your package name includes the '/' character, such as a package from a Github feed. When deploying to an Offline target the character will be converted to Windows-1252 encoding and cause the script execution to fail with an "Unexpected file format" error.

### Reproduction

- Create an offline target
- Configure a project with a Deploy Package step using a Github feed
- Deploy the project
- Attempt to run the offline script

### Error and Stacktrace

```shell
Deploying package:    D:\Downloads\Packagetest.Dev.Offline.0.0.2\Packages\calverp%2FGrades.8.03.178-RIS-470-SHA-bef6a1a.2.zip
System.Exception: Unexpected file format in calverp%2FGrades.8.03.178-RIS-470-SHA-bef6a1a.2.zip.
Expected Octopus cached file format: `<PackageId>@<Version>@<CacheBuster>.<Extension>` or `<PackageId>.<SemverVersion>.<Extension>`
   at Calamari.Common.Features.Packages.PackageName.FromFile(String path)
   at Calamari.Common.Features.Packages.ExtractPackage.ExtractToApplicationDirectory(PathToPackage pathToPackage, IPackageExtractor customPackageExtractor)
   at Calamari.Deployment.ConventionProcessor.RunInstallConventions()
   at Calamari.Deployment.ConventionProcessor.RunConventions()
Running rollback conventions...
```

### More Information

Step configuration used for above stack trace:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/20085569/144077733-293240fa-5012-4edb-8dd9-67f3fc9c2d56.png">

Ticket issue was reported in: https://help.octopus.com/t/offline-packages-with-in-the-id-is-translated-to-windows-1252-encoding/27438

**Comment by mjhilton** [comment]
We've put this one on our team's backlog, and will address it in a future release.

**Comment by maulemon** [comment]
Hi @mjhilton would it be possible to increase the priority for the fix. 
Each time when we make the offline deployment we need to manually search&replace within ZIP file.. :(

**Comment by mjhilton** [comment]
Hey @maulemon, I'm sorry that you're having to do manual steps to get your deployments working. 

Though we've assigned the `priority/low` label, that doesn't mean "never" :)

We don't currently have any issues in a higher priority bucket than `low`, so within that bucket, we've placed this one toward the top. We intend to tackle it as one of the next things on our list once our in-progress work is shipped. 

Paul was able to reproduce this problem in the latest Cloud release - would you mind letting me know the version of Octopus you're currently running so I can add that detail to the issue?

**Comment by mohammed-farwana** [comment]
Hi @mjhilton 
Currently we are on Octopus Deploy server version 2021.3.8275
