### ISSUE TITLE
"No package has been staged" for dynamic infrastructure targets with a package dependency in a worker on behalf of a role

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#7228]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low - a few customers affected

### Version

2021.3.9083, have not tried previous versions yet

### Latest Version

I could reproduce the problem in the latest build

### Links
[help.octopus.com report](https://help.octopus.com/t/no-package-has-been-staged/27115)
🔒[Slack thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1631014079054300) (Internal)

### What happened?

For deployment processes that add a Dynamic Infrastructure target in a role, with a subsequent step that has a package dependency and deploys to targets in that role via a Worker Pool, the deployment fails with error message "No package was staged".

### Reproduction

1. Upload a package containing a simple script to the Built-In Package Repository
2. Create a new Project
3. Add a `Run a Script` step which runs the script from the package uploaded in step 1. Set it to "Run once on a Worker".
4. Add a `Run a Script` step which creates a new target, for example an [Azure Web App target](https://octopus.com/docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-web-app-target). Set it to "Run once on a Worker". The script must assign a role to the target (eg "TestTargetRole")
5. Add a `Run a Script` step which runs the script from the package uploaded in step 1. Set it to "Run once on a Worker on behalf of targets in role", and select or create the role assigned to the target in step 4 (eg "TestTargetRole")
6. Ensure the Dynamic Infrastructure target does not yet exist (if there's been a previous run of the process, delete the target from the Infrastructure page) and run the process.

**Expected**: Step 3 of the process runs the script contained in the package, on behalf of the newly created target from Step 2.

**Actual**: Step 3 fails with message "No package has been staged"
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/730704/144335621-9ad0c883-c8cb-44fe-b7bf-bd5049b938aa.png">

Note: The initial `Run a Script` step is just there to force package acquisition to the start of the process. If there are no steps with package dependencies before the target is added, then package acquisition doesn't happen until after the target is created, and all works fine. 

### Error and Stacktrace

```shell
Task ID:        ServerTasks-775
Related IDs:    Deployments-245, Channels-141, Releases-225, Projects-121, Spaces-1, Environments-1
Task status:    Failed
Task queued:    Thursday, 02 December 2021 10:58:59 AM +11:00
Task started:   Thursday, 02 December 2021 10:59:00 AM +11:00
Task completed: Thursday, 02 December 2021 10:59:09 AM +11:00
Task duration:  10 seconds
Server version: 0.0.0-local
Server node:    SERVER

                    | == Failed: Deploy No package has been staged release 0.0.5 to Dev ==
10:59:00   Info     |   Step 1: Run a Script is disabled, and will not be executed
10:59:00   Verbose  |   Guided failure is not enabled for this task
10:59:09   Verbose  |   Releasing workers that required packages.
10:59:09   Verbose  |   Released worker Local Tentacle from lease WorkerTaskLeases-9
10:59:09   Fatal    |   The deployment failed because one or more steps failed. Please see the deployment log for details.
                    | 
                    |   == Success: Acquire packages ==
10:59:00   Info     |     Acquiring packages
10:59:00   Info     |     Making a list of packages to acquire
10:59:00   Verbose  |     Leased worker Local Tentacle from pool New Worker Pool (lease WorkerTaskLeases-9).
10:59:00   Verbose  |     Package Run-Script v1.0 is required by action 'Deploy to targets in Role'
10:59:00   Verbose  |     No packages are required on the Octopus Server
10:59:00   Verbose  |     Delta compression is enabled for package transfers from the Octopus Server to deployment targets
10:59:00   Verbose  |     Machine Local Tentacle still needs packages Run-Script v1.0 for action ('Deploy to targets in Role')
10:59:00   Verbose  |     Checking package cache for package Run-Script v1.0
10:59:00   Info     |     Package Run-Script v1.0 was found in cache. No need to download from feed.
10:59:00   Verbose  |     Using file: C:\OctopusDev\main\Server\Packages\Spaces-1\feeds-builtin\Run-Script\Run-Script.1.0.zip
10:59:02   Info     |     All packages have been acquired
10:59:02   Verbose  |     Acquire Packages completed
                    |   
                    |     Success: Local Tentacle
                    |     
                    |       Success: Upload package Run-Script v1.0
10:59:00   Verbose  |         Script isolation level: NoIsolation
10:59:01   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:01   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:01   Verbose  |         No user context provided. Running as current user.
10:59:01   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235900-775-29' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:01   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235900-775-29 exited with code 0
10:59:01   Verbose  |         Using Calamari.win-x64 20.4.0
10:59:01   Verbose  |         Script isolation level: NoIsolation
10:59:01   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:01   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:01   Verbose  |         No user context provided. Running as current user.
10:59:01   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235901-775-30' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:01   Verbose  |         Calamari Version: 20.4.0
10:59:01   Verbose  |         Environment Information:
10:59:01   Verbose  |         OperatingSystem: Microsoft Windows NT 10.0.22000.0
10:59:01   Verbose  |         OsBitVersion: x64
10:59:01   Verbose  |         Is64BitProcess: True
10:59:01   Verbose  |         CurrentUser: NT AUTHORITY\SYSTEM
10:59:01   Verbose  |         MachineName:  SERVER
10:59:01   Verbose  |         ProcessorCount: 8
10:59:01   Verbose  |         CurrentDirectory: C:\Octopus\Work\20211201235901-775-30
10:59:01   Verbose  |         TempDirectory: C:\WINDOWS\TEMP\
10:59:01   Verbose  |         HostProcess: Calamari (42256)
10:59:02   Verbose  |         Package Run-Script 1.0 hash 72da1fa364acc056d4400b190e1e101252394e2c has already been uploaded
10:59:02   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235901-775-30 exited with code 0
10:59:02   Verbose  |         Exit code: 0
10:59:02   Info     |         Package Run-Script version 1.0 found in cache. No need to upload this 181 B package. Using C:\Octopus\Files\Run-Script@S1.0@7E87189FC6C5FB4D9BEE31F87B038817.zip
                    |       
                    |   == Success: Step 2: Add Target ==
10:59:08   Verbose  |     Add Target completed
                    |   
                    |     == Success: Worker ==
10:59:02   Verbose  |       Octopus Server version: 0.0.0-local
10:59:02   Verbose  |       Environment Information:
                    |       IsRunningInContainer: False
                    |       OperatingSystem: Microsoft Windows 10.0.22000
                    |       OsBitVersion: x64
                    |       Is64BitProcess: True
                    |       CurrentUser:  SERVER\matt
                    |       MachineName:  SERVER
                    |       ProcessorCount: 8
                    |       CurrentDirectory: C:\code\OctopusDeploy\source\Octopus.Server\bin\net5.0
                    |       TempDirectory: C:\Users\matt\AppData\Local\Temp\
                    |       HostProcessName: Octopus.Server
                    |       PID: 47916
10:59:02   Verbose  |       Leased worker Local Tentacle from pool New Worker Pool (lease WorkerTaskLeases-10).
10:59:02   Verbose  |       Executing Add Target (type Run a Script) on Local Tentacle
10:59:02   Verbose  |       Script isolation level: NoIsolation
10:59:02   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:02   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:02   Verbose  |       No user context provided. Running as current user.
10:59:02   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235902-775-31' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:02   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235902-775-31 exited with code 0
10:59:02   Verbose  |       Using Calamari.win-x64 20.4.0
10:59:02   Verbose  |       Script isolation level: NoIsolation
10:59:03   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:03   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:03   Verbose  |       No user context provided. Running as current user.
10:59:03   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235902-775-32' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:03   Verbose  |       Calamari Version: 20.4.0
10:59:03   Verbose  |       Environment Information:
10:59:03   Verbose  |       OperatingSystem: Microsoft Windows NT 10.0.22000.0
10:59:03   Verbose  |       OsBitVersion: x64
10:59:03   Verbose  |       Is64BitProcess: True
10:59:03   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
10:59:03   Verbose  |       MachineName:  SERVER
10:59:03   Verbose  |       ProcessorCount: 8
10:59:03   Verbose  |       CurrentDirectory: C:\Octopus\Work\20211201235902-775-32
10:59:03   Verbose  |       TempDirectory: C:\WINDOWS\TEMP\
10:59:03   Verbose  |       HostProcess: Calamari (51468)
10:59:03   Verbose  |       Performing variable substitution on 'C:\Octopus\Work\20211201235902-775-32\Script.ps1'
10:59:03   Verbose  |       Executing 'C:\Octopus\Work\20211201235902-775-32\Script.ps1'
10:59:03   Verbose  |       Setting Proxy Environment Variables
10:59:04   Verbose  |       Name                           Value
10:59:04   Verbose  |       ----                           -----
10:59:04   Verbose  |       PSVersion                      5.1.22000.282
10:59:04   Verbose  |       PSEdition                      Desktop
10:59:04   Verbose  |       PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
10:59:04   Verbose  |       BuildVersion                   10.0.22000.282
10:59:04   Verbose  |       CLRVersion                     4.0.30319.42000
10:59:04   Verbose  |       WSManStackVersion              3.0
10:59:04   Verbose  |       PSRemotingProtocolVersion      2.3
10:59:04   Verbose  |       SerializationVersion           1.1.0.1
10:59:04   Verbose  |       PowerShell Environment Information:
10:59:04   Verbose  |       OperatingSystem: Microsoft Windows NT 10.0.22000.0
10:59:04   Verbose  |       OsBitVersion: x64
10:59:04   Verbose  |       Is64BitProcess: True
10:59:04   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
10:59:04   Verbose  |       MachineName:  SERVER
10:59:04   Verbose  |       ProcessorCount: 8
10:59:04   Verbose  |       CurrentDirectory: C:\Octopus\Work\20211201235902-775-32
10:59:04   Verbose  |       CurrentLocation: C:\Octopus\Work\20211201235902-775-32
10:59:04   Verbose  |       TempDirectory: C:\WINDOWS\TEMP\
10:59:04   Verbose  |       HostProcess: powershell (48640)
10:59:04   Verbose  |       TotalPhysicalMemory: 50027576 KB
10:59:04   Verbose  |       AvailablePhysicalMemory: 18445332 KB
10:59:04   Verbose  |       Invoking target script C:\Octopus\Work\20211201235902-775-32\Script.ps1 with  parameters.
10:59:04   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235902-775-32 exited with code 0
10:59:04   Verbose  |       Updating manifest with output variables
10:59:04   Verbose  |       Updating manifest with action evaluated variables
10:59:04   Info     |       Executing create-azurewebapptarget Service Message Action
10:59:04   Verbose  |       Executing create-azurewebapptarget with CreateDeploymentTargetOrchestrator
10:59:04   Verbose  |       CreateDeploymentTargetOrchestrator - create-azurewebapptarget
10:59:04   Verbose  |       8 properties found
10:59:04   Verbose  |       name = NoStagedPackageWebApp
10:59:04   Verbose  |       azureWebApp = no-staged-package-test
10:59:04   Verbose  |       azureWebAppSlot =
10:59:04   Verbose  |       azureResourceGroupName = no-staged-package-test
10:59:04   Verbose  |       octopusAccountIdOrName = LocalOctoTest
10:59:04   Verbose  |       octopusRoles = NoStagedPackageRole
10:59:04   Verbose  |       updateIfExisting = True
10:59:04   Verbose  |       octopusDefaultWorkerPoolIdOrName =
10:59:07   Info     |       Found new machines to include in the deployment: NoStagedPackageWebApp
10:59:08   Verbose  |       Released worker Local Tentacle from lease WorkerTaskLeases-10
10:59:08   Verbose  |       Successfully finished Add Target on a Worker
                    |     
                    |       == Success: Check deployment target: NoStagedPackageWebApp ==
10:59:04   Verbose  |         Checking connectivity to machine
10:59:04   Verbose  |         Leased worker Local Tentacle from pool New Worker Pool (lease WorkerTaskLeases-11).
10:59:04   Verbose  |         Script isolation level: NoIsolation
10:59:04   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:04   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:04   Verbose  |         No user context provided. Running as current user.
10:59:04   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235904-775-33' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:04   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235904-775-33 exited with code 0
10:59:05   Verbose  |         Using Calamari.AzureAppService.win-x64 2.1.1
10:59:05   Verbose  |         Script isolation level: NoIsolation
10:59:05   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
10:59:05   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
10:59:05   Verbose  |         No user context provided. Running as current user.
10:59:05   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20211201235905-775-34' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
10:59:05   Verbose  |         Calamari Version: 1.0.0
10:59:05   Verbose  |         Environment Information:
10:59:05   Verbose  |         OperatingSystem: Microsoft Windows NT 10.0.22000.0
10:59:05   Verbose  |         OsBitVersion: x64
10:59:05   Verbose  |         Is64BitProcess: True
10:59:05   Verbose  |         CurrentUser: NT AUTHORITY\SYSTEM
10:59:05   Verbose  |         MachineName:  SERVER
10:59:05   Verbose  |         ProcessorCount: 8
10:59:05   Verbose  |         CurrentDirectory: C:\Octopus\Work\20211201235905-775-34
10:59:05   Verbose  |         TempDirectory: C:\WINDOWS\TEMP\
10:59:05   Verbose  |         HostProcess: Calamari.AzureAppService (12628)
10:59:07   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211201235905-775-34 exited with code 0
10:59:07   Verbose  |         Released worker Local Tentacle from lease WorkerTaskLeases-11
10:59:07   Verbose  |         Exit code: 0
10:59:07   Verbose  |         Recording health check results
10:59:07   Info     |         The machine is online
                    |       
                    |   == Failed: Step 3: Deploy to targets in Role ==
10:59:09   Fatal    |     The step failed: Activity Deploy to targets in Role on NoStagedPackageWebApp failed with error 'No package has been staged'.
10:59:09   Verbose  |     Deploy to targets in Role completed
                    |   
                    |     == Failed: Worker on behalf of NoStagedPackageWebApp ==
10:59:08   Verbose  |       Octopus Server version: 0.0.0-local
10:59:08   Verbose  |       Environment Information:
                    |       IsRunningInContainer: False
                    |       OperatingSystem: Microsoft Windows 10.0.22000
                    |       OsBitVersion: x64
                    |       Is64BitProcess: True
                    |       CurrentUser:  SERVER\matt
                    |       MachineName:  SERVER
                    |       ProcessorCount: 8
                    |       CurrentDirectory: C:\code\OctopusDeploy\source\Octopus.Server\bin\net5.0
                    |       TempDirectory: C:\Users\matt\AppData\Local\Temp\
                    |       HostProcessName: Octopus.Server
                    |       PID: 47916
10:59:08   Verbose  |       Leased worker Local Tentacle from pool New Worker Pool (lease WorkerTaskLeases-12).
10:59:08   Verbose  |       Executing Deploy to targets in Role (type Run a Script) on Local Tentacle
10:59:08   Warning  |       Using the Azure tools bundled with Octopus Deploy is not recommended. Learn more about Azure Tools at https://g.octopushq.com/AzureTools.
10:59:08   Verbose  |       Released worker Local Tentacle from lease WorkerTaskLeases-12
10:59:08   Verbose  |       No package has been staged
                    |       System.Exception
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.CommandBuilders.CalamariCommandBuilder.WithStagedPackageArgument() in CalamariCommandBuilder.cs:line 51
                    |       at Sashimi.AzureScripting.AzurePowerShellActionHandler.Execute(IActionHandlerContext context, ITaskLog taskLog)
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Script.ScriptActionHandler.ExecuteWithRedirectHandlerIfFound(IActionHandlerContext context, ITaskLog taskLog) in ScriptActionHandler.cs:line 74
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Script.ScriptActionHandler.Execute(IActionHandlerContext context, ITaskLog taskLog) in ScriptActionHandler.cs:line 41
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.<>c__DisplayClass15_0.<Execute in NewActionDispatcher.cs:line 205
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in EitherAsyncOrSync.cs:line 36
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in Guidance.cs:line 111
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Maybe`1 callbackOnExclude, CancellationToken cancellationToken) in Guidance.cs:line 66
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Execute(ActionCommand command, Maybe`1 inContextOf, IExecutor executor, TargetManifest targetManifest, Maybe`1 stagedPackagePath, IEnumerable`1 packageAcquisitionInformation, IActionAndTargetScopedVariables variables, ITaskLog taskLog, Maybe`1 guidanceExcludeCallback, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 201
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.ExecuteOnWorker(ActionCommand command, Maybe`1 inContextOf, ITaskLog taskLog, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 163
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.NewActionDispatcher.Dispatch(ActionCommand command, DeploymentTarget deploymentTarget, ITaskLog taskLogForTarget, ITaskLog taskLogRoot, Maybe`1 guidanceExcludeCallback, CancellationToken cancellationToken) in NewActionDispatcher.cs:line 91
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.ProcessStepController.<>c__DisplayClass10_3.<ExecuteActionAndInitLoggingContext in ProcessStepController.cs:line 178
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in EitherAsyncOrSync.cs:line 36
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in Guidance.cs:line 111
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Maybe`1 callbackOnExclude, CancellationToken cancellationToken) in Guidance.cs:line 66
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.ProcessStepController.<>c__DisplayClass10_2.<ExecuteActionAndInitLoggingContext in ProcessStepController.cs:line 175
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.TransientErrorDetectionExecutor.Execute(Func`2 action, ExecutionPlan plan, ITaskLog taskLog, CancellationToken cancellationToken, DeploymentTarget deploymentTarget) in TransientErrorDetectionExecutor.cs:line 32
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.ProcessStepController.<>c__DisplayClass10_1.<ExecuteActionAndInitLoggingContext in ProcessStepController.cs:line 171
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass5_0`3.<Execute in UnitOfWorkExecutor.cs:line 87
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 65
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.DoAsync(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 71
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,T2,T3](Func`5 action, CancellationToken cancellationToken, String name) in UnitOfWorkExecutor.cs:line 82
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.ProcessStepController.ExecuteActionAndInitLoggingContext(ExecutionPlan plan, PlannedStep step, DeploymentTarget targetContext, PlannedAction action, ITaskLog taskLogForTarget, ITaskLog taskLogRoot, CancellationToken cancellationToken) in ProcessStepController.cs:line 169
10:59:08   Fatal    |       The action Deploy to targets in Role on NoStagedPackageWebApp failed
                    |
```

### More Information
The key to this reproduction is:
* Package acquisition needs to happen before the Dynamic Infrastructure Target is created
* The Target needs to actually be added/net-new. Things work fine if no new target is added (eg it already existed and was just updated). You would see this in the logs as `Did not find any new machines to include in the deployment.` (will not trigger this bug), versus `Found new machines to include in the deployment: <target name>` (will trigger this bug)
* The step needs to be configured to run on a worker on behalf of the role that the new target was assigned.

Reproduced on both Self-Hosted and Octopus Cloud, however for Self-Hosted, it requires a Worker Pool in the deployment process, so if reproducing on self-hosted, at least one Tentacle must be added (ie: doesn't work if you define the process using "Run on Server").

Also confirmed that, if there is an existing Target in the same Role as the Dynamic target, the existing one will succeed, but the Dynamic one will still fail:
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/730704/144335944-d0051bea-8390-4e4d-8c5c-458ec520ac13.png">

### Workaround
Workaround 1: Add a "Health Check" step after the Dynamic Infrastructure creation step, which will (somehow) trigger a re-acquisition of packages after it. The logs don't really indicate anything happened, but it seems to make it work.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/730704/144338419-de46415d-8e55-4e18-b49e-7dbcd91ce915.png">
![image](https://user-images.githubusercontent.com/730704/144338435-a80fd8f3-14ed-459b-9ad8-32f6b280d16e.png)

Workaround 2: Ensure the step which adds the Dynamic Infrastructure runs before package acquisition. This may be unviable in many circumstances.
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/730704/144335769-91ccea0d-5a8a-4722-9fc9-02df833f8f6c.png">

**Comment by mjhilton** [comment]
Very similar to https://github.com/OctopusDeploy/Issues/issues/6290

**Comment by mjhilton** [comment]
It'll be worth talking to @andrewabest about future plans for this area to make sure whatever fix we put in place is aligned.

**Comment by mark-lidstone-system1group** [comment]
Are there any plans to fix this issue?

**Comment by YihaoOct** [comment]
I invested into this issue, but unfortunately did not found a proper fix for it. The main thing is that when RunScript is used, it is hard to tell what is going on inside the script. It could create the target in more than one ways: invoking a PS Cmdlet, using curl to send a POST request to the target creation endpoint, or sending the request using a C#/Python library, etc. So we are not able inject a package acquisition step right after a script step that creates the target.

I think for now it makes sense to at least document the requirement to create manually add a health check after a target is created from scripts. So that it helps the user to understand what is going on and make things work. I made a [PR](https://github.com/OctopusDeploy/docs/pull/1763) to update the documentation.

**Comment by YihaoOct** [comment]
@mark-lidstone-system1group Hi~ Unfortunately, if you do create deployment targets using a Run a Script step, including on Azure, you'll need to add a [health check](https://octopus.com/docs/projects/built-in-step-templates/health-check) step after the target creation step, so that packages are staged on new targets before deployments.

However, we recommend to consider using the [Cloud Target Discovery](https://octopus.com/docs/infrastructure/deployment-targets/cloud-target-discovery) feature if it is feasible in your use case. It is now the preferred way over [Dynamic Infrastructure](https://octopus.com/docs/infrastructure/deployment-targets/dynamic-infrastructure). Cloud targets registered using the Cloud Target Discovery feature are not subject to this issue. The required packages will be downloaded to the discovered targets without manually adding the health check step.

Hope that helps :)

**Comment by YihaoOct** [comment]
Closing this issue as we [updated the documentation](https://github.com/OctopusDeploy/docs/pull/1763) on the requirement to add a health check step after the dynamic target creation.
