### ISSUE TITLE
Process editor commit failed silently due to sensitive variable declaration not support in CaC

### ISSUE THREAD

**Issue by StephenHeise** [OctopusDeploy/Issues#7239]
### Team

- [X] I've assigned a team label to this issue

### Severity

Minor

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

From [Slack message](https://octopusdeploy.slack.com/archives/C01AJE4K3T2/p1636446755060000) to #team-config-as-code-requests

> The Commit from the UI failed but didn't show me any error (lost original changes because of it). Easy fix from the process side but not the best user experience not seeing an error message.

![image](https://user-images.githubusercontent.com/88518/141014262-ea13986d-8968-4914-b301-4caabbc3b781.png)

We should see if we can return an error message about currently unsupported sensitive variables in CaC world to avoid this issue.

### Reproduction

Need to have a step that takes a sensitive parameter. Easiest way is to make one from a step template.
### Create a step template
1. Project > Select \<a project\> (create one if one doesn't already exist)
2. Process > Select \<a step\> (create one if one doesn't already exist)
3. (Configure features) ⋮ > Extract Step Template
4. Library > Step Templates > Select \<the template\>
5. Details > Parameters > Parameter
6. Add a parameter with a control type of 'Sensitive/password box'.
7. Save.
### Use a step in CaC project
1. Project > Select \<a CaC project\> (create one if one doesn't already exist)
2. Process > Add Step
3. Choose Step Template > Library Step Templates > \<step\>
4. Set the sensitive parameter to something.
5. Commit.

### Error and Stacktrace

```shell
Unhandled error on request: PUT http://localhost:8065/api/Spaces-1/projects/Projects-1/kuri/deploymentprocesses 800000d5-000f-fd00-b63f-84710c7967bb by admin : The property 'SensitiveTooth' is sensitive and not a variable declaration, which is not currently supported
System.NotSupportedException: The property 'SensitiveTooth' is sensitive and not a variable declaration, which is not currently supported
   at Octopus.Core.Serialization.Ocl.OclConverters.PropertiesDictionaryOclConverter.ToElements(OclConversionContext context, PropertyInfo propertyInfo, Object value)+MoveNext() in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\PropertiesDictionaryOclConverter.cs:line 27
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentActionOclConverter.GetElements(Object obj, OclConversionContext context) in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\DeploymentActionOclConverter.cs:line 132
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentActionOclConverter.ConvertInternal(OclConversionContext context, PropertyInfo propertyInfo, Object obj, Boolean includeNameAsLabel) in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\DeploymentActionOclConverter.cs:line 75
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentActionOclConverter.ToElements(OclConversionContext context, PropertyInfo propertyInfo, Object obj, Boolean includeNameAsLabel) in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\DeploymentActionOclConverter.cs:line 51
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.GetElements(Object obj, OclConversionContext context) in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\DeploymentStepOclConverter.cs:line 90
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.ConvertInternal(OclConversionContext context, PropertyInfo propertyInfo, Object obj)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.ConvertInternal(OclConversionContext context, PropertyInfo propertyInfo, Object obj) in C:\Dev\OctopusDeploy\source\Octopus.Core\Serialization\Ocl\OclConverters\DeploymentStepOclConverter.cs:line 20
   at Octopus.Ocl.Converters.OclConverter.ToElements(OclConversionContext context, PropertyInfo propertyInfo, Object obj)
   at Octopus.Ocl.Converters.DefaultCollectionOclConverter.ToElements(OclConversionContext context, PropertyInfo propertyInfo, Object value)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at Octopus.Ocl.OclDocument..ctor(IEnumerable`1 elements)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.ToDocument(OclConversionContext context, Object obj)
   at Octopus.Ocl.OclSerializer.ToOclDocument(Object obj)
   at Octopus.Ocl.OclSerializer.Serialize(Object obj)
   at Octopus.Core.Git.Transactions.GitTransaction.UpdateDocument[T](T document, String filename, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Git\Transactions\GitTransaction.cs:line 72
   at Octopus.Core.Persistence.Git.GitDocumentStore`2.AddAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\Git\GitDocumentStore.cs:line 173
   at Octopus.Core.Persistence.Git.GitDocumentStore`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\Git\GitDocumentStore.cs:line 151
   at Octopus.Core.Persistence.Git.NameAsIdDocumentStoreDecorator`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\Git\NameAsIdDocumentStoreDecorator.cs:line 61
   at Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathDocumentStoreDecorator`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\Database\ProjectPathDecorators\ProjectPathDocumentStoreDecorator.cs:line 70
   at Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\EntityTracking\EntityTrackingDocumentStoreDecorator.cs:line 83
   at Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\Auditing\AuditingDocumentStoreDecorator.cs:line 87
   at Octopus.Core.Persistence.DocumentStore`2.UpdateAsync(TDocument document, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Persistence\DocumentStore.cs:line 111
   at Octopus.Core.Features.DeploymentProcesses.Ocl.ModifyDeploymentProcessCommandHandler.Handle(ModifyDeploymentProcessCommand command, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Features\DeploymentProcesses\Ocl\ModifyDeploymentProcessCommandHandler.cs:line 92
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\AutofacMediator.cs:line 26
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\SystemComponentModelValidationDecorator.cs:line 27
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\FluentValidationsDecorator.cs:line 34
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\MessageBusSiphoningDecorator.cs:line 27
   at Octopus.Server.Web.Controllers.DeploymentProcesses.ModifyDeploymentProcessV2Controller.ModifyVcs(ModifyDeploymentProcessRequest request, CancellationToken cancellationToken) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Controllers\DeploymentProcesses\ModifyDeploymentProcessV2Controller.cs:line 40
   at lambda_method6250(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Infrastructure\Authentication\AuthorizationMiddlewareResultHandler.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 32
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 43
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusClientOldVersionWarningMiddleware.cs:line 26
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\DynamicContentHeadersMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\MaintenanceModeMiddleware.cs:line 54
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusAuthenticationMiddleware.cs:line 66
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.RequestLoggerMiddleware.InvokeAsync(HttpContext context) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\RequestLoggerMiddleware.cs:line 33
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\TelemetryMiddleware.cs:line 74
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in C:\Dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ErrorHandlingMiddleware.cs:line 37
```

**Comment by StephenHeise** [comment]
Release Note: Display error message to user when attempting to convert a project with sensitive variables to Config as Code.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8733 |
| 2022.1+ | _all releases_ |
