### ISSUE TITLE
.NET4.0 isn't deflating gzip file correctly producing JSONReader errors reading zipped json files

### ISSUE THREAD

**Issue by paraicoceallaigh** [OctopusDeploy/Issues#7267]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking one customer - no real workaround

### Version

2021.3.8275 Cloud

### Latest Version

I could reproduce the problem in the latest build

### What happened?

.NET4.0 handles gz files differently than later .NET versions which use httpClient. As a result it doesn't unzip gz files properly.
https://github.com/OctopusDeploy/Calamari/blob/58f2570451015b4d488baa995351bb61e3becd77/source/Calamari.Shared/Integration/Packages/NuGet/NuGetV3Downloader.cs#L207-L244

### Reproduction

Use a feed URL with a gzip index.json file but is actually compressed and it tries to parse the gz file as a json instead of uncompressing it first and fails.

C:\Octopus\Tools\Calamari.netfx\20.4.0\Calamari.exe download-package --packageId "delive
ryrecoveryservice" --packageVersion "2021.12.1.5422-ignore-inactive-account-suspension-notifications-6c322ee7" --feedUri
 "https://artifacts.postmark.ci.wildbit.com/nuget/builds/index.json" --feedUsername "redacted" --feedPassword "redacted" --feedId "Production"

Error does not appear in later .NET versions apparently

### Error and Stacktrace

```shell
Downloading NuGet package DeliveryRecoveryService vxxxxxxx from feed: 'https://xxxxxxxxx.xom/nuget/builds/index.json'
00:23:59   Verbose  |         Downloaded package will be stored in: 'C:\Octopus\Files\Feeds-1021'
00:23:59   Verbose  |         Downloading package (attempt 1 of 5)
00:24:00   Verbose  |         Attempt 1 of 5: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:24:00   Verbose  |         Going to wait 10s before attempting the download from the external feed again.
00:24:10   Verbose  |         Downloading package (attempt 2 of 5)
00:24:10   Verbose  |         Attempt 2 of 5: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:24:10   Verbose  |         Going to wait 20s before attempting the download from the external feed again.
00:24:31   Verbose  |         Downloading package (attempt 3 of 5)
00:24:31   Verbose  |         Attempt 3 of 5: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:24:31   Verbose  |         Going to wait 30s before attempting the download from the external feed again.
00:25:01   Verbose  |         Downloading package (attempt 4 of 5)
00:25:01   Verbose  |         Attempt 4 of 5: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:25:01   Verbose  |         Going to wait 40s before attempting the download from the external feed again.
00:25:42   Verbose  |         Downloading package (attempt 5 of 5)
00:25:42   Verbose  |         Attempt 5 of 5: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:25:42   Error    |         Failed to download package xxxxxxxx from feed: 'https://xxxxxxx.com/nuget/builds/index.json'
00:25:42   Error    |         The package DeliveryRecoveryService version xxxxxxxxx could not be downloaded from the external feed 'https://xxxxxxxxx.com/nuget/builds/index.json' after making 5 attempts over a total of 101s. Make sure the package is pushed to the external feed and try the deployment again. For a detailed troubleshooting guide go to http://g.octopushq.com/TroubleshootMissingPackages
00:25:42   Error    |         Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:25:42   Error    |         at Newtonsoft.Json.JsonTextReader.ParseValue()
00:25:42   Error    |         at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.<>c__DisplayClass12_0.<GetJsonResponse>b__0(Stream stream)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetHttp(Uri uri, ICredentials credentials, TimeSpan httpTimeout, Action`1 processContent)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetJsonResponse(Uri feedUri, ICredentials feedCredentials, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetDownloadUri(PackageIdentifier packageIdentifier, Uri feedUri, ICredentials feedCredentials, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String targetFilePath, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.InternalNuGetPackageDownloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String targetFilePath, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff, Action`5 action)
00:25:42   Error    |         System.Exception
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.InternalNuGetPackageDownloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String targetFilePath, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff, Action`5 action)
00:25:42   Error    |         at Calamari.Integration.Packages.Download.NuGetPackageDownloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String cacheDirectory, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff)
00:25:42   Error    |         at Calamari.Integration.Packages.Download.NuGetPackageDownloader.DownloadPackage(String packageId, IVersion version, String feedId, Uri feedUri, String feedUsername, String feedPassword, Boolean forcePackageDownload, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff)
00:25:42   Error    |         at Calamari.Integration.Packages.Download.PackageDownloaderStrategy.DownloadPackage(String packageId, IVersion version, String feedId, Uri feedUri, FeedType feedType, String feedUsername, String feedPassword, Boolean forcePackageDownload, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff)
00:25:42   Error    |         at Calamari.Commands.DownloadPackageCommand.Execute(String[] commandLineArguments)
00:25:42   Error    |         --Inner Exception--
00:25:42   Error    |         Unexpected character encountered while parsing value: . Path '', line 0, position 0.
00:25:42   Error    |         Newtonsoft.Json.JsonReaderException
00:25:42   Error    |         at Newtonsoft.Json.JsonTextReader.ParseValue()
00:25:42   Error    |         at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.<>c__DisplayClass12_0.<GetJsonResponse>b__0(Stream stream)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetHttp(Uri uri, ICredentials credentials, TimeSpan httpTimeout, Action`1 processContent)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetJsonResponse(Uri feedUri, ICredentials feedCredentials, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.GetDownloadUri(PackageIdentifier packageIdentifier, Uri feedUri, ICredentials feedCredentials, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.NuGetV3Downloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String targetFilePath, TimeSpan httpTimeout)
00:25:42   Error    |         at Calamari.Integration.Packages.NuGet.InternalNuGetPackageDownloader.DownloadPackage(String packageId, IVersion version, Uri feedUri, ICredentials feedCredentials, String targetFilePath, Int32 maxDownloadAttempts, TimeSpan downloadAttemptBackoff, Action`5 action)
00:25:42   Verbose  |         Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20211202002358-136455-10 exited with code 100
00:25:42   Verbose  |         Exit code: 100
```

### More Information

Ticket: https://octopus.zendesk.com/agent/tickets/80936. (private link)

### Workaround

don't use gzipped index.json files for feed URLs

**Comment by mjhilton** [comment]
We need to investigate here whether the best path is to fix the .NET 4.0 code, or if we are upgrading Calamari to always use .NET 4.5+, then we may automatically get a fix from doing that.
