### ISSUE TITLE
Enabling ARC on a project clears the Lifecycles > Usage page of all associated projects.

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7277]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking deployments, more of an issue when trying to find what lifecycles are associated with what projects.

### Version

2021.3.8825

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When creating a project with a lifecycle associated to it it will show that project in the Lifecycles - Usage tab.

![image](https://user-images.githubusercontent.com/92790462/146800557-ddc7f2ad-f16b-44d6-8929-1cc9b7842c71.png)

If you then enable ARC for that project and go back to Lifecycles > Usage - it will show there are no projects associated with that lifecycle.

![image](https://user-images.githubusercontent.com/92790462/146800725-2a6e7f67-d0bb-4dbb-9aca-b2d1a1a30e0b.png)

![image](https://user-images.githubusercontent.com/92790462/146800808-7675a7fd-61b6-44c7-ac0a-f697bdbad608.png)

If you then disable ARC for that project the Lifecycles > Usage page then goes back to showing it has associated projects.

Confirming Enabling ARC on a project clears the Lifecycles > Usage page of all associated projects.

### Reproduction

- Create a package in the internal octopus package repo.
- Create a project and add a 'deploy a package' step and link the package repo created above.
- Create a new lifecycle and associate it to the new project. 
- See the Lifecycles > Usage page shows it's associated with that project.
- Go back into the project and enable ARC and point it to the 'deploy package' step.
- Go back to Lifecycles > Usage page and see it shows it's **_not_** associated with any projects.
- Delete ARC for that project and see Lifecycles > Usage page shows it is once again associated with that project.

### More Information

https://help.octopus.com/t/lifecycle-usage-tab-still-empty/27497

This was mentioned in https://github.com/OctopusDeploy/Issues/issues/7004 but it has not been fixed.

This bug behaves differently in that ARC is showing the package whereas in the GitHub issue posted above it wasn't showing the package so a new Issue has been created.

### Workaround

No workarounds are known, the only way to show associated projects in a lifecycle is to disable ARC for the project.

**Comment by droyad** [comment]
This is occuring because when calling the usages endpoing (e.g. http://localhost/api/Spaces-1/lifecycles/Lifecycles-1/projects) the following exception is thrown within the Entity Tracker. Most worryingly is that it doesn't return this error to the UI, rather it returns an empty array.

```
The ConnectionString property has not been initialized.
   at Microsoft.Data.SqlClient.SqlConnection.PermissionDemand()
   at Microsoft.Data.SqlClient.SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Nevermore.Transient.RetryPolicy.<>c__DisplayClass26_0.<ExecuteAction>b__0()
   at Nevermore.Transient.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Nevermore.Transient.RetryPolicy.ExecuteAction(Action action)
   at Nevermore.Transient.DbConnectionExtensions.OpenWithRetry(DbConnection connection, RetryPolicy retryPolicy)
   at Nevermore.Transient.DbCommandExtensions.EnsureValidConnection(DbCommand command, RetryPolicy retryPolicy)
   at Nevermore.Transient.DbCommandExtensions.<>c__DisplayClass2_0.<ExecuteReaderWithRetry>b__0()
   at Nevermore.Transient.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Nevermore.Transient.DbCommandExtensions.ExecuteReaderWithRetry(DbCommand command, RetryPolicy commandRetryPolicy, CommandBehavior behavior, RetryPolicy connectionRetryPolicy, String operationName)
   at Nevermore.CommandExecutor.ExecuteReader()
   at Nevermore.Advanced.ReadTransaction.ExecuteReader(PreparedCommand preparedCommand)
   at Nevermore.Advanced.ReadTransaction.Stream[TRecord](PreparedCommand command)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Nevermore.Advanced.ReadTransaction.Load[TDocument,TKey](TKey id)
   at Octopus.Core.RelationalStorage.RawRelationalTransaction.Load[TDocument,TKey](TKey id) in C:\source\Octopus\Server\source\Octopus.Core\RelationalStorage\RawRelationalTransaction.cs:line 33
   at Octopus.Server.Web.Infrastructure.OctopusQueryExecutor.Load[TDocument,TKey](TKey id) in C:\source\Octopus\Server\source\Octopus.Server\Web\Infrastructure\OctopusQueryExecutor.cs:line 251
   at Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathQueryExecutorDecorator.Load[TDocument,TKey](TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\ProjectPathDecorators\ProjectPathQueryExecutorDecorator.cs:line 35
   at Octopus.Core.Persistence.Database.DatabaseDocumentStore`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\DatabaseDocumentStore.cs:line 66
   at Octopus.Core.Persistence.Database.FullTableCacheDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\FullTableCacheDocumentStoreDecorator.cs:line 66
   at Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\ProjectPathDecorators\ProjectPathDocumentStoreDecorator.cs:line 51
   at Octopus.Core.Persistence.EntityTracking.EntityTracker.GetOrTrack[TDocument,TKey](TKey id, Func`2 getDocument) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\EntityTracking\EntityTracker.cs:line 46
   at Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\EntityTracking\EntityTrackingDocumentStoreDecorator.cs:line 54
   at Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Auditing\AuditingDocumentStoreDecorator.cs:line 88
   at Octopus.Core.Persistence.Database.Deletion.DeleteRelatedDocumentsDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\Deletion\DeleteRelatedDocumentsDocumentStoreDecorator.cs:line 62
   at Octopus.Core.Persistence.Database.Deletion.VetoDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\Deletion\VetoDocumentStoreDecorator.cs:line 61
   at Octopus.Core.Persistence.Database.AccessCheckingDocumentStoreDecorator`2.Get(TKey id) in C:\source\Octopus\Server\source\Octopus.Core\Persistence\Database\AccessCheckingDocumentStoreDecorator.cs:line 46
   at Octopus.Core.Features.DeploymentProcesses.CurrentDeploymentProcessDocumentStoreExtensionMethods.GetByProject(IDocumentStore`2 documentStore, Project project) in C:\source\Octopus\Server\source\Octopus.Core\Features\DeploymentProcesses\CurrentDeploymentProcessDocumentStoreExtensionMethods.cs:line 15
   at Octopus.Server.Web.Mapping.DeploymentActionPackageNameMapper.GetProcess(Project project) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\DeploymentActionPackageNameMapper.cs:line 135
   at Octopus.Server.Web.Mapping.DeploymentActionPackageNameMapper.MapToNames(Project project, DeploymentActionPackage deploymentActionPackage) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\DeploymentActionPackageNameMapper.cs:line 50
   at Octopus.Server.Web.Mapping.Mappings.ProjectModelsToResourcesMappings.<ContributeMaps>b__0_5(Project project, ProjectResource resource, IResourceMappingContext ctx, IResourceMapper mapper, AllRoutes routes, ILifetimeScope _) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\Mappings\ProjectModelsToResourcesMappings.cs:line 52
   at Octopus.Server.Web.Mapping.ResourceMappingBuilder`2.<>c__DisplayClass10_1.<EnrichResource>b__1(TModel m, TResource r) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMappingBuilder.cs:line 112
   at Octopus.Server.Web.Mapping.ActionResourceEnricher`2.EnrichResource(TModel model, TResource resource) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ActionResourceEnricher.cs:line 19
   at Octopus.Server.Web.Mapping.ResourceMapping`2.<>c__DisplayClass15_0.<AfterMapToResourceInternal>b__0(Func`2 f) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapping.cs:line 98
   at Octopus.Server.Extensibility.HostServices.Infrastructure.EnumerableExtensions.ForEach[T](IEnumerable`1 these, Action`1 action)
   at Octopus.Server.Web.Mapping.ResourceMapping`2.AfterMapToResourceInternal(Object model, Object resource, ILifetimeScope scope) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapping.cs:line 98
   at Octopus.Server.Web.Mapping.ResourceMapping`2.<>c__DisplayClass13_0.<AfterMapToResource>b__0(ILifetimeScope resourceScope) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapping.cs:line 75
   at Octopus.Server.Web.Mapping.ResourceMapping`2.UsingLifetimeScopeForResource(Object resource, ILifetimeScope scope, Action`1 scopeAction) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapping.cs:line 92
   at Octopus.Server.Web.Mapping.ResourceMapping`2.AfterMapToResource(Object model, Object resource, ILifetimeScope scope) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapping.cs:line 72
   at Octopus.Server.Web.Mapping.ResourceMapper.ModelToResource(Object model, Object resource, Boolean detailed, IResourceMapping resourceMapping) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapper.cs:line 269
   at Octopus.Server.Web.Mapping.ResourceMapper.<>c__DisplayClass4_0.<ConvertTo>b__0(IResourceMapping mapping) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapper.cs:line 51
   at Octopus.Server.Web.Mapping.ResourceMapper.Apply(Object resource, Object model, Action`1 mappingAction) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapper.cs:line 149
   at Octopus.Server.Web.Mapping.ResourceMapper.ConvertTo(Object model, Type resourceType, ResourceMapperMode mode) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapper.cs:line 51
   at Octopus.Server.Web.Mapping.ResourceMapper.ConvertTo[TResource](Object model, ResourceMapperMode mode) in C:\source\Octopus\Server\source\Octopus.Server\Web\Mapping\ResourceMapper.cs:line 37
   at Octopus.Server.Web.Api.Actions.LifecycleProjectsAction.<>c__DisplayClass5_0.<ExecuteRegistered>b__2(Project p) in C:\source\Octopus\Server\source\Octopus.Server\Web\Api\Actions\LifecycleProjectsAction.cs:line 46
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   ```

**Comment by droyad** [comment]
I could reproduce this on `2021.3.9295`, so it's not #7204

**Comment by millerjn21** [comment]
Another instance here: https://octopus.zendesk.com/agent/tickets/81456

This user cannot use the workaround as they over a hundred projects using ARC. Is there any other method?

**Comment by sburmanoctopus** [comment]
Release Note: Lifecycles no longer clear on UI when enabling ARC

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7952 |
| 2021.3 | 2021.3.10322 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7952 |
| 2021.3 | 2021.3.10322 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.7952 |
| 2021.3 | 2021.3.10322 |
| 2022.1+ | _all releases_ |
