### ISSUE TITLE
Halibut - Polling Tentacle WebSocket via LoadBalancer Error - The identity line was empty

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7340]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround Exists

### Version

Effects Latest Version

### Latest Version

I could reproduce the problem in the latest build

### What happened?

After upgrading to 2021.3.8275, Polling Tentacles via Websockets are no longer passing their Health Checks when using an HTTPS listener on a LoadBalancer. 

The health check task times-out after 2mins and the Tentacle logs present an Error with Halibut: Unable to receive the remote identity; the identity line was empty.

This effects Polling Tentacles with Websockets that were configured over a LoadBalancer HTTPS 443 Listener only. WebSockets via Network LoadBalancing using TCP connections is working.

It appears the connection is being made successfully but then it is failing immediately afterwards: 
`7 06:45:26.5592   5144      8 DEBUG  wss://octo.domain.local/octopuscomms    8  Opening a new connection
2022-01-27 06:45:26.5904   5144      8 TRACE  wss://octo.domain.local/octopuscomms    8  Connection established
2022-01-27 06:45:26.5904   5144      8  INFO  wss://octo.domain.local/octopuscomms    8  Performing handshake
2022-01-27 06:45:26.5904   5144      8  INFO  wss://octo.domain.local/octopuscomms    8  Secure connection established. Server at wss://octo.domain.local/OctopusComms identified by thumbprint: XXXXXXX
2022-01-27 06:45:26.6217   5144      8 ERROR  wss://octo.domain.local/octopuscomms    8  Unexpected exception executing transaction.`

### Reproduction

Using Octopus Server Version 2020.6.4915.

Configure a WebSocket Polling Tentacle as [documented here](https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/polling-tentacles-web-sockets).

Use an AWS Application Load Balancer with an HTTPS Listener to route traffic to the Octopus Server. 

Confirm Tentacle passes health check while using 2020.6.4915.

Upgrade to 2021.3.8275 - Run health check and see error.

### Error and Stacktrace

```shell
7 06:45:26.5592   5144      8 DEBUG  wss://octo.domain.local/octopuscomms    8  Opening a new connection
2022-01-27 06:45:26.5904   5144      8 TRACE  wss://octo.domain.local/octopuscomms    8  Connection established
2022-01-27 06:45:26.5904   5144      8  INFO  wss://octo.domain.local/octopuscomms    8  Performing handshake
2022-01-27 06:45:26.5904   5144      8  INFO  wss://octo.domain.local/octopuscomms    8  Secure connection established. Server at wss://octo.domain.local/OctopusComms identified by thumbprint: XXXXXXX
2022-01-27 06:45:26.6217   5144      8 ERROR  wss://octo.domain.local/octopuscomms    8  Unexpected exception executing transaction.
Halibut.Transport.Protocol.ProtocolException: Unable to receive the remote identity; the identity line was empty.
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadRemoteIdentity()
   at Halibut.Transport.Protocol.MessageExchangeStream.ExpectServerIdentity()
   at Halibut.Transport.Protocol.MessageExchangeStream.IdentifyAsSubscriber(String subscriptionId)
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsSubscriber(Uri subscriptionId, Func`2 incomingRequestProcessor, Int32 maxAttempts)
   at Halibut.Transport.SecureWebSocketClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
2022-01-27 06:45:26.6217   5144      8 ERROR  wss://octo.domain.local/octopuscomms    8  Halibut client exception: An error occurred when sending a request to 'wss://octo.domain.local/OctopusComms', after the request began: Unable to receive the remote identity; the identity line was empty. Retrying in 120.0 seconds
Halibut.HalibutClientException: An error occurred when sending a request to 'wss://octo.domain.local/OctopusComms', after the request began: Unable to receive the remote identity; the identity line was empty. ---> Halibut.Transport.Protocol.ProtocolException: Unable to receive the remote identity; the identity line was empty.
   at Halibut.Transport.Protocol.MessageExchangeStream.ReadRemoteIdentity()
   at Halibut.Transport.Protocol.MessageExchangeStream.ExpectServerIdentity()
   at Halibut.Transport.Protocol.MessageExchangeStream.IdentifyAsSubscriber(String subscriptionId)
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsSubscriber(Uri subscriptionId, Func`2 incomingRequestProcessor, Int32 maxAttempts)
   at Halibut.Transport.SecureWebSocketClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Halibut.Transport.SecureWebSocketClient.HandleError(Exception lastError, Boolean retryAllowed)
   at Halibut.Transport.SecureWebSocketClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
   at Halibut.Transport.PollingClient.ExecutePollingLoop(Object ignored)
```

### More Information

[Internal - Customer Report](https://octopus.zendesk.com/agent/tickets/82164)
[Internal - Slack](https://octopusdeploy.slack.com/archives/C02U6K6016J)

### Workaround

WebSockets are still able to be used, however they will require an uninterrupted TCP connection for the LoadBalancer and so a Network LoadBalancer can be configured as a workaround. The Octopus Server configuration will not need to be modified. 

1. Change the tentacle communication port to use a custom port e.g. 80. See [the documentation here](https://octopus.com/docs/infrastructure/deployment-targets/windows-targets/polling-tentacles-web-sockets#changing-an-existing-tentacle) for an example.

2. Setup a Network LoadBalancer which has a TCP listener on the port the Tentacle is using. e.g. 80

3. Configure a Target Group to route traffic to the WebSocket Endpoint used by Octopus Server which by default is 443. Health check configured over the Traffic port.

Make sure to confirm that security groups allow access over those ports. All Octopus Tentacle communication will still use TLS. See [our documentation here](https://octopus.com/docs/security/octopus-tentacle-communication#Octopus-Tentaclecommunication-Octopus/Tentacletrustrelationship) for more info.

**Comment by tothegills** [comment]
Closing because we suspect this configuration is unsupported. Use an SSL pass-through load balancer.
