### ISSUE TITLE
"Sequence contains more than one matching element" error when creating a release in the CLI when release versioning set to a referenced package on a step that includes a deployment package

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#7359]
### Team

- [X] I've assigned a team label to this issue

### Severity

Not blocking, at least 1 affected customer

### Version

Tested in 2021.3.8275

### What happened?

"Sequence contains more than one matching element" error when creating a release in the CLI when release versioning set to a referenced package on a step that includes a deployment package

### Reproduction

Related to [7283](https://github.com/OctopusDeploy/Issues/issues/7283) 

1. Create a Run a Script step with Inline source code
2. Set a Referenced Package
3. Go to Deployments -> Settings for the Project -> Use the version number from an included package
4. Select the package from Step 2
5. Attempt to create a release from the CLI
     - Example: `octo create-release --server=http://Your_Octopus_Server --apikey=API-XXXXXXXXXXXXXXXXXXXXXXXXX --project="project_name"`

### Error and Stacktrace

```shell
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Cli.Commands.Releases.ReleasePlan.GetActionVersionNumber(String packageStepName, String packageReferenceName)
   at Octopus.Cli.Commands.Releases.CreateReleaseCommand.Request()
   at Octopus.Cli.Commands.ApiCommand.Execute()
   at Octopus.Cli.Commands.ApiCommand.Execute(String[] commandLineArguments)
   at Octopus.Cli.CliProgram.Run(String[] args)
Exit code: -3
```

### Workaround

Create a release via the Octopus Server UI rather than the CLI

or 

Create a placeholder step such as the example below:
![image](https://user-images.githubusercontent.com/63249187/152878064-ef9d1e02-7f1e-46b7-9190-fee10bb347de.png)

![image](https://user-images.githubusercontent.com/63249187/152878808-6e8d9b5e-e524-422a-9b74-da6bb83187dd.png)

![image](https://user-images.githubusercontent.com/63249187/152878972-5102f2d0-30e6-4510-91ac-49c3b832aeae.png)

**Comment by zentron** [comment]
Unable to reproduce this issue based on the steps provided:
![image](https://user-images.githubusercontent.com/1830666/152902571-6609b1fe-c5a8-4aea-8c37-e7c99ed46f87.png)
![image](https://user-images.githubusercontent.com/1830666/152902600-04b26c0b-6bdb-459b-97c1-81cbd3c61f9b.png)
![image](https://user-images.githubusercontent.com/1830666/152902678-333cecd5-0e62-47f6-9c08-0e5aff7061a2.png)

Based on the error message I would have expected multiple packages to have been defined. Do you have a cloud instance up I can test this against?

**Comment by donnybell** [comment]
@zentron I fixed the instructions

**Comment by zentron** [comment]
Thanks @donnybell , that seems to have helped me reproduce it
