### ISSUE TITLE
Always-run database upgrade scripts prevent server startup with an expired license

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#7427]
### Team

- [X] I've assigned a team label to this issue

### Severity

Impacting multiple customers

### Version

~2020.1 -> Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Since the introduction of always-run DB scripts, the server can't start on an expired license, due to the upgrade script runner performing a license check each time the server starts. In scenarios where a customer's license has expired, they are stuck in an offline state, and unable to easily update the license to get them back online.

### Reproduction

1. Try to start Octopus server with an expired license
2. 💥 

### Error and Stacktrace

```shell
2022-03-09 05:03:08.6730   5464     11  INFO  CommandLine: C:\Program Files\Octopus Deploy\Octopus\Octopus.Server.dll run --instance=OctopusServer

2022-03-09 05:03:08.6730   5464     11  INFO  Octopus.Server.dll version 2021.2.7462 (2021.2.7462+Branch.release-2021.2.Sha.3c05f5661c075045286d324bedf5dbeed014a783)

2022-03-09 05:03:08.6730   5464     11  INFO  Verifying Octopus directory contents...

2022-03-09 05:03:08.6892   5464     11  INFO  Octopus directory is 'C:\Program Files\Octopus Deploy\Octopus'

2022-03-09 05:03:08.9736   3532      1  INFO  Waiting for service to become Running. Current status: Running

2022-03-09 05:03:09.2754   3532      1  INFO  Service started

2022-03-09 05:03:25.4756   5464     11  INFO   - PASS: All expected files successfully found in Octopus directory

2022-03-09 05:03:25.5060   5464     11  INFO   - PASS: All files in the Octopus directory have the expected version

2022-03-09 05:03:25.5322   5464     11  INFO   - PASS: No extra files found in Octopus directory

2022-03-09 05:03:25.5348   5464     11  INFO  Using instance OctopusServer

2022-03-09 05:03:25.5521   5464     11  INFO  Using database data source=<snip>

2022-03-09 05:03:26.2796   5464     11  INFO  Testing the built-in worker configuration.

2022-03-09 05:03:26.2826   5464     11  INFO  Built-in worker: SUCCESS

2022-03-09 05:03:26.2826   5464     11  INFO  The Octopus Server is starting...

2022-03-09 05:03:26.7036   5464     11  INFO  Checking the Octopus Master Key has been configured.

2022-03-09 05:03:26.7241   5464     11  INFO  Making sure it's safe to upgrade the database schema...

2022-03-09 05:03:26.7527   5464     11  INFO  Ensuring pre-conditions for upgrading the database are satisfied...

2022-03-09 05:03:26.9731   5464     11  INFO  Searching for indexes that might upset the database upgrade process...

2022-03-09 05:03:26.9994   5464     11  INFO  - PASS: All columns use the default collation.

2022-03-09 05:03:27.0025   5464     11  INFO  - FAIL: Your Octopus Server would not be compliant with your license if we allowed the upgrade to continue. Here is the summary of the license check: Your Octopus Server subscription expired on Tuesday, 05 October 2021 (155 days ago) and has not been renewed. You will be prevented from performing key activities, like creating and deploying releases. Please visit https://g.octopushq.com/ServerSubscription for more information.

2022-03-09 05:03:27.0025   5464     11  INFO  - PASS: We've done our best to remove any unexpected database indexes.

2022-03-09 05:03:27.0025   5464     11  INFO  - PASS: The version of your SQL Server satisfies Octopus Server installation requirements.

2022-03-09 05:03:27.1309   5464     11 FATAL  One of the pre-conditions to safely upgrade your database has failed, and the upgrade cannot continue.

- PASS: All columns use the default collation.

- FAIL: Your Octopus Server would not be compliant with your license if we allowed the upgrade to continue. Here is the summary of the license check: Your Octopus Server subscription expired on Tuesday, 05 October 2021 (155 days ago) and has not been renewed. You will be prevented from performing key activities, like creating and deploying releases. Please visit https://g.octopushq.com/ServerSubscription for more information.

- PASS: We've done our best to remove any unexpected database indexes.

- PASS: The version of your SQL Server satisfies Octopus Server installation requirements.

Please take the following steps to get your Octopus Server back up and running:

Step 1: Re-run the installer for the version of Octopus Server you were using just before trying this upgrade. Your data hasn't been changed and everything will go back to how it was beforehand. This will give you time to solve the problem and try the upgrade again.

Step 2: Contact support@octopus.com with a copy of your Octopus Server log file so we can help you upgrade successfully.

Octopus.Shared.ControlledFailureException: One of the pre-conditions to safely upgrade your database has failed, and the upgrade cannot continue.

- PASS: All columns use the default collation.

- FAIL: Your Octopus Server would not be compliant with your license if we allowed the upgrade to continue. Here is the summary of the license check: Your Octopus Server subscription expired on Tuesday, 05 October 2021 (155 days ago) and has not been renewed. You will be prevented from performing key activities, like creating and deploying releases. Please visit https://g.octopushq.com/ServerSubscription for more information.

- PASS: We've done our best to remove any unexpected database indexes.

- PASS: The version of your SQL Server satisfies Octopus Server installation requirements.

Please take the following steps to get your Octopus Server back up and running:

Step 1: Re-run the installer for the version of Octopus Server you were using just before trying this upgrade. Your data hasn't been changed and everything will go back to how it was beforehand. This will give you time to solve the problem and try the upgrade again.

Step 2: Contact support@octopus.com with a copy of your Octopus Server log file so we can help you upgrade successfully.

 

   at Octopus.Core.Initialization.DatabaseUpgradeCoordinator.RunPreconditions() in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Core\Initialization\DatabaseUpgradeCoordinator.cs:line 109

   at Octopus.Core.Initialization.DatabaseUpgradeCoordinator.Upgrade(CancellationToken cancellationToken) in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Core\Initialization\DatabaseUpgradeCoordinator.cs:line 62

   at Octopus.Core.Initialization.DatabaseUpgradeCoordinatorFactory.DisposableDatabaseUpgradeCoordinatorFacade.Upgrade(CancellationToken cancellationToken) in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Core\Initialization\DatabaseUpgradeCoordinatorFactory.cs:line 153

   at Octopus.Core.Initialization.BuiltIn.DatabaseUpgradeInitializer.Initialize(IRawRelationalStore store) in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Core\Initialization\BuiltIn\DatabaseUpgradeInitializer.cs:line 21

   at Octopus.Core.Initialization.StoreInitializer.Initialize() in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Core\Initialization\StoreInitializer.cs:line 20

   at Octopus.Server.OctopusServerEngine.Start() in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Server\OctopusServerEngine.cs:line 79

   at Octopus.Server.Commands.RunCommand.Start() in C:\BuildAgent\work\eb99e602a96dd63\source\Octopus.Server\Commands\RunCommand.cs:line 79

   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)

   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime)

   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass2_0.<Run>b__0()

   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService()
```

### More Information

While a workaround does exist, it can be impractical in many enterprise or high-security scenarios where the Octopus users do not have access to the underlying server to run the command from the CLI, or Octopus is running under a service account with no ability to log in interactively.

This behavior is also counter to how we state it should work in our [sales FAQ](https://octopus.com/pricing/faq#server-expired).

### Workaround

The license can be manually updated using the Octopus.Server.exe command from a command prompt, as detailed here: https://octopus.com/docs/octopus-rest-api/octopus.server.exe-command-line/license

**Comment by Justin-Walsh** [comment]
Customer reports [Internal links]: 
- https://octopus.zendesk.com/agent/tickets/80607
- https://octopus.zendesk.com/agent/tickets/81083
- https://octopus.zendesk.com/agent/tickets/19970
- https://octopus.zendesk.com/agent/tickets/84658 
- https://octopus.zendesk.com/agent/tickets/85165

**Comment by donnybell** [comment]
[Another affected customer](https://octopus.zendesk.com/agent/tickets/88849)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.13021 |
| 2022.1 | 2022.1.2894 |
| 2022.2 | 2022.2.6864 |
| 2022.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.13021 |
| 2022.1 | 2022.1.2894 |
| 2022.2 | 2022.2.6864 |
| 2022.3 | 2022.3.3014 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.13021 |
| 2022.1 | 2022.1.2894 |
| 2022.2 | 2022.2.6864 |
| 2022.3 | 2022.3.3014 |
| 2022.4+ | _all releases_ |
