### ISSUE TITLE
When using a windows execution container and you have a ~ in a filename in your package, you get a SharpCompress error. SharpCompress.Common.ExtractionException: Entry is trying to write a file outside of the destination directory.

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#7500]
### Team

- [X] I've assigned a team label to this issue

### Severity

1, not blocking

### Version

2022.2.387-hotfix.903

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using a windows execution container and you have a ~ in a filename in your package, you get a SharpCompress error.

SharpCompress.Common.ExtractionException: Entry is trying to write a file outside of the destination directory.

### Reproduction

1) Create a zip file that has a file with a ~ in its name, for instance: `README.md~`
2) Upload the file to Octopus
3) Create a run a script step and reference the above package, make this step run on a windows execution container
4) See the error when it tries to extract it

### Error and Stacktrace

```shell
17:54:18   Error    |       SharpCompress.Common.ExtractionException: Entry is trying to write a file outside of the destination directory.
17:54:18   Error    |       at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
17:54:18   Error    |       at SharpCompress.Archives.IArchiveEntryExtensions.WriteToDirectory(IArchiveEntry entry, String destinationDirectory, ExtractionOptions options)
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.<>c__DisplayClass5_0.<ExtractEntry>b__2() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 58
17:54:18   Error    |       at Polly.Policy.<>c__DisplayClass57_0.<Execute>b__0(Context ctx, CancellationToken ct)
17:54:18   Error    |       at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
17:54:18   Error    |       at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
17:54:18   Error    |       at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
17:54:18   Error    |       at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
17:54:18   Error    |       at Polly.Policy.Execute(Action action)
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.ExtractEntry(String directory, ZipArchiveEntry entry) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 60
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.Extract(String packageFile, String directory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 31
17:54:18   Error    |       at Calamari.Common.Features.Packages.CombinedPackageExtractor.Extract(String packageFile, String directory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\CombinedPackageExtractor.cs:line 39
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.ExtractPackage(String packageFile, String extractionDirectory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 98
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.StagePackageReferences(RunningDeployment deployment) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 75
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.Install(RunningDeployment deployment) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 38
17:54:18   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 75
17:54:18   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 32
17:54:18   Error    |       Running rollback conventions...
17:54:18   Error    |       Entry is trying to write a file outside of the destination directory.
17:54:18   Error    |       SharpCompress.Common.ExtractionException
17:54:18   Error    |       at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
17:54:18   Error    |       at SharpCompress.Archives.IArchiveEntryExtensions.WriteToDirectory(IArchiveEntry entry, String destinationDirectory, ExtractionOptions options)
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.<>c__DisplayClass5_0.<ExtractEntry>b__2() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 58
17:54:18   Error    |       at Polly.Policy.<>c__DisplayClass57_0.<Execute>b__0(Context ctx, CancellationToken ct)
17:54:18   Error    |       at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
17:54:18   Error    |       at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
17:54:18   Error    |       at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
17:54:18   Error    |       at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
17:54:18   Error    |       at Polly.Policy.Execute(Action action)
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.ExtractEntry(String directory, ZipArchiveEntry entry) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 60
17:54:18   Error    |       at Calamari.Common.Features.Packages.ZipPackageExtractor.Extract(String packageFile, String directory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\ZipPackageExtractor.cs:line 31
17:54:18   Error    |       at Calamari.Common.Features.Packages.CombinedPackageExtractor.Extract(String packageFile, String directory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Features\Packages\CombinedPackageExtractor.cs:line 39
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.ExtractPackage(String packageFile, String extractionDirectory) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 98
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.StagePackageReferences(RunningDeployment deployment) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 75
17:54:18   Error    |       at Calamari.Deployment.Conventions.StageScriptPackagesConvention.Install(RunningDeployment deployment) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\Conventions\StageScriptPackagesConvention.cs:line 38
17:54:18   Error    |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 75
17:54:18   Error    |       at Calamari.Deployment.ConventionProcessor.RunConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 32
17:54:18   Error    |       at Calamari.Commands.RunScriptCommand.Execute(String[] commandLineArguments) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\RunScriptCommand.cs:line 95
17:54:18   Error    |       at Calamari.Deployment.PackageRetention.PackageJournalCommandDecorator.Execute(String[] commandLineArguments) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Deployment\PackageRetention\PackageJournalCommandDecorator.cs:line 49
17:54:18   Error    |       at Calamari.Program.ResolveAndExecuteCommand(IContainer container, CommonOptions options) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Program.cs:line 58
17:54:18   Error    |       at Calamari.Common.CalamariFlavourProgram.Run(String[] args) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\CalamariFlavourProgram.cs:line 78
```

### More Information

Source Ticket: https://help.octopus.com/t/failed-deployments-with-execution-containers/27776/6

### Workaround

Remove the ~ from file names in your package or use a linux execution container.

**Comment by millerjn21** [comment]
I only opened this for informational purposes, this is a limitation of SharpCompress and/or Windows containers. Please refer to the workaround to resolve the issue.
