### ISSUE TITLE
GitHub Nuget feeds return a 500 error when searching for packages but deploy successfully

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#7503]
### Team

- [X] I've assigned a team label to this issue

### Severity

1, not blocking

### Version

2022.2.387-hotfix.903

### Latest Version

I could reproduce the problem in the latest build

### What happened?

GitHub Nuget feeds return a 500 error when searching for packages but deploy successfully.

### Reproduction

1. Create a GitHub NuGet feed
2. Search for a package that you know exists.
3. See error

### Error and Stacktrace

```shell
System.Exception: Could not connect to the package feed
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass13_0`1.<<ProcessStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetJObjectAsync(HttpSourceRequest request, ILogger log, CancellationToken token)
   at NuGet.Protocol.RawSearchResourceV3.SearchPage(String searchTerm, SearchFilter filters, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Octopus.Core.Packages.NuGet.ExternalHttpNuGetPackageFeed.SearchForPackagesNamedLike(String packageId, Int32 take, CancellationToken cancellationToken, Boolean exactPackageIdMatch) in ./source/Octopus.Core/Packages/NuGet/ExternalHttpNuGetPackageFeed.cs:line 196
   at Octopus.Core.Packages.NuGet.ExternalHttpNuGetPackageFeed.SearchPackages(String term, CancellationToken cancellationToken, ILog log, Int32& total, Int32 skip, Int32 take) in ./source/Octopus.Core/Packages/NuGet/ExternalHttpNuGetPackageFeed.cs:line 92
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.SearchPackages(IPackageFeed repository, String term, Int32 skip, Int32 take, String feedId, ILog log) in ./source/Octopus.Server/Web/Api/Actions/PackageSearchAction.cs:line 109
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.ExecuteRegistered() in ./source/Octopus.Server/Web/Api/Actions/PackageSearchAction.cs:line 85
   at Octopus.Server.Web.Infrastructure.Api.CustomResponder`1.Respond(TDescriptor options, NancyContext context) in ./source/Octopus.Server/Web/Infrastructure/Api/CustomResponder.cs:line 321
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object _, CancellationToken _) in ./source/Octopus.Server/Web/Infrastructure/OctopusNancyModule.cs:line 150
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
   at Octopus.NancyOwin.NancyMiddleware.RequestComplete(NancyContext context, IDictionary`2 environment, CancellationToken cancellationToken) in ./source/Octopus.Server/Owin/NancyMiddleware.cs:line 174
   at Octopus.NancyOwin.NancyMiddleware.<>c__DisplayClass3_0.<<UseNancy>b__1>d.MoveNext() in ./source/Octopus.Server/Owin/NancyMiddleware.cs:line 110
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 53
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 49
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 61
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 67
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 76
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 96
```

### More Information

Internal Cloud Repro, Github Nuget Feed, a package that exists in this feed is `TestProject`: https://octopus-operations.octopus.app/app#/Spaces-83/library/feeds/Feeds-1221/test

### Workaround

Searching currently doesn't work, but deploying does. You will have to go get the exact package name from the feed itself and manually input it if searching isn't working.

**Comment by enf0rc3** [comment]
I have re-tested this and can not reproduce the issue, we assume that this is no longer an issue. 

Configured feed:

<img width="1802" height="463" alt="Image" src="https://github.com/user-attachments/assets/acd42a04-5e7f-4264-aa78-a110f21b3678" />

Version Selection:

<img width="1382" height="540" alt="Image" src="https://github.com/user-attachments/assets/04fdc211-f3df-4f4d-aed2-68996d15d5cb" />

Feed Test (search):

<img width="1799" height="546" alt="Image" src="https://github.com/user-attachments/assets/090f5256-f729-4d8b-b49b-14460dcfd5e1" />
