### ISSUE TITLE
Access denied when clearing git cache

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7543]
### Team

- [X] I've assigned a team label to this issue

### Version

Earliest tried was 2022.1.2386

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When trying to clear the git cache, an exception can be written to the logs, and the cache is not cleared. No feedback is provided to the UI.

### Reproduction

Reproduction not yet known.

### Error and Stacktrace

```shell
System.UnauthorizedAccessException: Access to the path 'D:\Octopus\Git\64CCONDKE3UZZVUGEM2IGZOJR2M6I5BZ\root\objects\pack\pack-01054a1fdf0ad967671ccf831211245c665a05d3.idx' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.TryToDoSomethingMultipleTimes(Action`1 thingToDo, Int32 numberAttempts, Int32 sleepTime, Boolean throwOnFailure, CancellationToken cancellationToken)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.DeleteFile(String path, CancellationToken cancellationToken, DeletionOptions options)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.PurgeDirectoryAsync(String targetDirectory, Predicate`1 includeFilter, Nullable`1 cancel, Nullable`1 includeTarget, Func`2 fileEnumerationFunc, DeletionOptions options)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.PurgeDirectoryAsync(String targetDirectory, Predicate`1 includeFilter, Nullable`1 cancel, Nullable`1 includeTarget, Func`2 fileEnumerationFunc, DeletionOptions options)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.PurgeDirectoryAsync(String targetDirectory, Predicate`1 includeFilter, Nullable`1 cancel, Nullable`1 includeTarget, Func`2 fileEnumerationFunc, DeletionOptions options)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.PurgeDirectoryAsync(String targetDirectory, Predicate`1 includeFilter, Nullable`1 cancel, Nullable`1 includeTarget, Func`2 fileEnumerationFunc, DeletionOptions options)
   at Octopus.Shared.Util.OctopusPhysicalFileSystem.PurgeDirectoryAsync(String targetDirectory, Predicate`1 includeFilter, Nullable`1 cancel, Nullable`1 includeTarget, Func`2 fileEnumerationFunc, DeletionOptions options)
```

### Workaround

If Octopus Server is self-hosted, then deleting the `Git` directory in the Octopus directory may resolve the issue.

**Comment by cstrzadala** [comment]
Closing as not being raised by customers at a reasonable cadence. May reopen if customers raise this issue.

**Comment by dan-close** [comment]
Another customer report: https://help.octopus.com/t/no-git-resource-with-the-name-error-converting-project-to-config-as-code/28337/4

**Comment by dan-close** [comment]
Another customer report: https://octopus.zendesk.com/agent/tickets/87419

**Comment by dan-close** [comment]
Another customer report: https://help.octopus.com/t/error-after-switch-to-configure-as-code/28366

**Comment by dan-close** [comment]
Another customer report: [Internal ticket](https://octopus.zendesk.com/agent/tickets/113935)
