### ISSUE TITLE
Runbook run to many machines exceeds SQL parameter limit

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7556]
### Team

- [X] I've assigned a team label to this issue

### Severity

Encountered internally

### Version

2022.2

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When running a runbook against 5000 tentacles, I hit a sql issue when finishing up the runbook completion about too many parameters, and sql server only supports 2100 parameters.

### Reproduction

Run a runbook on > 2100 machines

### Error and Stacktrace

```shell
Error while executing SQL command in transaction 'RunbookRunTaskController|ServerTasks-10086-5bfaa565-b780-4459-ace5-d4cccdd6be39|T4785': The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
The command being executed was:
UPDATE [dbo].[RunbookRun]  SET [Name] = @Name, [Created] = @Created, [EnvironmentId] = @EnvironmentId, [ProjectId] = @ProjectId, [RunbookId] = @RunbookId, [RunbookSnapshotId] = @RunbookSnapshotId, [TaskId] = @TaskId, [TenantId] = @TenantId, [DeployedBy] = @DeployedBy, [IsPublished] = @IsPublished, [SpaceId] = @SpaceId, [JSON] = @JSON WHERE [Id] = @Id

DECLARE @references as TABLE (Reference nvarchar(400), ReferenceTable nvarchar(400))

DELETE FROM @references

INSERT INTO @references VALUES (@relateddocument_0, 'Machine'), ...

System.Exception
   at Nevermore.CommandExecutor.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at Nevermore.Advanced.ReadTransaction.ExecuteNonQueryAsync(PreparedCommand preparedCommand, CancellationToken cancellationToken)
   at Nevermore.Advanced.WriteTransaction.ExecuteDataModificationAsync(PreparedCommand command, CancellationToken cancellationToken)
   at Nevermore.Advanced.WriteTransaction.ExecuteSingleDataModificationAsync(PreparedCommand command, CancellationToken cancellationToken)
   at Nevermore.Advanced.WriteTransaction.UpdateAsync[TDocument](TDocument document, UpdateOptions options, CancellationToken cancellationToken)
   at Octopus.Core.RelationalStorage.RawRelationalTransaction.Update[TKey](IId`1 document, CancellationToken cancellationToken, UpdateOptions options) in RawRelationalTransaction.cs:line 257
   at Octopus.Server.Web.Infrastructure.OctopusQueryExecutor.Update[TKey](IId`1 instance, CancellationToken cancellationToken, UpdateOptions options) in OctopusQueryExecutor.cs:line 449
   at Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathQueryExecutorDecorator.Update[TKey](IId`1 document, CancellationToken cancellationToken, UpdateOptions options) in ProjectPathQueryExecutorDecorator.cs:line 270
   at Octopus.Server.Orchestration.ServerTasks.Deploy.RunbookRunPlanService.SaveStateContainer(RunbookRun execution, CancellationToken cancellationToken) in RunbookRunPlanService.cs:line 98
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionPlanService`3.Cleanup(TExecutionPlan plan, CancellationToken cancellationToken) in ExecutionPlanService.cs:line 118
   at Octopus.Server.Orchestration.ServerTasks.Deploy.RunbookRunTaskController.<>c__DisplayClass5_0.<CleanupPlan in RunbookRunTaskController.cs:line 63
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass3_0`1.<Execute in UnitOfWorkExecutor.cs:line 87
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 75
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 75
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T](Func`3 action, CancellationToken cancellationToken, String name) in UnitOfWorkExecutor.cs:line 90
   at Octopus.Server.Orchestration.ServerTasks.Deploy.RunbookRunTaskController.CleanupPlan(RunbookRunPlan plan, CancellationToken cancellationToken) in RunbookRunTaskController.cs:line 60
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ExecutionTaskController`3.ExecuteBase(CancellationToken cancellationToken) in ExecutionTaskController.cs:line 122
   at Octopus.Server.Orchestration.ServerTasks.Deploy.RunbookRunTaskController.Execute(CancellationToken cancellationToken) in RunbookRunTaskController.cs:line 55
   at Octopus.Server.Orchestration.ServerTasks.RunningTask.<>c__DisplayClass31_1.<WorkerTask in RunningTask.cs:line 188
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 75
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in UnitOfWorkExtensionMethods.cs:line 75
   at Octopus.Server.Orchestration.ServerTasks.RunningTask.WorkerTask(CancellationToken cancellationToken) in RunningTask.cs:line 221

--Inner Exception--
SQL Error 8003 - The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
Microsoft.Data.SqlClient.SqlException
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at Nevermore.Transient.DbCommandExtensions.<>c__DisplayClass1_0.<ExecuteNonQueryWithRetryAsync
   at Nevermore.Transient.DbCommandExtensions.<>c__DisplayClass1_0.<ExecuteNonQueryWithRetryAsync
   at Nevermore.CommandExecutor.ExecuteNonQueryAsync(CancellationToken cancellationToken)
```

**Comment by octokhor** [comment]
Only found internally. If more customers run runbooks against > 2100 machines, we'll take a look at it again.
