### ISSUE TITLE
Package Selection Inconsistent on Create Release when Variables are used for Version

### ISSUE THREAD

**Issue by briggs-octo** [OctopusDeploy/Issues#7566]
### Team

- [X] I've assigned a team label to this issue

### Severity

1+, Workaround available

### Version

2022.2.4850

### Latest Version

I could not reproduce the problem

### What happened?

Using a variable (scoped to specific environments) to dynamically select a package from the built-in feed (in this case PackageType, with values of Debug and Release): 

![Screenshot from 2022-05-24 13-20-26](https://user-images.githubusercontent.com/104870596/170536851-97f9ca32-c5ed-4442-994a-65b25544a084.png)

When creating a release and not specifying a specific package version only the latest in feed shows up and is able to be used to create a release. When creating a release using version numbers below 1.0.0 without a suffix the feed is blank and an error is thrown:

![Screenshot from 2022-05-24 13-21-07](https://user-images.githubusercontent.com/104870596/170538350-f0461cbb-fe99-46de-b4b4-fbd6b83d2393.png)

![Release 0 1 0 - package 0 1 0](https://user-images.githubusercontent.com/104870596/170537770-93f5dc99-5fb1-4c70-ba6f-240f6aa3fa57.png)

The expectation would be that I would be able to select the specific package version when creating a release and this would dynamically pull from the built-in feed:

![package 0 1 0 (1)](https://user-images.githubusercontent.com/104870596/170538102-0ec7c421-a501-44b6-a353-bee99bdeed66.png)

### Reproduction

Unable to reproduce, but viewed on customer instance.

### Error and Stacktrace

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Core.Features.Projects.Releases.ReleaseNotesEvaluator.BuildReleaseNotes(IOctopusQueryExecutor queryExecutor, Release release, VariableCollection variables) in ./source/Octopus.Core/Features/Projects/Releases/ReleaseNotesEvaluator.cs:line 23
   at Octopus.Core.Features.Projects.Releases.EvaluateVariablesInReleaseNotesRule.Apply(Release model, IOctopusQueryExecutor queryExecutor, VariableCollection releaseVariables, IReleaseNotesEvaluator releaseNotesEvaluator) in ./source/Octopus.Core/Features/Projects/Releases/EvaluateVariablesInReleaseNotesRule.cs:line 15
   at Octopus.Core.Features.Projects.Releases.CreateReleaseCommandHandler.Handle(CreateReleaseCommand command, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/Projects/Releases/CreateReleaseCommandHandler.cs:line 145
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 29
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 32
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 45
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 35
   at Octopus.Server.Web.Controllers.Releases.CreateReleaseController.Create(ReleaseResource resource, Nullable`1 ignoreChannelRules, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/Releases/CreateReleaseController.cs:line 38
   at lambda_method11598938(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in ./source/Octopus.Server/Web/Infrastructure/Authentication/AuthorizationMiddlewareResultHandler.cs:line 52
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 53
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 49
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 61
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 67
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 76
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 96
```

### More Information

[Internal Zendesk :ticket: ](https://octopus.zendesk.com/agent/tickets/89623)
[Internal Slack :thread: ](https://octopusdeploy.slack.com/archives/C01HZFJRYSH/p1653432067572979)

### Workaround

Able to work around this by incrementing the major version number to > 0 (i.e. 1.0.0 (working) vs. 0.1.0 (non-working)).

Alternatively, can also temporarily duplicate the impacted step and specify the package you want to deploy manually within this step.

**Comment by gupta-kartik** [comment]
Build information had comments set to null which was throwing this error. No bug for now.
