### ISSUE TITLE
Octopus accepts null in BuildInformation.Commits[n].Comment, surfacing a NullReferenceException when creating a Release

### ISSUE THREAD

**Issue by rosslovas** [OctopusDeploy/Issues#7583]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocked one customer, they can work around it by not sending the null

### Version

Earliest tried was 2022.2.4850

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Build information can be sent to Octopus (e.g. by the `octo` CLI tool) that includes a `null` commit comment. It appears like this in the UI:

![image](https://user-images.githubusercontent.com/6970423/171753936-d8ab3c4b-1663-406c-b71d-47e593b0f1ab.png)

After doing this, attempting to create a release for the package associated with this build info surfaces an `Object reference not set to an instance of an object.` exception:

![image](https://user-images.githubusercontent.com/6970423/171754225-ee483c41-f3be-4dec-96c7-2d1f291ab6a6.png)

(there may be other places errors surface as a result of this too that have not yet been discovered)

### Reproduction

1. Upload a package
2. Create an erroneous `buildInfo.json`:
```
{
  "BuildEnvironment":"BitBucket",
  "Branch":"main",
  "BuildNumber":"288",
  "BuildUrl":"https://bitbucket.org/octopussamples/petclinic/addon/pipelines/home#!/results/288",
  "VcsType":"Git",
  "VcsRoot":"http://bitbucket.org/octopussamples/petclinic",
  "VcsCommitNumber":"314cf2c3ee916c92a384c2796a6abe332d678e4f",
  "Commits":[
      {
         "Id":"314cf2c3ee916c92a384c2796a6abe332d678e4f",
         "Comment": null
      }
   ]
}
```
3. Attach this information to the package you uploaded in step 1 via the `octo` CLI tool, for example:
`octo build-information --package-id="PetClinic.web" --version="1.0.200803.1002" --file="buildInfo.json" --server="http://samples.octopus.app" --apiKey="API-MyKey" --space="Target - Wildfly"`
4. Create a project
5. Attempt to create a release associated with the package you uploaded in step 1
6. Experience the error when hitting _Save_ on the _Create Release_ page.

### Error and Stacktrace

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Core.Features.Projects.Releases.ReleaseNotesEvaluator.BuildReleaseNotes(IOctopusQueryExecutor queryExecutor, Release release, VariableCollection variables) in ./source/Octopus.Core/Features/Projects/Releases/ReleaseNotesEvaluator.cs:line 23
   at Octopus.Core.Features.Projects.Releases.EvaluateVariablesInReleaseNotesRule.Apply(Release model, IOctopusQueryExecutor queryExecutor, VariableCollection releaseVariables, IReleaseNotesEvaluator releaseNotesEvaluator) in ./source/Octopus.Core/Features/Projects/Releases/EvaluateVariablesInReleaseNotesRule.cs:line 15
   at Octopus.Core.Features.Projects.Releases.CreateReleaseCommandHandler.Handle(CreateReleaseCommand command, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/Projects/Releases/CreateReleaseCommandHandler.cs:line 145
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 29
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 32
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 45
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 35
   at Octopus.Server.Web.Controllers.Releases.CreateReleaseController.Create(ReleaseResource resource, Nullable`1 ignoreChannelRules, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/Releases/CreateReleaseController.cs:line 38
   at lambda_method11598938(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in ./source/Octopus.Server/Web/Infrastructure/Authentication/AuthorizationMiddlewareResultHandler.cs:line 52
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 53
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 49
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 61
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 67
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 76
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 96
```

### More Information

This was the root cause of #7566.

**Comment by rosslovas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Either build information should disallow submitting null commit message, or null commit message should be accepted but not surface NullReferenceExceptions](https://trello.com/c/SncVgnSv/529-either-build-information-should-disallow-submitting-null-commit-message-or-null-commit-message-should-be-accepted-but-not-surfac)
