### ISSUE TITLE
Deploying multiple Azure Cloud Service packages in parallel part of path not found exception thrown

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#7631]
### Team

- [X] I've assigned a team label to this issue

### Severity

No, this is Intermittently affecting customers and can be mitigated by swapping to synchronous deployments.

### Version

2022.3.1455

### Latest Version

I could not reproduce the problem

### What happened?

The issue happens when multiple deployments are trying to re-pack the packages at the same time, some pack ok but some fail, this is the case if deploying to different targets too, most users had success on retry so it seems like the repackaging tasks are interrupting each other.

### Reproduction

See Zendesk issue for details and customer instance - https://octopus.zendesk.com/agent/tickets/89706

Attempts to reproduce this in a cloud environment have been done here - https://deploy-fnm.testoctopus.app/app#/Spaces-1/projects/synchronous-async-steps/deployments/process

And test based reproduction attcan be found here - https://github.com/OctopusDeploy/Sashimi.AzureCloudService/tree/isaac/repackage-parallel-reproductionattempt where multiple instances of the same test were run across multiple ides in parallel. Neither of these reproduction attempts were able to cause the issue to occur.

### Error and Stacktrace

```shell
Could not find a part of the path 'qximmpm3.0qo'.
11:43:45   Error    |       System.IO.DirectoryNotFoundException
11:43:45   Error    |       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
11:43:45   Error    |       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
11:43:45   Error    |       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath)
11:43:45   Error    |       at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
11:43:45   Error    |       at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, ReliableIsolatedStorageFileFolder folder)
11:43:45   Error    |       at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
11:43:45   Error    |       at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
11:43:45   Error    |       at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
11:43:45   Error    |       at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOFileItemStream.Write(Byte[] buffer, Int32 offset, Int32 count)
11:43:45   Error    |       at System.IO.Compression.DeflateStream.WriteDeflaterOutput(Boolean isAsync)
11:43:45   Error    |       at System.IO.Compression.DeflateStream.PurgeBuffers(Boolean disposing)
11:43:45   Error    |       at System.IO.Compression.DeflateStream.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.Stream.Close()
11:43:45   Error    |       at MS.Internal.IO.Packaging.CompressStream.ChangeMode(Mode newMode)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOLocalFileBlock.FlushExposedStreams()
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOLocalFileBlock.UpdateReferences(Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOBlockManager.SaveContainer(Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOBlockManager.SaveStream(ZipIOLocalFileBlock blockRequestingFlush, Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.Stream.Close()
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.AddContent(Package package, PackageDefinition manifest, Uri partUri, String file)
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.AddLocalContentParts(Package package, PackageDefinition manifest, LayoutDefinition layout, String baseDirectory, String relativeDirectory)
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.AddLocalContentParts(Package package, PackageDefinition manifest, LayoutDefinition layout, String baseDirectory, String relativeDirectory)
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.AddLocalContent(Package package, PackageDefinition manifest, String workingDirectory)
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.Execute(RunningDeployment context)
11:43:45   Error    |       Running rollback behaviours...
11:43:45   Error    |       Can not access a closed Stream.
11:43:45   Error    |       System.ObjectDisposedException
11:43:45   Error    |       at System.IO.Compression.DeflateStream.EnsureNotDisposed()
11:43:45   Error    |       at MS.Internal.IO.Packaging.CompressStream.Flush()
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOLocalFileBlock.FlushExposedStreams()
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOLocalFileBlock.UpdateReferences(Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOBlockManager.SaveContainer(Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOBlockManager.SaveStream(ZipIOLocalFileBlock blockRequestingFlush, Boolean closingFlag)
11:43:45   Error    |       at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.Stream.Close()
11:43:45   Error    |       at System.IO.StreamWriter.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.StreamWriter.Close()
11:43:45   Error    |       at System.Xml.XmlTextWriter.Close()
11:43:45   Error    |       at System.Xml.XmlWriter.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.Packaging.ZipPackage.ContentTypeHelper.SaveToFile()
11:43:45   Error    |       at System.IO.Packaging.ZipPackage.Dispose(Boolean disposing)
11:43:45   Error    |       at System.IO.Packaging.Package.System.IDisposable.Dispose()
11:43:45   Error    |       at Calamari.AzureCloudService.RePackageCloudServiceBehaviour.Execute(RunningDeployment context)
11:43:45   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<ExecuteBehaviour>d__16.MoveNext()
11:43:45   Error    |       --- End of stack trace from previous location where exception was thrown ---
11:43:45   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:43:45   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext()
11:43:45   Error    |       --- End of stack trace from previous location where exception was thrown ---
11:43:45   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:43:45   Error    |       at Calamari.Common.Plumbing.Pipeline.PipelineCommand.<Execute>d__13.MoveNext()
11:43:45   Error    |       --- End of stack trace from previous location where exception was thrown ---
11:43:45   Error    |       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:43:45   Error    |       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:43:45   Error    |       at Calamari.Common.CalamariFlavourProgramAsync.<Run>d__4.MoveNext()
11:43:57   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Tentacle\Work\20220527112712-95127-5383 exited with code 100
```

### Workaround

Run steps synchronously -
![image](https://user-images.githubusercontent.com/101079287/175842591-63bf0304-d0f5-4f46-a545-1a30af1e03d6.png)

**Comment by zentron** [comment]
Azure Cloud Services [are now deprecated](https://octopus.com/docs/deprecations#azure-cloud-services-classic)
