### ISSUE TITLE
Docker Images from Harbor Feed showing 'Unable to Login to Docker Registry' when deploying a release.

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7646]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking customers that use Harbor Feeds from deploying docker images.

### Version

2022.2.6764

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When deploying a docker image using a 'Run a Docker Container' step it errors out with login failures. 

![image](https://user-images.githubusercontent.com/92790462/176896667-9b6a5566-2bb1-45aa-b8ba-8120bc0d858e.png)

The feed tests successfully in external feeds and will pull a package:

![image](https://user-images.githubusercontent.com/92790462/176896994-83978447-e9fb-4b8b-b2ab-1265a72623ab.png)

One thing I did notice was if you don't search for the full package you get this error:

![image](https://user-images.githubusercontent.com/92790462/176898284-ea1628fa-bc7e-4b84-8408-60f8630d0597.png)

The step also shows the same error if you just search for a partial package name. I captured the error in a HAR File placed [here](https://octofront.com/Support/Files) (Internal Link - Under clare.martin@octopus.com and name Harbor)

It does work if you type the full package name though:

![image](https://user-images.githubusercontent.com/92790462/176899178-95d71e00-d684-46ab-814d-fd98d72713ca.png)

[Two customers ](https://help.octopus.com/t/failed-to-download-package-from-external-feed/28081/8)(same forum post) have reported the same issue (slightly different initial error messages but both login failures and both feeds are testing fine and finding packages). 

### Reproduction

- Create a harbor feed - I used their demo one which does work - Documentation here - https://goharbor.io/docs/2.5.0/install-config/demo-server/
- Add a docker image using the guide above to the feed:

![image](https://user-images.githubusercontent.com/92790462/176900026-b83d45ee-fe57-432d-9c32-1fedc5dfa055.png)

- Setup an external feed in Octopus and point it to the demo server:

![image](https://user-images.githubusercontent.com/92790462/176900306-e46cd61a-c571-4b73-9d22-1823bb78cdf8.png)

- Create a project and add a 'Run a Docker Container' step, use the feed we just setup.
- To see the auth error type a partial package name. Type the full package name and you will see it picks up the package.
- Create a release and deploy it to a target that has docker installed.
- Watch the login error appear and an error stating Octopus cant pull the docker image.

### Error and Stacktrace

```shell
Task ID:        ServerTasks-1631
Related IDs:    Deployments-67, Channels-184, Releases-65, Projects-184, Spaces-1, Environments-1
Task status:    Failed
Task queued:    Friday, 01 July 2022 4:46:27 AM -07:00
Task started:   Friday, 01 July 2022 4:46:27 AM -07:00
Task completed: Friday, 01 July 2022 4:47:13 AM -07:00
Task duration:  46 seconds
Server version: 2022.2.6764
Server node:    OCTODC

                    | == Failed: Deploy Docker release 0.0.8 to Development ==
04:46:27   Verbose  |   Guided failure is not enabled for this task
04:47:13   Fatal    |   The deployment failed because one or more steps failed. Please see the deployment log for details.
                    | 
                    |   == Failed: Acquire packages ==
04:46:27   Info     |     Acquiring packages
04:46:27   Info     |     Making a list of packages to acquire
04:46:27   Verbose  |     Package claretest/dockerfile vlatest is required by action 'Run a Docker Container'
04:46:27   Verbose  |     No packages are required on the Octopus Server
04:46:27   Verbose  |     Delta compression is enabled for package transfers from the Octopus Server to deployment targets
04:46:27   Verbose  |     Machine Main Computer Tentacle still needs packages claretest/dockerfile vlatest for action ('Run a Docker Container')
04:47:13   Fatal    |     The step failed: Activity failed with error 'The remote script failed with exit code 1'.
04:47:13   Verbose  |     Acquire Packages completed
                    |   
                    |     Failed: Main Computer Tentacle
04:46:28   Verbose  |       Acquiring isolation mutex RunningScript with NoIsolation in ServerTasks-1631
04:46:28   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:28   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:28   Verbose  |       No user context provided. Running as current user.
04:46:28   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114627-1631-5' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:28   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114627-1631-5 exited with code 0
04:46:28   Verbose  |       Using Calamari.win-x64 22.7.3
04:46:28   Verbose  |       Acquiring isolation mutex PackageRetention with FullIsolation in ServerTasks-1631
04:46:28   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:28   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:28   Verbose  |       No user context provided. Running as current user.
04:46:29   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114628-1631-6' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:29   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114628-1631-6 exited with code 1
04:46:29   Verbose  |       Using Calamari.win-x64 22.7.3
04:46:29   Info     |       The version 22.7.3 of the Calamari.win-x64 tool has not been extracted, it will be extracted automatically.
04:46:29   Verbose  |       Acquiring isolation mutex Calamari.win-x64 with NoIsolation in ServerTasks-1631
04:46:29   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:29   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:29   Verbose  |       No user context provided. Running as current user.
04:46:29   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114629-1631-7' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:29   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114629-1631-7 exited with code 0
04:46:30   Verbose  |       Acquiring isolation mutex Calamari.win-x64 with FullIsolation in ServerTasks-1631
04:46:30   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:30   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:30   Verbose  |       No user context provided. Running as current user.
04:46:30   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114630-1631-8' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:31   Verbose  |       Checking for C:\Octopus\Tools\Calamari.win-x64\22.7.3\Success.txt
04:46:31   Verbose  |       Package: C:\Octopus\Work\20220701114630-1631-8\Calamari.win-x64.22.7.3.nupkg
04:46:34   Verbose  |       Destination: C:\Octopus\Tools\Calamari.win-x64\22.7.3
04:46:34   Verbose  |       401 files extracted
04:46:34   Verbose  |       Calamari.win-x64 22.7.3 extracted to C:\Octopus\Tools\Calamari.win-x64\22.7.3
04:46:35   Verbose  |       Removing write permissions on C:\Octopus\Tools\Calamari.win-x64\22.7.3 for BUILTIN\Users
04:46:35   Verbose  |       Cleaning up old Calamari.win-x64 versions...
04:46:35   Verbose  |       Keeping only Calamari.win-x64 version 22.7.3...
04:46:35   Verbose  |       Found no old versions of Calamari.win-x64 to delete...
04:46:35   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114630-1631-8 exited with code 0
04:46:35   Info     |       Version 22.7.3 of the Calamari.win-x64 tool has been extracted successfully
04:46:35   Verbose  |       Acquiring isolation mutex PackageRetention with FullIsolation in ServerTasks-1631
04:46:35   Verbose  |       Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:35   Verbose  |       Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:35   Verbose  |       No user context provided. Running as current user.
04:46:38   Verbose  |       Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114635-1631-9' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:38   Verbose  |       Calamari Version: 22.7.3
04:46:38   Verbose  |       Environment Information:
04:46:38   Verbose  |       OperatingSystem: Microsoft Windows NT 10.0.22000.0
04:46:38   Verbose  |       OsBitVersion: x64
04:46:38   Verbose  |       Is64BitProcess: True
04:46:38   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
04:46:38   Verbose  |       MachineName: CLARE-WORK-LAPT
04:46:38   Verbose  |       ProcessorCount: 16
04:46:38   Verbose  |       CurrentDirectory: C:\Octopus\Work\20220701114635-1631-9
04:46:38   Verbose  |       TempDirectory: C:\WINDOWS\TEMP\
04:46:38   Verbose  |       HostProcess: Calamari (7356)
04:46:38   Info     |       Unable to determine disk space. Skipping free space package retention.
04:46:38   Verbose  |       Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114635-1631-9 exited with code 0
04:46:38   Verbose  |       Exit code: 0
04:47:13   Fatal    |       The remote script failed with exit code 1
04:47:13   Verbose  |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.SuccessArbitrator.ThrowIfNotSuccessful(IActionHandlerResult result) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/SuccessArbitrator.cs:line 22
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.AdHocActionDispatcher.Dispatch(Machine machine, ActionHandlerInvocation actionHandler, ITaskLog taskLog, VariableCollection variables) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/AdHocActionDispatcher.cs:line 61
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.PackageAcquisitionExecutionHandlers.Invoke(ActionHandlerInvocation invocation, ITaskLog taskLog) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs:line 116
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.PackageAcquisitionExecutionHandlers.DownloadPackage(String packageId, IVersion version, IFeed feed, ITaskLog taskLog, PackageCachePolicy packageCachePolicy) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs:line 71
                    |       at Octopus.Server.Orchestration.Targets.Common.PackageStagingMediator.DownloadPackageOnAgent(PackageIdentity packageIdentity, IDeploymentPackageDownloader deploymentPackageDownloader, PackageAcquisitionExecutionHandlers execs, ITaskLog taskLog) in ./source/Octopus.Server/Orchestration/Targets/Common/PackageStagingMediator.cs:line 59
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.StagePackage(PackageAcquisitionExecutionHandlers packageAcquisitionHandlers, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 152
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.Acquire(AcquiredPackageMap acquiredPackageMap, ITaskContext taskContext, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 104
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass5_3`3.<Execute>b__5() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 78
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in ./source/Octopus.Server/Infrastructure/EitherAsyncOrSync.cs:line 38
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Guidance.cs:line 136
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(EitherAsyncOrSync callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Maybe`1 callbackOnExclude, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Guidance.cs:line 76
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass5_3`3.<<Execute>b__4>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 77
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.TransientErrorDetectionExecutor.Execute(Func`2 action, ExecutionPlan plan, ITaskLog taskLog, CancellationToken cancellationToken, DeploymentTarget deploymentTarget) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/TransientErrorDetectionExecutor.cs:line 33
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass5_2`3.<<Execute>b__3>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 74
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass5_0`3.<<Execute>b__0>d.MoveNext() in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 125
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 75
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 75
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,T2,T3](Func`5 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 119
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass5_1`3.<<Execute>b__2>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 68
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.ParallelWorkOrderAsync`1.<>c__DisplayClass8_1.<<Execute>b__4>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/ParallelWorkOrderAsync.cs:line 62
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Infrastructure.EitherAsyncOrSync.Execute(CancellationToken cancellationToken) in ./source/Octopus.Server/Infrastructure/EitherAsyncOrSync.cs:line 38
                    |       at Octopus.Server.Orchestration.ServerTasks.OctoThreadClosureAsync`1.Execute(CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/OctoThreadClosureAsync.cs:line 63
                    |     
                    |       Failed: Download package claretest/dockerfile vlatest directly from Docker Registry v2 'Harbor Test' at https://demo.goharbor.io/ under claretest
04:46:38   Verbose  |         Acquiring isolation mutex RunningScript with NoIsolation in ServerTasks-1631
04:46:38   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:38   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:38   Verbose  |         No user context provided. Running as current user.
04:46:39   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114638-1631-10' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:39   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114638-1631-10 exited with code 0
04:46:39   Verbose  |         Using Calamari.win-x64 22.7.3
04:46:39   Verbose  |         Acquiring isolation mutex RunningScript with NoIsolation in ServerTasks-1631
04:46:39   Verbose  |         Executable directory is C:\WINDOWS\system32\WindowsPowershell\v1.0
04:46:39   Verbose  |         Executable name or full path: C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe
04:46:39   Verbose  |         No user context provided. Running as current user.
04:46:40   Verbose  |         Starting C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in working directory 'C:\Octopus\Work\20220701114639-1631-11' using 'OEM United States' encoding running as 'NT AUTHORITY\SYSTEM' with the same environment variables as the launching process
04:46:40   Verbose  |         Calamari Version: 22.7.3
04:46:40   Verbose  |         Environment Information:
04:46:40   Verbose  |         OperatingSystem: Microsoft Windows NT 10.0.22000.0
04:46:40   Verbose  |         OsBitVersion: x64
04:46:40   Verbose  |         Is64BitProcess: True
04:46:40   Verbose  |         CurrentUser: NT AUTHORITY\SYSTEM
04:46:40   Verbose  |         MachineName: CLARE-WORK-LAPT
04:46:40   Verbose  |         ProcessorCount: 16
04:46:40   Verbose  |         CurrentDirectory: C:\Octopus\Work\20220701114639-1631-11
04:46:40   Verbose  |         TempDirectory: C:\WINDOWS\TEMP\
04:46:40   Verbose  |         HostProcess: Calamari (10868)
04:46:40   Verbose  |         Feed type provided `Docker` using DockerImagePackageDownloader
04:46:40   Verbose  |         Setting Proxy Environment Variables
04:46:40   Verbose  |         Name                           Value
04:46:40   Verbose  |         ----                           -----
04:46:40   Verbose  |         PSVersion                      5.1.22000.653
04:46:40   Verbose  |         PSEdition                      Desktop
04:46:40   Verbose  |         PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
04:46:40   Verbose  |         BuildVersion                   10.0.22000.653
04:46:40   Verbose  |         CLRVersion                     4.0.30319.42000
04:46:40   Verbose  |         WSManStackVersion              3.0
04:46:40   Verbose  |         PSRemotingProtocolVersion      2.3
04:46:40   Verbose  |         SerializationVersion           1.1.0.1
04:46:40   Verbose  |         PowerShell Environment Information:
04:46:40   Verbose  |         OperatingSystem: Microsoft Windows NT 10.0.22000.0
04:46:40   Verbose  |         OsBitVersion: x64
04:46:40   Verbose  |         Is64BitProcess: True
04:46:40   Verbose  |         CurrentUser: NT AUTHORITY\SYSTEM
04:46:40   Verbose  |         MachineName: CLARE-WORK-LAPT
04:46:40   Verbose  |         ProcessorCount: 16
04:46:40   Verbose  |         CurrentDirectory: C:\Octopus\Work\20220701114639-1631-11
04:46:40   Verbose  |         CurrentLocation: C:\Octopus\Work\20220701114639-1631-11
04:46:40   Verbose  |         TempDirectory: C:\WINDOWS\TEMP\
04:46:41   Verbose  |         HostProcess: powershell (12112)
04:46:41   Verbose  |         TotalPhysicalMemory: 33267532 KB
04:46:41   Verbose  |         AvailablePhysicalMemory: 3652752 KB
04:46:41   Verbose  |         Docker version 20.10.12, build e91ed57
04:47:13   Info     |         Error response from daemon: Get "https://claretest/v2/": dial tcp: lookup claretest on 192.168.65.5:53: read udp 192.168.65.4:56844->192.168.65.5:53: i/o timeout
04:47:13   Error    |         NotSpecified: Login Failed
04:47:13   Error    |         At C:\Octopus\Work\20220701114639-1631-11\Bootstrap.Octopus.DockerLogin.ps1:902 char:2
04:47:13   Error    |         +     . '.\Octopus.DockerLogin.ps1'
04:47:13   Error    |         +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
04:47:13   Error    |         at <ScriptBlock>, C:\Octopus\Work\20220701114639-1631-11\Octopus.DockerLogin.ps1: line 48
04:47:13   Error    |         at <ScriptBlock>, C:\Octopus\Work\20220701114639-1631-11\Bootstrap.Octopus.DockerLogin.ps1: line 902
04:47:13   Error    |         at <ScriptBlock>, <No file>: line 1
04:47:13   Error    |         at <ScriptBlock>, <No file>: line 1
04:47:13   Error    |         Failed to download package claretest/dockerfile vlatest from feed: 'https://claretest'
04:47:13   Error    |         Unable to log in Docker registry
04:47:13   Verbose  |         Process C:\WINDOWS\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20220701114639-1631-11 exited with code 1
04:47:13   Verbose  |         Exit code: 1
                    |       
                    |   == Skipped: Step 1: Run a Docker Container ==
04:47:13   Info     |     Step "Run a Docker Container" runs only when all previous steps succeeded; skipping
                    |   
                    |   == Success: Release packages ==
04:47:13   Info     |     There are no packages to be released.
04:47:13   Verbose  |     Release Packages completed
                    |
```

### More Information

Errrors both users are getting are slightly different - 

```
Error response from daemon: Get [https://registry.harbor.com/v2/: 2](https://registry.harbor.com/v2/:) unauthorized: authentication required
June 22nd 2022 11:50:09Info
Login Failed
June 22nd 2022 11:50:09Error
Failed to download package stg/test_package vstaging from feed: ‘[https://registry.harbor.com/ 1](https://registry.harbor.com/)’
June 22nd 2022 11:50:09Error
Unable to pull Docker image

```

One user suggests - It seems like the credentials are not getting passed over to the tentacle. I have even tried manually using “docker login” on both base and root user to have the docker daemon already logged into the registry with no luck.

From what I can see both users have IP addresses for their feeds - Harbor is only On-Prem, they do not do a cloud version, so the difference in error messages to mine might just be because of the URL differences (my test was done on cloud, theirs on prem).

### Workaround

None, login details are correct as external feed authenticates and pulls the packages on a test.

**Comment by AndreyByhalenko** [comment]
Hello,
Do you have any estimated for the solution of this issue?
Thanks

**Comment by michelle-luana** [comment]
Hi Andrey
At this stage this isn't actively being worked on as we haven't had reports from other customers being impacted. We'll continue to monitor and if more customers are impacted by this we will reevaluate.
Thanks
Michelle

**Comment by sluebbert** [comment]
We had the same issue. We were using robot accounts in Harbor to use in Octopus Deploy. Harbor defaults to the robot username prefix of `robot$`. While this works in the Octopus web app just fine, it does not work at the time of deploying a release.

Harbor logs at that moment showed:
`failed to authenticate user:robot, error:Failed to authenticate user, due to error 'Not found an entry'`

Since the user we originally used for Octopus was `robot$octopusdeploy`, and the user logged by Harbor was just `robot`, we assumed Octopus wasn't escaping `$` very well or just didn't support that char in some way for Docker usernames.

Changing the robot name prefix in Harbor to something like `robot_` instead resolves the issue. Just be careful as that seems to immediately rename all of your robot account names in Harbor when you change it.

The UI searching auth errors you are referring to as well probably relates to how Harbor robot accounts do not have permission to query the registry catalog unless set as admin accounts or unless you set it through the Harbor API at the time of writing this.
https://github.com/goharbor/harbor/issues/6784
https://github.com/goharbor/community/pull/223

Ignore all of this if you aren't using a robot account :)
