### ISSUE TITLE
Scheduled triggers fail to execute for Config as Code projects with outdated OCL

### ISSUE THREAD

**Issue by YuKitsune** [OctopusDeploy/Issues#7716]
### Team

- [X] I've assigned a team label to this issue

### Severity

Only report so far.

### Version

Likely introduced in 2022.3.4517

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a "Deploy Release" scheduled trigger executes against a config as code project with outdated OCL, the following error may appear in the task logs:

```
A scheduled trigger failed while attempting to create and deploy a release Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.ApplyRedundantActionNameIfSolitary(OclConversionContext context, IEnumerable`1 elements, Object _) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentStepOclConverter.cs:line 162
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentStepOclConverter.cs:line 74
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.SetProperties(OclConversionContext context, Type type, IEnumerable`1 elements, Object target)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentStepOclConverter.cs:line 61
   at Octopus.Ocl.OclConversionContext.FromElement(Type type, IOclElement element, Object getCurrentValue)
   at Octopus.Ocl.Converters.DefaultCollectionOclConverter.<>c__DisplayClass3_0.<FromElement>b__0(IOclElement e)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Octopus.Ocl.Converters.DefaultCollectionOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Ocl.OclConversionContext.FromElement(Type type, IOclElement element, Object getCurrentValue)
   at Octopus.Ocl.Converters.OclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.SetProperties(OclConversionContext context, Type type, IEnumerable`1 elements, Object target)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Ocl.OclConversionContext.FromElement(Type type, IOclElement element, Object getCurrentValue)
   at Octopus.Ocl.OclSerializer.Deserialize(OclDocument document, Type type)
   at Octopus.Ocl.OclSerializer.Deserialize(String ocl, Type type)
   at Octopus.Ocl.OclSerializer.Deserialize[T](String ocl)
   at Octopus.Core.Serialization.Ocl.Transformation.Transforms.DeploymentProcessOclTransform.TransformFromOcl(String ocl, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/Transformation/Transforms/DeploymentProcessOclTransform.cs:line 66
   at Octopus.Core.Serialization.Ocl.Transformation.Transforms.Decorators.IdToSlugOclTransformDecorator`1.TransformFromOcl(String ocl, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/Transformation/Transforms/Decorators/IdToSlugOclTransformDecorator.cs:line 33
   at Octopus.Core.Serialization.Ocl.OclHandler.FromOcl[T](String ocl, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Serialization/Ocl/OclHandler.cs:line 56
   at Octopus.Core.Git.Transactions.GitOclDocumentService.GetDocumentOrNull[T](String fileName, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Git/Transactions/GitOclDocumentService.cs:line 46
   at Octopus.Core.Git.Transactions.GitOclDocumentService.GetDocument[T](String fileName, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Git/Transactions/GitOclDocumentService.cs:line 57
   at Octopus.Core.Git.Transactions.GitDocumentTransaction.<>c__DisplayClass16_0`1.<<GetDocument>b__0>d.MoveNext() in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 64
--- End of stack trace from previous location ---
   at Octopus.Core.Git.Transactions.GitDocumentTransaction.MigrateBeforeExecute[T](Func`1 innerOperation, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 210
   at Octopus.Core.Git.Transactions.GitDocumentTransaction.GetDocument[T](String fileName, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 63
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Octopus.Core.Extensions.TaskExtensionMethods.AsSync[T](Task`1 task) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Extensions/TaskExtensionMethods.cs:line 22
   at Octopus.Core.Persistence.Git.GitDocumentStore`2.GetOrNull(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/Git/GitDocumentStore.cs:line 159
   at Octopus.Core.Persistence.Git.GitDocumentStore`2.Get(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/Git/GitDocumentStore.cs:line 132
   at Octopus.Core.Persistence.Git.SlugDocumentStoreDecorator`2.Get(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/Git/SlugDocumentStoreDecorator.cs:line 54
   at Octopus.Core.Persistence.Database.ProjectPathDecorators.ProjectPathDocumentStoreDecorator`2.Get(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/Database/ProjectPathDecorators/ProjectPathDocumentStoreDecorator.cs:line 51
   at Octopus.Core.Persistence.EntityTracking.EntityTracker.GetOrTrack[TDocument,TKey](TKey id, Func`2 getDocument) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/EntityTracking/EntityTracker.cs:line 46
   at Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2.Get(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/EntityTracking/EntityTrackingDocumentStoreDecorator.cs:line 54
   at Octopus.Core.Persistence.Auditing.AuditingDocumentStoreDecorator`2.Get(TKey id) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Persistence/Auditing/AuditingDocumentStoreDecorator.cs:line 94
   at Octopus.Core.Features.DeploymentProcesses.CurrentDeploymentProcessDocumentStoreExtensionMethods.GetByProject(IDocumentStore`2 documentStore, Project project) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Core/Features/DeploymentProcesses/CurrentDeploymentProcessDocumentStoreExtensionMethods.cs:line 14
   at Octopus.Server.Communications.Packages.ReleaseCreation.ReleaseCreationFactory.FillAndCreateRelease(IOctopusQueryExecutor queryExecutor, Project project, Release release, IProjectScope projectScope, CancellationToken cancellationToken, IOctopusPrincipalInternal octopusPrincipal) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Server/Communications/Packages/ReleaseCreation/ReleaseCreationFactory.cs:line 63
   at Octopus.Server.Orchestration.ServerTasks.ProcessRecurringScheduledDeployments.ScheduledProjectTriggerProcessor.CreateRelease(Project project, DeploymentSettings settings, Channel channel, ProjectTrigger trigger, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Server/Orchestration/ServerTasks/ProcessRecurringScheduledDeployments/ScheduledProjectTriggerProcessor.cs:line 448
   at Octopus.Server.Orchestration.ServerTasks.ProcessRecurringScheduledDeployments.ScheduledProjectTriggerProcessor.DeployNewRelease(ProjectTrigger trigger, ITaskLog taskLog, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Server/Orchestration/ServerTasks/ProcessRecurringScheduledDeployments/ScheduledProjectTriggerProcessor.cs:line 327
   at Octopus.Server.Orchestration.ServerTasks.ProcessRecurringScheduledDeployments.ScheduledProjectTriggerProcessor.SafelyDeployNewRelease(ProjectTrigger trigger, ITaskLog taskLog, CancellationToken cancellationToken) in /Users/eoinmotherway/Developer/github.com/OctopusDeploy/OctopusDeploy/source/Octopus.Server/Orchestration/ServerTasks/ProcessRecurringScheduledDeployments/ScheduledProjectTriggerProcessor.cs:line 287
```

### Reproduction

1. Create a version controlled project
2. Add a step to the deployment process
3. Update the OCL to a schema version prior to version 4 (Before slugs were in OCL)
4. Create a scheduled trigger and set the action to `Deploy new release`
5. Wait for the trigger to execute
6. 💥

### Workaround

Upgrading the OCL can resolve the issue. this can be done by making a trivial change (E.g: Updating the notes) to the deployment process, or deployment settings via the UI, or the API.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7969 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7969 |
| 2022.4+ | _all releases_ |
