### ISSUE TITLE
Behavioural telemetry ingestion endpoint key not in dictionary error

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#7804]
### Team

- [X] I've assigned a team label to this issue

### Severity

Non blocking, although may result in no behavioural telemetry to be sent from UI

### Version

2022.3.7031-2022.4.1657

### Latest Version

The problem does not exist in the latest build

### What happened?

Users may experience errors in the console and in logs when behavioural telemetry is being sent to server. Once this happens, every action taken will end up with an error in the console consequently spamming the console/logs.

### Reproduction

Perform some actions with a version older than `2022.3.7031` but ensure server is not running so that behavioural telemetry is queued. Update server to a version prior to `2022.4.1657` but older or equal to `2022.3.7031` and perform any action that will send behavioural telemetry. In this particular scenario all telemetry ingestion will fail with a error message such as `The given key was not present in the dictionary`

### Error and Stacktrace

```shell
System.Collections.Generic.KeyNotFoundException: The given key 'a8c31069ec818e8506090f593e59dc2a1e13cc1d' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Octopus.Core.Features.Telemetry.BehaviouralTelemetry.Amplitude.AmplitudeEventBatchPayload.<>c__DisplayClass22_0.<UpdateUserIdForEvents>b__0(Object e) in ./source/Octopus.Core/Features/Telemetry/BehaviouralTelemetry/Amplitude/AmplitudeEventBatchPayload.cs:line 63
   at Octopus.Core.Features.Telemetry.BehaviouralTelemetry.Amplitude.AmplitudeEventBatchPayload.AugmentEventsWith(Action`1 propertySetter) in ./source/Octopus.Core/Features/Telemetry/BehaviouralTelemetry/Amplitude/AmplitudeEventBatchPayload.cs:line 78
   at Octopus.Core.Features.Telemetry.BehaviouralTelemetry.Amplitude.AmplitudeAnalyticsService.PostEventBatchForFrontend(AmplitudeEventBatchPayload eventBatch, CancellationToken cancellationToken, IPAddress forwardedForIpAddress) in ./source/Octopus.Core/Features/Telemetry/BehaviouralTelemetry/Amplitude/AmplitudeAnalyticsService.cs:line 91
   at Octopus.Core.Features.Telemetry.BehaviouralTelemetry.ProcessBehaviouralTelemetryBatchCommandHandler.Handle(ProcessBehaviouralTelemetryBatchCommand command, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/Telemetry/BehaviouralTelemetry/ProcessBehaviouralTelemetryBatchCommandHandler.cs:line 22
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 29
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 32
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 45
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Do[TCommand,TResponse](ICommand`2 command, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 33
   at Octopus.Server.Web.Controllers.Telemetry.ProcessBehaviouralTelemetryController.ProcessTelemetry(ProcessBehaviouralTelemetryBatchCommand processTelemetryBatchCommand, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/Telemetry/ProcessBehaviouralTelemetryController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 53
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 49
   at Octopus.Server.Web.Middleware.PrivateSpaceToggleMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/PrivateSpaceToggleMiddleware.cs:line 56
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 61
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 57
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 76
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 98
```

### Workaround

Clearing app data in the browser will clear out any captured telemetry and rectify the issue for the current active user session.

**Comment by shaunmarx** [comment]
Release Note: Fix issue where behavioural telemetry ingestion from the UI will cause key not present in dictionary errors

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.1657 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.1657 |
| 2023.1+ | _all releases_ |
