### ISSUE TITLE
Error: Can't map GitRefType.Unknown to RefTypes

### ISSUE THREAD

**Issue by FelixBrunet** [OctopusDeploy/Issues#7934]
Trying to change the branch of a trigger that is set to master

An unexpected error occurred in Octopus v2022.3.10828: "Error: Can't map GitRefType.Unknown to RefTypes"

consoleSink.ts:38 Error: Can't map GitRefType.Unknown to RefTypes
    at GitRefSelector.tsx:51:23
    at g (GitRefSelector.tsx:57:60)
    at Ki (react-dom.production.min.js:153:146)
    at wl (react-dom.production.min.js:261:496)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)

**Comment by FelixBrunet** [comment]
Duplicate as https://github.com/OctopusDeploy/Issues/issues/7774

**Comment by cailyoung** [comment]
Marking as 'not planned'.
