### ISSUE TITLE
Polling tentacle timeout / compression error

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#7956]
### Team

- [X] I've assigned a team label to this issue

### Severity

potentially blocking

### Version

n/a

### Latest Version

Not applicable

### What happened?

Polling tentacles can fail with a compression error or time out.

### Reproduction

We think this can be caused by heavy load or slow network.

### Error and Stacktrace

```shell
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal()
   at Newtonsoft.Json.Bson.BsonDataReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Halibut.Transport.Protocol.MessageSerializer.DeserializeMessage[T](JsonReader reader)
   at Halibut.Transport.Protocol.MessageSerializer.ReadCompressedMessageRewindable[T](Stream stream, IRewindableBuffer rewindable)
   at Halibut.Transport.Protocol.MessageSerializer.ReadMessage[T](Stream stream)
   at Halibut.Transport.Protocol.MessageExchangeStream.Receive[T]()
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ReceiveAndProcessRequest(IMessageExchangeStream stream, Func`2 incomingRequestProcessor)
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsSubscriber(Uri subscriptionId, Func`2 incomingRequestProcessor, Int32 maxAttempts)
   at Halibut.Transport.PollingClient.<ExecutePollingLoop>b__12_0(MessageExchangeProtocol protocol)
   at Halibut.Transport.SecureClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
2022-11-22 00:11:03.0089   8905      5 ERROR  https://demo.octopus.app:10943/    5  Halibut client exception: An error occurred when sending a request to 'https://demo.octopus.app:10943/', after the request began: The archive entry was compressed using an unsupported compression method. Retrying in 5.0 seconds
Halibut.HalibutClientException: An error occurred when sending a request to 'https://demo.octopus.app:10943/', after the request began: The archive entry was compressed using an unsupported compression method.
 ---> System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal()
   at Newtonsoft.Json.Bson.BsonDataReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Halibut.Transport.Protocol.MessageSerializer.DeserializeMessage[T](JsonReader reader)
   at Halibut.Transport.Protocol.MessageSerializer.ReadCompressedMessageRewindable[T](Stream stream, IRewindableBuffer rewindable)
   at Halibut.Transport.Protocol.MessageSerializer.ReadMessage[T](Stream stream)
   at Halibut.Transport.Protocol.MessageExchangeStream.Receive[T]()
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ReceiveAndProcessRequest(IMessageExchangeStream stream, Func`2 incomingRequestProcessor)
   at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsSubscriber(Uri subscriptionId, Func`2 incomingRequestProcessor, Int32 maxAttempts)
   at Halibut.Transport.PollingClient.<ExecutePollingLoop>b__12_0(MessageExchangeProtocol protocol)
   at Halibut.Transport.SecureClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Halibut.Transport.SecureClient.HandleError(Exception lastError, Boolean retryAllowed)
   at Halibut.Transport.SecureClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
   at Halibut.Transport.PollingClient.ExecutePollingLoop(Object ignored)
```

**Comment by veochen-octopus** [comment]
This has been fixed in tentacle:
- `6.2.277` for pre-net6
- `6.3.295` for net6

**Comment by LukeButters** [comment]
Both sides, tentacle and server must be upgraded to avoid this issue.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8267 |
| 2023.1 | 2023.1.4281 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8267 |
| 2023.1 | 2023.1.4281 |
| 2023.2+ | _all releases_ |
