### ISSUE TITLE
GIT cache Folder Error - Blocking project and release creation

### ISSUE THREAD

**Issue by FelixBrunet** [OctopusDeploy/Issues#7975]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking

### Version

2022.3.10828

### Latest Version

None

### What happened?

The Octopus folder on the server is locked and the project cannot access GIT
- The release cannot be created (main project page showing red error with the branch)
- The test git connection work
- The Clear local cache doesn't do the work

### Reproduction

No way to reproduce it but I got the problem a few time

### Error and Stacktrace

```shell
Errors: 
2023-01-05 11:06:02.4133   8428     71 ERROR  Unhandled error on request: "failed to make directory 'C:/Octopus/Git/UBOPJDYDMWPHVWX6EW2ZGFWJBNJYYR62/root/worktrees/bS4WG2LOG3VPP3LITO7ANEJHAH24PE5XX': directory exists"
LibGit2Sharp.NameConflictException: failed to make directory 'C:/Octopus/Git/UBOPJDYDMWPHVWX6EW2ZGFWJBNJYYR62/root/worktrees/bS4WG2LOG3VPP3LITO7ANEJHAH24PE5XX': directory exists
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /opt/buildagent/work/af149fa15da88873/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_worktree_add(RepositoryHandle repo, String name, String path, git_worktree_add_options options) in /opt/buildagent/work/af149fa15da88873/LibGit2Sharp/Core/Proxy.cs:line 3681
   at LibGit2Sharp.WorktreeCollection.Add(String committishOrBranchSpec, String name, String path, Boolean isLocked) in /opt/buildagent/work/af149fa15da88873/LibGit2Sharp/WorktreeCollection.cs:line 88
   at Octopus.Core.Git.Repositories.RepositoryRoot.AddWorktree(GitRef gitRef, String worktreeName, String workingDirectoryPath, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/RepositoryRoot.cs:line 163
   at Octopus.Core.Git.Repositories.ErrorHandlingRepositoryRootDecorator.AddWorktree(GitRef gitRef, String worktreeName, String workingDirectoryPath, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/ErrorHandlingRepositoryRootDecorator.cs:line 47
   at Octopus.Core.Git.Repositories.FileSystemLoggingRepositoryRootDecorator.AddWorktree(GitRef gitRef, String worktreeName, String workingDirectoryPath, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/FileSystemLoggingRepositoryRootDecorator.cs:line 61
   at Octopus.Core.Git.Repositories.SpaceLimitRepositoryRootDecorator.<>c__DisplayClass14_0.<<AddWorktree>b__0>d.MoveNext() in ./source/Octopus.Core/Git/Repositories/SpaceLimitRepositoryRootDecorator.cs:line 44
--- End of stack trace from previous location ---
   at Octopus.Core.Git.GitSpaceLimit.DoOperationWithPostCheck[T](Func`2 operation, CancellationToken cancellationToken, Func`1 onPostFailure) in ./source/Octopus.Core/Git/GitSpaceLimit.cs:line 56
   at Octopus.Core.Git.Repositories.SpaceLimitRepositoryRootDecorator.AddWorktree(GitRef gitRef, String worktreeName, String workingDirectoryPath, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/SpaceLimitRepositoryRootDecorator.cs:line 50
   at Octopus.Core.Git.Repositories.GitRepository.CreateRepositoryWorktree(GitRef gitRef, String worktreeName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/GitRepository.cs:line 222
   at Octopus.Core.Git.Repositories.GitRepository.CreateWorktree(GitRef gitRef, String worktreeName, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/GitRepository.cs:line 183
   at Octopus.Core.Tasks.AsyncConcurrentDictionary`2.<>c__DisplayClass3_0.<<AddOrUpdate>b__0>d.MoveNext() in ./source/Octopus.Core/Tasks/AsyncConcurrentDictionary.cs:line 48
--- End of stack trace from previous location ---
   at Octopus.Core.Tasks.AsyncConcurrentDictionary`2.InCriticalSection[T](Func`2 action, CancellationToken cancellationToken) in ./source/Octopus.Core/Tasks/AsyncConcurrentDictionary.cs:line 92
   at Octopus.Core.Tasks.AsyncConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 factoryFunc, Func`3 updateFunc, CancellationToken cancellationToken) in ./source/Octopus.Core/Tasks/AsyncConcurrentDictionary.cs:line 52
   at Octopus.Core.Git.Repositories.GitRepository.PrepareWorkTree(GitRef gitRef, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/GitRepository.cs:line 135
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Octopus.Core.Persistence.Git.GitTransactionFactory.BeginOrAdoptExisting() in ./source/Octopus.Core/Persistence/Git/GitTransactionFactory.cs:line 72
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
```

### Workaround

Octopus process need to be stop, removing all folder in the GIT folder, and everything is running fine after that

**Comment by Lexy2** [comment]
Second that, just ran into the same issue again. Funny enough, working with just 500 Mb repo after deletion. Maybe Octo doesn't pack the cache and remove stale branches.
