### ISSUE TITLE
Certificate warnings and expiry aren't being raised

### ISSUE THREAD

**Issue by felixi-octopus** [OctopusDeploy/Issues#7978]
### Team

- [X] I've assigned a team label to this issue

### Version

2023.1.1791

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Certificates won't raise the appropriate expiry warning or expiry audit record when **the certificate is already a replacement of another certificate** and either:

* The replaced certificate has raised a 20-day warning and the new certificate is raising a 20-day warning OR
* The replaced certificate has raised a 10-day warning and the new certificate is raising a 20-day warning OR
* The replaced certificate has raised a 10-day warning and the new certificate is raising a 10-day warning OR
* The replaced certificate has raised an expiry and the new certificate is raising a 20-day warning OR
* The replaced certificate has raised an expiry and the new certificate is raising a 10-day warning OR
* The replaced certificate has raised an expiry and the new certificate is raising an expiry

The new certificate should be able to raise warnings and expiry records, regardless of what warnings and expiry records have been raised previously by the certificate that it replaced.

### Reproduction

1. Create a certificate. Let's call this Certificate B.
2. Wait until Certificate B has a 10-day expiry warning raised.
4. Replace Certificate B with a new certificate, called Certificate A
4. Upgrade Octopus Server to 2023.1.1791
2. Wait until Certificate A has a 20-day expiry warning raised. Observe exception.

### Error and Stacktrace

```shell
System.InvalidOperationException: Cannot transition from SecondWarning back to FirstWarning
   at Octopus.Core.Model.Certificate.ChangeExpirationWarning(ExpirationWarning expirationWarning) in ./source/Octopus.Core/Model/Certificates/Certificate.cs:line 343
   at Octopus.Core.Model.Certificate.TryUpdateExpirationWarning(DateTimeOffset utcNow) in ./source/Octopus.Core/Model/Certificates/Certificate.cs:line 323
   at Octopus.Server.ScheduledJobs.Jobs.ExpiryWarning.CertificateExpiryEventRaiser.RaiseExpiryEvents(ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/ScheduledJobs/Jobs/ExpiryWarning/CertificateExpiryEventRaiser.cs:line 43
   at Octopus.Server.ScheduledJobs.Jobs.ExpiryWarning.RaiseExpiryEventsJob.Trigger(CancellationToken cancellationToken) in ./source/Octopus.Server/ScheduledJobs/Jobs/ExpiryWarning/RaiseExpiryEventsJob.cs:line 43
   at Octopus.Core.Features.ScheduledJobs.Scheduling.JobRunner.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() in ./source/Octopus.Core/Features/ScheduledJobs/Scheduling/JobRunner.cs:line 64
--- End of stack trace from previous location ---
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass3_0.<<Execute>b__0>d.MoveNext() in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 37
--- End of stack trace from previous location ---
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute(Type rawType, Func`3 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 40
   at Octopus.Core.Features.ScheduledJobs.Scheduling.JobRunner.Run(JobDefinition definition, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/ScheduledJobs/Scheduling/JobRunner.cs:line 77
```

**Comment by felixi-octopus** [comment]
Release Note: Certificates metadata corrected to allow expiry and warnings to be properly raised

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.5936 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.5936 |
| 2023.2+ | _all releases_ |
