### ISSUE TITLE
/nuget/packages endpoint no longer handles trailing slashes after query parameters

### ISSUE THREAD

**Issue by MissedTheMark** [OctopusDeploy/Issues#8021]
### Team

- [X] I've assigned a team label to this issue

### Severity

Two customers so far, but would potentally affect any customers using OctoPack and the ?replace=true parameter

### Version

Present from 2023.1.7359

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using Octopack to push a nuget package to the `nuget/packages` endpoint, with any query string parameter attached (eg `?replace=true`), a trailing slash is added to the request.

We guide people to attach a query string parameter if they want to replace packages that already exist [here](https://octopus.com/docs/packaging-applications/create-packages/octopack#push-a-nuget-package-that-already-exists).

The slash is taken as part of the value (e.g `true/`) and fails to bind to the model.

### Reproduction

Create a NuGet package, and attempt to push it to an Octopus instance using Octopack's version of NuGet:
`nuget.exe push my.package.1.0.1.nupkg -ApiKey <API-Key> -Source https://myserver:80/Spaces-1/nuget/packages?replace=true`

### Error and Stacktrace

```shell
System.FormatException: true/ is not a valid value for Boolean.
 ---> System.FormatException: String 'true/' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Octopus.Core.Infrastructure.AmazingConverter.Convert(Object source, Type targetType) in ./source/Octopus.Core/Infrastructure/AmazingConverter.cs:line 60
   at Octopus.Server.Web.Infrastructure.Binders.ApiContractModelBinder.ConvertUsingAmazingConverter(Type targetType, Object value) in ./source/Octopus.Server/Web/Infrastructure/Binders/ApiContractModelBinder.cs:line 360
   at Octopus.Server.Web.Infrastructure.Binders.ApiContractModelBinder.PopulateProperty(ModelBindingContext bindingContext, Object model, Object[] values, PropertyInfo property) in ./source/Octopus.Server/Web/Infrastructure/Binders/ApiContractModelBinder.cs:line 307
   at Octopus.Server.Web.Infrastructure.Binders.ApiContractModelBinder.PopulateProperty(ModelBindingContext bindingContext, PropertyInfo[] modelProperties, Object model, KeyValuePair`2 parameter, IEnumerable`1 propertiesToPreservePlusSigns, IEnumerable`1 propertiesToBindFromCsv)
   at Octopus.Server.Web.Infrastructure.Binders.ApiContractModelBinder.PopulateFromDictionary(ModelBindingContext bindingContext, PropertyInfo[] modelProperties, Object model, IEnumerable`1 parameters) in ./source/Octopus.Server/Web/Infrastructure/Binders/ApiContractModelBinder.cs:line 231
   at Octopus.Server.Web.Infrastructure.Binders.ApiContractModelBinder.BindModelAsync(ModelBindingContext bindingContext) in ./source/Octopus.Server/Web/Infrastructure/Binders/ApiContractModelBinder.cs:line 119
```

### Workaround

Remove the `?replace` query parameter if possible.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.1 | 2023.1.8513 |
| 2023.2+ | _all releases_ |
