### ISSUE TITLE
Helm Deployment - YAML parse error on Templates with Path longer than 100 characters

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8132]
### Severity

Not Blocking, Workaround Exists

### Version

2023.2.9087

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When deploying a Helm chart with a filename/path that is longer than 100 chars, the deployment will fail with YAML parse error even if the template is valid.

### Reproduction

1. Create Helm package with a template with a long file name (100+ characters)
2. Configure a Deploy Helm Chart Step using that package
3. See error - `UPGRADE FAILED: YAML parse error on example/templates/PaxHeaders.0/123456789012345678901234567890123456789012345678901234567890123456789: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead`

### Error and Stacktrace

```shell
05:48:22   Verbose  |       Invoking target script C:\Octopus\Ops Polling\Work\20230503054749-1740276-47\staging\Octopus.FunctionAppenderContext.ps1 with  parameters
05:48:22   Verbose  |       Invoking target script C:\Octopus\Ops Polling\Work\20230503054749-1740276-47\staging\Calamari.HelmUpgrade.ps1 with  parameters.
05:48:22   Error    |       history.go:56: [debug] getting history for release upgradeahelmchart-azurecloud
05:48:22   Error    |       upgrade.go:150: [debug] preparing upgrade for upgradeahelmchart-azurecloud
05:48:22   Error    |       upgrade.go:510: [debug] resetting values to the chart's original version
05:48:22   Error    |       Error: UPGRADE FAILED: YAML parse error on example/templates/PaxHeaders.0/123456789012345678901234567890123456789012345678901234567890123456789: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
05:48:22   Error    |       helm.go:84: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
05:48:22   Error    |       YAML parse error on example/templates/PaxHeaders.0/123456789012345678901234567890123456789012345678901234567890123456789
05:48:22   Error    |       helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
05:48:22   Error    |       helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
05:48:22   Error    |       helm.sh/helm/v3/pkg/releaseutil.SortManifests
05:48:22   Error    |       helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
05:48:22   Error    |       helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
05:48:22   Error    |       helm.sh/helm/v3/pkg/action/action.go:170
05:48:22   Error    |       helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
05:48:22   Error    |       helm.sh/helm/v3/pkg/action/upgrade.go:242
05:48:22   Error    |       helm.sh/helm/v3/pkg/action.(*Upgrade).RunWithContext
05:48:22   Error    |       helm.sh/helm/v3/pkg/action/upgrade.go:151
05:48:22   Error    |       main.newUpgradeCmd.func2
05:48:22   Error    |       helm.sh/helm/v3/cmd/helm/upgrade.go:207
05:48:22   Error    |       github.com/spf13/cobra.(*Command).execute
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:916
05:48:22   Error    |       github.com/spf13/cobra.(*Command).ExecuteC
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:1044
05:48:22   Error    |       github.com/spf13/cobra.(*Command).Execute
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:968
05:48:22   Error    |       main.main
05:48:22   Error    |       helm.sh/helm/v3/cmd/helm/helm.go:83
05:48:22   Error    |       runtime.main
05:48:22   Error    |       runtime/proc.go:250
05:48:22   Error    |       runtime.goexit
05:48:22   Error    |       runtime/asm_amd64.s:1598
05:48:22   Error    |       UPGRADE FAILED
05:48:22   Error    |       main.newUpgradeCmd.func2
05:48:22   Error    |       helm.sh/helm/v3/cmd/helm/upgrade.go:209
05:48:22   Error    |       github.com/spf13/cobra.(*Command).execute
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:916
05:48:22   Error    |       github.com/spf13/cobra.(*Command).ExecuteC
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:1044
05:48:22   Error    |       github.com/spf13/cobra.(*Command).Execute
05:48:22   Error    |       github.com/spf13/cobra@v1.6.1/command.go:968
05:48:22   Error    |       main.main
05:48:22   Error    |       helm.sh/helm/v3/cmd/helm/helm.go:83
05:48:22   Error    |       runtime.main
05:48:22   Error    |       runtime/proc.go:250
05:48:22   Error    |       runtime.goexit
05:48:22   Error    |       runtime/asm_amd64.s:1598
05:48:22   Error    |       Running rollback conventions...
05:48:22   Verbose  |       Calamari.Common.Commands.CommandException: Helm Upgrade returned non-zero exit code: 1. Deployment terminated.
05:48:22   Verbose  |       at Calamari.Kubernetes.Conventions.HelmUpgradeConvention.Install(RunningDeployment deployment) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Kubernetes\Conventions\HelmUpgradeConvention.cs:line 48
05:48:22   Verbose  |       at Calamari.Deployment.ConventionProcessor.RunInstallConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 71
05:48:22   Verbose  |       at Calamari.Deployment.ConventionProcessor.RunConventions() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Shared\Deployment\ConventionProcessor.cs:line 29
```

### More Information

The same template is able to be deployed outside of Octopus without any error.

### Workaround

Reduce the length of the filename/path so the total is less than 100 characters.

Note that the path also includes the following which reduces the total available length: `templates/PaxHeaders.0/`

**Comment by IsaacCalligeros95** [comment]
The root cause of this issue is how SharpCompress handles PaxHeaders in GZips, It doesn't... Alternatives like SharpZipLib do, however we've had other issues with SharpZipLib historically and re-implementing to run side-by-side with SharpCompress to resolve this issue doesn't feel like the right path forward. 

Dotnet 7 is shipping with built-in support for 
* Announcement https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-4/
* Proposal and details https://github.com/dotnet/runtime/issues/65951
* Blog post with implementation example https://www.nikouusitalo.com/blog/how-to-natively-read-tgz-files-with-the-new-c-tarreader-class/

While it may be a while off, I think handling packages with the built-in dotnet-supported tools will likely be our ideal future state. I've added details and will raise this internally as a to-do when we bump Calamari from net6.0 to 7.0.

**Comment by NickJosevski** [comment]
This should get resolved when we migrate https://github.com/octopusdeploy/calamari to net8.0, that's not yet scheduled.

Closing this issue as won't fix for now.
