### ISSUE TITLE
Package gets cleaned up between parallel deployments to the same target

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#8259]
### Severity

non-blocking

### Version

any

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When multiple deployments (e.g. tenanted) are happening at the same time on the same target, a package can get inadvertently cleaned up right before it's about to be registered for a deployment, resulting in a file not found error. Octopus performs package retention as part of package acquisition, which causes Calamari to remove packages if there's not enough disk space left. Between parallel deployments there's a chance that package retention from one of the earlier deployments will remove the referenced package in the middle of a later deployment's package acquisition.

### Reproduction

Not tested. This is a race condition and requires a target with a relatively full disk.

- Create a deployment process that references a package.
- Make multiple tenanted deployments to the same target at the same time. 
- Make sure one of the first few deployments triggers package cleanup.
- One of the later deployments should fail

### Error and Stacktrace

```shell
01:55:09   Info     |       Unable to register package use.
01:55:09   Info     |       System.IO.FileNotFoundException: Could not find file 'C:\Octopus\Files\my-awesome-package@S32@FA2571C0824CD046B1ADB59D34191C7A.nupkg'.
01:55:09   Info     |       File name: 'C:\Octopus\Files\my-awesome-package@S32@FA2571C0824CD046B1ADB59D34191C7A.nupkg'
01:55:09   Info     |       at System.IO.FileInfo.get_Length()
01:55:09   Info     |       at Calamari.Common.Plumbing.FileSystem.CalamariPhysicalFileSystem.GetFileSize(String path) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Plumbing\FileSystem\CalamariPhysicalFileSystem.cs:line 230
01:55:09   Info     |       at Calamari.Commands.RegisterPackageUseCommand.RegisterPackageUse() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\RegisterPackageUseCommand.cs:line 64
01:55:09   Info     |       at Calamari.Commands.RegisterPackageUseCommand.Execute(String[] commandLineArguments) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\RegisterPackageUseCommand.cs:line 50
01:55:09   Error    |       Could not find file 'C:\Octopus\Files\my-awesome-package@S32@FA2571C0824CD046B1ADB59D34191C7A.nupkg'.
01:55:09   Error    |       System.IO.FileNotFoundException
01:55:09   Error    |       at System.IO.FileInfo.get_Length()
01:55:09   Error    |       at Calamari.Common.Plumbing.FileSystem.CalamariPhysicalFileSystem.GetFileSize(String path) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari.Common\Plumbing\FileSystem\CalamariPhysicalFileSystem.cs:line 230
01:55:09   Error    |       at Calamari.Commands.RegisterPackageUseCommand.RegisterPackageUse() in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\RegisterPackageUseCommand.cs:line 64
01:55:09   Error    |       at Calamari.Commands.RegisterPackageUseCommand.Execute(String[] commandLineArguments) in C:\BuildAgent\work\e0cefbed4ad11812\source\Calamari\Commands\RegisterPackageUseCommand.cs:line 50
```

### More Information

Logs added in [shortcut](https://app.shortcut.com/octopusdeploy/story/54471/package-retention-between-parallel-deployments-causing-package-acquisition-to-fail)

### Workaround

Rerun the failed deployments

**Comment by LukeButters** [comment]
One possible cause of this issue is that during package acquisition we do a non atomic operation of:

 1. finding a package
 2. and later locking that package.
 
 This means we have an opportunity for something else to sneak in and delete the package we are just about to use.
 
 To reproduce this:
 
 I did manage to repro this.
I created two projects:
Project A: OctopusBypassDeploymentMutex=true and OctopusPackageRetentionPercentFreeDiskSpace=2
Project B: OctopusBypassDeploymentMutex=true and OctopusPackageRetentionPercentFreeDiskSpace=100
Both projects deploy the same package.
 0. Run project A, this is important since packages are only cleaned up if and only if they are referenced in PackageRetentionJournal.json stored on the tentacle.
Run project A, again. Manipulating octopus with an artificial delay just before [RegisterPackage](https://github.com/OctopusDeploy/OctopusDeploy/blob/main/source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs#L159).
 2. Run project B, Let it run cleanup (it will clean up the package). Manipulate octopus such that for this deployment it gets delayed before [staging the work](https://github.com/OctopusDeploy/OctopusDeploy/blob/main/source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs#L129)
 3. Let project A continue on with the register call which will fail, as in the [github ticket](https://github.com/OctopusDeploy/Issues/issues/8259).

**Comment by jimmyp** [comment]
Today we saw a task manage to clean up a package it was trying to acquire. We believe the series of events that allowed us to do this was:

1. Task-1 begins acquiring package to worker & acquires work coordinator lock
2. Task-1 finishes uploading package (but has not registered or released work coordinator lock)
3. Task-2 begins acquisition of package
4. Task-2 runs retention which deletes package
5. Task-2 blocks on work coordinator lock
6. Task-1 releases work coordinator lock
7. Task-1 now believes the package is on the worker and tries to register package and fails
8. Task-2 now believes the package is on the worker and tries to register package and fails

[Link to our internal issue
](https://slipway.octopushq.com/software-products/OctopusServer/problems/SoftwareReleaseProblems-7501)

**Comment by erikrosegs** [comment]
We are seeing this behavior as well after attempting to add parallelism to our tenanted deployments.

**Comment by KennethBates** [comment]
Another report (private): https://octopus.zendesk.com/agent/tickets/247484
