### ISSUE TITLE
Okta integration using a client secret does not work with Octopus bindings using a Virtual directory 

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#8262]
### Severity

Blocking any customer using Okta Integration with a client secret with a virtual directory as a binding

### Version

Only tried on latest Octopus server version

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have a virtual directory as a binding in Octopus and you have Okta setup using a client secret as per our documentation on setting up Okta [here](https://octopus.com/docs/security/authentication/okta-authentication) you will see an authentication error when trying to sign into Octopus using Okta:

**Error you will see in the UI:**

`{"title":"Sorry, something went wrong","message":"Could not authenticate against identity provider. Please check your configuration.","details":{"ErrorMessage":"Could not authenticate against identity provider. Please check your configuration."}`

**Error in the Octopus Server logs:**

```
2023-07-25 08:30:28.4982    592     31 ERROR  Authentication error from identity provider. Status Code: 400. Message: {"error":"invalid_grant","error_description":"The 'redirect_uri' does not match the redirection URI used in the authorization request."}
2023-07-25 08:30:28.4982    592     31 ERROR  Unhandled error on request: "Could not authenticate against identity provider. Please check your configuration."
```

**Screenshot 1 - Octopus bindings with virtual directory and one without:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/c78a66f8-d6a9-4bfa-9648-bcaca17b985a)

**Screenshot 2 - Okta settings with a client secret and virtual directories selected:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/f7f0dc5c-b827-4818-bd68-33fa8fd0f599)

**Screenshot 3 - Error message in the UI when you try logon to Octopus:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/22cde254-6ddd-42b6-ab2e-16bdaf312017)

If you take the virtual directory off of Octopus and use the binding without the virtual directory you are able to logon to Octopus fine with Okta which confirms all the settings and authentication details for Okta are correct.

If you then try and set up Okta with Implicit workflow and not use the client secret you are able to logon to Octopus via Okta with the virtual directory binding:

**Steps to setup implicit workflow as our documentation does not go through this process:**

1. In Okta in your Octopus app you created go to `General`, untick `Client Secret` and select `Public / Private key`:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/1ec4947f-3c74-4a56-a40a-a6f90b26e097)

2. Then on that same page under the Application settings tick `Implicit (hybrid)`:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/972c001f-f4b3-4b91-8a96-d0e31fcdaee8)

3. Then, in Octopus, remove the client secret from the Okta settings in the UI:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/ad642ad3-3750-4ac3-a865-9645463f7d96)

When you then sign into Octopus, it will allow you to sign in with Okta using the virtual directory:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/268081d5-ca0a-48ec-9249-c6cda75e443b)

### Reproduction

1. Have an Octopus instance with a public URL that has one binding with a virtual directory and one without (see Screenshot 1 in the 'What Happened' section above).

2. Set your browser to clear cookies and cache after closing the window (we need this setting for later on).

3. Setup Okta with a client secret and the Octopus binding with the virtual directory for the `Sign-in redirect URI` and the `Initiate login URI` using our documentation [here](https://octopus.com/docs/security/authentication/okta-authentication). (see Screenshot 2 in the 'What Happened' section above)

4. Logon to Octopus with Okta using the URL with the virtual directory and see the error in screenshot 3 in the 'What Happened' section above.

5. Close the browser window for Octopus (which will clear the cookies and cache). 

6. Go back to Okta and set the `Sign-in redirect URI` and the `Initiate login URI` to use the Octopus URL without the virtual directory:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/217535c7-d36b-47c6-ab42-8523a252ae9f)

7. Go to Octopus and open the URL without the virtual directory and sign into Octopus using Okta, you will then see you are able to sign on, proving the authentication details and Okta settings are correct, it's just the virtual directory that is the issue.

8. Close the browser window for Octopus and go back to Okta, change the `Sign-in redirect URI` and the `Initiate login URI` back to use the Octopus URL with the virtual directory.

9. Using the guide in the What Happened section for setting up Okta with Implicit flow not the client secret - set your Okta up to use Implicit flow and remove the client secret from the Okta Octopus settings.

10. Close your browser for Octopus and open the URL with the virtual directory. Try and sign in with Okta and you will now find you can sign on. The sign in details have not been cached from any previous sessions proving Octopus is not passing the virtual directory URL if using a client secret but it is if using Implicit flow.

11. Finally, change your browser settings back to not removing cookies and cache on browser close.

### Error and Stacktrace

```shell
2023-07-25 08:29:26.3253    592     52  INFO  "HTTP" "GET" to "clarevm.uksouth.cloudapp.azure.com""/" "completed" with 307 in 00:00:00.0024230 (2ms) by ""
2023-07-25 08:30:22.4896    592     32  INFO  "HTTPS" "POST" to "clarevm.uksouth.cloudapp.azure.com""/users/authenticate/Okta" "completed" with 200 in 00:00:00.7494321 (749ms) by "<anonymous>"
2023-07-25 08:30:28.4982    592     31 ERROR  Authentication error from identity provider. Status Code: 400. Message: {"error":"invalid_grant","error_description":"The 'redirect_uri' does not match the redirection URI used in the authorization request."}
2023-07-25 08:30:28.4982    592     31 ERROR  Unhandled error on request: "Could not authenticate against identity provider. Please check your configuration."
System.Exception: Could not authenticate against identity provider. Please check your configuration.
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.RequestAuthToken(String code, String redirectUri, String codeVerifier)
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.Handle(String code, String state, IOctoRequest request)
   at Octopus.Server.Web.Controllers.LegacyExtensibility.AspNetOctoRequest.HandleAsync[T1,T2](IResponderParameter`1 parameter1, IResponderParameter`1 parameter2, Func`3 onSuccess) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/AspNetOctoRequest.cs:line 90
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.ExecuteAsync(IOctoRequest request)
   at Octopus.Server.Extensibility.AnonymousWhenEnabledAsyncActionInvoker`2.Execute(IOctoRequest request, CancellationToken token) in ./source/Octopus.Server/Extensibility/AnonymousWhenEnabledAsyncActionInvoker.cs:line 43
   at Octopus.Server.Web.Controllers.LegacyExtensibility.ExtensibilityController`1.Invocation(CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/ExtensibilityController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 43
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 31
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 25
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 58
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 57
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 32
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 64
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 50
2023-07-25 08:30:28.6800    592     31  INFO  Request took 1069ms
2023-07-25 08:30:28.6800    592     31  INFO  "HTTPS" "GET" to "clarevm.uksouth.cloudapp.azure.com""/api/users/authenticatedToken/Okta" "completed" with 500 in 00:00:01.0706179 (1070ms) by "<anonymous>"
System.Exception: Could not authenticate against identity provider. Please check your configuration.
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.RequestAuthToken(String code, String redirectUri, String codeVerifier)
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.Handle(String code, String state, IOctoRequest request)
   at Octopus.Server.Web.Controllers.LegacyExtensibility.AspNetOctoRequest.HandleAsync[T1,T2](IResponderParameter`1 parameter1, IResponderParameter`1 parameter2, Func`3 onSuccess) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/AspNetOctoRequest.cs:line 90
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.ExecuteAsync(IOctoRequest request)
   at Octopus.Server.Extensibility.AnonymousWhenEnabledAsyncActionInvoker`2.Execute(IOctoRequest request, CancellationToken token) in ./source/Octopus.Server/Extensibility/AnonymousWhenEnabledAsyncActionInvoker.cs:line 43
   at Octopus.Server.Web.Controllers.LegacyExtensibility.ExtensibilityController`1.Invocation(CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/ExtensibilityController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 43
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 31
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 25
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 47
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 58
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 57
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 32
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 64
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 50
2023-07-25 08:30:28.6800    592     31  INFO  "HTTPS" "GET" to "clarevm.uksouth.cloudapp.azure.com""/octoclippy.3309599f0ed7ede136239299b755f3cb.hashedasset.svg" "completed" with 200 in 00:00:00.0008795 (0ms) by ""
2023-07-25 08:30:36.6901    592     53 ERROR  Unhandled error on request: "Your session has expired. Please try signing in again."
System.TimeoutException: Your session has expired. Please try signing in again.
```

### More Information

Customer ticket (Internal) - https://octopus.zendesk.com/agent/tickets/141040
Slack conversation (Internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1689682083448759

### Workaround

If you want to use Octopus with a virtual directory and Okta authentication, you will need to use Implicit workflow for the authentication in Okta not the client secret.

Note - Implicit workflow is not as secure as using PKCE and a client secret. You can find out more about the differences [here](https://oauth.net/2/pkce/).

**Comment by iryan2** [comment]
Release Notes: Custom authentication providers (Okta, AAD, etc) now work with virtual directories.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |
| 2025.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |
| 2025.3+ | _all releases_ |

**Comment by Clare-Octopus** [comment]
We have a regression of this in `2025.4.10464` and also our latest (as of typing this comment) `2026.2.13147` version.

We seem to be stripping out the virtual directory on the redirect URL when you have logged into Octopus through Okta, and Okta then redirects you to the Octopus URL - 

<img width="909" height="351" alt="Image" src="https://github.com/user-attachments/assets/b7e8cbf7-7d02-4e9a-a8dd-8b29c046cc01" />

### Workarounds

From my testing it will allow you to logon if you see the 404 error in your browser and you manually add the virtual directory to the URL from within the browser:

<img width="1055" height="437" alt="Image" src="https://github.com/user-attachments/assets/69055690-5817-447d-a98a-d5a5048a5708" />

<br>This also works if you use Implicit flow as mentioned in the workaround above in the main Github issue:

So set your Okta settings to use Implicit (Hybrid) and allow the ID Token:

<img width="1078" height="755" alt="Image" src="https://github.com/user-attachments/assets/dcda4a2f-c943-4799-809a-c5326015c156" />

<br>And then remove the client secret from within the Okta settings in Octopus:

<img width="881" height="764" alt="Image" src="https://github.com/user-attachments/assets/7662d031-a2a7-41ce-9866-bec652a7ad7f" />

<br>This will allow a direct logon after you have logged in through Okta and will not strip the virtual directory from the URL.

If you have any questions on this, please contact support@octopus.com 

Kind Regards,
Clare
