### ISSUE TITLE
Azure AD integration using a client secret does not work with Octopus bindings using a Virtual directory

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#8263]
### Severity

Blocking any customer using Azure AD Integration with a client secret with a virtual directory as a binding

### Version

Only tried on latest Octopus server version

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If you have a virtual directory as a binding in Octopus and you have Azure Active Directory (AAD) setup using a client secret as per our documentation on setting up AAD [here](https://octopus.com/docs/security/authentication/azure-ad-authentication) you will see an authentication error when trying to sign into Octopus using AAD:

Error you will see in the UI:

`{"title":"Sorry, something went wrong","message":"Could not authenticate against identity provider. Please check your configuration.","details":{"ErrorMessage":"Could not authenticate against identity provider. Please check your configuration."}`

Error in the Octopus Server logs:

```
2023-07-25 11:01:11.2074   7968     56 ERROR  Authentication error from identity provider. Status Code: 400. Message: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'https://clarevm.uksouth.cloudapp.azure.com/api/users/authenticatedToken/AzureAD' does not match the reply address 'https://clarevm.uksouth.cloudapp.azure.com/octopus/api/users/authenticatedToken/AzureAD' provided when requesting Authorization code.\r\nTrace ID: fed66959-2796-4345-ad80-d70e118b4100\r\nCorrelation ID: 1da72d9d-8430-4328-a715-3e4a2bac7a95\r\nTimestamp: 2023-07-25 11:01:09Z","error_codes":[500112],"timestamp":"2023-07-25 11:01:09Z","trace_id":"fed66959-2796-4345-ad80-d70e118b4100","correlation_id":"1da72d9d-8430-4328-a715-3e4a2bac7a95"}
2023-07-25 11:01:11.2074   7968     56 ERROR  Unhandled error on request: "Could not authenticate against identity provider. Please check your configuration."
```

**Screenshot 1 - Octopus bindings with virtual directory and one without:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/c78a66f8-d6a9-4bfa-9648-bcaca17b985a)

**Screenshot 2 - AAD settings with a client secret and virtual directories selected:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/71526183-d18b-4e10-87c8-261661b4f934)

**Screenshot 3 - Error message in the UI when you try logon to Octopus:**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/90d2f350-b9d6-4501-8786-77739214cde3)

If you take the virtual directory off of Octopus and use the binding without the virtual directory you are able to logon to Octopus fine with AAD which confirms all the settings and authentication details for AAD are correct.

If you then try and set up AAD with Implicit workflow and not use the client secret you are able to logon to Octopus via AAD with the virtual directory binding:

To setup implicit workflow rather than use the client secret all you need to do is remove the client secret from the Azure AD settings in the Octopus UI which will force Octopus to use Implicit workflow:

**Screenshot 4 - Octopus Azure AD settings using implicit flow (no client secret):**

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/ef89e132-b2a9-422e-a2ee-b4477f4f8c0b)

When you then sign into Octopus, it will allow you to sign in with AAD using the virtual directory:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/da7e6727-1e5f-4ee6-9d10-07aebbeb1d75)

### Reproduction

1. Have an Octopus instance with a public URL that has one binding with a virtual directory and one without (see Screenshot 1 in the 'What Happened' section above).

2. Set your browser to clear cookies and cache after closing the window (we need this setting for later on).

3. Setup AAD with a client secret and the Octopus binding with the virtual directory for the `Redirect URI` using our documentation [here](https://octopus.com/docs/security/authentication/azure-ad-authentication). (see Screenshot 2 in the 'What Happened' section above)

4. Logon to Octopus with AAD using the URL with the virtual directory and see the error in screenshot 3 in the 'What Happened' section above.

5. Close the browser window for Octopus (which will clear the cookies and cache). 

6. Go back to AAD and set the `Redirect URI` to use the Octopus URL without the virtual directory:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/066977a3-f1a2-4c08-9695-16c48806cf6c)

7. Go to Octopus and open the URL without the virtual directory and sign into Octopus using AAD, you will then see you are able to sign on, proving the authentication details and AAD settings are correct, it's just the virtual directory that is the issue.

8. Close the browser window for Octopus and go back to AAD, change the `Redirect URI` back to use the Octopus URL with the virtual directory.

9. Set your AAD in Octopus up to use Implicit flow by removing the client secret from the Azure AD Octopus settings page  (see Screenshot 4 in the 'What Happened' section above)

10. Close your browser for Octopus and open the URL with the virtual directory. Try and sign in with AAD and you will now find you can sign on. The sign in details have not been cached from any previous sessions proving Octopus is not passing the virtual directory URL if using a client secret but it is if using Implicit flow.

11. Finally, change your browser settings back to not removing cookies and cache on browser close.

### Error and Stacktrace

```shell
2023-07-25 11:00:47.0235   7968     89  INFO  "HTTPS" "POST" to "clarevm.uksouth.cloudapp.azure.com""/users/authenticate/AzureAD" "completed" with 200 in 00:00:00.3126577 (312ms) by "<anonymous>"
2023-07-25 11:01:11.2074   7968     56 ERROR  Authentication error from identity provider. Status Code: 400. Message: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'https://clarevm.uksouth.cloudapp.azure.com/api/users/authenticatedToken/AzureAD' does not match the reply address 'https://clarevm.uksouth.cloudapp.azure.com/octopus/api/users/authenticatedToken/AzureAD' provided when requesting Authorization code.\r\nTrace ID: fed66959-2796-4345-ad80-d70e118b4100\r\nCorrelation ID: 1da72d9d-8430-4328-a715-3e4a2bac7a95\r\nTimestamp: 2023-07-25 11:01:09Z","error_codes":[500112],"timestamp":"2023-07-25 11:01:09Z","trace_id":"fed66959-2796-4345-ad80-d70e118b4100","correlation_id":"1da72d9d-8430-4328-a715-3e4a2bac7a95"}
2023-07-25 11:01:11.2074   7968     56 ERROR  Unhandled error on request: "Could not authenticate against identity provider. Please check your configuration."
System.Exception: Could not authenticate against identity provider. Please check your configuration.
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.RequestAuthToken(String code, String redirectUri, String codeVerifier)
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.Handle(String code, String state, IOctoRequest request)
   at Octopus.Server.Web.Controllers.LegacyExtensibility.AspNetOctoRequest.HandleAsync[T1,T2](IResponderParameter`1 parameter1, IResponderParameter`1 parameter2, Func`3 onSuccess) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/AspNetOctoRequest.cs:line 90
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.ExecuteAsync(IOctoRequest request)
   at Octopus.Server.Extensibility.AnonymousWhenEnabledAsyncActionInvoker`2.Execute(IOctoRequest request, CancellationToken token) in ./source/Octopus.Server/Extensibility/AnonymousWhenEnabledAsyncActionInvoker.cs:line 44
   at Octopus.Server.Web.Controllers.LegacyExtensibility.ExtensibilityController`1.Invocation(CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/ExtensibilityController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 44
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 52
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 48
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 59
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 58
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 41
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 65
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 50
2023-07-25 11:01:11.2074   7968     56  INFO  Request took 1304ms
2023-07-25 11:01:11.2074   7968     56  INFO  "HTTPS" "GET" to "clarevm.uksouth.cloudapp.azure.com""/api/users/authenticatedToken/AzureAD" "completed" with 500 in 00:00:01.3051196 (1305ms) by "<anonymous>"
System.Exception: Could not authenticate against identity provider. Please check your configuration.
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.RequestAuthToken(String code, String redirectUri, String codeVerifier)
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.Handle(String code, String state, IOctoRequest request)
   at Octopus.Server.Web.Controllers.LegacyExtensibility.AspNetOctoRequest.HandleAsync[T1,T2](IResponderParameter`1 parameter1, IResponderParameter`1 parameter2, Func`3 onSuccess) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/AspNetOctoRequest.cs:line 90
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Web.UserAuthenticatedPkceAction`3.ExecuteAsync(IOctoRequest request)
   at Octopus.Server.Extensibility.AnonymousWhenEnabledAsyncActionInvoker`2.Execute(IOctoRequest request, CancellationToken token) in ./source/Octopus.Server/Extensibility/AnonymousWhenEnabledAsyncActionInvoker.cs:line 44
   at Octopus.Server.Web.Controllers.LegacyExtensibility.ExtensibilityController`1.Invocation(CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/LegacyExtensibility/ExtensibilityController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 44
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 52
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 48
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 59
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 58
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 41
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 65
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 50
```

### More Information

Customer ticket (Internal) - https://octopus.zendesk.com/agent/tickets/141040
Slack conversation (Internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1689682083448759

Similar to this GitHub issue (for Okta) - #8262

### Workaround

If you want to use AAD authentication with a virtual directory you will need to use Implicit workflow for the authentication in Octopus not the client secret.

Note - Implicit workflow is not as secure as using PKCE and a client secret. You can find out more about the differences [here](https://oauth.net/2/pkce/).

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |
| 2025.3+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.2 | 2025.2.1659 |
| 2025.3+ | _all releases_ |
