### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by poteb** [OctopusDeploy/Issues#8286]
### Severity

Fatal

### Version

2023.2.13151

### Latest Version

None

### What happened?

Service has crashed and I found the error in Windows Event Viewer.
I don't know which file it can't access, but maybe an Octopus Deploy developer can have a look because the stackstrace contains line numbers. (why is it build in debug?)

### Reproduction

No

### Error and Stacktrace

```shell
2023-08-13 02:20:13.9510   4772     11 FATAL  Unhandled AppDomain exception occurred: "The process cannot access the file because it is being used by another process."
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (32): The process cannot access the file because it is being used by another process.
   at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at Octopus.Server.Web.WebServerInitializer.<>c__DisplayClass14_0.<Start>b__2() in ./source/Octopus.Server/Web/WebServerInitializer.cs:line 100
   at Octopus.Server.Web.WebServerInitializer.SocketInUseRetry(Action`4 onRetry, Action execute) in ./source/Octopus.Server/Web/WebServerInitializer.cs:line 324
   at Octopus.Server.Web.WebServerInitializer.Start() in ./source/Octopus.Server/Web/WebServerInitializer.cs:line 92
   at Octopus.Server.OctopusServerEngine.Start() in ./source/Octopus.Server/OctopusServerEngine.cs:line 73
   at Octopus.Server.Commands.RunCommand.Start() in ./source/Octopus.Server/Commands/RunCommand.cs:line 89
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in ./source/Octopus.Shared/Startup/AbstractCommand.cs:line 101
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 504
   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass2_0.<Run>b__0() in ./source/Octopus.Shared/Startup/WindowsServiceHost.cs:line 26
   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService() in ./source/Octopus.Shared/Startup/WindowsServiceAdapter.cs:line 48
   at System.Threading.Thread.StartCallback()
```

### More Information

Self hosted on Windows Server 2022 Standard.

### Workaround

Start the service again.

**Comment by donnybell** [comment]
Hi @poteb,

For Octopus Support inquiries, please contact us at [Support@Octopus.com](mailto:Support@Octopus.com).

As this is a support case and not a bug report, this issue will be closed.

Best,
Donny
