### ISSUE TITLE
Deploy a Bicep Template step fails when CAC is enabled

### ISSUE THREAD

**Issue by IsaacCalligeros95** [OctopusDeploy/Issues#8368]
### Severity

Blocking a handful of customers, workaround is disabling CAC not viable for many customers

### Version

2023.4.3998, likely in first version with Deploy a Bicep Template added.

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the Deploy a Bicep template step in a VCS/CaC project we error out with various object errors in the UI and during deployment (if you can get that far). Step works fine outside of CaC.

### Reproduction

* Create a Deploy a Bicep Template step with CAC enabled
* UI errors out saving the step
* Customer has been able to save the step but deployments fail with 'Object reference not set to an instance of an object.'

### Error and Stacktrace

```shell
Error while saving in UI using CAC
System.ArgumentException: Could not determine JSON object type for type Octopus.Ocl.OclStringLiteral.
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
   at Newtonsoft.Json.Linq.JProperty..ctor(String name, Object content)
   at Octopus.Core.Serialization.Ocl.OclConverters.StepPackageInputsConverter.JObjectFromOclElement(JsonSchema schema, IOclElement element) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/StepPackageInputsConverter.cs:line 101
   at Octopus.Core.Serialization.Ocl.OclConverters.StepPackageInputsConverter.JObjectFromOclElement(JsonSchema schema, IOclElement element) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/StepPackageInputsConverter.cs:line 93
   at Octopus.Core.Serialization.Ocl.OclConverters.StepPackageInputsConverter.FromElement(IMayBeFromAStepPackage mayBeFromAStepPackage, IOclElement element) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/StepPackageInputsConverter.cs:line 24
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentActionOclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentActionOclConverter.cs:line 106
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.SetProperties(OclConversionContext context, Type type, IEnumerable`1 elements, Object target)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentActionOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentActionOclConverter.cs:line 142
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Octopus.Ocl.Converters.DefaultCollectionOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Ocl.Converters.OclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentStepOclConverter.cs:line 70
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.SetProperties(OclConversionContext context, Type type, IEnumerable`1 elements, Object target)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Core.Serialization.Ocl.OclConverters.DeploymentStepOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue) in ./source/Octopus.Core/Serialization/Ocl/OclConverters/DeploymentStepOclConverter.cs:line 56
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Octopus.Ocl.Converters.DefaultCollectionOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Ocl.Converters.OclConverter.SetProperties(OclConversionContext context, IEnumerable`1 elements, Object target, IReadOnlyList`1 properties)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.SetProperties(OclConversionContext context, Type type, IEnumerable`1 elements, Object target)
   at Octopus.Ocl.Converters.DefaultBlockOclConverter.FromElement(OclConversionContext context, Type type, IOclElement element, Object currentValue)
   at Octopus.Ocl.OclSerializer.Deserialize(OclDocument document, Type type)
   at Octopus.Ocl.OclSerializer.Deserialize[T](String ocl)

Error while deploying:
'Object reference not set to an instance of an object.'
```

### Workaround

Disable CAC

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2023.3 | 2023.3.13069 |
| 2023.4 | 2023.4.5013 |
| 2024.1+ | _all releases_ |
