### ISSUE TITLE
Embedded mp4 video file not working on macOS

### ISSUE THREAD

**Issue by borland** [OctopusDeploy/Issues#8499]
### Severity

Low

### Version

-

### Latest Version

I could reproduce the problem in the latest build

### What happened?

In our Deployment Process Editor, the tooltip/help for the "On Targets in Roles" heading has a small embedded video, helping show users what to do.
On Chrome browsers on macOS, this video didn't load.

### Reproduction

Use chrome on a mac, and open the video in the deployment process editor per this screenshot.

![image](https://github.com/OctopusDeploy/Issues/assets/6362/8b3c29e9-a5cb-4b3a-986d-8bb65736c236)

### Error and Stacktrace

The following error will be logged on the server when the browser attempts to open the file.

```shell
System.NotSupportedException: This operation is not supported.
   at System.IO.Compression.DeflateStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, IFileInfo file, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendRangeAsync()
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)
   at Octopus.Server.Web.Middleware.BundledStaticContentMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/BundledStaticContentMiddleware.cs:line 86
```

**Comment by borland** [comment]
Release Note: Fixed embedded video files not playing on some browsers

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2937 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.2937 |
| 2024.2+ | _all releases_ |
