### ISSUE TITLE
Unable to deploy releases created before Config-as-Code conversion

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#8508]
After converting a project to config-as-code, any releases created before the conversion cannot be deployed:

> Cannot create DatabaseProjectReference for non-Database project

The full stack trace:
```
System.ArgumentException: Cannot create DatabaseProjectReference for non-Database project
   at Octopus.Core.Model.Projects.DatabaseProjectReference..ctor(Project project) in ./source/Octopus.Core/Model/Projects/ProjectReference.cs:line 36
   at Octopus.Server.Web.Controllers.DeploymentProcesses.VariableLoader.LoadForRelease(Release release) in ./source/Octopus.Server/Web/Controllers/DeploymentProcesses/VariableLoader.cs:line 77
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentWorkItemCalculator.GetDeploymentReleaseNotes(IOctopusQueryExecutor queryExecutor, Release release, IReadOnlyCollection`1 releasesForProject, DeploymentEnvironmentBase environment, Tenant tenant, Boolean discreteChannelRelease)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentFactory.CreateDeploymentPreviewWithEnvironmentAndTenant(IOctopusQueryExecutor queryExecutor, DeploymentEnvironmentId environmentId, TenantId tenantId, Tenant tenant, Boolean includeDisabledSteps, IOctopusPrincipal user, Release release, IReadOnlyCollection`1 releasesForProject, Project project, DeploymentProcess deploymentProcess, IOctopusQueryExecutor queryExecutorAsUserWithAllPermissions, Channel channel, ProjectGroup projectGroup, Space space, VariableCollection projectVariables, VariableCollection libraryVariables, DeploymentEnvironmentBase environment, List`1 promptVariables, List`1 deploymentTargetsInEnvironment)
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentFactory.<>c__DisplayClass24_2.<CreateDeploymentPreviews>b__17(TenantId tenantId) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/DeploymentFactory.cs:line 309
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.IterativeCopy[T](IEnumerable`1 source, T[] array, Int32 arrayIndex, Int32 count)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Octopus.Server.Orchestration.ServerTasks.Deploy.DeploymentFactory.CreateDeploymentPreviews(IOctopusQueryExecutor queryExecutor, ReleaseId releaseId, IEnumerable`1 previewRequests, Boolean includeDisabledSteps, IOctopusPrincipal user)
   at Octopus.Core.Features.Releases.GetCreateDeploymentDeploymentPreviewsBffRequestHandler.Handle(GetCreateDeploymentDeploymentPreviewsBffRequest request, CancellationToken cancellationToken) in ./source/Octopus.Core/Features/Releases/GetCreateDeploymentDeploymentPreviewsBffRequestHandler.cs:line 48
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 37
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 60
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 78
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 37
   at Octopus.Server.Web.Controllers.Releases.Bff.GetDeploymentPreviews.GetCreateDeploymentDeploymentPreviewsBffController.GetCreateDeploymentDeploymentPreviewsBff(GetCreateDeploymentDeploymentPreviewsBffRequest request, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/Releases/Bff/GetDeploymentPreviews/GetCreateDeploymentDeploymentPreviewsBffController.cs:line 21
   ```

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.3433 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.1 | 2024.1.3433 |
| 2024.2+ | _all releases_ |
