### ISSUE TITLE
Unhelpful exception in tentacle log when tentacle & server thumbprint doesn't match

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#8519]
### Severity

Sev-3-low

### Version

master

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When the thumbprint for tentacle and server do not match, tentacle logs show an unhelpful exception.

### Reproduction

1. Create new tentacle and create a project that deploys to it
3. Change the tentacle thumbprint on server, go to tentacle logs and see unhelpful exception message

### Error and Stacktrace

```shell
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageSerializer.ReadMessageAsync[T](RewindableBufferStream stream, CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageSerializer.ReadMessageAsync[T](RewindableBufferStream stream, CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageExchangeStream.ReceiveAsync[T](CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageExchangeStream.ReceiveRequestAsync(TimeSpan timeoutForReceivingTheFirstByte, CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageExchangeProtocol.ReceiveAndProcessRequestAsSubscriberAsync(IMessageExchangeStream stream, Func`2 incomingRequestProcessor, CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsSubscriberAsync(Uri subscriptionId, Func`2 incomingRequestProcessor, Int32 maxAttempts, CancellationToken cancellationToken)
2023-12-06 15:20:57    at Halibut.Transport.PollingClient.<>c__DisplayClass13_0.<<ExecutePollingLoopAsync>b__0>d.MoveNext()
2023-12-06 15:20:57 --- End of stack trace from previous location ---
2023-12-06 15:20:57    at Halibut.Transport.SecureClient.ExecuteTransactionAsync(ExchangeActionAsync protocolHandler, RequestCancellationTokens requestCancellationTokens)
2023-12-06 15:20:57    at Halibut.Transport.SecureClient.ExecuteTransactionAsync(ExchangeActionAsync protocolHandler, RequestCancellationTokens requestCancellationTokens)
2023-12-06 15:20:57 https://host.docker.internal:10943/   58  Halibut client exception: An error occurred when sending a request to 'https://host.docker.internal:10943/', after the request began: Attempted to read past the end of the stream. Retrying in 5.0 seconds
2023-12-06 15:20:57 Halibut.HalibutClientException: An error occurred when sending a request to 'https://host.docker.internal:10943/', after the request began: Attempted to read past the end of the stream.
```

**Comment by michelle-luana** [comment]
The Octopus engineering team has reviewed this issue.  
After careful consideration, we’ve classed this low priority. This means we won’t work on it in the near future. 
We prioritize issues based on the number of people affected, the impact type, and available workarounds. 
If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.
