### ISSUE TITLE
Git Sourced Packages Not Working with Offline Package Drop - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#8566]
### Severity

workaround exists

### Version

2024.1.7120

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using Git Sourced Packages and Offline Deployment Targets, the package isn't able to be acquired and an error is shown

### Reproduction

Configure a Run a Script step to sourced from a Git Package and targeting an Offline Package Drop Deployment Target

### Error and Stacktrace

```shell
19:10:49   Fatal    |       Object reference not set to an instance of an object.
19:10:49   Verbose  |       at Octopus.Core.Packages.FileNameEscaper.Escape(String input) in ./source/Octopus.Core/Packages/FileNameEscaper.cs:line 26
                    |       at Octopus.Server.Orchestration.Targets.OfflineDrop.OfflineDropBatch.ExecutionDirectory(String tenantName, String environmentName, String projectName, String snapshotIdentifier) in ./source/Octopus.Server/Orchestration/Targets/OfflineDrop/OfflineDropBatch.cs:line 268
                    |       at Octopus.Server.Orchestration.Targets.OfflineDrop.OfflineDropBatch.ExecutionDirectory(IImmutableVariableDictionary variables) in ./source/Octopus.Server/Orchestration/Targets/OfflineDrop/OfflineDropBatch.cs:line 263
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.Deferred.DeferredExecutor.ExecuteCalamari(CalamariFlavour flavour, String calamariCommand, IReadOnlyList`1 calamariArguments, IReadOnlyList`1 files, IReadOnlyList`1 deploymentTools, VariableCollection extraVariables, TargetManifest targetManifest, CalamariPlatformConstraint calamariPlatformConstraint, Nullable`1 mutexTimeout, String mutexName, ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionExecution/Deferred/DeferredExecutor.cs:line 108
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionExecution.CommandBuilders.CalamariCommandBuilder.Execute(ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionExecution/CommandBuilders/CalamariCommandBuilder.cs:line 161
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.PackageAcquisitionExecutionHandlers.<>c__DisplayClass6_0.<<FindPackage>b__0>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs:line 74
```

### More Information

[Internal Link - Slack](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1705375707849449)
[Internal Link - Zendesk](https://octopus.zendesk.com/agent/tickets/168154)

### Workaround

Source scripts from a package in the built in feed or define it in-line for Offline Package Drop Targets

**Comment by SeanStanway-Octopus** [comment]
Customer instance [internal link](https://octopus.zendesk.com/agent/tickets/218832)

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13081 |
| 2024.4 | 2024.4.7076 |
| 2025.1 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13081 |
| 2024.4 | 2024.4.7076 |
| 2025.1 | 2025.1.6689 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.13081 |
| 2024.4 | 2024.4.7076 |
| 2025.1 | 2025.1.6689 |
| 2025.2+ | _all releases_ |
