### ISSUE TITLE
ApplicationHost.config Write Errors

### ISSUE THREAD

**Issue by renevo** [OctopusDeploy/Issues#869]
We are running into this issue a lot (#85 does not fix this) where the applicationHost.config is locked for whatever reason and the step fails (thank you for guided failure). We had hoped that the 2.0 upgrade from 1.6 would fix this issue, but we still run into it.

Is it possible to do a retry on this (n) amount of times before failing the step?

This occurs with the IIS home directory feature.

Exception:

```
Filename: \\?\C:\Windows\system32\inetsrv\config\applicationHost.config
Error: Cannot write configuration file


System.IO.FileLoadException: Filename: \\?\C:\Windows\system32\inetsrv\config\applicationHost.config
Error: Cannot write configuration file


   at Microsoft.Web.Administration.Interop.AppHostWritableAdminManager.CommitChanges()
   at Microsoft.Web.Administration.Configuration.CommitChanges()
   at Microsoft.Web.Administration.ConfigurationManager.CommitChanges()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Octopus.Tentacle.Integration.Iis.WebServerSevenSupport.FindVirtualDirectory(String webSiteName, String virtualDirectoryPath, Action`1 found) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Tentacle\Integration\Iis\WebServerSevenSupport.cs:line 92
   at Octopus.Tentacle.Integration.Iis.WebServerSevenSupport.ChangeHomeDirectory(String webSiteName, String virtualDirectoryPath, String newWebRootPath) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Tentacle\Integration\Iis\WebServerSevenSupport.cs:line 74
   at Octopus.Tentacle.Procedures.Implementations.Iis.IisHomeDirectoryUpdateProcedure.Start(IProcedureHost host, ProcedureState state) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Tentacle\Procedures\Implementations\Iis\IisHomeDirectoryUpdateProcedure.cs:line 36
   at Octopus.Tentacle.Orchestration.Procedures.ProcedureCallOrchestrator.Receive(CallProcedureCommand message) in c:\TeamCity\buildAgent\work\1116bd9da9e239fd\source\Octopus.Tentacle\Orchestration\Procedures\ProcedureCallOrchestrator.cs:line 73
   at Pipefish.Actor.OnReceivingTyped[TBody](Message message) in c:\TeamCity\buildAgent\work\cf0b1f41263b24b9\source\Pipefish\Actor.cs:line 113
```

**Comment by bigbam505** [comment]
Just want to say I had this happen to me on Octopus 3.1.3.  So not sure if this is a fluke or its something I did wrong?  We only had it happen for one region.

**Comment by brettveenstra** [comment]
We just started seeing a rash of these errors in Octopus 3.17.9 ...any advice?
