### ISSUE TITLE
External Security Group with null DisplayName causes authentication failure

### ISSUE THREAD

**Issue by emilol** [OctopusDeploy/Issues#8717]
### Severity

Sev 1

### Version

Earliest tried was 2024.2.4147

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Various API endpoints which require authentication are returning a HTTP 500 error with the message `Data is Null. This method or property cannot be called on Null values.`

Stacktrace confirms it's related to the Entity Framework migration.

### Reproduction

This issue affects any instance that returns results for the following query:

```
SELECT * FROM TeamExternalSecurityGroup WHERE DisplayName IS NULL
```

### Error and Stacktrace

```shell
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method11050(Closure, DbDataReader, Int32[])
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateSplitIncludeCollectionAsync>g__InitializeReaderAsync|26_0[TIncludingEntity,TIncludedEntity](RelationalQueryContext queryContext, RelationalCommandCache relationalCommandCache, IReadOnlyList`1 readerColumns, Boolean detailedErrorsEnabled, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateSplitIncludeCollectionAsync[TIncludingEntity,TIncludedEntity](Int32 collectionId, RelationalQueryContext queryContext, IExecutionStrategy executionStrategy, RelationalCommandCache relationalCommandCache, IReadOnlyList`1 readerColumns, Boolean detailedErrorsEnabled, SplitQueryResultCoordinator resultCoordinator, Func`3 childIdentifier, IReadOnlyList`1 identifierValueComparers, Func`5 innerShaper, Func`4 relatedDataLoaders, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.TaskAwaiter(Func`1[] taskFactories)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Octopus.Core.Extensions.QueryableExtensionMethods.ToListAsync[T](IQueryable`1 query, CancellationToken cancellationToken)
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.GetTableInternal[TModel,TKey](IReadQueryExecutor trn, CachedTableStatistics latest, Int32 count, SpaceId spaceId, CancellationToken cancellationToken)
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.GetTable[TModel,TKey](IReadQueryExecutor trn, CachedTableStatistics latest, Int32 count, SpaceId spaceId, CancellationToken cancellationToken, Func`2 filter)
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.<>c__DisplayClass10_0`2.<<GetMergedTable>g__GetTableDataForPartition|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.<>c__DisplayClass10_0`2.<<GetMergedTable>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Octopus.Core.RelationalStorage.Caching.LatestAndCountsForPartitions`1.<>c__DisplayClass2_0.<<ForEachPartition>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIteratorWithTaskAndCancellation`2.MoveNextCore()
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 56
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 91
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Octopus.Core.RelationalStorage.Caching.LatestAndCountsForPartitions`1.ForEachPartition(Func`5 getDataForPartition, CancellationToken cancellationToken)
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.GetMergedTable[TModel,TKey](IReadQueryExecutor trn, LatestAndCountsForPartitions`1 latestAndCounts, CancellationToken cancellationToken, Func`2 filter)
   at Octopus.Core.RelationalStorage.Caching.NonCloningRawFullTableCache.Get[T1Model,T1Key,T2Model,T2Key,T3Model,T3Key](IReadQueryExecutor trn, SpacePartitionsDefinition partitions, CancellationToken cancellationToken) in ./source/Octopus.Core/RelationalStorage/Caching/NonCloningRawFullTableCache.cs:line 73
   at Octopus.Server.Web.Infrastructure.Authentication.OctopusPrincipalLoader.GetPrincipalForUser(IUser user, AuthenticationSourceDescriptor sourceDescriptor, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Infrastructure/Authentication/OctopusPrincipalLoader.cs:line 59
   at Octopus.Server.Web.Infrastructure.Authentication.WebAuthCache.GetPrincipalForUser(IUser user, AuthenticationSourceDescriptor authenticationSource, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Infrastructure/Authentication/WebAuthCache.cs:line 129
   at Octopus.Server.Web.Infrastructure.Authentication.WebAuthCache.<>c__DisplayClass10_0.<<GetPrincipalFor>b__0>d.MoveNext() in ./source/Octopus.Server/Web/Infrastructure/Authentication/WebAuthCache.cs:line 74
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Octopus.Server.Web.Infrastructure.Authentication.WebAuthCache.GetPrincipalFor(IUser user, AuthenticationSourceDescriptor sourceDescriptor, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Infrastructure/Authentication/WebAuthCache.cs:line 67
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IUserSessionService userSessionService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 48
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 35
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 64
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 51
```

### Workaround

Backup your db before trying the below workaround.

Running the following SQL command against the database can resolve the issue.
```sql
UPDATE TeamExternalSecurityGroup SET DisplayName = '' WHERE DisplayName IS NULL;
```

**Comment by YuKitsune** [comment]
Release note: Fixed an issue where a null DisplayName in an external security group would cause authentication to fail.

**Comment by driesgroblerw** [comment]
Thanks team!

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4248 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.4248 |
| 2024.3+ | _all releases_ |
