### ISSUE TITLE
Edit Step link on Task log  causes resource not found error

### ISSUE THREAD

**Issue by stevencl840** [OctopusDeploy/Issues#8931]
### Severity

Low

### Version

2024.3.3026

### Latest Version

I could reproduce the problem in the latest build

### What happened?

After running a Runbook go to view the Runbook run. next to a step, click the "Edit Step" link. It should take you to the step editor, instead it presents a resource not found.

### Reproduction

After running a Runbook go to view the Runbook run. next to a step, click the "Edit Step" link. It should take you to the step editor, instead it presents a resource not found.

### Error and Stacktrace

```shell
"HTTP" "GET" to "localhost:8066""/api/Spaces-1/runbooks/backupdb" "completed" with 404 in 00:00:16.1089757 (16108ms) by "admin"
Octopus.Core.Model.Exceptions.EntityNotFoundException: Exception of type 'Octopus.Core.Model.Exceptions.EntityNotFoundException' was thrown.
   at Octopus.Core.Persistence.Database.DatabaseDocumentStore`2.GetAsync(TKey id, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Persistence\Database\DatabaseDocumentStore.cs:line 59
   at Octopus.Core.Persistence.Database.FullTableCacheDocumentStoreDecorator`2.GetAsync(TKey id, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Persistence\Database\FullTableCacheDocumentStoreDecorator.cs:line 57
   at Octopus.Core.Persistence.ChangeTracking.NevermoreAndGit.NonTrackingDocumentStoreDecorator`2.GetAsync(TKey id, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Persistence\ChangeTracking\NevermoreAndGit\NonTrackingDocumentStoreDecorator.cs:line 38
   at Octopus.Core.Persistence.DocumentStore`2.GetAsync(TKey id, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Persistence\DocumentStore.cs:line 85
   at Octopus.Core.Persistence.ReadOnlyDocumentStore`2.GetAsync(TKey id, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Persistence\ReadOnlyDocumentStore.cs:line 44
   at Octopus.Core.Features.Runbooks.GetRunbookByIdRequestHandler.Handle(GetRunbookByIdInDatabaseRequest request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Features\Runbooks\GetRunbookByIdRequestHandler.cs:line 33
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\AutofacMediator.cs:line 45
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\SystemComponentModelValidationDecorator.cs:line 48
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\FluentValidationsDecorator.cs:line 62
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Core\Infrastructure\Mediator\Decorators\MessageBusSiphoningDecorator.cs:line 37
   at Octopus.Server.Web.Controllers.Runbooks.GetRunbookByIdController.GetRunbookByIdInDatabase(GetRunbookByIdInDatabaseRequest request, CancellationToken cancellationToken) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Controllers\Runbooks\GetRunbookByIdController.cs:line 24
   at lambda_method12173(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\BoundaryTrailerRewriteMiddleware.cs:line 45
   at Octopus.Server.Web.Middleware.OpenFeatureUserContextMiddleware.InvokeAsync(HttpContext httpContext, IOctopusPrincipalInternal principal, IFeatureClient client) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\OpenFeatureUserContextMiddleware.cs:line 31
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Infrastructure\Authentication\AuthorizationMiddlewareResultHandler.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 31
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 42
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusClientOldVersionWarningMiddleware.cs:line 24
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\DynamicContentHeadersMiddleware.cs:line 50
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\MaintenanceModeMiddleware.cs:line 58
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, EnableSkipAuthenticationAttributeFeatureToggle enableSkipAuthenticationAttributeFeatureToggle, IUserAuthenticator userAuthenticator, IUserSessionService userSessionService, IWebAuthCache authCache, ILogger logger) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusAuthenticationMiddleware.cs:line 71
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\TelemetryMiddleware.cs:line 64
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in D:\repo\OctopusDeploy\source\Octopus.Server\Web\Middleware\ErrorHandlingMiddleware.cs:line 51
```

**Comment by stevencl840** [comment]
Release Note: Fix "Edit Step" link not working on Runbook Task List

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.7832 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.7832 |
| 2024.4+ | _all releases_ |
