### ISSUE TITLE
Signing Key rotation does not function for Google, AzureAD and Okta configuration

### ISSUE THREAD

**Issue by nick-roscarel-octo** [OctopusDeploy/Issues#9019]
### Severity

Affects any Octopus Server instance that makes use of Google Apps, AzureAD, or Okta authentication

### Version

Earliest tried was 2024.4.917, but it has likely existed for all versions since 2017

### Latest Version

The problem does not exist in the latest build

### What happened?

When rotating the signing key, certain OpenID-based configurations (Google Apps, AzureAD & Okta) do not rotate their client secrets, resulting in failures during authentication.

### Reproduction

1. Configure a Client secret for Google, AzureAD or Okta authentication
2. Perform a signing key rotation, either through the UI or by running the `Octopus.Server rotate-master-key` command
3. Restart Octopus Server

### Error and Stacktrace

```
Nevermore.ReaderException: Error reading row 1, column 3. Padding is invalid and cannot be removed..
Compiled reader expression:

(DbDataReader reader, DocumentReaderContext context) => 
{
    Type deserializeAsType = Octopus.Server.Extensibility.Authentication.AzureAD.Configuration.AzureADConfiguration
    context.Column = 0
    String temp0 = IIF(reader.IsDBNull(0), null, reader.GetString(0))
    context.Column = 1
    String temp1 = IIF(reader.IsDBNull(1), null, reader.GetString(1))
    context.Column = 2
    String temp2 = IIF(reader.IsDBNull(2), null, reader.GetString(2))
    context.Column = 3
    AzureADConfiguration deserializedFromJson = context.DeserializeText(reader, 3, deserializeAsType)
    AzureADConfiguration result = deserializedFromJson
    if (result != null)
    {
        result.Name = temp1
        result.ExtensionAuthor = temp2
    }

    result
}

 ---> System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.SymmetricPadding.GetPaddingLength(ReadOnlySpan`1 block, PaddingMode paddingMode, Int32 blockSize)
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean useAsync, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Octopus.Core.Security.MasterKey.MasterKeyEncryption.ToPlaintext(Byte[] masterKey, EncryptedBytes encrypted) in ./source/Octopus.Core/Security/MasterKey/MasterKeyEncryption.cs:line 76
   at Octopus.Core.Security.MasterKey.StoredMasterKeyEncryption.ToPlaintext(EncryptedBytes encrypted) in ./source/Octopus.Core/Security/MasterKey/StoredMasterKeyEncryption.cs:line 80
   at Octopus.Core.Security.MasterKey.MasterKeyEncryptionExtensionMethods.ToPlaintextString(IMasterKeyEncryption encryption, EncryptedBytes encrypted) in ./source/Octopus.Core/Security/MasterKey/MasterKeyEncryptionExtensionMethods.cs:line 21
   at Octopus.Core.RelationalStorage.TypeHandlers.SensitiveStringConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in ./source/Octopus.Core/RelationalStorage/TypeHandlers/SensitiveStringConverter.cs:line 56
   at Octopus.Core.RelationalStorage.TypeHandlers.SensitiveStringTypeHandler.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in ./source/Octopus.Core/RelationalStorage/TypeHandlers/SensitiveStringTypeHandler.cs:line 53
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Nevermore.Advanced.Serialization.NewtonsoftDocumentSerializer.DeserializeSmallText(String text, Type type)
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderContext.DeserializeText[TDocument](DbDataReader reader, Int32 index, Type concreteType)
   at lambda_method5471(Closure, DbDataReader, DocumentReaderContext)
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass4_1`1.<CreateReader>b__1(DbDataReader dbDataReader)
   --- End of inner exception stack trace ---
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass4_1`1.<CreateReader>b__1(DbDataReader dbDataReader)
   at Nevermore.Advanced.ReadTransaction.ProcessReader[TRecord](DbDataReader reader, PreparedCommand command)+MoveNext()
   at Nevermore.Advanced.ReadTransaction.<>c__DisplayClass112_0`1.<<Stream>g__Execute|0>d.MoveNext()
   at Nevermore.Advanced.EnumerableWithConcurrencyHandling`1.EnumeratorWithConcurrencyHandling.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Nevermore.Advanced.ReadTransaction.Load[TDocument,TKey](TKey id)
   at Octopus.Core.RelationalStorage.NevermoreQueryExecutor.Load[TDocument,TKey](TKey id) in ./source/Octopus.Core/RelationalStorage/NevermoreQueryExecutor.cs:line 55
   at Octopus.Core.RelationalStorage.RawRelationalTransaction.Load[TDocument,TKey](TKey id) in ./source/Octopus.Core/RelationalStorage/RawRelationalTransaction.cs:line 56
   at Octopus.Core.RelationalStorage.IReadQueryExecutor.Load[TDocument](String id) in ./source/Octopus.Core/RelationalStorage/IRawReadQueryExecutor.cs:line 27
   at Octopus.Core.Repositories.RawConfigurationStore.Get[TDocument](String id) in ./source/Octopus.Core/Repositories/RawConfigurationStore.cs:line 32
   at Octopus.Core.Repositories.RawConfigurationStoreCacheDecorator.Get[TDocument](String id) in ./source/Octopus.Core/Repositories/RawConfigurationStoreCacheDecorator.cs:line 26
   at Octopus.Core.Repositories.RawConfigurationStoreCacheDecorator.Get[TDocument](String id) in ./source/Octopus.Core/Repositories/RawConfigurationStoreCacheDecorator.cs:line 26
   at Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common.Configuration.DatabaseInitializer`1.Execute() in ./source/Octopus.Server.Extensibility.Authentication.OpenIDConnect.Common/Configuration/DatabaseInitializer.cs:line 21
   at Octopus.Core.Initialization.BuiltIn.ConfigurationInitializer.Initialize(IRawRelationalStore store) in ./source/Octopus.Core/Initialization/BuiltIn/ConfigurationInitializer.cs:line 24
   at Octopus.Core.Initialization.StoreInitializer.Initialize() in ./source/Octopus.Core/Initialization/StoreInitializer.cs:line 19
   at Octopus.Server.Commands.DatabaseCommand.Start() in ./source/Octopus.Server/Commands/DatabaseCommand.cs:line 220
   at Octopus.Shared.Startup.AbstractSynchronousStandardCommand.Start(CancellationToken cancellationToken) in ./source/Octopus.Shared/Startup/AbstractSynchronousStandardCommand.cs:line 27
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions, CancellationToken cancellationToken) in ./source/Octopus.Shared/Startup/AbstractCommand.cs:line 103
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 509
   at Octopus.Shared.Startup.ConsoleHost.Run(Func`2 start, Func`1 shutdown) in ./source/Octopus.Shared/Startup/ConsoleHost.cs:line 35
   at Octopus.Shared.Startup.OctopusProgram.RunHost(ICommandHost host) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 222
   at Octopus.Shared.Startup.OctopusProgram.Run(Action flushAndCloseLogger) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 164
```

### More Information

[Internal Slack Discussion](https://octopusdeploy.slack.com/archives/C07MRS67KMJ/p1726530355753329)

### Workaround

If the client secrets are updated after rotation, then they will be correctly encrypted with the new signing key.

**Comment by nick-roscarel-octo** [comment]
Release Note: Fixed signing key rotation for Google, AzureAD and Okta OpenID authentication

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.1830 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.4 | 2024.4.1830 |
| 2025.1+ | _all releases_ |
