### ISSUE TITLE
Deployment fails when using bound variable to github repo URL for git sourced scripts

### ISSUE THREAD

**Issue by patrick-smergut-octopus** [OctopusDeploy/Issues#9033]
### Severity

Reported by one customer, will affect others

### Version

Reported in 2024.3.12751, tested in 2024.4.2718

### Latest Version

None

### What happened?

When using a bound variable in a step to point to a github repo URL for git-sourced scripts, the deployment will fail because the variable doesn't get evaluated during deployment.

### Reproduction

1. Create a variable holding the value of the URL to your git repo (e.g. https://github.com/OctopusDeploy/OctopusClients.git)
2. Configure a Run a Script step sourcing the script from a git repository
3. Bind the Repository URL field to the repo variable
4. Create a release
5. Deploy the release and see error

![image](https://github.com/user-attachments/assets/50eee8e9-6281-47cf-8296-82e7033f8632)

### Error and Stacktrace

```shell
Failed: Upload package #{MyGitHubUrl}, Commit: 55a75*******, with 0 glob paths/files

16:37:07   Verbose  |       at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
                    |       at Octopus.Core.Git.Repositories.GitRepositoryKey.BuildRepositoryDirectoryName() in ./source/Octopus.Core/Git/Repositories/GitRepositoryKey.cs:line 50
                    |       at Octopus.Core.Git.Repositories.GitRepositoryKey.BuildRepositoryDirectoryPath(String workingDirectory) in ./source/Octopus.Core/Git/Repositories/GitRepositoryKey.cs:line 25
                    |       at Octopus.Core.Git.Repositories.RawGitRepositoryFactory.<>c__DisplayClass5_0.<GetOrCreate>b__0(GitRepositoryKey _) in ./source/Octopus.Core/Git/Repositories/RawGitRepositoryFactory.cs:line 40
                    |       at Octopus.Core.Threading.MultiReaderLock.GetReaderLockAndExecute[T](Func`1 func) in ./source/Octopus.Core/Threading/MultiReaderLock.cs:line 25
                    |       at Octopus.Core.Git.Repositories.GitRepositoryFactory.GetOrCreate(IGitRepositoryAccessSettings settings, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Repositories/GitRepositoryFactory.cs:line 35
                    |       at Octopus.Core.Packages.GitResourcePackageCreator.GetCommitReader(GitResourceIdentity identity, ILog log, CancellationToken cancellationToken) in ./source/Octopus.Core/Packages/GitResourcePackageCreator.cs:line 131
                    |       at Octopus.Core.Packages.GitResourcePackageCreator.CreatePackageForGitResource(GitResourceIdentity identity, ILog log, CancellationToken cancellationToken) in ./source/Octopus.Core/Packages/GitResourcePackageCreator.cs:line 41
                    |       at Octopus.Core.Packages.FROZEN_DeploymentPackageDownloader.<>c__DisplayClass11_0.<<DownloadDependency>b__0>d.MoveNext() in ./source/Octopus.Core/Packages/FROZEN_DeploymentPackageDownloader.cs:line 61
```

### More Information

Similar to https://github.com/OctopusDeploy/Issues/issues/8902, though this is during deployment rather than the release creation stage.

### Workaround

Specify the repo URL directly in the script step instead of binding to a variable holding that same value.

**Comment by patrick-smergut-octopus** [comment]
Reported [here](https://octopus.zendesk.com/agent/tickets/205586) [internal]
