### ISSUE TITLE
Connection Test Only Health Check Runs Scripts

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#9142]
### Severity

Fails health check for targets without Bash

### Version

Introduced in `2024.2.5864` via [this PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/24068), toggled on by default in `2024.3.5805`

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When health checking a target where the machine policy is set to "Only perform connection test (useful for raw scripting)" it fails if bash is not available. This is unexpected as it should not be trying to run any scripts on the target.

This is for a SSH target. I have not checked if it applies to tentacle targets (or whether it should).

### Reproduction

- Create a VM that does not have bash
- Enable SSH to that VM
- Configure a machine policy with `Only perform connection test (useful for raw scripting)`
- Create a SSH target for that machine with that machine policy
- Perform a health check

### Error and Stacktrace

```shell
/bin/bash shell missing.
SSH connection disposed.
Exit code: 127
The remote script failed with exit code 127 Octopus.Server.Orchestration.Targets.Tasks.ActionHandlerFailedException: The remote script failed with exit code 127
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.SuccessArbitrator.ThrowIfNotSuccessful(IActionHandlerResult result) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/SuccessArbitrator.cs:line 25
   at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.AdHocActionDispatcher.Dispatch(ExecutionsMachine machine, ActionHandlerInvocation actionHandler, ITaskLog taskLog, CancellationToken cancellationToken, VariableCollection variables) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/AdHocActionDispatcher.cs:line 80
   at Octopus.Server.Orchestration.ServerTasks.HealthCheck.Providers.SshEndpointHealthProvider.ExecutePreCheckScript(Machine machine, TimeSpan cancellationTimeout, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/Providers/SshEndpointHealthProvider.cs:line 50
   at Octopus.Server.Orchestration.ServerTasks.HealthCheck.Providers.MachineHealthProvider.PerformHealthCheckAndSaveResult(Machine machine, CancellationToken cancellationToken, ExceptionHandling exceptionHandling) in ./source/Octopus.Server/Orchestration/ServerTasks/HealthCheck/Providers/MachineHealthProvider.cs:line 92
Octopus.Server version 2025.1.1477 (2025.1.1477)
```

### More Information

[Health Check task log](https://github.com/user-attachments/files/17895691/ServerTasks-238.log.txt)

### Workaround

None available

**Comment by Jtango18** [comment]
Release Note:  Resolved an issue where targets with "Only Perform Connection Test" set where still trying to execute a script on using Bash. Behaviour is restored to testing for a connection only.

**Comment by Justin-Walsh** [comment]
Fixed in 2025.1.5799

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2025.1 | 2025.1.5799 |
| 2025.2+ | _all releases_ |
